adobe/react-spectrum

packages/dev/docs/src/Layout.js, packages/dev/docs/src/docs.css
The margin after the Dividers in the docs are no longer being applied due to https://github.com/adobe-private/react-spectrum-v3/pull/219/files#diff-d8e11efd03c2819ee9dcbff951997962R40. To fix, I added the 33px from https://github.com/adobe-private/react-spectrum-v3/blob/46eb66cbe0fd197d458d4ef93f3c4961667dbf64/packages/dev/docs/src/docs.css#L107 to the h2 Divider in Layout as a override
=> Adding 33px marginBottom to docs h2 Dividers 

packages/@adobe/spectrum-css-temp/components/dialog/index.css
Grid based classes should probably all be selectors of
`.container-grid .element`
so that they have a higher default specificity, we can discuss with css
Closes
=> Fix dialog divider margin

packages/@react-spectrum/well/docs/Well.mdx, packages/@react-spectrum/well/src/Well.tsx, packages/dev/docs/src/HeaderInfo.js
Closes RSP-1262
Note: i've also made `sourceData` default to an empty `[]` so that if we dont have it, we dont have to add the extra prop.
`Well` docs should appear on the website.
=> Well documentation

packages/@react-spectrum/dialog/src/Dialog.tsx, packages/@react-spectrum/dialog/stories/Dialog.stories.tsx, packages/@react-spectrum/dialog/stories/DialogTrigger.stories.tsx, packages/@react-spectrum/dialog/test/Dialog.test.js, packages/@react-spectrum/overlays/test/Popover.test.js, packages/@react-spectrum/utils/src/Slots.tsx, packages/@react-spectrum/utils/src/styleProps.ts, packages/@react-spectrum/view/src/Content.tsx, packages/@react-types/shared/src/style.d.ts
Make all the dialog things look pretty
Add flexBasis/Grow/Shrink to styles
Add a clear slots component. All it does it clear the context object so that nothing below it is influenced by the slots above
More info on ClearSlots:
Was thinking, slots is a bit pervasive, in a dialog, it applies specific styles to the Divider. If someone wanted to make a two column layout in their content and use a Divider, they'd need to do some work to get rid of the class name the dialog applies.
My thought was to start by just having the semantic element always clear the slots context because I don't think we typically want to reach into that region of anything with our styles.
This is also a convenience component to stop slots context propagation
Example added in stories
Closes …
=> Dialog story fixes

packages/@adobe/spectrum-css-temp/components/dialog/index.css, packages/@adobe/spectrum-css-temp/components/dialog/skin.css, packages/@react-spectrum/dialog/src/AlertDialog.tsx, packages/@react-spectrum/dialog/src/Dialog.tsx, packages/@react-spectrum/dialog/stories/Dialog.stories.tsx, packages/@react-spectrum/dialog/stories/DialogTrigger.stories.tsx, packages/@react-types/dialog/src/index.d.ts
Closes https://jira.corp.adobe.com/browse/RSP-1578
Look through all the dialog/dialogTrigger stories and make sure the heading is in the right place and looks correct
=> (RSP-1578) Updating Dialogs to use the right semantic element/slot for the title

packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@react-aria/collections/src/CollectionItem.tsx, packages/@react-aria/collections/src/CollectionView.tsx, packages/@react-aria/collections/src/ScrollView.tsx, packages/@react-aria/collections/src/index.ts, packages/@react-aria/collections/src/useCollectionItem.ts, packages/@react-aria/listbox/src/useListBoxSection.ts, packages/@react-spectrum/listbox/src/ListBox.tsx, packages/@react-spectrum/listbox/src/ListBoxOption.tsx, packages/@react-spectrum/listbox/src/ListBoxSection.tsx, packages/@react-spectrum/listbox/stories/ListBox.stories.tsx, packages/@react-spectrum/listbox/test/ListBox.test.js, packages/@react-spectrum/sidenav/package.json, packages/@react-spectrum/sidenav/src/SideNav.tsx, packages/@react-spectrum/sidenav/src/SideNavItem.tsx, packages/@react-spectrum/sidenav/src/SideNavSection.tsx, packages/@react-stately/collections/src/CollectionManager.ts, packages/@react-stately/collections/src/LayoutInfo.ts, packages/@react-stately/collections/src/ListLayout.ts, packages/@react-stately/collections/src/TreeCollection.ts, packages/@react-stately/collections/src/index.ts, packages/@react-stately/collections/src/types.ts, packages/@react-stately/collections/src/useCollectionState.ts
This allows us to retain actual DOM heirarchy (good for a11y) while still use virtualized scrolling (good for performance).
In order to implement it, CollectionManager still operates on a flattened set of visible keys, but the heirarchy is reconstructed at the end. LayoutInfo objects have a `parentKey` property that's used to do this. LayoutInfos are still positioned absolutely relative to the entire collection, and during rendering their parent's position is subtracted so that this works with the DOM.
=> Add support for DOM heirarchy in CollectionView

.storybook-v3/config.js, packages/@react-aria/i18n/src/useCollator.ts, packages/@react-aria/i18n/src/useNumberFormatter.ts, packages/@react-aria/selection/package.json, packages/@react-aria/selection/src/ListKeyboardDelegate.ts, packages/@react-aria/selection/src/useSelectableCollection.ts, packages/@react-aria/selection/src/useSelectableList.ts, packages/@react-aria/selection/src/useTypeSelect.ts, packages/@react-spectrum/listbox/package.json, packages/@react-spectrum/listbox/src/ListBox.tsx, packages/@react-spectrum/listbox/stories/ListBox.stories.tsx, packages/@react-spectrum/listbox/test/ListBox.test.js, packages/@react-spectrum/menu/stories/Menu.stories.tsx, packages/@react-spectrum/menu/test/Menu.test.js, packages/@react-spectrum/sidenav/package.json, packages/@react-spectrum/sidenav/src/SideNav.tsx, packages/@react-stately/collections/src/CollectionBuilder.ts, packages/@react-stately/collections/src/Item.ts, packages/@react-stately/collections/src/ListLayout.ts, packages/@react-stately/collections/src/types.ts, packages/@react-types/shared/src/collections.d.ts
This adds support for type to select to our collection components, which allows users to start typing the name of an option to jump to it. This is supported automatically for simple `<Item>` elements with only plain text inside. For complex children, a `textValue` prop is required on the `<Item>` to make it support type to select. There's a warning in case the user misses this.
For internationalization support, [Intl.Collator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator) is used to do the string comparisons. That handles case folding, ignoring of accents, etc. for us.
=> Support type to select in ListBox, Menu, and SideNav

packages/@react-aria/radio/package.json, packages/@react-aria/radio/src/useRadio.ts, packages/@react-aria/toggle/package.json, packages/@react-aria/toggle/src/useToggle.ts
Closes https://jira.corp.adobe.com/browse/RSP-1593
Go to Switch and Checkbox stories in Safari. Click on the Switch or Checkbox, then press space to toggle selection/active state. Note that it actually works and that the screen doesn't scroll down
Go to RadioGroup stories in Safari. Click on a Radio, then press down/up arrow to change radio selection. Note that it works
=> (RSP-1593) Manually focusing checkboxes/radios/switches on mouse events for safari

packages/@react-aria/breadcrumbs/test/useBreadcrumbItem.test.js, packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/interactions/test/usePress.test.js, packages/@react-aria/link/test/useLink.test.js
* Only handle left clicks. Right clicking or other mouse buttons should be ignored. The browser will likely show a context menu.
* Reset state on key up even if focus moves between key down and key up. This is done by adding the key up handler to the document instead of the element we're listing for press events on.
* Ignore repeating keyboard events (e.g. if you hold down a key). If focus moves while a keyboard event is repeating, the target changes to the newly focused element. We only want to trigger a press event on the first target in a key repeat sequence.
* Adjust keyboard handling for links so that onPressStart and onPressEnd are called at the right time rather than waiting until the click event at the end. This fixes the active state styling of buttons with role=link.
=> usePress fixes

packages/@react-aria/button/src/useButton.ts, packages/@react-aria/interactions/src/index.ts, packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/interactions/src/usePressableInput.ts, packages/@react-aria/radio/src/useRadio.ts, packages/@react-aria/toggle/src/useToggle.ts
Safari moves focus to the body between mouse down and mouse up. If focus was manually moved on mouse down (e.g. opening a menu), then we don't want the button to steal focus back on mouse up.
=> Only focus buttons, radios, and checkboxes on press end if focus is on the body

packages/@react-aria/interactions/src/useInteractOutside.ts, packages/@react-aria/interactions/test/useInteractOutside.test.js, packages/@react-aria/overlays/test/useOverlay.test.js, packages/@react-spectrum/dialog/test/DialogTrigger.test.js, packages/@react-spectrum/menu/test/MenuTrigger.test.js, packages/@react-spectrum/overlays/test/Modal.test.js, packages/@react-spectrum/overlays/test/Popover.test.js, packages/@react-spectrum/overlays/test/Tray.test.js
Previously, we only handled pointer up events in useInteractOutside. This meant that if the component that called useInteractOutside was mounted between mouse down and mouse up, it would immediately unmount on mouse up. Now, we require a pointer down event to occur before pointer up while useInteractOutside is mounted so that this doesn't happen.
=> Require pointer down event before pointer up in useInteractOutside

Makefile, package.json
Temporary workaround for docs build issue
Closes https://jira.corp.adobe.com/browse/RSP-1613
Verification done in Progress Circle PR
here's the build btw with the no scope hoisting, things aren't perfect (sidenav is out of order) but the individual pages appear to display correctly https://reactspectrum.blob.core.windows.net/reactspectrum/67cdab621d0c186b305d9f2d958294ff541d5232/docs/react-spectrum/Well.html
4:21
this is from this pull https://github.com/adobe-private/react-spectrum-v3/pull/239
4:21
which if you scroll up to the previous docs build, you can see that the pages starting at progress bar are messed up
=> Temp no scope hoist

packages/@react-aria/dialog/package.json, packages/@react-aria/dialog/src/useDialog.ts, packages/@react-aria/utils/src/useId.ts, packages/@react-spectrum/dialog/src/Dialog.tsx, packages/@react-spectrum/dialog/stories/Dialog.stories.tsx, packages/@react-spectrum/dialog/test/Dialog.test.js
pass an id through slots to the header, if it successfully renders into the dom, label the dialog with that same id
Closes https://jira.corp.adobe.com/browse/RSP-1583
Run storybook, go to dialog stories
Inspect the title of the dialog and verify that it's id is the same as the role=dialog aria-labelledby
=> Dialogs aria-labelledby

specs/accessibility/List.mdx, specs/accessibility/Menu.mdx
Update Menu and List accessibility specs to support groups.
Closes https://jira.corp.adobe.com/browse/RSP-1572
- Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- Updated documentation (if it already exists for this component).
Review accessibility specs for Menu and List under WAI-ARIA properties.
Accessibility
=> RSP-1572 Update Menu accessibility spec with groups

packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@react-aria/utils/src/mergeProps.ts, packages/@react-spectrum/actiongroup/stories/ActionGroup.stories.tsx, packages/@react-spectrum/actiongroup/test/ActionGroup.test.js, packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx, packages/@react-spectrum/button/docs/Button.mdx, packages/@react-spectrum/button/package.json, packages/@react-spectrum/button/src/ActionButton.tsx, packages/@react-spectrum/button/src/Button.tsx, packages/@react-spectrum/button/src/FieldButton.tsx, packages/@react-spectrum/button/stories/ActionButton.stories.tsx, packages/@react-spectrum/button/stories/Button.stories.tsx, packages/@react-spectrum/button/test/Button.test.js, packages/@react-spectrum/calendar/src/CalendarBase.tsx, packages/@react-spectrum/datepicker/src/DatePicker.tsx, packages/@react-spectrum/datepicker/src/DateRangePicker.tsx, packages/@react-spectrum/dialog/src/Dialog.tsx, packages/@react-spectrum/divider/stories/Divider.stories.tsx, packages/@react-spectrum/layout/src/Grid.tsx, packages/@react-spectrum/layout/stories/Grid.stories.tsx, packages/@react-spectrum/utils/src/Slots.tsx, packages/@react-types/button/src/index.d.ts, packages/dev/docs/src/client.js, specs/api/Button.md
This removes the `icon` prop from button components and uses slots to accept an icon and a label (via `<Text>`) as children. If a string is passed, it is automatically wrapped in `<Text>` so it gets the proper label class name.
One question is whether we need to switch to CSS Grid for this so that the order of the children doesn't affect the layout. @snowystinger thoughts?
=> Use slots for button children instead of icon prop

packages/@adobe/spectrum-css-temp/components/accordion/index.css, packages/@adobe/spectrum-css-temp/components/barloader/index.css, packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@adobe/spectrum-css-temp/components/dialog/index.css, packages/@adobe/spectrum-css-temp/components/dropdown/index.css, packages/@adobe/spectrum-css-temp/components/dropindicator/index.css, packages/@adobe/spectrum-css-temp/components/overlay/index.css, packages/@adobe/spectrum-css-temp/components/searchwithin/index.css, packages/@adobe/spectrum-css-temp/components/slider/index.css, packages/@adobe/spectrum-css-temp/components/slider/skin.css, packages/@adobe/spectrum-css-temp/components/splitview/index.css, packages/@adobe/spectrum-css-temp/components/steplist/index.css, packages/@adobe/spectrum-css-temp/components/tabs/index.css, packages/@adobe/spectrum-css-temp/components/tags/index.css, packages/@adobe/spectrum-css-temp/components/tooltip/index.css, packages/@adobe/spectrum-css-temp/components/treeview/index.css
Closes https://jira.corp.adobe.com/browse/RSP-1584
The problem showed up when we switched postcss from v6 to v7. Changing order for how css calc() makes a variable negative fixed it; calc(-1*var()) to calc(var()*-1).
confirm that progress bar indeterminate works.
check that RTL works
RSP
=> Fixing ProgressBar Indeterminate Animation

packages/@react-spectrum/overlays/package.json, packages/@react-spectrum/overlays/stories/Modal.stories.tsx
Closes 
while fixing this, i noticed that in the unmounting example, keyboard focus isn't returned to the button after the modal closes
?path=/story/modal--unmounting-trigger
=> Make the modal examples look nice while we wait for other things

packages/@adobe/spectrum-css-temp/components/dropdown/index.css, packages/@adobe/spectrum-css-temp/components/dropdown/skin.css, packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@react-spectrum/listbox/src/ListBoxOption.tsx, packages/@react-spectrum/menu/src/MenuItem.tsx, packages/@react-spectrum/menu/stories/Menu.stories.tsx, packages/@react-spectrum/picker/package.json, packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-spectrum/picker/stories/Picker.stories.tsx, packages/@react-stately/collections/src/CollectionBuilder.ts, packages/@react-stately/collections/src/TreeCollection.ts
This adds support for complex menu items to be selected in Picker. Icons and labels are displayed, and description text is hidden.
Also now always reserves space for the checkmark in menu items when selectable even when not selected so that the content doesn't shift when it is selected.
=> Support complex menu items in Picker

packages/@react-aria/listbox/src/useOption.ts, packages/@react-aria/menu/src/useMenuItem.ts, packages/@react-spectrum/listbox/src/ListBoxOption.tsx, packages/@react-spectrum/listbox/test/ListBox.test.js, packages/@react-spectrum/menu/src/MenuItem.tsx, packages/@react-spectrum/menu/test/Menu.test.js
This uses `aria-labelledby` and `aria-describedby` to provide better labeling of complex menu items and listbox options for accessibility. Before this change, all of the text of the menu item or option was concatenated together without break to form the accessibility label for the item. This resulted in confusing sounding items when used with a screen reader, because label text, description, keyboard shortcuts and more were read as one.
Now we use `aria-labelledby` to point to the just the main label text for the item, and `aria-describedby` to point to the description of the item, the value in key/value menu items, and the keyboard shortcut for the item. All of these are optional, so we use `useSlotId` to generate an id and pass this through the slot context to the proper child.
=> Use aria-labelledby and aria-describedby for complex menu items

package.json, packages/@react-spectrum/dialog/docs/Dialog.mdx, packages/@react-spectrum/dialog/src/Dialog.tsx, packages/@react-types/dialog/src/index.d.ts, packages/dev/docs/src/template.mdx
Closes https://jira.corp.adobe.com/browse/RSP-1536
Initial version of the dialog docs.
Added a dialog documentation page, with valid links and an example. It will have followup work for the remaining parts.
Added typescript interface JSDocs.
review dialog documentation page 
RSP
=> Dialog docs v1

packages/@adobe/spectrum-css-temp/components/dropdown/index.css, packages/@adobe/spectrum-css-temp/components/fieldlabel/index.css, packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@react-spectrum/form/stories/Form.stories.tsx, packages/@react-spectrum/listbox/stories/ListBox.stories.tsx, packages/@react-spectrum/overlays/src/Popover.tsx, packages/@react-spectrum/picker/package.json, packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-spectrum/picker/stories/Picker.stories.tsx, packages/@react-types/shared/src/style.d.ts
This implements the menu width behavior for Picker. It is as follows:
* If standard, use the width of the button by default.
* If quiet, use `--spectrum-alias-single-line-width` as a default width.
* The width can be overridden by the `menuWidth` option.
* If standard, the minimum width is the width of the button.
* If quiet, the minimum width is the width of the button plus the offset.
Also adds a bunch of stories to test the behavior of Picker with different options and within a Form.
=> Implement Picker menu width behavior

packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-aria/focus/test/FocusScope.test.js, packages/@react-aria/interactions/src/useFocusWithin.ts, packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/menu/src/useMenuTrigger.ts, packages/@react-aria/menu/test/useMenuTrigger.test.js, packages/@react-spectrum/breadcrumbs/test/Breadcrumbs.test.js, packages/@react-spectrum/listbox/src/ListBoxBase.tsx, packages/@react-spectrum/menu/src/Menu.tsx, packages/@react-spectrum/menu/src/context.ts, packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx, packages/@react-spectrum/menu/test/MenuTrigger.test.js, packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-spectrum/utils/src/filterDOMProps.ts
This adds support for automatically closing menus and moving focus to the element before or after the trigger when tabbing out. 
Closing the menu is handled using `useFocusWithin` to detect when focus moves outside.
Because overlays are rendered into a portal at the end of the body, letting the browser handle the Tab key as it normally would is insufficient as it would just tab to the next element in the document (or back to the body if nothing is after the portal). In order to support tabbing out of overlays and back to the element after/before the target, FocusScope handles the tab key and moves focus accordingly.
=> Close menu and focus correct element when tabbing out

packages/@adobe/spectrum-css-temp/components/dialog/index.css, packages/@react-spectrum/button/src/ButtonGroup.tsx, packages/@react-spectrum/button/src/index.ts, packages/@react-spectrum/dialog/src/AlertDialog.tsx, packages/@react-spectrum/dialog/src/Dialog.tsx, packages/@react-spectrum/dialog/stories/Dialog.stories.tsx, packages/@react-spectrum/dialog/stories/DialogTrigger.stories.tsx, packages/@react-spectrum/overlays/stories/Modal.stories.tsx, rfcs/2019-v3-slots.md
Move buttons to the bottom for fullscreen mobile
Give the title the full width of the top
Move button group out of footer and into its own placeholder component
Do not move title out because collapse rules mean that it couldn't take the full width for any dialogs where a button group was provided. I'll try to demo here:
```
". .       .           ."
". title   header      ."
". content content     ."
". footer  buttonGroup ."
". .       .           ."
```
this is simplified, but if there is no header supplied and there is a buttonGroup supplied, then the title cannot expand in the header area. It's better to leave that as one area because all dialogs, the title is right next to the header, and flex can be used in there so that things expand/collapse as needed
Closes …
=> Dialogs mobile fullscreen

packages/@react-aria/menu/src/useMenuItem.ts, packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx, packages/@react-spectrum/breadcrumbs/stories/Breadcrumbs.stories.tsx, packages/@react-spectrum/breadcrumbs/test/Breadcrumbs.test.js, packages/@react-spectrum/menu/src/Menu.tsx, packages/@react-spectrum/menu/src/MenuItem.tsx, packages/@react-spectrum/menu/src/MenuSection.tsx, packages/@react-spectrum/menu/stories/Menu.stories.tsx, packages/@react-spectrum/menu/test/Menu.test.js, packages/@react-spectrum/menu/test/MenuTrigger.test.js, packages/@react-types/breadcrumbs/src/index.d.ts, packages/@react-types/menu/src/index.d.ts, packages/@react-types/shared/src/collections.d.ts
This switches to `selectionMode="none` by default for Menu since it's more likely to be used for performing actions than selection. In addition, after debating further with @dannify, we decided to switch to `onAction` instead of `onPress` for menu items and breadcrumbs, and move the prop to the top-level component rather than on `<Item>`. This was for a few reasons:
1. Menu items are activated on key down, and pointer up, so are inconsistent with `onPress` in other places. A higher level action event seems more appropriate.
2. We have moved most other actions to the top level for collections components. It's useful to receive the key of the item that was activated.
3. Less props on `<Item>`, which is shared between all collections components.
=> Change to selectionMode="none" by default for Menu, and onAction instead of onPress

packages/@adobe/spectrum-css-temp/components/dropdown/index.css, packages/@react-aria/interactions/src/usePress.ts
Safari on iOS starts selecting text on long press. This is undesirable for components that use `usePress`, e.g. Picker. Adding `user-select: none` to the pressable element prevents that element from being selected, but nearby elements may still receive selection when long pressing on it. The only way to avoid this, it seems, is to add `user-select: none` to the entire document instead. We add it on touch start, and remove it again on touch end to prevent selection from occurring.
=> Disable text selection on long press on iOS

packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/interactions/test/usePress.test.js, packages/@react-types/shared/src/events.d.ts
This fixes clicking on menu items with a screen reader, which fires only an `onClick` event rather than keyboard or mouse events. It's solved by firing events with a `'virtual'` pointerType rather than a fake `'keyboard'` event, which let's us handle the event differently than for keyboard events.
=> Fire screen reader clicks with a 'virtual' pointerType instead of 'keyboard'

.circleci/config.yml
default resource_class is medium, try bumping to large to see if our docs build faster (ever)
Closes
=> Speed up build of docs with more resources

packages/@react-spectrum/dialog/src/Dialog.tsx
Doesn't support `:scope` without a polyfill
=> Fix Edge using hasChild hook

packages/@react-spectrum/illustrated-message/stories/IllustratedMessage.stories.tsx, packages/@react-types/illustrated-message/src/index.d.ts
Closes https://jira.corp.adobe.com/browse/RSP-1653
and follow up to https://github.com/adobe-private/react-spectrum-v3/pull/311 and https://jira.corp.adobe.com/browse/RSP-1585
Inspect both illustrated message stories for their aria and role attributes
RSP
=> adding aria and role to storybook stories

packages/@react-spectrum/dialog/docs/AlertDialog.mdx, packages/@react-spectrum/dialog/src/AlertDialog.tsx, packages/@react-spectrum/dialog/stories/Dialog.stories.tsx, packages/@react-spectrum/dialog/stories/DialogTrigger.stories.tsx, packages/@react-spectrum/dialog/test/AlertDialog.test.js, packages/@react-spectrum/menu/stories/Menu.stories.tsx, packages/@react-types/dialog/src/index.d.ts
New prop names for button labels
`primaryActionLabel`
`secondaryActionLabel`
Make two separate event handlers to replace `onConfirm`:
`onPrimaryAction`
`onSecondaryAction`
=> RSP-1639: AlertDialog prop updates for buttons

packages/@adobe/spectrum-css-temp/components/popover/index.css, packages/@adobe/spectrum-css-temp/components/popover/skin.css, packages/@react-aria/overlays/src/calculatePosition.ts, packages/@react-spectrum/overlays/src/Popover.tsx
Trying to fix popover tips for Safari and hoping it works for windows. Also fixed them for RTL.
I've added a lot of code comments to explain what i've tried and come up with
Closes
=> Fixing Popover tips more

packages/@react-aria/interactions/src/useFocusVisible.ts
Please don't puke.
This fixes the issue where hovering over items in Picker/Menu shows keyboard focus styling.
=> Don't switch to keyboard modality for programmatic focus() calls

packages/@react-spectrum/provider/src/Provider.tsx, packages/@react-spectrum/provider/test/Provider.test.js
Fix provider blows up if using previous colorScheme on theme without the colorScheme
if the new theme doesn't support the prevColorScheme, we must resort to the auto
Closes
=> Fix provider blowup

packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx
=> Removing split button example in MenuTrigger story

packages/@adobe/spectrum-css-temp/components/buttongroup/index.css, packages/@react-spectrum/buttongroup/src/ButtonGroup.tsx
It seems that `flex-wrap` inside CSS grid caused it to take up extra space. Adjusting the overflow computation to be based on the X position rather than the Y position.
=> Fix strange issue with ButtonGroup in dialog

packages/@adobe/spectrum-css-temp/components/dialog/index.css, packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx
fix close button  position in grid so that it always has room and affects layout
rely on negative width columns having a width of zero
it does look a little funny in large scale because the padding on the close button side is bigger :-/
Closes
=> Fix close button placement

packages/@adobe/spectrum-css-temp/components/dropdown/skin.css
when the picker trigger is focused, then the focus styles should be applied, not just when it's the label
Closes
=> Fix hover state of picker

packages/@react-aria/focus/src/FocusScope.tsx
=> fixing refocusing Dialog on underlay click for Firefox

packages/@react-spectrum/picker/src/Picker.tsx
I am a marvelously bearded programmer who has fixed two pickers open at once when they should close on blur. thanks devon
Closes
=> Fix two pickers open at once

packages/@react-aria/checkbox/src/useCheckbox.ts, packages/@react-aria/radio/src/useRadio.ts, packages/@react-aria/switch/src/useSwitch.ts, packages/@react-aria/textfield/src/useTextField.ts, packages/@react-aria/textfield/test/useTextField.test.js, packages/@react-aria/toggle/src/useToggle.ts, packages/@react-spectrum/radio/src/Radio.tsx, packages/@react-spectrum/switch/src/Switch.tsx, packages/@react-spectrum/textfield/src/TextFieldBase.tsx
goto dialog form story, close the modal, tab to the trigger button, press enter, (opens modal), press escape, (closes) and the trigger button has focus
also tested with checkbox, switch, and radio
RSP
=> refactoring autofocus on form elements to pass ref to useFocusable

packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@adobe/spectrum-css-temp/components/tray/index.css, packages/@react-aria/collections/src/CollectionView.tsx, packages/@react-aria/collections/src/ScrollView.tsx, packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/interactions/test/usePress.test.js, packages/@react-aria/overlays/src/usePreventScroll.ts, packages/@react-spectrum/listbox/src/ListBoxBase.tsx, packages/@react-spectrum/menu/src/MenuTrigger.tsx, packages/@react-spectrum/overlays/src/Tray.tsx, packages/@react-spectrum/overlays/test/Tray.test.js, packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-stately/collections/src/ListLayout.ts, packages/@react-types/overlays/src/index.d.ts
We need to calculate the max-height for Tray in JS rather than relying on percentages or viewport units in CSS. When only percentages are used, there is nothing for the browser to base them off of. Viewport units are out of the question due to them changing on scroll on mobile when the addressbar/toolbar hide.
This also fixes menus to use padding instead of margin for the top and bottom of their content. This ensures that the entire tray/popover is scrollable and the padding is only at the top and bottom of all of the list items rather than outside the scrollable region. For ListBox we also have to do this in JS due to absolute positioning.
Finally, I found that Chrome on Windows sometimes displays unwanted horizontal scrollbars due to rounding errors in `clientWidth`. The real width …
=> Fix tray scrolling

packages/@react-spectrum/listbox/docs/ListBox.mdx, packages/@react-spectrum/listbox/src/ListBox.tsx, packages/@react-types/shared/src/collections.d.ts, packages/dev/docs/src/types.js, packages/dev/parcel-packager-docs/DocsPackager.js, packages/dev/parcel-transformer-docs/DocsTransformer.js
Debugging docs build for cyclic types
Closes
=> Fix cyclic definitions for props table

packages/@adobe/spectrum-css-temp/components/overlay/index.css, packages/@adobe/spectrum-css-temp/vars/spectrum-large.css, packages/@adobe/spectrum-css-temp/vars/spectrum-medium.css
Closes 
https://jira.corp.adobe.com/browse/RSP-1678
fix for top and left position... edge doesnt like translate-calc-var combo
=> RSP-1678: Fix Popover position in Edge

.gitignore, .yarnrc, Makefile, package.json, packages/@react-spectrum/sidenav/test/SideNav.test.js, scripts/v2-package.json, yarn.lock
Yarn's ignore optionals wasn't working great. I was getting random cache errors. Instead, this copies a fake package into `packages/dev/v2-test-deps` when `make adobe_setup` is run which includes the v2 deps. This package is in the `.gitignore` so won't be committed.
=> Better strategy for optional v2 test dependencies

packages/dev/docs/src/Layout.js
This fixes an issue where preload + embed were using different crossorigin attributes and so the script would be transferred twice.
Embeds / examples in docs should work as expected
React Spectrum
=> Defer scripts in head section of docs rather than preload + footer.

package.json
Causes babel to compile less. Smaller bundle sizes. Also fixes a bug in babel loose mode that breaks some of our examples by not compiling it and letting the browser handle that syntax instead. 😄
=> Update browser targets for docs website

packages/@react-spectrum/table/src/Table.tsx, packages/@react-spectrum/table/src/TableLayout.ts, packages/@react-spectrum/table/stories/HidingColumns.tsx, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-spectrum/table/test/Table.test.js, packages/@react-stately/collections/src/CollectionBuilder.ts, packages/@react-stately/collections/src/ListLayout.ts, packages/@react-stately/collections/src/types.ts, packages/@react-stately/grid/src/Column.ts, packages/@react-stately/grid/src/GridCollection.ts, packages/@react-stately/grid/src/Row.ts
This adds an example of adding and removing columns from a Table to storybook and tests, and fixes a bunch of issues that caused it to be broken. Mostly due to over-aggressive caching.
=> Support adding and removing columns in Table

packages/@adobe/spectrum-css-temp/components/table/index.css, packages/@react-spectrum/table/src/Table.tsx, packages/@react-spectrum/table/src/TableLayout.ts, packages/@react-spectrum/table/src/table.css, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-spectrum/table/test/Table.test.js, packages/@react-stately/collections/src/ListLayout.ts
This adds support for adjusting the row height of rows in a Table. It can be set to a fixed number, or `"auto"` to automatically measure the contents of each cell and size the rows accordingly. This enables each row height to be different potentially. This is also supported for column headers, which may wrap and make the row taller. 
By default, the `"auto"` behavior is off since it is considerably less performant due to all the measuring we have to do. In addition, there is one downside, which is that when horizontal scrolling occurs, we cannot properly measure all of the cells in a row, so it may get taller as you scroll horizontally if a really long cell is off the screen on initial render. I think we'll simply recommend that when horizontal scrolling is on, don't use auto row heights. …
=> Support variable row heights in Table and add layout tests

packages/@react-aria/grid/src/GridKeyboardDelegate.ts, packages/@react-aria/grid/src/useGrid.ts, packages/@react-spectrum/table/src/Table.tsx, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-spectrum/table/test/Table.test.js
This implements page up and page down support for Table, along with typeahead.
Page up/page down are implemented by passing the layout to GridKeyboardDelegate. If available, this will be used to get layout information instead of the DOM, so it works with virtualization. When starting from a cell, focus ends on a cell in the corresponding column. When starting on a row, it ends on a row.
Typeahead is implemented by looking at the text contents or `textValue` prop of the cells in columns marked as row headers. When starting from a cell, focus is moved to the row header cell with the matching text. When starting from a row, focus is moved to the row with the matching text.
=> Implement page up/page down and typeahead for Table

packages/@adobe/spectrum-css-temp/components/dialog/index.css, packages/@adobe/spectrum-css-temp/components/overlay/index.css
Bumps opacity to .9999 so background content isn't visible through Modals
Also will try to fix the dialog close button css (import order issue?) here
Opacity .99 (notice the faded black vertical line aka the scroll bar that bleeds through the middleish of the screenshot) :
vs
Opacity .9999
=> Followup Dialog fixes

packages/@adobe/spectrum-css-temp/components/table/index.css, packages/@adobe/spectrum-css-temp/components/table/skin.css, packages/@react-spectrum/table/src/Table.tsx
This adds a focus ring to table rows so that users can tell which row is focused, and also adds a background color to the row when a cell within it are focused. It also fixes the hover/focus background colors so they have better contrast.
=> Add focus ring to table rows and fix hover/focus color

packages/@react-spectrum/buttongroup/stories/ButtonGroup.stories.tsx
CTA buttons shouldn't be quiet
Closes
=> [storybook] Fix quiet button to not be cta button variant

packages/@react-spectrum/picker/test/Picker.test.js, packages/@react-stately/select/src/useSelectState.ts
Small bugfix. Previously, if you clicked on an already selected item, it would de-select it. This is incorrect behavior for Picker, so now it doesn't do that.
=> Don't deselect when pressing an already selected item in Picker

packages/@adobe/spectrum-css-temp/components/dropdown/index.css, packages/@react-aria/collections/src/CollectionView.tsx, packages/@react-aria/select/src/HiddenSelect.tsx, packages/@react-spectrum/listbox/intl/en-US.json, packages/@react-spectrum/listbox/package.json, packages/@react-spectrum/listbox/src/ListBoxBase.tsx, packages/@react-spectrum/listbox/stories/ListBox.stories.tsx, packages/@react-spectrum/listbox/test/ListBox.test.js, packages/@react-spectrum/picker/intl/en-US.json, packages/@react-spectrum/picker/package.json, packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-spectrum/picker/stories/Picker.stories.tsx, packages/@react-spectrum/picker/test/Picker.test.js, packages/@react-spectrum/table/intl/en-US.json, packages/@react-spectrum/table/src/Table.tsx, packages/@react-spectrum/table/test/Table.test.js, packages/@react-stately/collections/src/ListLayout.ts, packages/@react-stately/collections/src/TreeCollection.ts, packages/@react-stately/select/src/useSelectState.ts
This adds async loading and infinite scrolling support to ListBox and Picker. I needed an example of this for the docs that wasn't Table. Plus people have been asking for it and it's relatively simple to add.
=> Add async loading support for Picker and ListBox

packages/@adobe/spectrum-css-temp/components/table/index.css, packages/@react-aria/actiongroup/src/useActionGroup.ts, packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-aria/grid/src/useGridCell.ts, packages/@react-aria/grid/src/useSelectionCheckbox.ts, packages/@react-aria/grid/src/useTabKey.ts, packages/@react-aria/selection/package.json, packages/@react-aria/selection/src/useSelectableCollection.ts, packages/@react-aria/selection/src/useSelectableItem.ts, packages/@react-aria/sidenav/src/useSideNav.ts, packages/@react-aria/sidenav/test/useSideNav.test.js, packages/@react-aria/toggle/src/useToggle.ts, packages/@react-spectrum/actiongroup/src/ActionGroup.tsx, packages/@react-spectrum/checkbox/src/Checkbox.tsx, packages/@react-spectrum/sidenav/src/SideNav.tsx, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-spectrum/table/test/Table.test.js, packages/@react-spectrum/tree/src/Tree.tsx, packages/@react-stately/selection/src/useMultipleSelectionState.ts
This makes tables behave as a single tab stop, even though they may contain tabbable elements inside their cells. To navigate between cells, users must use the arrow keys. The tab key should navigate them in or out of the entire table.
This is slightly complicated to implement because we don't control the rendering of cell contents, so there's no good way for us to enforce `tabIndex={-1}`. So instead, we need to handle events and marshal focus to the correct element. However, we only want to do this when tabbing, not when focus moves in other ways (e.g. mouse, screen reader).
To accomplish this, we handle the Tab key ourselves for events within the table, and manually move focus to the next tabbable element before/after the table. This overrides the default browser behavior which would be …
=> Make table behave as a single tab stop

packages/@react-aria/selection/src/useSelectableItem.ts, packages/@react-spectrum/table/stories/CRUDExample.tsx, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-spectrum/table/test/Table.test.js, packages/@react-spectrum/test-utils/src/triggerPress.js, packages/@react-stately/data/src/useAsyncList.ts, packages/@react-stately/data/src/useListData.ts, packages/@react-stately/data/test/useListData.test.js, packages/@react-stately/select/src/useSelectState.ts, packages/@react-stately/selection/src/SelectionManager.ts, packages/@react-stately/selection/src/types.ts, packages/@react-stately/selection/src/useMultipleSelectionState.ts, packages/@react-types/shared/src/collections.d.ts
When select all is active, new items that are added to the table (e.g. when infinite scrolling) are automatically shown as selected. This is true when users click the select all checkbox or use Ctrl + A. If they manually select each item in the table, then new items will not be automatically selected.
This is implemented by adding a special selection type. `selectedKeys` can now be the string `"all"` or a list of keys, and `onSelectionChange` also reflects this. This allows bulk actions that operate on the selection to change their behavior when everything is selected (e.g. a different API call), so that if affects all items rather than just loaded ones.
This PR also adds a bunch of tests for various selection behavior including select all, range selection, etc.
=> Implement select all behavior for infinite scrolling

packages/dev/docs/src/Layout.js, packages/dev/docs/src/ResourceCard.js, packages/dev/docs/src/types.js, packages/dev/docs/src/utils.js
Fixes a privacy issue.
While this issue was being fixed, it was useful to add spectrum styling to links in the description of the props table.
Before:
After:
Closes 
React spectrum
=> Add rel="noreferrer" to external links

packages/dev/docs/src/Layout.js, packages/dev/docs/src/docs.css
This avoids two extra http calls on page load, one of which is to a different domain (p.typekit.net).
Note: the downside here is that the typekit script could be updated behind the scenes and we would be out of date. However, we are already hardcoded with preload tags, so this would already happen. It would be manual either way.
Closes 
There should be 2 fewer http requests (one to use.typekit.net and one to p.typekit.net) on every page load.
React Spectrum
=> Inline font-face declarations from external css into docs.css

packages/@react-aria/searchfield/src/useSearchField.ts, packages/@react-aria/searchfield/test/useSearchField.test.js, packages/@react-spectrum/buttongroup/src/ButtonGroup.tsx
Closes https://jira.corp.adobe.com/browse/RSP-1760
Go to SearchField onClear story. Test clearing the field with ESC key and by clicking the 'x' button in the field. Verify that the clear action in the storybook action panel is called with `[ ]` meaning it is passed nothing
=> (RSP-1760) Stop passing press event to onClear 

packages/@adobe/spectrum-css-temp/components/dropdown/index.css, packages/@react-spectrum/picker/src/Picker.tsx
this file set it to always flex column, so needed to override that
Closes https://jira.corp.adobe.com/browse/RSP-1767
=> (Picker) "isQuiet, labelPosition=side" story has label on top

.circleci/config.yml
Skip the V2 package installation when NPM_PASSWORD isn't set so that builds pass for open source pull requests.
=> Skip the V2 package installation when NPM_PASSWORD isn't set

packages/@react-aria/listbox/src/useOption.ts, packages/@react-spectrum/listbox/test/ListBox.test.js
Closes https://jira.corp.adobe.com/browse/RSP-1742
Go to default ListBox story with voiceover on and navigate through the list. The first item should say "1 of 9" instead of "0 of 9"
=> (RSP-1742) Updating aria-posinset in useOption so it is index origin 1

packages/@adobe/spectrum-css-temp/components/dialog/index.css
I hope I'm not undoing something intentional
Some other potential options, put margins around form and accept that they won't edge align with the divider?
Do the above, but also shrink in the header/divider etc?
Put padding on ALL semantic container elements?
Closes https://jira.corp.adobe.com/browse/RSP-1779
=> Dialog needs extra padding top/bottom for focus ring

packages/@react-spectrum/breadcrumbs/test/Breadcrumbs.test.js, packages/@react-spectrum/dialog/src/AlertDialog.tsx, packages/@react-spectrum/dialog/src/Dialog.tsx, packages/@react-spectrum/illustratedmessage/src/IllustratedMessage.tsx
we shouldn't spread styleprops directly on a react spectrum component, only on dom elements. as a result, unpack it and pass it through the appropriate way
Closes https://jira.corp.adobe.com/browse/RSP-1725
=> Cleanup use of style prop in Alert Dialog

packages/@adobe/spectrum-css-temp/components/dialog/index.css, packages/@adobe/spectrum-css-temp/components/modal/index.css
This adds the css fix to account for the safari navigation bar
it still has some oddities, such as clicking a button causes it to bring up the navigation bar, the buttons then correctly render over it
Closes
=> Fix buttons redering under safari nav bar in mobile fullscreen dialogs

packages/@adobe/spectrum-css-temp/components/checkbox/index.css, packages/@adobe/spectrum-css-temp/components/radio/index.css, packages/@adobe/spectrum-css-temp/components/toggle/index.css
This was causing it to eat mouse events from a picker opened over the top of it due to `isolation: isolate`. It's also unnecessary, because the label wraps the entire radio and causes a click on the actual input.
=> Remove z-index from checkbox, radio, and switch

packages/@react-aria/overlays/src/calculatePosition.ts, packages/@react-aria/overlays/test/useOverlayPosition.test.js
use clientHeight instead of innerHeight to fix Picker height with window scrollbars
Closes https://jira.corp.adobe.com/browse/RSP-1791
=> Fix Picker height with window scrollbars

packages/@react-spectrum/button/test/Button.test.js, packages/@react-spectrum/link/test/Link.test.js
jsdom has only implemented hash changes to navigation
as noted https://github.com/adobe-private/react-spectrum-v3/pull/502
Closes
=> fix error of class Not implemented: navigation

packages/@adobe/spectrum-css-temp/components/checkbox/skin.css
Increase selector specificity because it was losing to the ui icon definition
Closes https://jira.corp.adobe.com/browse/RSP-1795
=> Debug why Checkboxes in docs aren't the right color

packages/@adobe/spectrum-css-temp/components/tray/index.css
The tray backdrop seems to have been catching the click and somehow sending focus to the body when in an iframe. Not entirely sure why. Adding `pointer-events: none` fixes it. This was already in `.spectrum-Modal-wrapper`.
=> Fix picker closing on blur on Chrome Android

packages/@react-aria/interactions/src/useFocusVisible.ts
This fixes the issue where a focus ring is visible on the first click of a component inside an iframe in Firefox. This was due to an extra focus event that Firefox fires where the target is `document`. No other browser fires this event, and it was messing up our internal focus visibility state. This event is now ignored.
=> Fix focus ring on first click in iframe in Firefox

packages/@adobe/spectrum-css-temp/components/menu/index.css
Overriding DNA for now. Sent a PR also: https://git.corp.adobe.com/Spectrum/spectrum-dna/pull/409.
Before:
After:
=> Fix menu item padding in large scale

packages/@adobe/spectrum-css-temp/components/dropdown/index.css, packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx, packages/@react-spectrum/picker/src/Picker.tsx
Max width for menus set to 320px as per spectrum. Icons, keyboard shortcuts, checkmark, key/value, etc. all now top aligned.
=> Update max width and alignment for menu items

packages/@adobe/spectrum-css-temp/components/checkbox/index.css, packages/@adobe/spectrum-css-temp/components/radio/index.css, packages/@adobe/spectrum-css-temp/components/toggle/index.css
Try isolating three common components with z-index specified so we can test on browsers between checkmarks and tables, and picker and radio
Closes
=> Try isolation on checkbox and radio

packages/@adobe/spectrum-css-temp/components/dropdown/index.css, packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@react-spectrum/menu/src/MenuTrigger.tsx, packages/@react-spectrum/picker/src/Picker.tsx
=> Fix to Menu max width so it doesn't apply on Menu Trays

packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@adobe/spectrum-css-temp/components/menu/skin.css, packages/@adobe/spectrum-css-temp/vars/spectrum-large.css, packages/@adobe/spectrum-css-temp/vars/spectrum-medium.css, packages/@react-spectrum/listbox/src/ListBoxBase.tsx, packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx
The estimated heights weren't matching the real heights after my last PR, so there was extra "margin" between the items. Also the padding was much too small in large scale. Adjusted to match the XD file, but required an override of DNA for now.
Also fixed typeahead in the complex items example in MenuTrigger, and the color of the menu item description text.
=> Fix menu item heights

package.json, packages/dev/docs/src/FunctionAPI.js, packages/dev/docs/src/Layout.js, packages/dev/docs/src/docs.css, packages/dev/docs/src/syntax-highlight.css, packages/dev/docs/src/types.js, packages/dev/parcel-transformer-mdx-docs/MDXFragments.js, packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js, packages/dev/parcel-transformer-mdx-docs/package.json, yarn.lock
This makes the code examples in the docs responsive, and ensures they are formatted consistently. It runs each example through prettier at three widths: 25 characters, 60 characters, and 80 characters. These all get placed in the output HTML with separate classes, and we use media queries to switch between them. So on small screens, you'd get more wrapping than large screens, but the wrapping is "smart" and includes proper indentation.
In some cases, e.g. on super small screens, there may still be some overflow, and this has been changed to wrap rather than horizontally scroll as recommended by the accessibility team. But because of the prettier formatting, this should be much more rare.
Also adjusted the API types the same way, and fixed some issues with syntax highlighting of multiple …
=> Responsive code examples

packages/@react-spectrum/button/docs/ActionButton.mdx
=> Removing isEmphasized and isSelected example from ActionButton docs

packages/@react-spectrum/button/docs/ActionButton.mdx, packages/@react-spectrum/button/src/ActionButton.tsx, packages/@react-spectrum/button/src/FieldButton.tsx, packages/@react-spectrum/button/stories/ActionButton.stories.tsx, packages/@react-spectrum/button/test/ActionButton.test.js, packages/@react-types/actiongroup/src/index.d.ts, packages/@react-types/button/src/index.d.ts
holdAffordance, elementType, href, target
Closes https://jira.corp.adobe.com/browse/RSP-1806
=> Remove unsupported props from ActionButton

packages/@react-aria/radio/src/useRadioGroup.ts, packages/@react-spectrum/radio/test/Radio.test.js
Let key events that we aren't handling continue
I don't know why the jest test can't catch it...
Pushing anyways so that i can at least get feedback
Closes
=> Fix RadioGroup can be tabbed through each Radio

packages/@react-stately/collections/src/CollectionBuilder.ts
We were accidentally incrementing an extra time sometimes, and we rely on these keys for things like selection, so probably best if they follow the right pattern
Closes
=> Fix collectionbuilder unique keys

packages/@react-aria/interactions/src/useFocusVisible.ts, packages/@react-aria/select/src/HiddenSelect.tsx
This avoids false positive in automated accessibility checks for the hidden input inside Picker. The error was that focusable elements cannot be inside an `aria-hidden` container. The hidden input is used to marshal focus on mobile, so we can't get rid of it. To work around this, we set its `tabIndex` to `-1` until a user actually interacts with the page in any way. This way, automated checkers that just look at the DOM with doing any interaction won't fail.
This is accomplished by refactoring the existing listeners in `useFocusVisible` to expose the current interaction modality. If it's null, then the user hasn't interacted with the page yet.
=> Avoid false positive in a11y checkers for Picker hidden input

packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@adobe/spectrum-css-temp/components/checkbox/index.css, packages/@adobe/spectrum-css-temp/components/radio/index.css, packages/@adobe/spectrum-css-temp/components/toggle/index.css
This forces the halo to be rendered on the pixel grid instead of slightly off which caused it to look like one side was thinner than the other due to anti-aliasing
see https://github.com/adobe/spectrum-css/pull/742
Closes
=> Fix focus halo stroke width in FF

packages/@adobe/spectrum-css-temp/components/checkbox/index.css, packages/@adobe/spectrum-css-temp/components/checkbox/skin.css
If you try to scroll in tableview with the arrow keys while on the checkbox column it becomes very jumpy because of the box-shadow transition
Instead, have the box-shadow always there and only change it's opacity
We should be doing this to more items... it's a huge savings
Closes
=> Smooth checkbox focus animation

packages/@adobe/spectrum-css-temp/components/actiongroup/index.css, packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@adobe/spectrum-css-temp/components/button/skin.css, packages/@react-spectrum/actiongroup/src/ActionGroup.tsx, packages/@react-spectrum/actiongroup/stories/ActionGroup.stories.tsx, packages/@react-spectrum/actiongroup/stories/styles.css, packages/@react-spectrum/button/docs/ActionButton.mdx, packages/@react-spectrum/button/docs/Button.mdx, packages/@react-spectrum/button/stories/ActionButton.stories.tsx, packages/@react-spectrum/button/stories/Button.stories.tsx, packages/@react-spectrum/layout/src/Flex.tsx, packages/@react-spectrum/layout/src/flex.css
This fixes ActionGroup wrapping behavior so that there is space between the rows and no extra margin at the start of each row. It uses the same technique used by our `<Flex>` component to implement `gap`. We cannot actually use this component though due to API limitations, so for now, I've copied the CSS into action group. We should move this somewhere shared later so other things in Spectrum CSS can use it.
=> Fix ActionGroup wrapping

packages/@react-spectrum/buttongroup/src/ButtonGroup.tsx
Noticed that the buttongroup button focus ring was a bit off, updated the calculation to take in account the negative margin applied by the halo focus ring.
=> Update calculation to accomodate for focus ring gap margin

packages/@adobe/spectrum-css-temp/components/breadcrumb/index.css, packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx, packages/@react-spectrum/breadcrumbs/stories/Breadcrumbs.stories.tsx, packages/@react-spectrum/breadcrumbs/test/Breadcrumbs.test.js, packages/@react-types/breadcrumbs/src/index.d.ts
This rewrites the breadcrumbs resizing behavior to match Spectrum design better. The `maxVisibleItems` prop is gone. Instead, the behavior is as follows:
* We show a max of 4 items. If there are more than 4 items, they are collapsed into a menu.
* The menu counts as one of the 4 items, so if a menu is shown, up to 3 additional items are visible.
* If the `showRoot` option is passed, it is shown in addition to the menu if it fits. If it does not fit, then the root is hidden and also collapsed into the menu. The root item counts as one of the 4 visible items.
* The last breadcrumb truncates with an ellipsis if there isn't enough room.
In order to do this, we need to do up to 3 re-renders to measure the breadcrumbs. First, we re-render to show all breadcrumbs, and measure them to see how …
=> Fix breadcrumbs resizing behavior

packages/@adobe/spectrum-css-temp/components/modal/index.css
Adds a min-width to the modal equal to the dialog min width. This stops the contents of the dialog from spilling out of the modal at screen sizes smaller than 280 px like so:
=> set modal min width to dialog min width

packages/@adobe/spectrum-css-temp/components/dialog/index.css, packages/@react-spectrum/buttongroup/src/ButtonGroup.tsx
=> Fix firefox buttongroup without breaking dialog headers

packages/@react-aria/radio/src/useRadio.ts, packages/@react-aria/radio/src/useRadioGroup.ts, packages/@react-spectrum/radio/test/Radio.test.js
Calling `.click()` in Safari prevented scrolling to that radio for some reason. Instead, update our state directly. Also ensure that we pass through the `value` prop to the `<input>` element.
=> Fix scrolling to radios in Safari

scripts/bumpVersions.js
This updates the version bumping script to support multiple statuses, e.g. alpha, beta, rc, and released. Starting from the react-spectrum packages, all dependencies are marked with the same status (e.g. `@react-aria/button` would have the same status as `@react-spectrum/button`). The versions of each package are then updated according to semver rules within this status.
=> Update version bumping script

packages/@react-types/statuslight/src/index.d.ts
Children shouldn't be required. You can provide an `aria-label` instead.
=> Fix status light types

packages/@react-spectrum/dialog/docs/Dialog.mdx
This ensures the docs are correct per https://spectrum.adobe.com/page/dialog/#Primary-action-label.
> The primary action label is for the first (right-most) button.
React Spectrum
=> Ensure cta is the first button in dialog docs

packages/@react-spectrum/listbox/stories/ListBox.stories.tsx, packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx
no jira
adding selected items to the autoFocus=true menu and listbox stories since they mean focus on the selected item. For listbox it worked without setting a selectionMode, but that seemed weird to focus on something that wasn't visible selected.
autoFocus=true stories for menu and listbox focus on items now
RSP
=> adding selected items to autofocus=true stories to menu/list

packages/@react-types/radio/src/index.d.ts
`AriaRadioGroupProps` depends on `RadioGroupProps` and is an input type for `useRadioGroup`, as this hook is not responsible for rendering it doesn't really depend on things like `children` so it doesn't make sense to require it there. From what I understand this prop might actually be needed for `SpectrumRadioGroupProps` as it's the puzzle piece that is responsible for actual rendering 😉
=> Move children prop definition from RadioGroupProps to SpectrumRadioGroupProps

packages/dev/docs/src/PropTable.js, packages/dev/docs/src/syntax-highlight.css, packages/dev/docs/src/types.js
This ensures the Spectrum colors we use for syntax highlighting are accessible for both light and dark theme. The celery, orange, and yellow are replaced with green, purple, and indigo.
=> Accessible colors for syntax highlighting

package.json, packages/@react-aria/tabs/src/useTabList.ts, packages/@react-spectrum/tabs/src/TabList.tsx, packages/@react-stately/tabs/src/useTabListState.ts, packages/@react-types/listbox/package.json, packages/@react-types/menu/package.json, yarn.lock
2 things:
1. a couple instances where these had higher deps verses other packages
2. when running `tsc` with `skipLibCheck: false` there would be multiple conflicting copies of `@types/react` floating around. This attempts to unify on a single version and reduces the number of errors (when running the aformentioned command) from around ~200-300 to ~50.
This fixes a number of linting errors that occur with the `Tab` and `TabList` work. I know this is going to be reconsidered, so I provided workarounds for now.
React Spectrum
=> Unify react versions in the packages

packages/@react-aria/toast/src/useToast.ts, packages/@react-aria/toast/test/useToast.test.js, packages/@react-spectrum/alert/src/Alert.tsx, packages/@react-spectrum/icon/src/Icon.tsx, packages/@react-spectrum/icon/src/UIIcon.tsx, packages/@react-spectrum/icon/test/Icon.test.js, packages/@react-spectrum/icon/test/UIIcon.test.js, packages/@react-spectrum/label/src/Label.tsx, packages/@spectrum-icons/color/stories/IconsColor.stories.tsx, packages/@spectrum-icons/workflow/stories/IconsWorkflow.stories.tsx, packages/dev/docs/src/Layout.js, packages/dev/docs/src/types.js, specs/api/Icon.md
Replaced alt prop with aria-label only.
Removed color as it is not supported.
Use scale from Provider.
=> Icons - clean up api

packages/@react-spectrum/textfield/test/TextField.test.js
A new test was added that caused this warning   'If you do not provide a visible label, you must specify an aria-label or aria-labelledby attribute for accessibility'
Closes https://github.com/adobe-private/react-spectrum-v3/pull/502
=> Fix class of error No visible label

packages/@react-aria/listbox/src/useOption.ts
With Safari and VoiceOver, options using `aria-labelledby` or `aria-label` to label the item by referencing an internal content slot are announced simply as "Text". Fix may be to not use `aria-labelledby` or `aria-describedby` to label the option using slots, and simply allow the option to be labeled by its textContent.
Closes [RSP-1746](https://jira.corp.adobe.com/browse/RSP-1746)
1. On MacOS with VoiceOver running, open https://reactspectrum.blob.core.windows.net/reactspectrum/4ac4e0d7a3c371215be9a6d990ca577266294815/storybook/iframe.html?id=listbox--with-semantic-elements-static in Safari
2. Navigate into the listbox
3. Verify that VoiceOver announces each option item using its full textContent, rather than just announcing "text"
4. In Chrome, VoiceOver will announce each item, but …
=> RSP-1746 [Safari/VoiceOver] Listbox options with aria-labelledby announce as "Text"

packages/@react-aria/textfield/src/useTextField.ts
SearchField is causing this message anytime a defaultValue is specified on it because it just goes right through all the props and through the useTextField aria hook.
Fix error class   '%s contains an input of type %s with both value and defaultValue props',
I'm not sure this is the best way to do it, because this will silently protect people from having both value and defaultValue
I don't want to remove defaultValue because aria should view that as an acceptable prop
Maybe useControlledValue should export a function to remove the defaultValue and we call that in the component? seems like a lot to remember :(
Closes https://github.com/adobe-private/react-spectrum-v3/pull/502
=> Fix error class both value and defaultValue props

packages/@react-aria/selection/src/useSelectableItem.ts, packages/@react-spectrum/actiongroup/test/ActionGroup.test.js, packages/@react-spectrum/dialog/stories/DialogTrigger.stories.tsx, packages/@react-spectrum/table/test/Table.test.js
The `useLayoutEffect` that focused the item ran before the `useLayoutEffect` in the enclosing FocusScope. This cause the scope to not be registered, and the popover stole focus back since it did not occur within a known scope.
=> RSP-1841: Fix menu trigger with auto focus inside a popover

packages/@react-spectrum/actiongroup/src/ActionGroup.tsx, packages/@react-spectrum/layout/src/Flex.tsx, packages/@react-spectrum/layout/src/Grid.tsx, packages/@react-spectrum/radio/src/Radio.tsx, packages/@react-spectrum/radio/src/RadioGroup.tsx, packages/@react-spectrum/statuslight/src/StatusLight.tsx
The descriptions must be on the forwardRef assignment, not on the original function for TS to pick them up when generating d.ts files for publishing.
=> Move jsdoc descriptions to forwardRef

packages/@react-spectrum/provider/src/Provider.tsx
Closes https://jira.corp.adobe.com/browse/RSP-1846
The nested provider message goes away on the false positives and is a dir message is there with nested dir's.
RSP
=> changing the provider nested lang check to a dir check

packages/@react-aria/interactions/test/usePress.test.js
As noted https://github.com/adobe-private/react-spectrum-v3/pull/502
Closes
=> Fix error class React does not recognize the prop on a DOM element

packages/dev/docs/pages/react-spectrum/getting-started.mdx, packages/dev/docs/pages/react-spectrum/theming.mdx, packages/dev/docs/pages/react-spectrum/versioning.mdx, packages/dev/docs/src/HeaderInfo.js, packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js, scripts/buildWebsite.js, yarn.lock
Depends on #706.
This updates the docs when building for production to show imports to the monopackage instead of the individual packages. This is implemented as a simple babel plugin that runs over each example to convert the imports when needed. With a little hacking, I was also able to avoid needing to convert the AST back to code with babel and then reparse it in prettier by making prettier use the babel ast directly.
=> Display monopackage imports in the docs when building for production

packages/@react-spectrum/provider/docs/Provider.mdx, packages/@react-spectrum/provider/src/Provider.tsx, packages/@react-types/provider/src/index.d.ts
The Provider docs needed to have a little more info relating to the use of certain props and when nesting makes sense. I also changed a few examples to remove things like setting scale since we do not advise people to do that. 
Updated the descriptions.
=> Add more info about root vs provider in docs

packages/@react-aria/interactions/src/useInteractOutside.ts, packages/@react-aria/overlays/src/useOverlay.ts
Closes [RSP-1859](https://jira.corp.adobe.com/browse/RSP-1859)
Steps to reproduce:
1. open docs site to [https://react-spectrum.adobe.com/react-aria/useListBox.html]
2. click code example link: labelled "AriaListBoxOptions" to open popover
3. within Popover, click "CollectionChildren" link
4. within Popover, click "CollectionElement" link
5. within Popover, click "SectionElement" link
6. within Popover, click "SectionProps" link, Breadcrumbs will collapse to show menu button
7. click Breadcrumbs menu button to expand menu
8. using mouse, click a menu item before the current selection
Expected behavior:
Menu should close without also closing the Popover, and the contents of the Popover should update based on the selected breadcrumb.
Actual behavior:
Both the Menu and the Popover close, and …
=> fix RSP-1859 Clicking Breadcrumb MenuItem within Popover in Documentation closes Popover

package.json, packages/@react-spectrum/icon/package.json, scripts/buildWebsite.js
Dev dependencies won't be installed from published packages when building the docs for production
=> Move docs dev dependency to root package.json

packages/dev/docs/src/Layout.js
Provide unique label names for permalink links in documentation.
Closes [RSP-1863](https://jira.corp.adobe.com/browse/RSP-1863)
1. Run yarn start:docs, open http://localhost:1234/react-aria/useListBox.html
2. Verify that each permalink within each heading has a unique label like: "Direct link to Features"
Accessibility
=> RSP-1863 [Docs][A11y] Improve permalink labeling

packages/@react-spectrum/icon/docs/workflow-icons.mdx
Removes the icon table for now. Likely a parcel issue where the css for textfield wasn't getting placed in the correct bundle groups. Luckily, Spectrum already has an icon page we can link to in the meantime.
=> Workaround search field css issue

packages/dev/docs/pages/contribute.mdx
no jira/issue
goto the contributing page in the docs
confirm the instructions to start storybook are `yarn start`
RSP
=> fixed a command to start storybook in contributing docs

packages/dev/docs/pages/blog/PostListing.js, packages/dev/docs/pages/blog/index.mdx, packages/dev/docs/pages/blog/introducing-react-spectrum.mdx, packages/dev/docs/src/Layout.js, packages/dev/docs/src/docs.css, packages/dev/parcel-optimizer-ssg/SSGOptimizer.js, packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js
Depends on #733.
This adds a blog section to the website, along with the first post. The blog works slightly different from other sections of the site. Rather than listing the posts in the sidebar, the blog lives at the root of the site. There's a separate post listing page that can be used to navigate to one of the individual blog post pages. Each post works similarly to our existing pages. The only addition is a date property in the metadata which is used to display the post date in both the listing and individual pages. Finally, there's an `image` meta property which is used to generate the `og:image` meta tag for social sharing.
=> Add blog to website

packages/@react-aria/interactions/docs/useKeyboard.mdx
In the `useKeyboard` doc it has an example using both the `onKeyDown` and `onKeyUp` handlers, but both were actually using `onKeyDown`. I've changed the second handler to `onKeyUp` since it seems that was intended.
```tsx example
let {keyboardProps} = useKeyboard({
onKeyDown: e => setEvents(
events => [`key down: ${e.key}`, ...events]
),
onKeyUp: e => setEvents(
events => [`key up: ${e.key}`, ...events]
)
});
```
=> Fix useKeyboard example

packages/dev/docs/src/HeaderInfo.js
Hey,
Was just trying out react-aria and noticed the docs have an incorrect import in the usage section.
This PR attempts to fix that.
Current Behaviour:
Expected behaviour (I think, not sure):
There's not really a github issue for this and didn't really wanna open one as I might as well just fix it right away :)
Congrats on the release and looking forward to using react-aria a lot in the future
Closes
=> keep package name for everything except react-spectrum

packages/@react-aria/interactions/src/useFocusVisible.ts
`setupGlobalFocusEvents` should check if window exists to prevent crash on server side.
cc @Skona27
Closes #767
=> Check is window exists in setupGlobalFocusEvents

packages/@react-aria/utils/docs/mergeProps.mdx, packages/@react-aria/utils/src/mergeProps.ts, packages/@react-aria/utils/test/mergeProps.test.js
Currently `mergeProps` only allows 2 arguments to be passed in at a time, which results in extra nesting whenever there are more than 2 prop objects that need to be merged, as seen in [this example](https://codesandbox.io/s/playing-with-react-aria-wvcjd?file=/src/App.js:1346-1417).
So instead of:
```js
let props = mergeProps(mergeProps(buttonProps, hoverProps), focusProps)
```
You can just do:
```js
let props = mergeProps(buttonProps, hoverProps, focusProps)
```
@devongovett [mentioned on twitter](https://twitter.com/devongovett/status/1283881587516424192) that the team ran into issues with TypeScript handling an arbitrary number.
I was able to [find a solution on stackoverflow](https://stackoverflow.com/questions/51603250/typescript-3-parameter-list-intersection-type/51604379#51604379) …
=> Allow arbitrary number of prop objects to be passed to mergeProps

packages/dev/docs/pages/react-spectrum/versioning.mdx, packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js, yarn.lock
Closes #765 
Add `keepIndividualImports` tag to retain the individual package imports for specific code samples.
```tsx keepIndividualImports
import {Button} from '@react-spectrum/button';
```
-> https://reactspectrum.blob.core.windows.net/reactspectrum/aa4130204964a98a4b8d99a3fed05e217bb1e88a/docs/react-spectrum/versioning.html#using-individual-packages
=> Docs: keepIndividualImport

packages/@react-spectrum/menu/src/MenuItem.tsx, packages/@react-spectrum/menu/test/MenuTrigger.test.js
Closes 
Create a menu with `selectedKeys` defined but no `selectionMode` prop and see that no items are selected
Adobe
=> Use selection manager isSelected method to check if menuitem is selected

packages/@react-aria/select/src/HiddenSelect.tsx, packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-spectrum/picker/test/Picker.test.js
Closes #786 
You can test this PR by running the new tests in `Picket.test.js`. You can also manually test this PR by going to the Picker docs in storybook and looking at the disabled section. Found [here](http://localhost:1234/react-spectrum/Picker.html#disabled). You can then inspect the input and find the hidden input in the DOM. You can see that they now have `disabled` DOM attribute on them when previously they didn't.
=> Adding disabled attribute to HiddenInput

packages/@react-spectrum/picker/test/Picker.test.js, packages/@react-stately/list/src/index.ts, packages/@react-stately/list/src/useSingleSelectListState.ts, packages/@react-stately/select/src/useSelectState.ts
This refactors some of the logic currently in `useSelectState` into a `useSingleSelectListState` hook that's more reusable. This hook handles mapping the props for components supporting single selection to the internal state which is stored as a set of one key. This should allow reuse in other components that support only single selection, e.g. combo box, tabs, and accordion.
One difference that was introduced: `onSelectionChange` is now always fired, regardless of whether the key actually changed. This was to ensure that the picker closes when selecting the same item, but I think there are other use cases to know when a user selected the same item as before and this matches what happens with multiple selection more closely (`new Set() !== new Set()`).
=> Add useSingleSelectListState

packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js
Closes #800
Fixup for #792
I still don't know why it worked correctly with `yarn build:docs` (and also in the CI preview) and not with `make website-production`
=> Fixup keepIndividualImports

packages/@react-aria/interactions/src/useHover.ts, packages/@react-aria/interactions/test/useHover.test.js
This works around a bug in iOS Safari that fires the `onPointerEnter` and `onMouseEnter` between the `onPointerUp` and `onFocus` events. This caused `onPointerEnter` to be fired twice: once on touch and once before focus, which meant that `useHover` fired a hover event even though you're on a touch device. Webkit bug filed here: https://bugs.webkit.org/show_bug.cgi?id=214609.
The workaround is to register a global event listener for the `pointerup`/`touched` event, which sets a flag and unsets it after a quick timeout (after the `onFocus` event). This handles two scenarios: the iOS case where `onPointerEnter` is fired prior to focus, and the non-iOS case where this event is not fired. In that case, we do not want to leave the flag hanging, because if the user switched to a mouse after …
=> Workaround for iOS hover events bug

packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx
The name for this story was misleading because it couldn't handle selections
Closes
=> Fix MenuTrigger story

packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@adobe/spectrum-css-temp/components/textfield/index.css, packages/@react-spectrum/actiongroup/src/ActionGroup.tsx
Missed a hover style in ActionGroup
Add transitions to hover for icons in buttons and textfields
Closes
=> Fix hover styles

packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@adobe/spectrum-css-temp/components/button/skin.css, packages/@adobe/spectrum-css-temp/components/search/index.css, packages/@adobe/spectrum-css-temp/components/search/skin.css, packages/@adobe/spectrum-css-temp/components/textfield/index.css, packages/@adobe/spectrum-css-temp/components/textfield/skin.css, packages/@react-spectrum/button/src/ClearButton.tsx
can't transition color in svg's on safari, use fill instead
Closes
=> Change icon transition from color to fill

packages/@react-spectrum/button/src/ActionButton.tsx, packages/@react-spectrum/button/src/Button.tsx, packages/@react-spectrum/button/src/ClearButton.tsx, packages/@react-spectrum/button/src/FieldButton.tsx, packages/@react-spectrum/button/src/LogicButton.tsx, packages/@react-spectrum/checkbox/src/Checkbox.tsx, packages/@react-spectrum/datepicker/src/DatePicker.tsx, packages/@react-spectrum/datepicker/src/DateRangePicker.tsx, packages/@react-spectrum/menu/src/MenuItem.tsx, packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-spectrum/radio/src/Radio.tsx, packages/@react-spectrum/sidenav/src/SideNavItem.tsx, packages/@react-spectrum/switch/src/Switch.tsx, packages/@react-spectrum/tag/src/Tag.tsx, packages/@react-spectrum/textfield/src/TextFieldBase.tsx
Also prevent unintentionally passing through undocumented hover event props by passing props directly to `useHover`. We only need to pass through `isDisabled`.
=> Fix placeholder hover styles in Picker

packages/@react-aria/interactions/docs/useHover.mdx, packages/@react-stately/list/docs/useSingleSelectListState.mdx, packages/dev/docs/pages/blog/index.mdx, packages/dev/docs/pages/releases/2020-07-23.mdx, packages/dev/docs/pages/releases/index.mdx, packages/dev/docs/src/Layout.js, packages/dev/docs/src/PostListing.js, packages/dev/docs/src/index.js
Adds a releases section to the top-level nav. It's structured similar to the blog, with a page for each release and a listing page showing the latest one at the top. Also added docs for the new `useSingleSelectListState` hook, and updated `useHover` for the added `isHovered` return value.
=> Add releases section and update docs for latest release

jest.config.js, jest.ssr.config.js, package.json, packages/@react-spectrum/button/test/Button.ssr.test.js, packages/@react-spectrum/checkbox/test/Checkbox.ssr.test.js, packages/@react-spectrum/dialog/test/Dialog.ssr.test.js, packages/@react-spectrum/divider/test/Divider.ssr.test.js, packages/@react-spectrum/form/test/Form.ssr.test.js, packages/@react-spectrum/test-utils/package.json, packages/@react-spectrum/test-utils/src/SSREnvironment.js, packages/@react-spectrum/test-utils/src/hydrateWorker.js, packages/@react-spectrum/test-utils/src/ssrUtils.js, packages/@react-spectrum/test-utils/src/testSSR.js, patches/@jest+types++chalk+3.0.0.patch
Related to #760, #699 
This sets up a test harness for server side rendering support. The main objective is to ensure that every component supports being rendered in an environment without access to DOM globals (e.g. `window`/`document`), and that the HTML that is rendered can be hydrated without any React warnings/errors on the client side (e.g. non-matching props between server and client).
This is accomplished by setting up a separate Jest test suite that runs in a node environment instead of a jsdom environment. A utility function called `testSSR` will then render each component in this environment to ensure no errors on the server side. Then, the HTML output of this is sent to a separate worker thread which is running in a JSDOM environment. The worker attempts to use the React code …
=> Setup SSR test harness

NOTICE.txt, packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx, packages/@react-spectrum/breadcrumbs/src/ResizeObserver.d.ts
Use ResizeObserver instead of listening on window resize on Breadcrumbs component
Closes https://github.com/adobe/react-spectrum/issues/773
=> Use ResizeObserver instead of listening on window resize

packages/@react-aria/select/docs/useSelect.mdx, packages/@react-stately/collections/docs/collections.mdx
=> Add missing ref to useButton in useSelect example

packages/@react-aria/selection/src/useTypeSelect.ts, packages/@react-aria/sidenav/test/useSideNav.test.js, packages/@react-spectrum/listbox/test/ListBox.test.js, packages/@react-spectrum/picker/src/Picker.tsx
Closes #851
1. Go to storybook
2. Go to **ListBox > ListBox w/ many sections and selection**
3. Make sure the listbox is in focus
4. Type in an item name including the space character; e.g. `Section 8`
5. If the item is highlighted without being selected, tests 1/2 pass ✅ 
6. Wait about a second or so (to clear the typeahead timeout), then press the *Spacebar* on your keyboard
7. If the item is selected, tests 2/2 pass ✅ 
8. Everything is fine, nothing is ruined
Adobe React-Spectrum
=> Fix ListBox typeahead spacebar issue

packages/@react-spectrum/numberfield/test/NumberField.test.js, packages/@react-types/tabs/package.json, scripts/buildWebsite.js
* Mark tabs package as private so it isn't part of the website build
* Only copy the babel patch into the sandbox, not jest patch. Was causing patch-package to fail within the sandbox because jest isn't installed there.
=> Fix production website build

packages/@react-types/shared/src/labelable.d.ts
Related to: https://github.com/adobe/react-spectrum/pull/868#discussion_r464361906
=> Move isRequired from LabelableProps to SpectrumLabelableProps

packages/@react-aria/slider/index.ts, packages/@react-aria/slider/package.json, packages/@react-aria/slider/src/index.ts, packages/@react-aria/slider/src/useMultiSlider.ts, packages/@react-aria/slider/src/useSlider.ts, packages/@react-aria/slider/src/useSliderThumb.ts, packages/@react-aria/slider/src/utils.ts, packages/@react-aria/slider/stories/Slider.stories.tsx, packages/@react-aria/slider/stories/StoryMultiSlider.tsx, packages/@react-aria/slider/stories/StoryRangeSlider.tsx, packages/@react-aria/slider/stories/StorySlider.tsx, packages/@react-aria/slider/stories/story-slider.css, packages/@react-aria/slider/test/useSlider.test.js, packages/@react-aria/slider/test/useSliderThumb.test.js, packages/@react-aria/utils/src/useDrag1D.ts, packages/@react-stately/slider/index.ts, packages/@react-stately/slider/package.json, packages/@react-stately/slider/src/index.ts, packages/@react-stately/slider/src/useMultiSliderState.ts, packages/@react-stately/slider/src/useSliderState.ts, packages/@react-stately/slider/test/useSliderState.test.js, packages/@react-types/slider/README.md, packages/@react-types/slider/package.json, packages/@react-types/slider/src/index.d.ts
This creates:
* `useMultiSliderState` for @react-stately/slider for managing slider state for multiple values
* `useMultiSlider` for @react-aria/slider for managing interactions and accessibility for slider components
Includes some Storybook stories and toy components using the above hooks to build sliders.
Does _not_ include slider implementations for @react-aria/spectrum.
Closes #763
For now, just visual tests on Storybook under the "Slider" group, starting here: http://localhost:9003/?path=/story/slider--single
[Plasmic](https://plasmic.app)
=> Slider component for @react-stately and @react-aria

packages/@adobe/spectrum-css-temp/components/textfield/index.css
* use --spectrum-font-family-base fonts
Closes #847
I looked at the current for TextField and could find any tests for fonts. So I tested this manually the StoryBook using the web-developer tools in Firefox
Result in current main-branch:
Result with above fix applied:
=> use default font-families

packages/@adobe/spectrum-css-temp/components/actiongroup/index.css, packages/@react-spectrum/layout/src/flex.css
In general this is a problem with specificity, the component may be rendering a button and need to do a style reset. In that case, we are at the mercy of the order of css loading. We can raise that by one specificity level and that will solve most cases. Someone could override it pretty easily and accidentally. We might want to consider !important for this very specific use case.
Closes
=> Add specificity to flex gap children to fix docs

packages/@react-types/shared/src/dom.d.ts
Closes #894 
Descriptions for `onCompositionStart` and `onCompositionEnd` were swapped
`yarn start:docs` and check event props for `TextArea` and `TextField`
N/A
=> Fix docs for composition events

packages/@react-aria/overlays/src/useOverlay.ts, packages/@react-aria/overlays/test/useOverlay.test.js
Allows you to filter overlay dismissal by the outside element that was
interacted with.
Closes #892 
[Plasmic](https://plasmic.app)
=> Add shouldCloseOnInteractOutside prop to useOverlay()

packages/@react-aria/select/src/HiddenSelect.tsx, packages/@react-aria/visually-hidden/src/VisuallyHidden.tsx
Closes #857. Depends on #911.
This adds `useVisuallyHidden` and `useHiddenSelect` hooks of the corresponding components, which may be useful for users with alternative renderers than React. Users of the hooks versions are responsible for rendering the actual elements and spreading props onto them.
=> Add hooks versions of VisuallyHidden and HiddenSelect

packages/@react-aria/textfield/src/useTextField.ts, packages/@react-spectrum/textfield/src/TextArea.tsx, packages/@react-spectrum/textfield/test/TextField.test.js, packages/@react-types/textfield/src/index.d.ts
Adds the `inputElementType` option added to `useTextArea` in #831 to the spectrum TextArea component. Also moved the option to be specific to aria and not exposed as a prop to Spectrum, where you can't actually change the element type we render.
=> Add inputElementType in TextArea

packages/@adobe/spectrum-css-temp/components/button/skin.css
Ported from Spectrum CSS's recent changes, plus one addition for the quiet, emphasized, active state. 😂
=> Fix active state of toggle button focus ring

packages/@react-aria/interactions/src/useInteractOutside.ts, packages/@react-aria/overlays/src/useOverlay.ts, packages/@react-aria/select/src/useSelect.ts, packages/@react-spectrum/menu/src/MenuTrigger.tsx, packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx, packages/@react-spectrum/menu/test/MenuTrigger.test.js, packages/@react-spectrum/overlays/src/Popover.tsx, packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-spectrum/picker/stories/Picker.stories.tsx, packages/@react-spectrum/picker/test/Picker.test.js, packages/@react-stately/overlays/src/useOverlayTriggerState.ts, packages/@react-types/overlays/src/index.d.ts
Closes https://github.com/adobe/react-spectrum/issues/850
This moves useInteractOutside to fire on mouse down instead of on up, this means menus won't reopen after they've been closed by the blur
It also takes advantage of shouldCloseOnInteractOutside, which lets us detect if the the interaction was on the trigger, which will automatically toggle the menu when clicked. If we couldn't filter that event out, then the menu would just be closed from outside interaction and toggled open again immediately
cleans up trigger toggle state so it always uses the latest state
=> Fix double open menu

packages/dev/docs/pages/blog/building-a-button-part-1.mdx
attempt to make some sentences less confusing
add kbd wrappers around keys
Closes
=> Update blog post

packages/@adobe/spectrum-css-temp/components/button/skin.css, packages/@react-spectrum/button/chromatic/ToggleButton.chromatic.tsx
The following states were broken:
* emphasized + selected + focus-ring + active
* emphasized + selected + focus-ring + hovered
* quiet + selected + focus-ring + hovered
Also added a story to chromatic that creates a powerset of all possible states so we can easily catch regressions.
=> Fix more toggle button states

packages/@adobe/spectrum-css-temp/components/textfield/index.css
Height is 52 on Firefox windows but 39 on Firefox OSX. Difference seems to be scrollbars (even if not visible)
=> Fix Textarea height on Firefox on windows

scripts/bumpVersions.js
This updates the script to bump versions of packages to have a UI for selecting _how_ to bump the version for each package (e.g. alpha, patch, minor, major, etc.). It starts a simple web server and triggers your browser to open to a page listing all of the changed packages.
It then propagates these version selections as necessary to dependent packages. Specifically, if the version is a prerelease, then it propagates the version bump upwards to anything that has a dependency on the package being published. This is so that the dependent packages get the updated pinned version. Additionally, we also propagate the version bump downward to all packages that the package depends on, to ensure that all dependencies are published and up to date.
For now, the rest of the script works as it did, …
=> Update script to bump versions of packages

packages/@react-aria/interactions/src/useInteractOutside.ts, packages/@react-aria/overlays/src/useOverlay.ts, packages/@react-aria/select/src/useSelect.ts, packages/@react-spectrum/menu/src/MenuTrigger.tsx, packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx, packages/@react-spectrum/menu/test/MenuTrigger.test.js, packages/@react-spectrum/overlays/src/Popover.tsx, packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-spectrum/picker/stories/Picker.stories.tsx, packages/@react-spectrum/picker/test/Picker.test.js, packages/@react-stately/overlays/src/useOverlayTriggerState.ts, packages/@react-types/overlays/src/index.d.ts
Reverts adobe/react-spectrum#925
Found a couple issues. I think we'll need to revisit the behavior of whether we open/close on mouse down or mouse up. Reverting for the release and we can come back to this.
=> Revert "Fix double open menu"

packages/@react-aria/slider/src/useSlider.ts, packages/@react-aria/slider/src/useSliderThumb.ts, packages/@react-aria/slider/src/utils.ts, packages/@react-aria/slider/stories/Slider.stories.tsx, packages/@react-aria/slider/stories/StoryMultiSlider.tsx, packages/@react-aria/slider/stories/StoryRangeSlider.tsx, packages/@react-aria/slider/stories/StorySlider.tsx, packages/@react-aria/slider/stories/story-slider.css, packages/@react-aria/slider/test/useSlider.test.js, packages/@react-aria/slider/test/useSliderThumb.test.js, packages/@react-aria/utils/src/useDrag1D.ts, packages/@react-stately/slider/src/useSliderState.ts
Fixing a few issues:
* `SliderState` needs to know which thumbs are editable, so that it can block edits to uneditable thumbs by track-dragging
* Make track-dragging less fragile to different DOM structures.  Previously, it only handles drag events on itself, not its children; you are expected to place the track DOM by itself, with no children, so that the drag events on the track element and the thumb elements don't conflict.  Now, we keep track of whether we are dragging by track; if so, the thumb drag events won't do anything.  This makes how you structure your DOM less strict; you can put the trackProps on an element by itself, or on the container of the thumbs.  The Story*Slider components have been updated to show the different variations.
* Removed unnecessary …
=> A few tweaks and fixes to slider:

packages/@react-spectrum/dialog/src/DialogTrigger.tsx, packages/@react-spectrum/dialog/stories/DialogTrigger.stories.tsx, packages/@react-spectrum/dialog/test/DialogTrigger.test.js
Closes https://github.com/adobe/react-spectrum/issues/985
- [N/A?] Updated documentation (if it already exists for this component).
- [N/A?] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)
Open the Storybook for DialogTrigger popover, verify that contents are visible, try to close it with the cancel button, verify it's closed
=> DialogTrigger in popover should accept function as 2nd child

packages/@react-aria/focus/docs/FocusRing.mdx
Closes #791
Uses @snowystinger's suggestion. from #797
Original pr: https://github.com/adobe/react-spectrum/pull/814
=> Add info about focusing after window blur in docs

packages/@react-aria/i18n/package.json, packages/@react-aria/i18n/src/useDefaultLocale.ts, packages/@react-spectrum/provider/test/Provider.ssr.test.js
Came across this hydrating error while testing in Next.js
=> Fix mismatch of lang and dir attributes of Provider during SSR hydration

packages/@react-aria/combobox/test/useComboBox.test.js, packages/@react-aria/menu/test/useMenuTrigger.test.js, packages/@react-aria/overlays/src/useCloseOnScroll.ts, packages/@react-aria/overlays/src/useOverlayPosition.ts, packages/@react-aria/overlays/src/useOverlayTrigger.ts, packages/@react-aria/overlays/test/useOverlayPosition.test.js, packages/@react-aria/overlays/test/useOverlayTrigger.test.js, packages/@react-spectrum/combobox/src/ComboBox.tsx, packages/@react-spectrum/menu/src/MenuTrigger.tsx, packages/@react-spectrum/menu/test/MenuTrigger.test.js, packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-spectrum/picker/test/Picker.test.js
Follow up from #1007.
Tapping near the bottom of the screen on an iPhone causes Safari to show its toolbar. When a tray is showing, this causes scrolling of the page to occur which makes the tray close. We want to avoid this so the user can actually tap on the item they meant to.
Unfortunately, this is currently handled in `useOverlayTrigger` rather than `useOverlayPosition`, and we'd need to pass a prop through 3+ layers to get it there. Additionally, we'd probably like it to not be the default. We'd like to move this handling into `useOverlayPosition` given that it only affects positioning, but to do that we'd need an additional `onClose` prop to be passed which would be a breaking change.
To work around this, we do move it, but keep a WeakMap of trigger DOM node to an `onClose` …
=> Do not close tray on scroll

packages/@react-aria/slider/test/useSliderThumb.test.js, packages/@react-aria/utils/src/useDrag1D.ts, packages/@react-stately/slider/src/useSliderState.ts, packages/@react-stately/slider/test/useSliderState.test.js, packages/@react-stately/splitview/src/useSplitViewState.ts
Related to #944, #999.
Found in testing that sometimes the slider handle would stop moving, and other times it would continue firing zeros after reaching the end. This was because the state in the closure was stale due to events firing more quickly than state updates. This is solved by using a functional state update which ensures we always have up to date values.
=> Fix updating stale state in Slider

packages/@adobe/react-spectrum/package.json, packages/@adobe/react-spectrum/src/index.ts, packages/@react-aria/i18n/docs/internationalization.mdx, packages/@react-aria/ssr/docs/SSRProvider.mdx, packages/@react-aria/ssr/docs/useIsSSR.mdx, packages/@react-aria/ssr/src/SSRProvider.tsx, packages/@react-aria/ssr/test/SSRProvider.test.js, packages/dev/docs/pages/react-aria/ssr.mdx, packages/dev/docs/pages/react-spectrum/ssr.mdx, packages/dev/docs/src/Layout.js, packages/dev/docs/src/syntax-highlight.css, packages/dev/parcel-optimizer-ssg/SSGOptimizer.js, packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js
Adds docs for SSR including how to use react-aria and react-spectrum with Next.js and Gatsby. Also fixes a bug I found in SSRProvider, and exports SSRProvider from the monopackage.
DO NOT MERGE until the release.
=> SSR docs and bugfix

packages/@react-spectrum/checkbox/stories/CheckboxGroup.stories.tsx, packages/@react-spectrum/radio/stories/Radio.stories.tsx
Closes n/a
Confirm that necessity indicator stories exist for Radio and CheckboxGroup.
Confirm the stories work.
RSP
=> Radio and CheckboxGroup - adding neccsityIndicator stories

packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-aria/focus/test/FocusScope.test.js, packages/@react-aria/select/docs/useSelect.mdx
Fixes an issue reported by @adamwathan on Twitter: https://twitter.com/adamwathan/status/1301546588020576256.
In the [useSelect example](https://react-spectrum.adobe.com/react-aria/useSelect.html) in the docs, tabbing out of the menu doesn't work as expected and focus stays within it. This does not occur in the React Spectrum picker because it uses a portal to place the menu at the end of the document body. The useSelect example does not do this, so the next thing after the trigger button is the menu itself, so focus is placed back inside on tab. I've fixed this by skipping over elements inside the focus scope when attempting to move to the next element, so now tabbing out of the menu moves to the next element and closes the select as expected.
=> Fix tabbing out of select in react-aria example

packages/@react-spectrum/picker/test/Picker.test.js, packages/@react-stately/list/src/useSingleSelectListState.ts
This PR allows Picker options which have falsey keys (except `null`) to be selected. The use case where a user might encounter this is when a Picker contains an Option with `key=""` as would be the convention in regular HTML when creating a placeholder value for a select input.
Closes #1016
1. Construct a Picker with an option containing an empty key
```jsx
<Picker label="Color">
<Option key="">None</Option>
<Option key="red">Red</Option>
<Option key="blue">Blue</Option>
<Option key="green">Green</Option>
</Picker>
```
2. Select the "None" option
3. Picker should now show "None" in the Picker button
=> Allow Options with falsey keys to be selected

packages/@adobe/spectrum-css-temp/components/button/index.css
Closes #1042 
Render an Action Button with an icon on a page with this style rule applied. Verify the icon is sized correctly
```css
* {
box-sizing: inherit;
}
```
Since this is an edge case style-only code change, what type of test would y'all like?
Adobe - Magento
=> fix icon size issue with inherited box sizing

packages/@react-aria/tooltip/src/useTooltipTrigger.ts, packages/@react-spectrum/actiongroup/stories/ActionGroup.stories.tsx, packages/@react-spectrum/actiongroup/test/ActionGroup.test.js, packages/@react-spectrum/tooltip/src/Tooltip.tsx, packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx, packages/@react-spectrum/tooltip/src/context.ts, packages/@react-spectrum/tooltip/stories/Tooltip.stories.tsx, packages/@react-spectrum/tooltip/stories/TooltipTrigger.stories.tsx, packages/@react-spectrum/tooltip/test/Tooltip.test.js, packages/@react-spectrum/tooltip/test/TooltipTrigger.test.js, packages/@react-stately/tooltip/package.json, packages/@react-stately/tooltip/src/useTooltipTriggerState.ts, packages/@react-types/tooltip/src/index.d.ts
Fixes a few things I found while reviewing the Tooltip API:
* Remove `role` prop from Tooltip since it only allows one value anyway.
* Remove unnecessary `useId` from Tooltip since the id comes from TooltipTrigger.
* Support aria labeling in Tooltip.
* Change default placement to `top` to match Spectrum.
* Support passing a DOMRef `ref` to Tooltip and sync with ref from TooltipTrigger context.
* Remove forward ref from TooltipTrigger to match DialogTrigger. Ref can be added to Tooltip directly.
* Don't export `useTooltipProvider` from package.
* Don't export `TOOLTIP_DELAY` and `TOOLTIP_COOLDOWN` from package.
* Don't depend on aria package in stately.
* Separate spectrum props from aria/stately tooltip trigger props.
* Support for TooltipTriggers wrapping Item in ActionGroup and other …
=> Tooltip API review and fixes

packages/@react-aria/overlays/src/usePreventScroll.ts, packages/@react-aria/overlays/test/usePreventScroll.test.js
=> Enhancement: Makes usePreventScroll controllable.

packages/@react-spectrum/button/stories/Button.stories.tsx
Removed "note" from last two button stories.
RSP
=> Removing the storybook 'note' that explained a browser preference issue

packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx, packages/@react-spectrum/tooltip/stories/TooltipTrigger.stories.tsx, packages/@react-types/tooltip/src/index.d.ts
Closes #941
1. Go to the storybook
2. Select **TooltipTrigger** > _placement: top_
3. Inspect gap between tooltip and button. If the gap is wide enough, the test passes.
4. Select _placement: top with offset_
5. Inspect gap between tooltip and button. If the gap is large (about 50px), the test passes.
6. Select _placement: bottom with crossOffset_
7. Verify that the tooltip is anchored at the bottom right corner of the button.
RSP
=> Expose offset and crossOffset in TooltipTrigger

package.json
runInBand means that tests run serially, so we can eliminate the potential for conflict
it may run faster than using the two workers as well due to build machine constraints
faster would be roughly < 17sec
First finding using --runInBand took roughly 31seconds, this is almost double
Closes
=> Intermittent SSR test failures

packages/@adobe/react-spectrum/src/index.ts
Closes 
As mentioned in #1101  CheckboxGroup wasnt exported so this PR closes that issue
Closes #1101
=> added CheckBoxGroup export

packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/interactions/test/usePress.test.js
Closes https://github.com/adobe/react-spectrum/issues/918
=> Fix #918 Adding preventFocusOnPress to usePress

packages/@react-aria/overlays/src/useModal.tsx, packages/@react-spectrum/actiongroup/test/ActionGroup.test.js, packages/@react-spectrum/dialog/docs/DialogContainer.mdx, packages/@react-spectrum/dialog/src/DialogContainer.tsx, packages/@react-spectrum/dialog/src/DialogTrigger.tsx, packages/@react-spectrum/dialog/src/context.ts, packages/@react-spectrum/dialog/src/useDialogContainer.ts, packages/@react-spectrum/dialog/stories/DialogContainer.stories.tsx, packages/@react-spectrum/dialog/stories/DialogContainerExamples.tsx, packages/@react-spectrum/dialog/test/DialogContainer.test.js, packages/@react-spectrum/dialog/test/DialogTrigger.test.js, packages/@react-spectrum/menu/test/Menu.test.js, packages/@react-spectrum/overlays/src/Modal.tsx, packages/@react-spectrum/table/stories/CRUDExample.tsx, packages/@react-types/dialog/src/index.d.ts, packages/@react-types/overlays/src/index.d.ts
Closes #966. Closes #1039.
Based on learnings from #965, this implements a `DialogContainer` component that can be used in cases where there is no trigger element, or when the trigger may unmount while the dialog is open (e.g. a menu item). A `useDialogContainer` hook is also added to allow custom dialog components to dismiss the dialog programmatically without manually passing through an `onDismiss` function.
In addition, this adds a warning when a `DialogTrigger` detects that it is unmounted while a modal is open, suggesting the use of `DialogContainer` instead.
See the docs and updates to the Table CRUD example for details on the API.
=> Add DialogContainer component to support controlled dialogs

packages/@react-spectrum/picker/stories/Picker.stories.tsx
Followup to #1015
Adding a story for testing picker none example.
Confirm that picker works with the new falsy story.
RSP
=> Adding Picker story for falsy/none/null key

packages/@react-aria/interactions/src/textSelection.ts, packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/interactions/test/usePress.test.js
Closes https://github.com/adobe/react-spectrum/issues/862
Fix the user-select not removed on HTML element issue, add tests for it.
quickly and repeatedly toggling a checkbox and then move the cursor away from the checkbox component and let go, `user-select:none` on html element is always removed. can check this on document site, I've tested it.
`yarn test usePress`
=> Fix usePress user-select not removed on HTML element

packages/@react-aria/selection/src/useTypeSelect.ts, packages/@react-aria/table/src/TableKeyboardDelegate.ts, packages/@react-spectrum/picker/test/Picker.test.js
=> Fixing typeselect for falsy key values

packages/@react-aria/listbox/src/useListBox.ts, packages/@react-spectrum/listbox/src/ListBoxBase.tsx
Closes #1100
`AriaListBoxOptions -> AriaListBoxProps -> ListBoxProps -> CollectionBase.children`
Any `children` prop passed into `useListBox` was never actually used.
=> Fix prop types for useListBox

packages/@react-aria/tooltip/src/useTooltipTrigger.ts, packages/@react-spectrum/tooltip/test/TooltipTrigger.test.js
`useTooltipTrigger` always adds `aria-describedby` regardless of whether the `state.isOpen` or not.
At:
https://github.com/adobe/react-spectrum/blob/975957a3c3fb4a9f3be358428e0980a4d4e51c1a/packages/%40react-aria/tooltip/src/useTooltipTrigger.ts#L135
`state.open` is a `function`, so it's always `true`, whereas `state.isOpen` is a `boolean`, this line should be:
```jsx
'aria-describedby': state.isOpen ? tooltipId : undefined,
```
Closes #1149
1. Inspect and TooltipTrigger examples in Storybook
2. The trigger element should not have `aria-describedby` when the Tooltip is hidden, and should only have it when the Tooltip opens on hover or focus.
=> fix(#1149) useTooltipTrigger should not add aria-describedby when Tooltip it references is not in DOM

packages/@adobe/spectrum-css-temp/components/table/index.css, packages/@react-aria/table/src/useTableColumnHeader.ts, packages/@react-aria/tooltip/src/useTooltipTrigger.ts, packages/@react-spectrum/table/package.json, packages/@react-spectrum/table/src/Table.tsx, packages/@react-spectrum/table/src/table.css, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-spectrum/table/test/Table.test.js, packages/@react-stately/layout/src/ListLayout.ts, packages/@react-stately/layout/src/TableLayout.ts, packages/@react-stately/table/src/TableCollection.ts, packages/@react-types/table/src/index.d.ts
Closes 
https://github.com/adobe/react-spectrum/issues/912
Add a `hideHeader` prop to the column. This will
1) Not add a textual header to the column
2) Tooltip will be added instead of the text
3) The column will have a default fixed width depending on the scale
=> Implement table headerless column

packages/@react-spectrum/layout/docs/Flex.mdx, packages/@react-spectrum/layout/docs/Grid.mdx, packages/dev/docs/pages/react-spectrum/layout.mdx
Closes #1169 
- Clone repo, run `yarn install` then `yarn start:docs`
- Load up the Flex, Grid and Layout documentation pages.
- See sweet sweet linkage to Spectrum dimension values in all places where the term is used.
=> Link all references to Spectrum dimension values (#1169)

packages/@react-aria/dialog/docs/useDialog.mdx, packages/@react-aria/interactions/src/useInteractOutside.ts
Follow logic of usePress and preventDefault on clicks handled by useInteractOutside, which is can be thought of as usePressOutside
Closes https://github.com/adobe/react-spectrum/issues/919
=> Don't text select after dismissing a dialog in FF

packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-aria/focus/test/FocusScope.test.js, packages/@react-spectrum/dialog/stories/Dialog.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/1168
=> Fix(#1168): Check document.activeElement in focus containment onBlur so focus in iframes is retained

packages/@react-aria/overlays/src/usePreventScroll.ts
Apparently React 17 made useEffect cleanup functions async and for some reason that's having an effect on restoring the scroll position on iOS when a dialog closes (it scrolls to the top). Using `useLayoutEffect` instead fixes the issue.
=> Fix usePreventScroll on iOS with React 17

packages/@react-aria/interactions/src/useMove.ts
Fixes a typo [useMove.ts#L175](https://github.com/adobe/react-spectrum/blob/879cbbdd5031a8d6ac4e91272c8e73d7dd38b0c9/packages/%40react-aria/interactions/src/useMove.ts#L175)
=> Fix function name typo

packages/@react-aria/live-announcer/src/LiveAnnouncer.tsx, packages/@react-spectrum/listbox/src/ListBoxOption.tsx
=> chore: improved LiveAnnouncer types

packages/@react-aria/live-announcer/src/LiveAnnouncer.tsx
Reverts adobe/react-spectrum#1210 due to changes made in https://github.com/adobe/react-spectrum/pull/1176
Will be re-added.
=> Revert "chore: improved LiveAnnouncer types"

packages/@adobe/spectrum-css-temp/components/dropdown/skin.css, packages/@react-spectrum/picker/stories/Picker.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/1079
Added a new storybook for this case.
Goto the 'isDisabled, selectedKey` story.
Click on "One" and the text color won't change.
RSP
=> picker adding text color for disabled active selected value

packages/@react-aria/interactions/src/useInteractOutside.ts
Reverts adobe/react-spectrum#1187
Closes: https://github.com/adobe/react-spectrum/issues/1220
This caused issues with Combobox and and nested dialogs.
We're currently working on a better fix for the original issue but need to discuss it more
=> Revert "Don't text select after dismissing a dialog in FF"

packages/@react-aria/i18n/src/useNumberFormatter.ts
Closes https://github.com/adobe/react-spectrum/issues/1248
=> Catch Intl.NumberFormat error for unsupported option

packages/@spectrum-icons/illustrations/src/NoSearchResults.tsx
Closes https://github.com/adobe/react-spectrum/issues/1253
Nothing should have changed, IllustratedMessages test still test this component. Checked the built docs and storybook and the illustration still renders as expected 👍 
Changes were 
`stroke-linecap` --> `strokeLinecap`
`stroke-linejoin` --> `strokeLinejoin`
`stroke-width` --> `strokeWidth`
Also compressed the component to have it follow the same style as all the other `Illustrations`
Adobe
=> RSP-1253: Update NoSearchResults svg formatting

packages/@react-spectrum/tabs/src/Tabs.tsx, packages/@react-spectrum/tabs/test/Tabs.test.js
The aria-labelledby attribute on the tabpanel should be updated to refer to the Picker rather than the current tab, which is no longer in the DOM.
Closes #1271 
1. Open http://localhost:9003/?path=/story/tabs--collapse-behavior
2. Inspect the element with `role="tabpanel"` in the Web Inspector
4. resize the webpage viewport width to test.
3. Verify that when the Tabs are collapsed the tabpanel element's `aria-labelledby` attribute points to the Picker button element.
4. Verify that when the Tabs are not collapsed the tabpanel element's `aria-labelledby` attribute points to the selected Tab.
=> fix(#1271): tabpanel should be labelled by the Picker button element when Tabs are collapsed

packages/@react-aria/select/docs/useSelect.mdx
Pass along props so that the Listbox knows that it has been labelled.
Closes https://github.com/adobe/react-spectrum/issues/1179
=> Fix docs useSelect console warning

packages/@react-aria/button/docs/useToggleButton.mdx, packages/@react-aria/button/src/useButton.ts, packages/@react-aria/button/src/useToggleButton.ts, packages/@react-spectrum/button/src/Button.tsx, packages/@react-spectrum/button/src/ClearButton.tsx, packages/@react-types/button/src/index.d.ts
Closes #1172
Hello Adobe team 👋 
This is an implementation proposal to the types modification request in response to the following issue: #1172
I modified four files :
- `useButton` and `useToggleButton` hooks on which I added functions overloading (thanks to @devongovett advices) to dynamically modify the generic type passed to the returned `ButtonAria` depending on `elementType` props. I also modified the ref object generic type `HTMLElement` to match with the `elementType` one.
- button types in `@react-types/button`: changed `elementType` type from string to `React.ElementType` which may enforce typing to be sure `buttonProps` ref and `elementType` are corresponding to the HTML DOM element used.
- Button spectrum element for a small generic type update
--> Did not added testable code …
=> [useButton & useToggleButton]: Add dynamic ref type depending on elementType props

packages/@react-aria/overlays/src/usePreventScroll.ts
This fixes a regression introduced in #1105 where non-text input elements (e.g. checkboxes, radios, etc.) did not work inside dialogs in mobile safari because we preventDefault on touch end. We actually only want to do this for text input types that will result in the software keyboard appearing.
=> Fix non-text inputs in dialogs in mobile safari

packages/@react-aria/interactions/src/useInteractOutside.ts, packages/@react-aria/interactions/test/useInteractOutside.test.js
Closes https://github.com/adobe/react-spectrum/issues/1262
If you use the isDisabled prop, make sure that no events are called.
=> fix(#1262): added isDisabled to useInteractOutside

packages/@react-aria/numberfield/src/useNumberField.ts, packages/@react-spectrum/numberfield/stories/NumberField.stories.tsx, packages/@react-spectrum/numberfield/test/NumberField.test.js
While NumberField uses useSpinButton, we need to override the spinbutton role, otherwise we can't focus the control button with VoiceOver on iOS.
* Use role="textbox" rather than role="textfield" for input.
* With role="textbox" instead of role="spinbutton", aria-valuemin, aria-valuemax, aria-valuenow, and aria-valuetext are no longer valid attributes for the input.
Closes 
1. http://localhost:9003/?path=/story/numberfield--default
2. For each of the NumberField story, verify that there are "No accessibility violations found." in the Accessibility Add-on panel.
=> fix(#1029): NumberField: fix accessibility role and aria-value* props

packages/dev/docs/pages/contribute.mdx
quick fix for typo on https://react-spectrum.adobe.com/contribute.html
=> chore: fix typo on Contribute docs page

packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-spectrum/picker/stories/Picker.stories.tsx, packages/@react-types/select/src/index.d.ts
Closes #1229 
Run the new story book sample
=> provide autofocus property

packages/@react-spectrum/layout/chromatic/Flex.chromatic.tsx, packages/@react-spectrum/layout/stories/Flex.stories.tsx, packages/@react-spectrum/utils/src/styleProps.ts
Closes #1152 
When using order prop, make sure that the elements follow the order specified on the prop.
=> fix(#1152): add order style prop

packages/@react-spectrum/combobox/src/ComboBox.tsx, packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx, packages/@react-spectrum/picker/src/Picker.tsx
combobox menu should remeasure whenever the combobox input/button change size
Closes
=> Observe Combobox trigger for resize

packages/@react-aria/checkbox/docs/useCheckboxGroup.mdx
Closes #1302
Shows getting `selected` and `disabled` states for checkboxgroup item (which is different from standalone checkbox) in docs example. Also adds missing `ref`.
=> docs: Add selected/disabled states to useCheckboxGroupItem example

packages/@react-spectrum/textfield/docs/TextArea.mdx
=> fixing textarea doc links

packages/@react-aria/color/src/useColorSlider.ts, packages/@react-aria/slider/src/useSliderThumb.ts, packages/@react-aria/slider/test/useSliderThumb.test.js, packages/@react-spectrum/color/test/ColorSlider.test.tsx, packages/@react-spectrum/slider/test/RangeSlider.test.tsx
Per https://github.com/adobe/react-spectrum/pull/1148#pullrequestreview-553088926 and https://bugs.chromium.org/p/chromium/issues/detail?id=1159567
Closes #1231, relates to #1148. Closes #1148. Closes #1231.
- Filled out test instructions.
- Updated documentation (if it already exists for this component).
Adobe/accessibility
=> Slider accessibility name calculation fixes for Chrome (#1148)

packages/@react-spectrum/slider/src/SliderBase.tsx
There are 3 additional characters + the formatted numbers
Closes
=> Fix valuelabel wrapping

packages/@react-aria/slider/src/useSlider.ts, packages/@react-aria/slider/test/useSlider.test.js, packages/@react-spectrum/slider/test/RangeSlider.test.tsx, packages/@react-spectrum/slider/test/Slider.test.tsx
Works around https://bugs.webkit.org/show_bug.cgi?id=172464, which causes the range slider's minimum handle not to be announced correctly.
=> Work around iOS VoiceOver labeling issue with Slider

packages/@adobe/spectrum-css-temp/components/slider/index.css, packages/@react-spectrum/slider/src/RangeSlider.tsx, packages/@react-spectrum/slider/src/Slider.tsx, packages/@react-spectrum/slider/src/SliderBase.tsx, packages/@react-spectrum/slider/stories/RangeSlider.stories.tsx, packages/@react-spectrum/slider/stories/Slider.stories.tsx, packages/@react-spectrum/slider/test/RangeSlider.test.tsx, packages/@react-spectrum/slider/test/Slider.test.tsx, packages/@react-types/slider/src/index.d.ts
Replaces `valueLabel` with a `getValueLabel` function which returns a string. This allows us to pre-allocate space for the maximum length value label, and also enables uncontrolled sliders to have a custom value label that updates correctly when the value changes.
=> Fix wrapping and support uncontrolled value label in slider

packages/@react-aria/color/src/useColorSlider.ts, packages/@react-aria/slider/src/useSliderThumb.ts, packages/@react-aria/slider/test/useSliderThumb.test.js, packages/@react-spectrum/color/test/ColorSlider.test.tsx, packages/@react-spectrum/slider/test/RangeSlider.test.tsx
Reverts adobe/react-spectrum#1389. [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1159567) will hopefully be fixed in v88 (slated for January), and the workaround caused an issue where the `role="presentation"` element was announced as a group.
=> Revert "Slider accessibility name calculation fixes for Chrome (#1148)"

packages/@react-aria/slider/src/useSlider.ts, packages/@react-spectrum/slider/test/RangeSlider.test.tsx, packages/@react-spectrum/slider/test/Slider.test.tsx
Closes #1400 
1. Open http://localhost:9003/iframe.html?id=slider--formatoptions-centimeter on Android device with TalkBack screen reader turned on.
2. Navigate to output element showing the current value of the Slider.
3. Output should announce as "Label 0 centimeters status"
Adobe/accessibility
=> Slider: Work around TalkBack not announcing the output element's text content

packages/@react-aria/slider/src/useSlider.ts
followup PR https://github.com/adobe/react-spectrum/pull/1393 to improving handling of stack thumbs
click to the left of slider thumbs
RSP
=> explicitly defining slider closest thumb support for splitting on zero

packages/@adobe/spectrum-css-temp/components/slider/index.css
Not sure why it was different in css than regular slider...
=> Fix text selection starting on drag in RangeSlider

packages/@adobe/spectrum-css-temp/components/slider/index.css
fixes slider shrinking to containing parent width.
goto side custom width story, width is like 350 to 400px
in chrome dev tools change the width to 300
see that the slider stays full custom width and doesn't shrink to width
RSP
=> prevent shrinking of custom width below defined

package.json, plop-templates/@react-aria/docs/useComponent.mdx.hbs, plop-templates/@react-aria/package.json.hbs, plop-templates/@react-aria/src/useComponent.ts.hbs, plop-templates/@react-aria/test/useComponent.test.js.hbs, plop-templates/@react-spectrum/chromatic/Component.chromatic.tsx.hbs, plop-templates/@react-spectrum/docs/Component.mdx.hbs, plop-templates/@react-spectrum/package.json.hbs, plop-templates/@react-spectrum/src/Component.tsx.hbs, plop-templates/@react-spectrum/stories/Component.stories.tsx.hbs, plop-templates/@react-spectrum/test/Component.test.js.hbs, plop-templates/@react-stately/docs/useComponentState.mdx.hbs, plop-templates/@react-stately/package.json.hbs, plop-templates/@react-stately/src/useComponentState.ts.hbs, plop-templates/@react-types/package.json.hbs, plop-templates/@react-types/src/index.d.ts.hbs, scripts/plopfile.js
garage week dev task
- adds some examples in the cli prompts
- user no longer needs to type a space in the css module prompt if they don't put anything in it
- some additional stuff added to templates (jsdocs, types, comments explaining what some hooks do)
- logic to add package imports and types only if user is plopping a specific combo of scopes
- general fixes
=> Plop improvements

packages/@react-stately/tooltip/src/useTooltipTriggerState.ts, packages/@react-types/tooltip/src/index.d.ts
This reflects reality better - I've refactored those types so particular types only contain types for properties actually utilized by the consuming utility function.
`yarn check-types`
=> Refactor types around useTooltip, useTooltipTrigger & useTooltipTriggerState

packages/@react-spectrum/button/src/Button.tsx, packages/@react-spectrum/button/stories/Button.stories.tsx, packages/@react-types/button/src/index.d.ts
Type stories to catch this
Closes https://github.com/adobe/react-spectrum/issues/1360
=> elementType of 'a' fails on Spectrum Button

packages/@react-aria/utils/test/number.test.js, scripts/lint-packages.js
https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message
> Deprecated: Use assert.strictEqual() instead.
=> Replace assert.equal with assert.strictEqual and jest.expect

packages/dev/docs/src/client.js
Closes 
By not trying to apply styles to the button, we don't need to worry about specificity with its own classes. Instead, we wrap it, which allows us to hide it regardless of what the button has for its display.
=> Make hamburger menu more resistant to specificity bugs

packages/@react-aria/menu/src/useMenuSection.ts
We had a copy paste issue
Closes https://github.com/adobe/react-spectrum/issues/1266
=> Fix documentation on return type of useMenuSection

packages/@react-aria/color/test/useColorWheel.test.tsx, packages/@react-aria/color/test/useHexColorField.test.js, packages/@react-spectrum/color/src/ColorThumb.tsx, packages/@react-spectrum/color/stories/ColorSlider.stories.tsx, packages/@react-spectrum/color/stories/ColorThumb.stories.tsx, packages/@react-spectrum/color/stories/ColorWheel.stories.tsx, packages/@react-spectrum/color/stories/HexColorField.stories.tsx, packages/@react-spectrum/color/test/ColorSlider.test.tsx, packages/@react-spectrum/color/test/ColorWheel.test.tsx, packages/@react-spectrum/color/test/HexColorField.test.js, packages/@react-stately/color/src/Color.ts, packages/@react-stately/color/src/useColor.ts, packages/@react-stately/color/src/useColorSliderState.ts, packages/@react-stately/color/src/useColorWheelState.ts, packages/@react-stately/color/src/useHexColorFieldState.ts, packages/@react-stately/color/test/Color.test.js, packages/@react-stately/color/test/useColor.test.js, packages/@react-stately/color/test/useHexColorFieldState.test.js, packages/@react-types/color/package.json, packages/@react-types/color/src/index.d.ts
Refactors the `Color` class constructor into a `parseColor` function that returns an interface instead to avoid a circular dependency between `@react-types/color` and `@react-stately/color`
=> Fix circular dependency between @react-types/color and @react-stately/color

packages/@react-stately/utils/src/useControlledState.ts, packages/@react-stately/utils/test/useControlledState.test.js
NaN !== NaN, but we can compare them using Object.is https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is
Closes
=> Prevent extra onChanges from useControlledState

packages/@adobe/spectrum-css-temp/components/fieldlabel/index.css, packages/@react-spectrum/textfield/stories/TextArea.stories.js
Closes https://github.com/adobe/react-spectrum/issues/1453
=> Fixing textareas with labels so they grow to fill the user specified height

packages/@adobe/spectrum-css-temp/components/colorslider/index.css, packages/@react-aria/color/src/useColorSlider.ts, packages/@react-spectrum/color/src/ColorSlider.tsx, packages/@react-spectrum/color/stories/ColorSlider.stories.tsx, packages/@react-stately/color/src/useColorSliderState.ts
We previously only accounted for custom widths for horizontal sliders. Now we account for custom heights of vertical sliders. And this also fixes the label position on vertical sliders so it's not off to the side.
=> Fix label position and custom height for vertical ColorSlider

packages/@adobe/spectrum-css-temp/components/stepper/skin.css
=> Making disabled NumberField button styles more specific than active styles 

packages/@react-spectrum/textfield/src/TextArea.tsx, packages/@react-spectrum/textfield/stories/TextArea.stories.js
=> Textarea should not behave differently inside a flex

packages/@react-aria/color/src/useColorWheel.ts, packages/@react-aria/color/test/useColorWheel.test.tsx, packages/@react-spectrum/slider/stories/Slider.stories.tsx
So that a screen reader user can change the value with focus on the ColorWheel input we need to keep the input value in sync with the ColorWheel value and handle change events from the input.
Per release testing.
1. Open http://localhost:9003/?path=/story/colorwheel--default
2. Open VoiceOver screen reader on macOS or iOS device.
3. Navigate VoiceOver cursor to set focus to the ColorWheel input.
4. The input value should match the hue value of the ColorWheel.
5. Use increment/decrement gesture on iOS or arrow keys to change the value of the input on macOS.
6. Verify that the value change for the input is announced by VoiceOver and that the ColorWheel thumb updates and repositions to display the new hue value.
=> ColorWheel: sync input ChangeEvent and value with state

packages/@react-spectrum/color/stories/HexColorField.stories.tsx
No issue from testing session
Adding a story to make sure autofocus works with HexColorField
goto storybook
goto hexcolorfield stories
goto the autofocus story
confirm that it is autofocused
RSP
=> adding an autofocus story to hexColorField

packages/@react-spectrum/combobox/test/ComboBox.test.js, packages/@react-stately/combobox/src/useComboBoxState.ts
=> Prevent allowCustomValue ComboBox from removing selected key on blur if inputValue wasn't changed

packages/@react-aria/select/src/useSelect.ts, packages/@react-spectrum/picker/stories/Picker.stories.tsx
=> Picker left/right arrows shouldn't scroll containers

packages/@adobe/spectrum-css-temp/components/textfield/index.css, packages/@react-spectrum/textfield/stories/TextArea.stories.js
Closes 
Match specs https://spectrum.adobe.com/page/text-area/#Anatomy
Also allows us to fix https://www.chromatic.com/test?appId=5f0dd5ad2b5fc10022a2e320&id=6019c2037b753a002180e3b6
=> Move TextArea validation Icon to top right

packages/@adobe/spectrum-css-temp/components/fieldlabel/index.css, packages/@react-spectrum/combobox/src/ComboBox.tsx, packages/@react-spectrum/textfield/src/TextFieldBase.tsx
=> Fixing fieldlabel css so only textareas expand to fill available height

packages/@react-aria/combobox/docs/useComboBox.mdx
=> Fixing fully controlled combobox aria example

packages/@adobe/spectrum-css-temp/components/inputgroup/index.css, packages/@adobe/spectrum-css-temp/components/stepper/index.css
=> Fix numberfield css specificity collision

packages/@react-stately/collections/src/CollectionBuilder.ts
This change makes it possible to use a prop other than `key` in components that implement the `getCollectionNode` method.
The context here is that we're attempting to use `@react-stately/collections` to help us build a new `Select` component (similar to `Picker` in `@react-spectrum` world). However our component interface does not use `key` prop - instead we use a `value` prop like below:
```tsx
<Select label="color">
<SelectOption value="red" />
<SelectOption value="orange" />
<SelectOption value="yellow" />
<SelectOption value="green" />
<SelectOption value="blue" />
<SelectOption value="purple" />
</Select>
```
The flexibility that `getCollectionNode` provides already is **almost** enough, except that it's impossible to customize the value used for the key. …
=> Support custom key in getCollectionNode

packages/@react-spectrum/searchfield/stories/SearchField.stories.js, packages/@react-spectrum/textfield/stories/TextArea.stories.js
Closes - no issue
Added a story to see the min-wdith behavior of searchfield with clear icon and validation indicator.
Added a story to see the min-wdith behavior of textarea with clear icon and validation indicator.
goto storybook
goto searchfield
goto new story about custom width and narrow parent
current you can't see the value of the input field, this is to demonstrate the fixes needed and improve testing
also goto the textarea custom width small story
RSP
=> SearchField & TextArea stories added - custom width small and min-width

packages/@react-spectrum/provider/src/Provider.tsx
Closes https://github.com/adobe/react-spectrum/issues/1520
Using this structure in an OS dark theme
```
light
-> light dark
```
Will result in the inner one using the OS for the color-scheme, and not following the parent light setting.
This is in Chrome and Safari.
See issue for more detailed explanation.
=> Fix color scheme for scrollbars

packages/@react-spectrum/menu/docs/Menu.mdx
Closes https://github.com/adobe/react-spectrum/issues/1555
Docs for Items will be handled separately
=> Removing broken Item Spectrum link from Menu docs

packages/@react-aria/select/src/HiddenSelect.tsx, packages/@react-spectrum/picker/test/Picker.test.js
Closes https://github.com/adobe/react-spectrum/issues/1634
- context: https://github.com/adobe/react-spectrum/discussions/1626
- `yarn test packages/@react-spectrum/picker/test/Picker.test.js`
=> Picker within a `<form>` submits the first option by default

packages/@react-aria/combobox/src/useComboBox.ts, packages/@react-aria/combobox/test/useComboBox.test.js
Closes https://github.com/adobe/react-spectrum/issues/1646
=> Preventing form submission on Enter if combobox menu is open

packages/@react-spectrum/tabs/docs/Tabs.mdx
Closes https://github.com/adobe/react-spectrum/issues/1595
- This is just a visual issue. 
- Check **Collapse (overflow behavior)** of `react-spectrum/Tabs.html`
=> Documentation: Collapsed Tab is cutoff by container in docs

packages/@react-aria/aria-modal-polyfill/src/index.ts
I need this as I have a modal container that is dynamically rendered.
I'm a little bit confused by this:
1. this kind of feature is not the core functionality of modals/overlays right now. The only thing that happens in relation to `aria-hidden` there is that it is being set on the ModalProvider [here](https://github.com/adobe/react-spectrum/blob/f55249bf75b6fd43fa90b9bece035d1b0af69854/packages/%40react-aria/overlays/src/useModal.tsx#L80). This is somewhat OK as this is usually wrapping the root of the application. However, I think that this is not uncommon to have some non-React elements (there are a lot of popular 3rd party widgets for instance) on the page and from what I understand those require to be aria-hidden. I like that you don't impose extra code on your consumers just to …
=> Return revert function from watchModals

packages/@react-aria/dnd/src/index.ts, packages/@react-aria/dnd/src/useClipboard.ts, packages/@react-aria/dnd/src/useDrag.ts, packages/@react-aria/dnd/src/useDrop.ts, packages/@react-aria/dnd/src/utils.ts, packages/@react-aria/dnd/stories/DroppableGrid.tsx, packages/@react-aria/dnd/stories/dnd.stories.tsx, packages/@react-aria/dnd/test/mocks.js, packages/@react-aria/dnd/test/useClipboard.test.js, packages/@react-stately/dnd/src/useDraggableCollectionState.ts
This adds a `useClipboard` hook which can be used to implement cut/copy/paste support. This is very similar to drag and drop - in fact, they share the same underlying native API (DataTransfer). For this reason, I've added it to the dnd package and examples. I've made copy/paste support use the same API as our dnd API as well, which should make it easy to adopt.
This uses the beforecopy/beforecut/beforepaste events to enable the browser's actions in the Edit menu, but this is only supported in Safari. In other browsers, those options are always enabled. But in Safari this means that only the relevant actions will be enabled when you are focused on an element, which is kinda cool. In addition, cmd/ctrl + c/x/v work as expected and as handled by the browser. You can also trigger these …
=> Implement copy/paste support

.eslintrc.js, packages/@react-aria/dnd/src/DragManager.ts, packages/@react-aria/dnd/src/constants.ts, packages/@react-aria/dnd/src/useDrop.ts, packages/@react-aria/dnd/src/utils.ts, packages/@react-aria/dnd/stories/DraggableCollection.tsx, packages/@react-aria/dnd/stories/DroppableGrid.tsx, packages/@react-aria/dnd/stories/DroppableListBox.tsx, packages/@react-aria/dnd/stories/Reorderable.tsx, packages/@react-aria/dnd/stories/VirtualizedListBox.tsx, packages/@react-aria/dnd/stories/dnd.stories.tsx, packages/@react-aria/dnd/test/dnd.test.js, packages/@react-aria/dnd/test/examples.js, packages/@react-aria/dnd/test/mocks.js, packages/@react-aria/dnd/test/useClipboard.test.js, packages/@react-aria/dnd/test/useDraggableCollection.test.js, packages/@react-aria/dnd/test/useDroppableCollection.test.js, packages/@react-stately/dnd/src/useDroppableCollectionState.ts, packages/@react-types/shared/src/dnd.d.ts
Depends on #1701.
This adds support for dropping files from a user's filesystem (e.g. Finder), as well as directories of files. The API for drop items has changed accordingly to support these items in addition to the existing `text` items. In addition, the API for dragging changed slightly to simplify it a bit. Currently only dropping files is supported, dragging files is not because no browser currently supports this well. 
Pasting files is also "supported", but only Safari currently works. Other browsers don't allow pasting files at all. Unfortunately, this means copy/paste as a keyboard friendly alternative to dragging and dropping files won't really work for a majority of users, and we'll need to encourage applications to provide alternative ways of uploading files other than drag and …
=> Support for dropping files and directories

packages/@react-aria/interactions/src/usePress.ts
=> Trigger onPressEnd for pressed elements even if they've become disabled

packages/@react-spectrum/color/docs/ColorField.mdx, packages/@react-spectrum/color/src/ColorField.tsx, packages/@react-spectrum/color/stories/ColorField.stories.tsx, packages/@react-types/color/src/index.d.ts, packages/@react-types/textfield/src/index.d.ts
Closes #1606 
Adding a docs page for ColorField within the color package.
Adding some stories to test the full functionality like width, necessity indicator, etc.
Test the new stories
Review the new docs page
RSP
=> ColorField docs page and more stories

packages/@react-aria/utils/src/useDrag1D.ts
Just noticed this file still floating around, and we can't remove it without it being a major version bump, but we can at least clear up what it is and what people should be using instead
Closes
=> Discourage use of useDrag1D in favor of useMove

packages/@react-types/link/src/index.d.ts
Closes https://github.com/adobe/react-spectrum/issues/1762
No regressions with `useLink`
children no longer a typescript required prop for `useLink`
=> Move children from LinkProps to SpectrumLinkProps and remove LinkProps

packages/@adobe/spectrum-css-temp/components/tabs/index.css, packages/@adobe/spectrum-css-temp/components/tabs/skin.css, packages/@react-aria/tabs/package.json, packages/@react-aria/tabs/src/useTabPanel.ts, packages/@react-spectrum/tabs/chromatic/Tabs.chromatic.tsx, packages/@react-spectrum/tabs/src/Tabs.tsx, packages/@react-spectrum/tabs/stories/Tabs.stories.js, packages/@react-spectrum/tabs/test/Tabs.test.js, packages/@react-stately/collections/src/Item.ts, packages/@react-stately/list/src/useListState.ts, packages/@react-stately/list/src/useSingleSelectListState.ts, packages/@react-stately/tabs/src/useTabsState.ts
Fixes #1755 #1737
* Fixes spectrum design feedback.
* Implements focus ring design for tabpanel
* Changes tabpanel to only have tabIndex=0 when there are no tabbable elements within it
* Adds support for style props to `<TabList>` and `<TabPanels>`
* Suppresses warning about `textValue` prop on `<Item>` elements in tabs since we don't support typeahead there anyway.
* Simplifies stories and adds a few new ones.
=> Tabs design updates

package.json, patches/eslint-plugin-monorepo+0.3.2.patch, yarn.lock
Patching eslint-plugin-monorepo based on a PR I opened to that repo, you can see details here https://github.com/azz/eslint-plugin-monorepo/pull/21
On circle ci the average for the lint run is ~3min, this patch on the first run brought it down to 1min 35sec.
Closes
=> Speed up eslint

packages/@react-aria/focus/src/useFocusable.tsx, packages/@react-aria/interactions/src/DOMPropsContext.ts, packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/overlays/src/useOverlayPosition.ts, packages/@react-aria/utils/src/useSyncRef.ts, packages/@react-spectrum/menu/src/Menu.tsx
Closes https://github.com/adobe/react-spectrum/issues/1694
One can check this [storybook example](http://localhost:9003/?path=/story/useoverlayposition--positioned-container-bottom). 
Sometimes after reload clicking on trigger leads to flicker. Note - Only happens on first mount as new position gets stored and it's used in re-renders.
GeekyAnts
=> fix - useOverlayPosition mount flicker

packages/@react-spectrum/table/src/Table.tsx, packages/@react-stately/layout/src/TableLayout.ts
Closes #1752
This refines the table animations so that:
* When async loading, there is no zoom effect, only a fade in. No animation at all looked weird, so this seems like a good balance. The fade is also there for loading more as well.
* When inserting/removing a row, the zoom effect is retained. Only fading looked weird because the other rows also move over the top of the added/removed row.
* The duration is much shorter. 160ms for fade in animations, 220ms for zoom.
=> Refine table animations

.circleci/config.yml
=> fix Prod Docs build

packages/@react-aria/color/src/useColorField.ts, packages/@react-aria/interactions/src/useScrollWheel.ts, packages/@react-aria/numberfield/src/useNumberField.ts
Closes https://github.com/adobe/react-spectrum/issues/1792
also fix performance of useScrollWheel so it's not listened for at all while disabled
things considered while doing this
/**
* scrollstart/stop by setting a timeout/raf and ending scrolling if no new scroll events
* have come through in that time period, but if someone is scrolling slowly, this could be a lot of events
*
* adding a global document listener, and if the mouse moves declare the scrolling over
* this could be odd with a mouse though or something where movement is independent of the scrolling
*
* listen for how many fingers are down, but that doesn't register on trackpads
*
* use wheelDelta but that's deprecated
*
* take an absolute value comparison on each event, some flipping may occur if it's a diagonal close to 45 …
=> Fix diagonal scrolling in Numberfield

packages/@adobe/spectrum-css-temp/components/barloader/index.css, packages/@react-spectrum/meter/stories/Meter.stories.tsx, packages/@react-spectrum/progress/stories/ProgressBar.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/1192
Changed the width to min-width and added inline size.
Goto the meter and/or progress bar stories
Check out the new width stories
Also check the other stories like side labels without width because that was a problem case when making the change.
RSP
=> adding custom width support to meter and progressbar

packages/@react-aria/color/src/useColorField.ts, packages/@react-spectrum/color/src/ColorField.tsx, packages/@react-spectrum/color/src/colorfield.css
Closes 
Also fixes RTL entering of hex values 
From our i18n team:
The characters should flow right to left as you type them, and the entire string should be right-aligned within the text input field. The attached recording illustrates the expected behavior.
https://user-images.githubusercontent.com/698229/115625849-80dfe500-a2b1-11eb-8c88-32b9ff355716.mp4
=> Only allow colorfield scrolled stepping when focused

packages/@adobe/spectrum-css-temp/components/tabs/index.css, packages/@adobe/spectrum-css-temp/components/tabs/skin.css
Safari doesn't support transitioning `currentColor` in SVGs apparently.
=> Fix tab icon animation in Safari

packages/@react-aria/button/stories/useButton.stories.tsx, packages/@react-spectrum/button/stories/Button.stories.tsx, packages/@react-spectrum/dialog/stories/Dialog.stories.tsx
=> Adding additional stories for testing

packages/@react-aria/button/package.json
This dependency is not used by this package and can be safely removed.
=> Remove unused @react-aria/i18n dependency from @react-aria/button

packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx, packages/@react-stately/data/src/useAsyncList.ts, packages/@react-stately/data/test/useAsyncList.test.js
=> Fixing useAsyncList loadMore skip logic

packages/@react-spectrum/tabs/src/Tabs.tsx, packages/@react-spectrum/tabs/stories/Tabs.stories.js, packages/@react-spectrum/tabs/test/Tabs.test.js
Found during release testing
Added a persisting unique key to each tab to prevent value spreading between components all the same child position of TabPanels.
Statement of Issue:::
Goto https://reactspectrum.blob.core.windows.net/reactspectrum/a9f71944e0bbacf4b7ba0f3651c2875dbac7aefe/storybook/index.html?path=/story/tabs--focusable-element-in-tab-panel
enter a value in the text field
switch tabs and it persists between tabs.
Caused by no keys on element.
Goto the existing tabs focusable-element-in-tab-panel story
Enter a value in the text field, switch panels and it goes away and does not come back when going to the original tab.
Got the new tabs tabs-controlled-child story
Enter a value in first tab, switch tabs and it isn't in the second, go back to the first and it is still there.
RSP
=> adding key to TabPanel to prevent children value sharing

packages/@react-spectrum/combobox/docs/ComboBox.mdx
Closes 
Followup to https://github.com/adobe/react-spectrum/pull/1749
=> Updating combobox docs to explain onOpenChange changes

.github/ISSUE_TEMPLATE/Bug_Report.md
If we offer a link to a codesandbox that people can just start editing, maybe we'll get more reports with a reproduction case
Closes
=> Add codesandbox template to bug report template

packages/@react-aria/menu/docs/useMenuTrigger.mdx
HI team,
I was going through the `useMenuTrigger`  documentation to use in my own project and noticed that there was an import missing in the example for `useMenuTrigger`. I've added it in this PR 👍🏼
=> Add missing `useMenuTrigger` import to documentation

packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@adobe/spectrum-css-temp/components/button/skin.css, packages/@react-spectrum/button/chromatic/ActionButton.chromatic.tsx, packages/@react-spectrum/button/chromatic/ToggleButton.chromatic.tsx, packages/@react-spectrum/button/src/ActionButton.tsx, packages/@react-spectrum/button/src/ToggleButton.tsx, packages/@react-spectrum/button/stories/ActionButton.stories.tsx, packages/@react-spectrum/button/stories/ToggleButton.stories.tsx, packages/@react-types/button/src/index.d.ts
Implements the new `staticColor` option for ActionButton and ToggleButton, which can be set to `white` or `black`. This is useful when the button is placed over a color background, and will be needed for ActionBar.
The implementation makes use of CSS vars to avoid duplicating all of the classes many times. In addition it uses the mix-blend-mode property to knock out the text in the selected version so that it becomes whatever color is behind the button automatically!
This also implements halo focus rings for emphasized toggle buttons.
=> Implement staticColor prop for ActionButton and ToggleButton

packages/@react-spectrum/menu/docs/Menu.mdx, packages/@react-spectrum/menu/docs/MenuTrigger.mdx
Closes 
Spectrum links to Popovers should no longer be broken
RSP
=> [menu docs fix] broken spectrum links

packages/@react-spectrum/layout/src/Flex.tsx, packages/@react-spectrum/layout/src/Grid.tsx, packages/@react-spectrum/provider/src/Provider.tsx, packages/@react-spectrum/utils/src/styleProps.ts, packages/@react-spectrum/view/src/View.tsx
Closes 
While not documented, this function is technically exported, better to be safe and keep the existing function signature unbroken
introduced in https://github.com/adobe/react-spectrum/pull/1684
=> Revert function signature breaking change useStyleProps

packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-spectrum/table/test/Table.test.js, packages/@react-stately/layout/src/ListLayout.ts
Closes #1885
Test steps:
1. Go to http://localhost:9003/?path=/story/tableview--controlled-selection-mode
2. change selection mode to multiple
3. Select any table row
4. Change selection mode to none. Note the table shouldn't throw
=> fix(#1885) Making ListLayout updateItemSize early return if layoutInfo is undefined

packages/@react-aria/tabs/src/useTabPanel.ts
Closes https://github.com/adobe/react-spectrum/issues/1886
Open the Storybook in the `Tabs.stories.tsx`, verify the stories 'tabs at the bottom'. The `div` should not contain the HTML attribute `height` with the value "size-1000",
Outside adobe.
=> Limit props to the interface when calling useTabPanel

packages/@react-spectrum/listview/package.json
Closes 
reference to alpha.1 was causing us to install it from npm
=> Fix grid deps

packages/@adobe/spectrum-css-temp/components/breadcrumb/index.css, packages/@adobe/spectrum-css-temp/components/breadcrumb/skin.css, packages/dev/docs/package.json, packages/dev/docs/src/docs.css, packages/dev/docs/src/docs.js
Reasoning being that we need to manage focus in the docs, not by changing our component if at all possible.
Closes
=> Revert docs breadcrumb focus

packages/@react-spectrum/provider/src/Provider.tsx, packages/@react-spectrum/provider/test/Provider.test.js, packages/@react-spectrum/utils/src/styleProps.ts
Fixes a couple issues I found with responsive style props while writing the docs.
1. Default breakpoints. There are now more of them, and the small breakpoint is now 640px instead of 320px. The `base` value should be used for smaller values than that. These values were shamelessly stolen from Tailwind CSS. https://tailwindcss.com/docs/responsive-design
2. Fixed falsy values in responsive style props, as well as the `hidden` DOM attribute for the `isHidden` style prop.
=> Fixes for responsive style props

packages/@react-aria/interactions/src/usePress.ts
Fixes an issue introduced in #1613 where we noticed that clicks were sometimes not being registered.
=> Fix usePress hit detection

packages/@react-spectrum/combobox/src/MobileComboBox.tsx, packages/@react-spectrum/combobox/test/ComboBox.test.js
Matches desktop behavior so that the tray shows all items when re-opening a combobox, even when something is selected.
=> Show all items when opening mobile combobox

packages/@react-spectrum/combobox/src/MobileComboBox.tsx, packages/@react-spectrum/combobox/test/ComboBox.test.js
Because the validation icon is visible, show the clear button even when the field is empty so there isn't empty space like we do for loading states.
=> Always show clear button when mobile combobox has validation state

packages/@react-spectrum/menu/docs/MenuTrigger.mdx, packages/@react-spectrum/tooltip/docs/Tooltip.mdx
Closes #1245 
Check docs at React Spectrum -> Tooltip -> Content
=> Update TooltipTrigger docs to mention trigger and tooltip ordering (#1245)

packages/dev/docs/pages/react-spectrum/styling.mdx
=> Add docs for CSS functions in style props

packages/@react-spectrum/menu/docs/MenuTrigger.mdx
Small fix, just noticed that this was broken when looking at flip behavior
=> Fixing MenuTrigger docs examples

packages/@adobe/spectrum-css-temp/components/actiongroup/index.css
Fixes an issue seen in the prod build of the docs where the chevron is on the wrong side of the button. https://react-spectrum.adobe.com/react-spectrum/ActionGroup.html#selection-1
=> Fix ActionGroup CSS specificity

packages/@react-spectrum/table/test/Table.test.js, packages/@react-stately/virtualizer/src/Virtualizer.ts
Closes https://github.com/adobe/react-spectrum/issues/1153
Go to http://localhost:9003/?path=/story/tableview--hiding-columns
Hide all columns via clicking each checkbox
Hover each row and make sure the highlight extends to the end of the table
=> Properly update TableView row width when it is the last column remaining

packages/@react-spectrum/utils/src/BreakpointProvider.tsx
In react spectrum there was a new type that failing strictNullChecks for a custom string.
=> Fix type for strictNullChecks

patches/@parcel+bundler-default+2.0.0-nightly.359.patch
Disables the bundle optimization step completely for now. Will result in a single bundle per page duplicating all shared code between pages rather than separate individually cacheable bundles.
=> Patch parcel to workaround docs issue

.circleci/config.yml
Node 14 fails to build the nightly release, reverting back to node 12 where it is successful and keeping a different branch open to debug 14
Closes
=> Revert to node 12.22 to fix nightly

packages/@react-aria/combobox/src/useComboBox.ts
e.g. in the case of a search autocomplete field that doesn't have an explicit button to open the combobox
Fixes this example on blur: https://codesandbox.io/s/dreamy-burnell-3i2jy?file=/src/ListBox.tsx
=> Fix error when buttonRef is not provided to useComboBox

packages/@react-aria/aria-modal-polyfill/src/index.ts
Noticed in the ComboBox docs on iPad that I could not navigate between the input and the listbox. This was because the aria-modal-polyfill was hiding the entire page due to the `data-ismodal` attribute appearing on the popover. But it shouldn't apply when set to false.
=> Prevent aria-modal-polyfill from hiding ComboBox in the docs

packages/@react-aria/aria-modal-polyfill/src/index.ts
When rendering into iframes, for example when using [react-frame-component](https://github.com/ryanseddon/react-frame-component/), the usual intention is to listen for events from that iframe's document/window and not from the ones in the frame in which the script is executed (those can be two different global environments).
This is a somewhat test PR - we wonder if you would be open to accepting similar ones for more places in the code. I believe that a `useGlobals` hook (or similar) could be introduced and those globals could be provided using React context so all hooks could receive that information from the context, without manual prop drilling using options etc.
=> Add support for a custom document in `watchModals`

packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-aria/focus/src/useFocusable.tsx, packages/@react-aria/selection/src/useSelectableCollection.ts
I believe that `autoFocus` prop should behave like the native one - so it should only be handled when the component in question gets mounted to the DOM.
React takes the liberty to refire effects (after cleaning them up) which can already happen today when one performs a Fast Refresh update. I don't think that in such a scenario we should focus the element.
Assess correct behavior manually - I don't think this deserves unit tests due to rather complex test setup that would be required to cover this.
=> Prevent autoFocus from being reexecuted during Fast Refresh

CONTRIBUTING.md
While reading the contributing guidelines, I noticed that the link to the documentation of the architecture was broken. This PR fixes that link so it points to [the page](https://react-spectrum.adobe.com/architecture.html) that is referred to elsewhere.
=> Fix link to architecture documentation in CONTRIBUTING.md

packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx
TL;DR the `current` field on a ref is `T | null` not `T` and we must
guard against invalid access by first interrogating `current`.
Since refs are initialized as null and can become null at runtime, blind
access to `current` can lead `TypeError`s (as cited in #1979).
In practice it seems this _can happen reliably_ in situations where a
`Breadcrumb` component is being unmounted as part of a larger component
tree.
Unfortunately, I have not been able to reduce this error case to a small
reproduction, therefore I have not been able to add a test explicitly
to signal regressions.
Still, and this is quite troubling, the Typescript compiler should be
flagging invalid access such as this. I'm not sure if something has been
disarmed in the tsconfig to assume `T | null` is `T` in this case, but
a …
=> Fixup null reference access in Breadcrumbs `computeVisibleItems`.

plop-templates/@react-aria/docs/useComponent.mdx.hbs, plop-templates/@react-aria/index.ts.hbs, plop-templates/@react-aria/src/index.ts.hbs, plop-templates/@react-aria/src/useComponent.ts.hbs, plop-templates/@react-aria/test/useComponent.test.js.hbs, plop-templates/@react-spectrum/chromatic/Component.chromatic.tsx.hbs, plop-templates/@react-spectrum/docs/Component.mdx.hbs, plop-templates/@react-spectrum/index.ts.hbs, plop-templates/@react-spectrum/src/Component.tsx.hbs, plop-templates/@react-spectrum/src/index.ts.hbs, plop-templates/@react-spectrum/stories/Component.stories.tsx.hbs, plop-templates/@react-spectrum/test/Component.test.js.hbs, plop-templates/@react-stately/docs/useComponentState.mdx.hbs, plop-templates/@react-stately/index.ts.hbs, plop-templates/@react-stately/src/index.ts.hbs, plop-templates/@react-stately/src/useComponentState.ts.hbs, plop-templates/@react-types/src/index.d.ts.hbs, plop-templates/@scope/index.ts.hbs, plop-templates/@scope/src/index.ts.hbs, scripts/plopfile.js
Closes https://github.com/adobe/react-spectrum/issues/2147
1. Run `yarn plop`
2. Do the needful
3. Inspect license header in generated files
4. Should pick current year (2021 as of the year of authoring this PR)
Adobe/RSP
=> Make plop pick current year

packages/@adobe/spectrum-css-temp/components/table/index.css, packages/@react-spectrum/table/src/TableView.tsx, packages/@react-spectrum/table/test/Table.test.js
Closes #2089
Goto any table story with selection (checkboxes).
Goto the spectrum and spectrum-css docs and compare that the selected checkbox has the same whitespace as these docs. https://spectrum.adobe.com/page/table/ and https://opensource.adobe.com/spectrum-css/table.html
RSP
=> #2089 cleaning up selected checkbox whitespace

packages/@react-aria/table/intl/en-US.json, packages/@react-aria/table/package.json, packages/@react-aria/table/src/useTable.ts, packages/@react-aria/table/src/useTableColumnHeader.ts, packages/@react-spectrum/table/test/Table.test.js, packages/@react-stately/table/src/Column.ts, packages/@react-types/table/src/index.d.ts
Closes #2063 
1. Go to tableview--async-loading story with VoiceOver/JAWS/NVDA
2. Navigate to the column headers and make sure their sortablity is announced
3. Change the sort order of the column and make sure it is announced
Known issues:
- Announcements of table sort order changes are quite flakey on iPhone/iPad VoiceOver. Either they cut out or don't announce at all.
- iOS VoiceOver doesn't announce the `aria-describedby` content of the table columns at all, happens with native `th` elements as well (https://xyi4e.csb.app/)
- You must tap on/navigate off of and back on the column header in iOS VoiceOver to hear the aria-sort of the current column  
RSP
=> Making TableView columns announce sort info and sort order changes 

packages/@react-spectrum/label/src/Field.tsx
Closes https://github.com/adobe/react-spectrum/issues/1981
I know this introduces a new bit of dom structure, but it's the only way I can think of. We really shouldn't be changing how a component displays.
=> Fix field label overriding display property

packages/@adobe/spectrum-css-temp/components/searchwithin/index.css
Verify Searchwithin default and min width of size-3000.
RSP
=> Add min width to Searchwithin

packages/@react-spectrum/table/test/Table.test.js, packages/@react-stately/virtualizer/src/LayoutInfo.ts, packages/@react-stately/virtualizer/test/LayoutInfo.test.tsx
Closes 
Fixes issue where overflowMode="wrap" TableViews would have their selection checkbox cells covered by the other TableView cell when scrolling to the right.
1. Go to TableView's "overflowMode: wrap" story in storybook
2.  Shrink your window so that you can scroll the contents of the TableView
3. Scroll to the right. Note that the contents of the table slide under the selection checkbox cell rather than covering them up.
RSP
=> Fix "overflowMode: wrap" TableViews so that the selection checkbox cells have the proper z-index

packages/@react-aria/grid/src/useGridRow.ts, packages/@react-aria/listbox/src/useOption.ts, packages/@react-spectrum/listbox/test/ListBox.test.js, packages/@react-spectrum/table/test/Table.test.js
Closes 
Fixes erroneous announcement of row/option selected state by NVDA when those rows/options don't support selection
Go to TableView/ListBox stories where selectionMode="none". Check that screen readers don't announce the rows/options as "not selected"
RSP
=> Omitting aria-selected if grid or option doesn't support selection

packages/@react-aria/interactions/src/useInteractOutside.ts, packages/@react-spectrum/menu/src/MenuTrigger.tsx, packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-spectrum/table/test/Table.test.js
Two separate issues:
* On iOS, the tray seems to get blurred sometimes which causes it to close. Fixed by not closing trays on blur, which seems weird anyway considering they are overlays and should trap focus.
* On Android Firefox, the pointerdown event seems to be fired during the mount of the Tray component, which is followed by a pointerup event that closes it. This was related to us re-binding the event on every render when the callbacks rather than only on mount. Now the callbacks are stored in a ref to avoid that.
=> Fix MenuTrigger closing immediately

packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-spectrum/dialog/test/DialogTrigger.test.js
Closes 
Go to DialogTrigger -> with Menu Trigger, use the keyboard to open the Menu, press tab, focus should be restore to the Menu Trigger button
=> Fix focus scope restore losing focus

packages/@react-spectrum/searchwithin/src/SearchWithin.tsx, packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx
Closes 
There are no designs and it's not in the SearchWithin API to support validationState, this uses slots to ensure it can't be set on the individual components nor can it be set via the Provider
=> Searchwithin validationState behavior

packages/@adobe/spectrum-css-temp/components/table/index.css, packages/@react-spectrum/table/src/TableView.tsx
no github issue, found during a testing session
decided to go with a CSS solution rather then preventing a divider class from being added to the last cell
goto stoybook and check that their is no divider on the last cell of table row
once https://github.com/adobe/react-spectrum/pull/2163 is merged we can test this in those stories
RSP
=> TableView - preventing a divider from showing on the last cell of a table row

packages/@react-spectrum/table/stories/Table.stories.tsx
No jira - added two stories to better test defaultSelectedKeys, selectedKeys, and showDivder.
There are a couple issues with these related to dividers and selection, but they are existing issues and recorded in the testing spreadsheet. I'm not sure if fixes should be included in this PR.
New stories
- defaultSelectedKeys, dynamic, multiple selection, showDivider
- selectedKeys, dynamic, multiple selection, quiet, showDivider
RSP
=> TableView new stories to test selected keys and dividers

packages/@react-spectrum/label/src/Field.tsx
Reverts adobe/react-spectrum#2164
This is causing more issues than it solves at the moment. We'll need to fix another way.
=> Revert "Fix field label overriding display property"

packages/@adobe/spectrum-css-temp/components/fieldlabel/index.css, packages/@adobe/spectrum-css-temp/components/searchwithin/index.css, packages/@react-spectrum/label/src/Field.tsx, packages/@react-spectrum/searchwithin/chromatic/SearchWithin.chromatic.tsx, packages/@react-spectrum/searchwithin/src/SearchWithin.tsx
Closes 
As found here: https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=93
and as shown fixed here: https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=94
And also fixes SearchWithin label position side where changing the scope changed the overall width of the component
=> Fix Field-field shrink behavior

packages/dev/docs/pages/react-spectrum/ssr.mdx
Closes #2159 
In Docs, check React Spectrum -> Server Side Rendering -> Next.js. Test with new Next app.
RSP
=> Update SSR docs for Next.js 11

packages/@react-stately/data/src/useListData.ts, packages/@react-stately/data/test/useListData.test.js
Followup to https://github.com/adobe/react-spectrum/pull/2200. 
Adds check to last method which refers to `selectedKeys`.
In the `TableView async loading` story, click the select all checkbox and then click the *Remove first item* button. Note selection remains selected for all
=> Fix useListData remove method for all selection

packages/@internationalized/number/src/NumberParser.ts, packages/@internationalized/number/test/NumberParser.test.js
We ran into a bug with number fields formatted as `style: percent` — regardless of other formatting settings, the decimal character is considered invalid unless `minimumFractionDigits` is greater than `0`. For example, even with `maximumFractionDigits: 1`, you can't type the decimal character in a number field.
The values used for determining valid characters only have a single decimal place, but percent formatting multiplies this by 100, removing the decimal unless `minimumFractionDigits` is set.  This PR pads the decimal out to 3 places, fixing the issue.
- I can file an issue if that's preferred, but the fix is simple enough that I figured I'd get a PR up
I added two test cases to cover this issue. Both failed before this change and pass with this PR.
=> Fix decimals in `percent` number fields without `minimumFractionDigits`

packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-aria/focus/test/FocusScope.test.js, packages/@react-spectrum/dialog/test/DialogTrigger.test.js
This fixes a few FocusScope issues found while working on DatePicker.
* In #2139, we added a check if a FocusScope container another nested one to prevent them from clashing. However, this DOM check only checked if one was contained inside another, not that the active element was actually inside it. For example, a focus scope could be a sibling of another focusable element. Focus scopes can also not have the `contain` property set, in which case this also doesn't apply.
* If you didn't have `restoreFocus` enabled, we still handled the Tab key rather than leaving it to the browser.
The fix is to track which the focus scope hierarchy in a tree so we can allow the correct one to handle focus/blur events rather than all of them. This is done in a map, and via context. Moving to a child focus …
=> Fix FocusScope issues

packages/@react-stately/data/src/useAsyncList.ts, packages/@react-stately/data/src/useListData.ts, packages/@react-stately/data/test/useAsyncList.test.js
If list data has unloaded items, removing the last visible selected item will keep the selection at the `all` value. If all items have been loaded, removing the last visible selected item will change selection to an empty set.
If list data has unloaded items, a remove `all` selected items will remain at the `all` value. If all items have been loaded, a remove `all` will change selection to an empty set.
=> Update useListData to handle select all w/ unloaded lists

packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/interactions/test/usePress.test.js, packages/@react-types/shared/src/events.d.ts
Closes #2235
In the story `Button` actions now fire with the altKey modifier in the event.
=> Add altKey modifier to usePress hook events

packages/@react-stately/utils/src/useControlledState.ts
This reverts commit 573b61efe73342812f1024621c370eefc75664dd.
Rob's partial fix for useControlledState accidentally got merged in with the Help Text PR #1846.
* Build passes
* Test instructions from #1846 are all still valid
=> Revert "Update useControlledState for StrictMode"

packages/@react-types/layout/src/flex.d.ts
This PR changes the children for `Flex` to be `ReactNode` to support child expressions like:
```tsx
<Flex>
<span>Hello</span>
{name && <span>, {name}</span>}
</Flex>
```
Before, it used to complain:
`
Type 'boolean' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>'.ts(2322)
`
```
yarn test
```
Adobe/RSP
=> Make Flex take ReactNode children

packages/@react-types/color/src/index.d.ts
Closes #1666
- remove `onChange` prop of `ValueBase`
=> Fixes #1666: Omit duplicated type in ColorFieldProps

packages/@react-spectrum/list/src/ListView.tsx, packages/@react-spectrum/list/src/ListViewItem.tsx, packages/@react-spectrum/list/test/ListView.test.js, packages/@react-stately/grid/src/useGridState.ts
Selection is pretty iffy even with this change (shift + keyboard/mouse doesn't range select) and now that I thought about it more, I don't think this is really a correct usage of `allowsCellSelection` so gonna revert my suggestion and apply a different approach that fixes selection. This way we won't be adding a new prop to useGridState to enable behavior that I'm not 100% on
NOTE: This does break keyboard navigation for the ListView, but IMO better that than release a new prop on useGridState for now
=> Removing allowsCellSelection from useGridState

packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx, packages/@react-spectrum/numberfield/stories/NumberField.stories.tsx
There are now with description and with error message stories for combobox and numberfield.
RSP
=> adding helptext stories to combobox and numberfield

packages/@react-aria/numberfield/src/useNumberField.ts, packages/@react-aria/searchfield/src/useSearchField.ts, packages/@react-aria/select/src/useSelect.ts, packages/@react-spectrum/numberfield/src/NumberField.tsx, packages/@react-spectrum/numberfield/test/NumberField.test.js, packages/@react-types/numberfield/src/index.d.ts
=> Fixing error message and description announcement for NumberField

packages/@react-aria/tooltip/docs/useTooltipTrigger.mdx, packages/@react-aria/tooltip/src/useTooltipTrigger.ts, packages/@react-spectrum/actiongroup/stories/ActionGroup.stories.tsx, packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx, packages/@react-spectrum/tooltip/test/TooltipTrigger.test.js
Reverts adobe/react-spectrum#2102
This is because it has added a dom node to several components and they can't handle the extra nodes in their calculations at this point. Because we don't know everything affected, we're reverting this and we'll try a different method to handle it, potentially portalling them to the end of the document body
=> Revert "fix(#2101): TooltipTrigger: Tooltip should remain hidden in the DOM to provide an IDREF for aria-describedby on trigger element"

packages/@adobe/spectrum-css-temp/components/textfield/index.css
Closes 
Turns off horizontal resizing because if we use min-width, you can expand a textarea but never shrink it
=> Fix textarea can be shrunk horizontally

packages/@adobe/spectrum-css-temp/components/table/index.css
Closes 
Fixes an issue seen in Docs prod where all sort icons are visible across all columns
Fixed in same manner as https://github.com/adobe/react-spectrum/pull/2023
=> Fixes visible sort icons in docs prod

packages/@react-spectrum/menu/src/ActionMenu.tsx
=> add rest of style props to action menu

packages/@adobe/spectrum-css-temp/components/textfield/index.css
Closes 
This appeared in datetime picker work
=> Restrict resizeability of textfield to textarea

packages/@adobe/spectrum-css-temp/components/inputgroup/skin.css, packages/@adobe/spectrum-css-temp/components/stepper/skin.css, packages/@adobe/spectrum-css-temp/components/textfield/skin.css, packages/@react-spectrum/textfield/stories/Textfield.stories.js
Noticed that some browsers apply form validation as you type when using the `type` or `pattern` attributes. This currently only shows the red border and not the error icon and is a bug I believe. Validation should only be shown when the `validationState` prop is set, so that apps can control validation behavior (i.e. only validate on submit rather than every keystroke).
=> Disable red border on browser form validation

packages/@react-spectrum/form/src/Form.tsx, packages/@react-spectrum/form/stories/Form.stories.tsx, packages/@react-spectrum/form/test/Form.test.js
Related to #2401. If you use `type="email"`, `pattern`, etc. native form validation UI shows rather than spectrum's help text. This adds `noValidate` to `<Form>` by default to avoid this.
Question: do we need a way to override this? I can't think of a valid use case that wouldn't be better served by custom Spectrum validation.
=> Add noValidate to Form by default

packages/@adobe/spectrum-css-temp/components/textfield/index.css
Thanks Chromatic https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=137
Closes
=> Disabled Textarea cannot be resized

packages/@react-spectrum/list/src/ListViewItem.tsx, packages/@react-spectrum/list/src/listview.css, packages/@react-spectrum/list/stories/ListView.stories.tsx
Align RSP ListView with Archon ListView pattern. Helps with Quarry GH 1344. 
I can't find any docs within the `list` component
Under the ListView section in the storybook, there is a story containing the new scenario ActionGroup + ActionMenu. No accessibility changes as far as I can see.
=> Add actionMenu slot to ListView

packages/@react-aria/color/src/useColorArea.ts, packages/@react-aria/color/src/useColorWheel.ts, packages/@react-aria/color/test/useColorWheel.test.tsx, packages/@react-aria/interactions/src/useMove.ts, packages/@react-aria/interactions/test/useMove.test.js, packages/@react-spectrum/color/test/ColorWheel.test.tsx, packages/@react-stately/color/src/useColorAreaState.ts, packages/@react-stately/color/src/useColorWheelState.ts, packages/@react-types/shared/src/events.d.ts
Reopening: #2491 by @snowystinger after it was mistakenly merged into #2483 
Closes 
Pulled into its own PR for discussion.
~useMove frequently appears with useKeyboard to handle page size movements, page movements are still movements, so this refactors to include that information. This has a side benefit that it means people can't mess up the order of keyboard events + use move events which resulted in bad onChange/onChangeEnd values.~
Update:
keep pageup/down and home/end separate from useMove to keep useMove from being a one-stop-shop. especially since those keys can mean vastly different things depending on what useMove is being used in. For example, 1d vs 2d movements. People may also want to hook up "wasd" for movement, which isn't covered by useMove and we probably wouldn't add it. …
=> Combine the useMove frequently appears with useKeyboard 

packages/@react-aria/color/src/useColorArea.ts
To better reflect behavior of slider inputs with mobile screen readers on iOS and Android, each input should be labeled by its individual channel name and we should remove aria-roledescription so the input is identified simply as a slider control.
Relates to: #2483, #1732 and #1118 in particular: https://github.com/adobe/react-spectrum/pull/2483#discussion_r746975895
1. Open [a ColorArea story](https://reactspectrum.blob.core.windows.net/reactspectrum/967edb1559fff010f4ce6873e54ae2b3b5db7150/storybook/iframe.html?id=colorarea--x-blue-y-green&providerSwitcher-locale=&providerSwitcher-theme=&providerSwitcher-scale=&providerSwitcher-toastPosition=bottom&viewMode=story) in Safari on an iOS device.
2. Turn on VoiceOver for iOS.
3. Use right swipe VoiceOver gesture to navigate to the first of …
=> ColorArea: remove aria-roledescription on iOS/Android

packages/@react-spectrum/list/test/ListView.test.js
Closes 
Has caused a couple intermittent failures. I'm not sure why it's not 100% reproducible, but I'm guessing it's rounding related + some timing that causes the virtualized list not to load a third item since the height of the overall view is only 1.5x a single item's height. Once we move to modern jest timers, maybe this will resolve. React 18 may shed some light on this as well if something is updating when we don't expect it to.
https://app.circleci.com/pipelines/github/adobe/react-spectrum/6342/workflows/7873a221-7f4f-479a-8ea2-f232b3a01e60/jobs/55705/steps?invite=true#step-103-84
https://app.circleci.com/pipelines/github/adobe/react-spectrum/6345/workflows/4c69c065-45d3-4813-872e-3f097f6a0e16/jobs/55746/parallel-runs/2
=> Fix flaky test

packages/@react-spectrum/tooltip/stories/TooltipTrigger.stories.tsx
Closes 
Great news, chrome was reading it, it was just hard to detect because it sounded like such a normal thing to VO to say. So I made the text much more obvious
=> Make link tooltip testing story obvious

packages/@react-aria/grid/src/useGridCell.ts, packages/@react-aria/grid/src/useGridRow.ts, packages/@react-aria/selection/src/useSelectableItem.ts, packages/@react-aria/table/src/useTableCell.ts, packages/@react-aria/table/src/useTableHeaderRow.ts, packages/@react-aria/table/src/useTableRow.ts
Updates found while working on #2579.
* Exposes `isPressed` from `useTableCell` and `useTableRow` as well as grid hooks. This lets you style the active state more easily.
* Change from `onKeyDown` to `onKeyUp` for emitting `onAction`. This is closer to how buttons typically work, and fixes an issue I saw where using `alert` in `onAction` caused the pressed state to never get removed from the row.
=> Highlight updates

packages/@react-aria/virtualizer/src/Virtualizer.tsx
Closes 
1. Go to Picker story: "picker async-loading"
2. Open the Picker and scroll down so it loads a couple more sets of results. Select one of those pokemon
3. Close the dropdown and reopen it. The selected item should be brought into view
=> Removing the prevent scroll behavior on virtualizer item focus

patches/@parcel+transformer-typescript-types+2.0.0-nightly.359.patch
Closes #1388
This applies the patch I created for Parcel fixing function signature overload types a while back, PR is here: https://github.com/parcel-bundler/parcel/pull/7036.
Rebuild `@react-aria/button` and verify that the type definitions for `useButton` in `dist/types.d.ts` contain no type errors.
N/A
=> Update parcel patch to fix generated function overload types

packages/@react-aria/color/src/useColorField.ts, packages/@react-aria/color/test/useColorField.test.js, packages/@react-spectrum/color/test/ColorField.test.js
Closes #2598 
1. Open any of the [ColorField examples in storybook](https://reactspectrum.blob.core.windows.net/reactspectrum/d0c3b850da21761efc49e6ea1cf1ce74fea1d5d7/storybook/index.html?path=/story/colorfield--default).
2. Focus the ColorField and enter a HEX value for a color.
3. Browser should not add red dotted underling for spellchecking the value entered.
=> fix(#2598): ColorField input should disable spellcheck

packages/@react-aria/datepicker/src/useDateSegment.ts, packages/@react-aria/selection/src/useSelectableCollection.ts, packages/@react-aria/utils/src/index.ts, packages/@react-aria/utils/src/scrollIntoView.ts, packages/@react-spectrum/datepicker/stories/DateRangePicker.stories.tsx
This fixes an issue found during release where DatePicker would cause the entire page to scroll when it was focused. This was due to the native `scrollIntoView`. This was not caught because we didn't have any stories with scrolling. We do need this to allow scrolling when using the arrow keys to move between segments, but only want the immediate container to scroll rather than the whole page. I extracted the utility we already use in selection and reused that instead.
=> Prevent date picker scrolling the whole page when focused

packages/@react-aria/searchfield/src/useSearchField.ts, packages/@react-aria/searchfield/test/useSearchField.test.js
Closes #2253
Verify new test for onKeyDown passes and user-provided onKeyDown even is called if provided as prop to SearchField.
RSP
=> Fix SearchField to call onKeyDown

packages/@react-aria/datepicker/src/useDateField.ts, packages/@react-aria/datepicker/src/useDateSegment.ts, packages/@react-spectrum/datepicker/test/DateField.test.js, packages/@react-spectrum/datepicker/test/DatePicker.test.js, packages/@react-spectrum/datepicker/test/DateRangePicker.test.js
This fixes two issues identified during previous testing sessions:
1. The currently selected date is not read until you change one of the segments and the live announcer picks up the change.
2. The help text and error message is not read unless you manually navigate to the group wrapper with the SR cursor (impossible with touch screen readers).
This is solved by applying the `aria-describedby` attribute to the individual date segments rather than only the group. However, reading the help text and currently selected date every single time you navigate to a segment is very repetitive and verbose. So, I only applied it to the first segment of a field (within a date range picker there are two fields). Assuming users navigate linearly, this should be ok and much less verbose. When there is an …
=> Add aria-describedby to date field segments so help text and value is read

packages/dev/docs/pages/react-spectrum/ssr.mdx
Without this change, Next.js latest fails to compile and complains with:
```
./node_modules/@react-spectrum/table/dist/main.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@react-spectrum/table/dist/module.js
```
NB: In the future, it might be nice to template this section in the doc
to automatically include the requisite imports, but I'm not familiar
enough with this project, nor Next, nor MDX to make that change at the
moment.
Closes #2639 
Create a boiler plate Next.js project and attempt to use a `Button` from `@adobe/react-spectrum`.
N/A
=> Fix Next.js SSR Docs

packages/@adobe/spectrum-css-temp/components/checkbox/skin.css
Closes 
1. Check out this branch and run storybook
2. Navigate to the [TableView / dynamic with selection](http://localhost:9003/?path=/story/tableview--dynamic-with-selection) story.
3. Select all checkboxes.
4. Click any of the rows repeatedly to toggle its checkbox on and off.
5. Notice how the Select All checkbox will no longer flicker grey.
Issue: [Checkbox flickers gray when switching from indeterminate to selected in Chrome #1834](https://github.com/adobe/react-spectrum/issues/1834)
If you navigate to the hosted [TableView / dynamic with selection](https://reactspectrum.blob.core.windows.net/reactspectrum/21f32255590d88597e73618614e83a3a6a8cc73e/storybook-17/index.html?path=/story/tableview--dynamic-with-selection) story, you will see that after selecting all the checkboxes  and …
=> fix(checkbox): removes + selector to solve grey flicker

packages/@adobe/spectrum-css-temp/components/breadcrumb/index.css, packages/@adobe/spectrum-css-temp/components/coachmark/index.css, packages/@adobe/spectrum-css-temp/components/dialog/index.css, packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@adobe/spectrum-css-temp/components/sidenav/index.css
Currently when using react-spectrum eslint will show a warning about `start` having mixed support:
```
./node_modules/@react-spectrum/breadcrumbs/dist/main.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/@rea
Warning
(1:745) start value has mixed support, consider using flex-start instead
./node_modules/@react-spectrum/breadcrumbs/dist/main.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/@rea
Warning
(1:83) start value has mixed support, consider using flex-start instead
```
This was reported in #956, #844 and #768.
This fixes those warnings.
This takes over from https://github.com/adobe/react-spectrum/pull/1793 (from @MarkRedeman), which has been …
=> Replace "start" with "flex-start" in CSS

packages/@react-aria/ssr/docs/useIsSSR.mdx, packages/@react-aria/utils/docs/mergeProps.mdx
Found when testing the parcel upgrade with docs-differ.
The previous configuration was adding missing semi-colons.
goto react aria useIsSSR and mergeProps and all the code should have semicolons. 
RSP
=> missing semi-colon that parcel upgrade and docs-differ revealed

packages/@react-aria/interactions/docs/interactions.mdx
Closes 
We don't test on 12 anymore, so we cannot verify its support. We follow along with roughly the last two major versions of any given browser. iOS is now on 15.
We also aren't going to prioritize fixing anything for iOS 12, though we still welcome contributions to provide wider support if the PR isn't overly complicated.
=> Updating minimum supported version for iOS

packages/@adobe/spectrum-css-temp/components/accordion/skin.css, packages/@adobe/spectrum-css-temp/components/avatar/skin.css, packages/@adobe/spectrum-css-temp/components/barloader/skin.css, packages/@adobe/spectrum-css-temp/components/breadcrumb/skin.css, packages/@adobe/spectrum-css-temp/components/circleloader/skin.css, packages/@adobe/spectrum-css-temp/components/dialog/skin.css, packages/@adobe/spectrum-css-temp/components/sidenav/skin.css, packages/@adobe/spectrum-css-temp/components/statuslight/skin.css, packages/@adobe/spectrum-css-temp/components/tabs/skin.css, packages/@adobe/spectrum-css-temp/components/tags/skin.css, packages/@adobe/spectrum-css-temp/components/toast/skin.css, packages/@adobe/spectrum-css-temp/components/tooltip/skin.css, packages/@react-spectrum/actionbar/src/actionbar.css
partial resolution for #2529
Test the following stories in WHCM 
* accordion
* actionbar
* avatar
* breadcrumbs
* tooltip
* toast
* tags
* statuslight
* sidenav
* progressCircle
* progessBar
* dialog
* tabs
| Component | Screenshot B4 | Screenshot After |
| --------------- | --------------- | --------------- |
| Accordion | ![Accordion - disabledKeys_ files, shared ⋅ Storybook and 1 more page - Work - Microsoft​ Edge 11_30_2021 4_50_26 PM](https://user-images.githubusercontent.com/1724479/144152759-9bcc4627-92a9-468d-ada1-accda4aa4114.png) | ![Accordion - disabledKeys_ files, shared ⋅ Storybook and 1 more page - Work - Microsoft​ Edge 11_30_2021 4_50_17 PM](https://user-images.githubusercontent.com/1724479/144152715-5d583591-4329-4cee-9cca-ff1a158a91e6.png) |
| ActionBar | ![Accordion - …
=> Whcm fixes

packages/@react-spectrum/icon/docs/workflow-icons.mdx
Fixes Workflow Icons page being missing from docs build
Verify Workflow Icons page is present in docs build
RSP
=> Fix Icons docs build

plop-templates/@react-spectrum/docs/{{ componentName }}.mdx.hbs
Verify new plop template for React Spectrum components is compatible with MDX v2
RSP
=> Fix plop docs template after MDX upgrade

packages/@react-spectrum/list/src/listview.css
When working on ListView's docs, I noticed some css specificity issues that weren't apparent in storybook. This PR essentially moves some selectors to be explicit descendants:
```scss
.react-spectrum-ListViewItem {
....
}
.react-spectrum-ListViewItem-checkbox {
...
}
```
to
```scss
.react-spectrum-ListViewItem {
....
.react-spectrum-ListViewItem-checkbox {
...
}
}
```
Generic checkbox styles were getting precedence over ListViewItem's checkbox styles in the docs, so this fixes that.
Verify that there are no style changes in storybook
RSP
=> Fix ListView css specificity

packages/@adobe/spectrum-css-temp/components/actiongroup/index.css
Fixes the following ActionGroup static color bug caught by chromatic: https://www.chromatic.com/test?appId=5f0dd5ad2b5fc10022a2e320&id=61de104b777900003aa56549
Uses the alternative method mentioned in https://github.com/adobe/react-spectrum/pull/2710.
Check the static color action group stories and make sure the text color/icon color matches the background div.
Also check that the borders between disabled and non disabled buttons in ActionGroup's "overflow mode: collapse, disabledKeys" story are clearly defined like shown below
RSP
=> Fix ActionGroup static color

packages/@adobe/spectrum-css-temp/components/card/index.css, packages/@react-spectrum/card/src/GalleryLayout.tsx
Closes https://github.com/adobe/react-spectrum/issues/2465
Unable to reproduce the following from the issue:
- Very difficult to scroll the default story gallery layout in iPhone, it requires multiple swipe gestures to get it going, i think the card view container is too tall? 
- in gallery layout dynamic cards, low variance in aspect ratios on iPhone, i get flashes as i'm scrolling of layout redoing something
1. Check the CardView gallery stories in large scale and verify that none of the cards overlap
2. Go to the "static card" story in Gallery Layout and try resizing the CardView container so it has 0 width. Resize it back to its original width and the cards should reappear.
RSP
=> Fixing CardView Gallery layout card overlap and container resizing

packages/@adobe/spectrum-css-temp/components/card/index.css, packages/@react-spectrum/card/src/GalleryLayout.tsx, packages/@react-spectrum/card/src/WaterfallLayout.tsx, packages/@react-spectrum/card/stories/GalleryCardView.stories.tsx, packages/@react-spectrum/card/stories/WaterfallCardView.stories.tsx
Just some things I felt were a bit off:
- item padding didn't really do anything in WaterfallLayout so I removed it 
- reduced the vertical item spacing between cards in quiet Waterfall and Gallery
Test the Gallery layout and Waterfall layout stories for CardView. Ignore the overlapping issue in Gallery large scale, solved by different PR
RSP
=> Reduce vertical item spacing in CardView and remove item padding option from Waterfall layout

packages/@adobe/spectrum-css-temp/components/card/index.css, packages/@react-spectrum/card/src/CardBase.tsx
Closes #2762 
Go to the Gridlayout CardView stories and the quiet grid Card stories. Make sure the square images don't have any padding around the image. For comparison: https://reactspectrum.blob.core.windows.net/reactspectrum/0661785f30971bdbcbd291282b26836cf272c3f8/storybook/index.html?path=/story/cardview-grid-layout--dynamic-cards (this is with the smart padding)
RSP
=> Removing smart padding from quiet grid cards

scripts/bumpVersions.js, scripts/diff.js
This adds a script that can be used to diff the packages to determine what changed since the last release. It also updates the logic in the versioning script to match.
We must diff each package individually, based on the git tag of the last release for that package. We previously just looked at the last tag on the whole repo, but this doesn't work if some packages are skipped during the last release.
=> Add release diffing script

packages/@react-aria/interactions/src/useMove.ts, packages/@react-aria/interactions/test/useMove.test.js, packages/@react-types/shared/src/events.d.ts
Closes 
Pulling this out of ColorArea PR
=> Add modifier keys to useMove

packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-aria/focus/stories/FocusScope.stories.tsx, packages/@react-aria/focus/test/FocusScope.test.js
Closes https://github.com/adobe/react-spectrum/issues/2415
Keep focus scope up to date with changing children and auto focus children.
The two cases observed are:
1) Open a dialog, change the children in the dialog, hit esc, focus is lost.
This was fixed by using scopeRef.current as pointed out in the issue description because the scope was out of date.
2) Open a dialog where a child has autofocus, hit esc, focus is lost.
This was fixed by changing when nodeToRestore is set so that it runs before autoFocus takes place.
We are preferring this PR over https://github.com/adobe/react-spectrum/pull/2416 right now because it's difficult to review due to the refactor. Not that the refactor is bad, but by breaking this up, we can make sure we know what the fix is, and we can refactor it …
=> Fix focus scope with changing children

packages/@react-spectrum/list/src/ListView.tsx, packages/@react-spectrum/list/src/listview.css, packages/@react-spectrum/list/stories/ListView.stories.tsx, packages/@react-spectrum/list/test/ListView.test.js
Closes 
Look at the loading and loadingMore ListView stories and verify that loading spinner takes all available space and loadingMore spinner takes a rows worth of space. Also try the async story and verify you can scroll and load items
RSP
=> ListView loading spinner height fix

package.json, packages/@react-aria/interactions/docs/interactions.mdx
Followup to #2776. This bumps the versions we have defined in our browserslist to match our documented browser support matrix. Due to this, our CSS gets smaller due to needing fewer prefixes (11 KB smaller than main, 15 KB smaller than cssnano).
=> Update browserslist config

packages/@react-aria/tag/src/useTag.ts
Closes 
Fixing some issues found from testing sesion
1. Verify that the disabled tags are announced as disabled when navigating through them via VO/Talkback. Do this for the individual disabled tag stories and the TagGroup disabled story
2. Verify the new messaging when navigating to a removable Tag via VO/Talkback
3. 
RSP
=> Adding aria-disabled to Tag

packages/@react-aria/grid/src/useGridRowGroup.ts, packages/@react-aria/table/src/index.ts
Something must have broken in the Parcel upgrade. @jrgarciadev reported that the CommonJS build of `@react-aria/table` was broken in the nightly version. The ESM version is fine, but NextJS uses the CJS build for server rendering. For now, I've applied a workaround, and I will investigate the Parcel issue separately.
=> Workaround Parcel bug with re-exports

packages/@react-aria/ssr/package.json, packages/@react-aria/ssr/src/SSRProvider.tsx, scripts/findCircularDeps.js, scripts/lint-packages.js
We had one from `@react-aria/ssr` -> `@react-aria/utils` -> `@react-aria/ssr`. Fixed it and added a lint script to check this so it doesn't happen again.
=> Add a script to detect circular dependencies

.browserslistrc, package.json
#2857
Two issues:
1. Browserslist was not picked up by Parcel because it was not in the package.json of each package. The root package.json was not used. Instead, we can move the browserslist to a `.browserslistrc` file in the root so that we don't need to repeat it. This fixes private class fields being compiled.
2. We need to lower our browser targets to a browser version that doesn't support optional chaining and nullish coalescing because webpack 4 is still widely used and doesn't support them. At some point in the future we will raise this again, so we encourage all users to upgrade webpack soon if possible.
=> Adjust browserslist to compile optional chaining

packages/@react-spectrum/card/stories/GridCardView.stories.tsx
trivial fix, forgot I had to exclude any non-story exports when using the new story format
Make sure there is only one falsy id story for CardView -> grid layout stories and that it works
RSP
=> Fixing broken cardview story

packages/@react-spectrum/combobox/test/ComboBox.test.js
Just adding a test for the combobox name propagation so we don't have to test it manually
N/A
RSP
=> Adding test for Combobox name propagation

packages/@react-stately/numberfield/package.json, packages/@react-stately/numberfield/src/useNumberFieldState.ts
Closes https://github.com/adobe/react-spectrum/issues/2870
Go to NumberField `controlled` story
Select all the text in the input
Type '1'
Blur
Should no longer see a blur showing the original value before the formatting takes hold
=> Fix controlled numberfield blur shows old value quickly

packages/@react-spectrum/list/src/ListViewItem.tsx, packages/@react-spectrum/list/test/ListView.test.js
Testing followup
Go to the draggable story for ListView and make sure all selectable rows are selected on pressUp
RSP
=> Making listview items select on pressUp if list is draggable

scripts/changelog.js
More of a starting point than a full changelog, but it at least formats the commits for all changed packages. Each package is diffed individually so that skipped packages in the last release are included. Then the commits are deduped and sorted by date.
One improvement could be to be able to exclude packages that we aren't publishing. Maybe integrate it into the versioning script.
=> Add a script to generate a changelog

packages/@react-spectrum/dialog/docs/AlertDialog.mdx, packages/@react-types/dialog/src/index.d.ts
Fixes broken links to spectrum docs in https://react-spectrum.adobe.com/react-spectrum/AlertDialog.html
=> updating AlertDialog spectrum doc links

packages/@adobe/spectrum-css-temp/components/calendar/index.css, packages/@adobe/spectrum-css-temp/components/calendar/skin.css, packages/@react-spectrum/calendar/docs/Calendar.mdx, packages/@react-spectrum/calendar/docs/RangeCalendar.mdx, packages/@react-spectrum/calendar/src/CalendarCell.tsx, packages/@react-spectrum/calendar/stories/Calendar.stories.tsx, packages/@react-spectrum/calendar/stories/RangeCalendar.stories.tsx, packages/@react-spectrum/calendar/test/Calendar.test.js, packages/@react-spectrum/calendar/test/CalendarBase.test.js, packages/@react-spectrum/datepicker/docs/DatePicker.mdx, packages/@react-spectrum/datepicker/docs/DateRangePicker.mdx, packages/@react-spectrum/datepicker/src/DatePicker.tsx, packages/@react-spectrum/datepicker/src/DateRangePicker.tsx, packages/@react-spectrum/datepicker/stories/DatePicker.stories.tsx, packages/@react-spectrum/datepicker/stories/DateRangePicker.stories.tsx, packages/@react-stately/calendar/src/useCalendarState.ts, packages/@react-stately/calendar/src/useRangeCalendarState.ts, packages/@react-types/calendar/src/index.d.ts, packages/@react-types/datepicker/src/index.d.ts
Closes [Add possibility to disable multiple date intervals in `Calendar` and `Datepicker` components](https://github.com/adobe/react-spectrum/issues/2792)
After starting Storybook (`yarn start`), check out those stories:
- [Date and Time/Calendar - multiple disabled intervals](http://localhost:9003/?path=/story/date-and-time-calendar--multiple-disabled-intervals)
- [Date and Time/RangeCalendar - multiple disabled intervals](http://localhost:9003/?path=/story/date-and-time-rangecalendar--multiple-disabled-intervals)
- [Date and Time/DatePicker - multiple disabled intervals](http://localhost:9003/?path=/story/date-and-time-datepicker--multiple-disabled-intervals)
- [Date and Time/DateRangePicker - multiple disabled intervals](http://localhost:9003/?path=/story/date-and-time-daterangepicker-- …
=> Add possibility to disable multiple date intervals in `Calendar` and `Datepicker` components

packages/@react-aria/visually-hidden/docs/VisuallyHidden.mdx
The `useVisuallyHidden` example was importing `VisuallyHidden` instead of `useVisuallyHidden`.
=> Fix typo in VisuallyHidden docs

packages/@react-spectrum/list/src/listview.css
Should be 12px padding like it was before, draggable rows override this themselves
Run chromatic.
Padding between the row border and text/icon/checkbox for non draggable rows should be `spectrum-150` (aka 12px medium scale)
Padding between the row border and text/icon/checkbox for draggable rows should be `spectrum-250` (aka 20px medium scale)
RSP
=> Reverting ListView item padding back to 12px

packages/@react-aria/calendar/docs/useCalendar.mdx, packages/@react-aria/calendar/docs/useRangeCalendar.mdx, packages/@react-aria/datepicker/src/useDatePicker.ts, packages/@react-aria/datepicker/src/useDateRangePicker.ts, packages/@react-spectrum/calendar/docs/Calendar.mdx, packages/@react-spectrum/calendar/docs/RangeCalendar.mdx, packages/@react-spectrum/calendar/stories/Calendar.stories.tsx, packages/@react-spectrum/calendar/test/CalendarBase.test.js, packages/@react-spectrum/datepicker/test/DatePickerBase.test.js, packages/@react-stately/calendar/src/useCalendarState.ts, packages/@react-types/calendar/src/index.d.ts
Depends on #2772 and #2873.
Closes #2627. Closes #2628.
This adds `focusedValue` and `defaultFocusedValue` props that allow setting or controlling the focused date in a calendar from the outside. Setting either one of these does not move DOM focus immediately, but just sets which date will get focus when the user tabs there. It also controls what month is visible in the calendar, if set to a value outside the currently visible range. There is also an `onFocusChange` event that is triggered whenever the user moves focus within the calendar.
This enables the `placeholderValue` prop on date picker to control where the calendar is opened up to, rather than always going to today's date if nothing is selected. You can also use it to control what month is showing from the outside, e.g. in the …
=> Add support for controlling focused date in calendar

packages/@react-aria/calendar/src/useCalendarCell.ts, packages/@react-spectrum/calendar/test/RangeCalendar.test.js
Depends on https://github.com/adobe/react-spectrum/pull/2772 and https://github.com/adobe/react-spectrum/pull/2873.
This fixes an issue in RangeCalendar when the `isReadOnly` prop is provided, where clicking on one of the selected dates caused selection to start and you couldn't get out of it. Now the date will only be focused.
=> Fix readonly range calendar behavior

packages/@react-aria/button/src/useButton.ts
Closes #2875
Closes #2925
Run the tests and typechecking with [the example from the @react-aria/button docs](https://react-spectrum.adobe.com/react-aria/useButton.html#example).
--
=> Make 'button' function overload default

packages/@react-spectrum/list/src/ListViewItem.tsx
`src` is not published, so we need to use the top-level built icons.
=> Fix import of icon

packages/@react-aria/overlays/src/usePreventScroll.ts
Closes #2030
See reproducible example: https://sosbp.csb.app/ from Issue [#2030](https://github.com/adobe/react-spectrum/issues/2030)
Private repository w/ [@contra](https://github.com/contra)
=> fix: allow input pasting on iOS Safari inside of Modals

packages/@react-aria/calendar/src/useCalendarBase.ts, packages/@react-aria/interactions/src/useFocus.ts, packages/@react-aria/interactions/src/useFocusWithin.ts, packages/@react-aria/interactions/src/utils.ts, packages/@react-aria/interactions/test/useFocus.test.js, packages/@react-aria/interactions/test/useFocusWithin.test.js, packages/@react-spectrum/calendar/package.json, packages/@react-spectrum/calendar/src/Calendar.tsx, packages/@react-spectrum/calendar/src/CalendarBase.tsx, packages/@react-spectrum/calendar/src/RangeCalendar.tsx, packages/@react-spectrum/calendar/test/CalendarBase.test.js, packages/@react-spectrum/textfield/test/TextField.test.js, packages/@react-stately/calendar/src/useCalendarState.ts
Closes #1935
This fixes two issues:
1. Focus ring not disappearing when a focused button becomes disabled. That is due to a combination of a React issue, where onBlur is not fired if a button becomes disabled, and the same issue natively in Firefox. This is solved by using native blur events, as well as a `MutationObserver` to simulate those for Firefox.
2. In calendar, when the previous and next buttons become disabled as a result of pressing them, focus is lost. Now we send it to the calendar body instead.
=> Improve handling when focused button becomes disabled

packages/@react-aria/datepicker/docs/useDateField.mdx, packages/@react-aria/datepicker/docs/useDatePicker.mdx, packages/@react-aria/datepicker/docs/useDateRangePicker.mdx, packages/@react-aria/datepicker/src/useDateField.ts, packages/@react-aria/datepicker/src/useDatePickerGroup.ts, packages/@react-aria/datepicker/src/useDateSegment.ts, packages/@react-spectrum/datepicker/src/DateField.tsx, packages/@react-spectrum/datepicker/src/DatePickerField.tsx, packages/@react-spectrum/datepicker/src/DatePickerSegment.tsx, packages/@react-stately/calendar/docs/useCalendarState.mdx, packages/@react-stately/calendar/docs/useRangeCalendarState.mdx, packages/@react-stately/calendar/src/useCalendarState.ts, packages/@react-stately/calendar/src/useRangeCalendarState.ts, packages/@react-stately/datepicker/docs/useDateFieldState.mdx, packages/@react-stately/datepicker/docs/useDatePickerState.mdx, packages/@react-stately/datepicker/docs/useDateRangePickerState.mdx, packages/@react-stately/datepicker/docs/useTimeFieldState.mdx, packages/@react-stately/datepicker/src/index.ts, packages/@react-stately/datepicker/src/useDateFieldState.ts, packages/@react-stately/datepicker/src/useDatePickerState.ts, packages/@react-stately/datepicker/src/useDateRangePickerState.ts, packages/@react-stately/datepicker/src/useTimeFieldState.ts
Mainly TS descriptions, and some basic MDX pages to show them.
Also renamed `useDatePickerFieldState` to `useDateFieldState` for consistency with the other hooks.
=> React Stately docs for DatePicker and Calendar

packages/@adobe/spectrum-css-temp/components/calendar/index.css, packages/@adobe/spectrum-css-temp/components/calendar/skin.css, packages/@internationalized/date/src/calendars/BuddhistCalendar.ts, packages/@internationalized/date/src/calendars/JapaneseCalendar.ts, packages/@internationalized/date/src/calendars/TaiwanCalendar.ts, packages/@internationalized/date/tests/conversion.test.js, packages/@react-aria/calendar/src/useCalendarGrid.ts, packages/@react-aria/calendar/src/useRangeCalendar.ts, packages/@react-aria/calendar/src/utils.ts, packages/@react-aria/datepicker/src/useDateField.ts, packages/@react-aria/datepicker/src/useDatePicker.ts, packages/@react-aria/datepicker/src/useDatePickerGroup.ts, packages/@react-aria/datepicker/src/useDateRangePicker.ts, packages/@react-aria/datepicker/src/useDateSegment.ts, packages/@react-spectrum/calendar/src/CalendarBase.tsx, packages/@react-spectrum/calendar/src/CalendarCell.tsx, packages/@react-spectrum/calendar/stories/Calendar.stories.tsx, packages/@react-spectrum/calendar/test/RangeCalendar.test.js, packages/@react-spectrum/datepicker/src/DatePickerField.tsx, packages/@react-spectrum/datepicker/src/DateRangePicker.tsx, packages/@react-spectrum/datepicker/src/Input.tsx, packages/@react-spectrum/datepicker/test/DateField.test.js, packages/@react-spectrum/datepicker/test/DatePicker.test.js, packages/@react-spectrum/datepicker/test/DateRangePicker.test.js, packages/@react-stately/calendar/src/useCalendarState.ts, packages/dev/docs/src/docs.css
The individual commits may be easier to review. This fixes many bugs found during testing:
* Day names are not centered (DG)
* If you switch to Japanese calendar it repeats monday twice (DG)
* Dark mode strike outs on unavailable dates are hard to see (RS)
* Remove hover and active state in read only (DG)
* If I click outside the circle but inside the cell, it will start and end my new range immediately, making it feel broken (RS)
* Option+Up arrow doesn't open the popover, only Option+Down arrow. Given that menus, pickers, etc open for both, I feel like this should too (RS)
* For the zoned time story it announces the range as march and not february. Devon says it should be march and is display february. Screenshot row 11 (KT)
* Minor issue with the "ZonedDateTime" text appearing above …
=> Bug fixes for DatePicker and Calendar

packages/@react-aria/table/src/index.ts, packages/@react-spectrum/table/src/Resizer.tsx
=> fix useTableColumnResize imports and exports

patches/@parcel+packager-js+2.2.1.patch
I'll get this upstreamed to Parcel soon, but this fixes an issue with the CJS build involving re-exports.
=> Patch parcel to workaround bug in CommonJS build

packages/@react-aria/overlays/src/useOverlay.ts
Per: https://github.com/adobe/react-spectrum/pull/2451#discussion_r729421265 and https://github.com/adobe/react-spectrum/pull/2451/files#r825220630
Closes #2449 but does not resolve all issues with restoring focus to TableView when ActionBar closes, which are addressed in #2451.
1. Open https://reactspectrum.blob.core.windows.net/reactspectrum/df4b5baa4f4be99ad54f624eaada3d689774c689/storybook/index.html?path=/story/actionbar--default
2. Tab and use Arrow keys to set focus to a row or cell within the TableView.
3. Press Space key to select the row.
4. Tab to move focus to the ActionGroup within the open ActionBar.
5. Use ArrowRight to focus the "..." dropdown menu button within the ActionGroup.
6. Press Space, Enter or ArrowDown to expand the dropdown menu.
7. Press Esc key to close the …
=> fix(#2449): ActionBar: add stopPropagation to useOverlay Esc key handler

packages/@react-types/autocomplete/src/index.d.ts, packages/@react-types/color/src/index.d.ts, packages/@react-types/combobox/src/index.d.ts, packages/@react-types/shared/src/inputs.d.ts, packages/@react-types/textfield/src/index.d.ts
As @LFDanLu noted in https://github.com/adobe/react-spectrum/pull/2966#discussion_r840133828, we can't just deprecate `placeholder` on `TextInputBase`, because it is used by `TextFieldProps`, which `useTextField` uses. So we'll need to change up types a bit in order to only deprecate `placeholder` on Spectrum components. This PR creates a `SpectrumTextInputBase` with the deprecated field. Opening as its own PR so its a bit easier to see. Definitely open to any better alternatives.
=> Fix types to deprecate placeholder

packages/@react-stately/virtualizer/src/Virtualizer.ts
A resize buffer column (spooky column) was added to the table collection if any columns are resizable. The purpose of the resize buffer is to grow and shrink when resizing to keep the width of the table constant if a user tries to shrink a column when the content width is greater than the virtualizer width.
Typically the resize buffer has a width of 0 since it only needs to take up space while actively resizing.
When `updateSubviews` gets called in `Virtualizer`, it determines everything that needs to be added/updated/removed. To determine what needs to be added, the `_visibleViews` is compared against the `visibleLayoutInfos`.  If the `_visibleViews` doesn't include the resizeBuffer, it will be added to the `toAdd` set.
`_postTransaction` calls `relayoutNow` with an `afterLayout` …
=> Virtualizer: don't remove zero width items from _visibleViews

packages/@adobe/spectrum-css-temp/components/dialog/index.css, packages/@spectrum-icons/build-tools/generateIcons.js, packages/@spectrum-icons/workflow/chromatic/Workflow.chromatic.tsx
Closes 
In preparation to being able to upgrade icon packages again in the future. Since we'll always pin our version now, we can rely on chromatic tests so we know if any particular update breaks anything.
It's broken up alphabetically with large heights so that if a single icon is added/removed we'll know without it affected every single other icon in the chromatic. Instead, it'll only affect icons after it in it's section of the alphabet.
Also contains a dialog style fix that was broken in chromatic
=> Add chromatic story with all icons

packages/@adobe/spectrum-css-temp/components/dialog/index.css
=> Fix Dialog grid iphone

packages/@react-aria/i18n/src/useDefaultLocale.ts, packages/@react-aria/i18n/src/utils.ts
Closes  #2436
Added try-catch to `isRTL` helper. Since `navigator.language` may return unpredictable outputs and it is not respecting the 
BCP 47 language tag standard the code may crash if we provide this value directly to `Intl.Locale()`
Since we can't write to navigator.language, I'm afraid testing it is hardly possible 😄
[LiveChat](https://www.livechat.com/)
=> add try-catch to isRTL and fallback to en-US

packages/@internationalized/date/src/CalendarDate.ts, packages/@internationalized/date/src/calendars/BuddhistCalendar.ts, packages/@internationalized/date/src/calendars/GregorianCalendar.ts, packages/@internationalized/date/src/calendars/IndianCalendar.ts, packages/@internationalized/date/src/calendars/JapaneseCalendar.ts, packages/@internationalized/date/src/calendars/TaiwanCalendar.ts, packages/@internationalized/date/tests/conversion.test.js, packages/@internationalized/date/tests/queries.test.js
Fixes issues identified by @majornista in https://github.com/adobe/react-spectrum/pull/3046#issuecomment-1106757623. The underlying cause was in code that converts Gregorian dates to and from a Julian day number, which is used for comparison and conversion between calendars. For this, we need to compute the "extended year", which flips the sign for dates in the BC era. This also needs to be handled in all calendars that extend from GregorianCalendar.
=> Fix issues converting and comparing Gregorian dates in BC

packages/@adobe/spectrum-css-temp/components/table/skin.css, packages/@react-spectrum/list/src/listview.css
Testing followups
Go to any ListView story and verify that selected + keyboard focused rows are a darker blue compared to just selected rows
RSP
=> Making selected, keyboard focused, emphasized ListView rows a darker blue

packages/@react-aria/calendar/src/useCalendarBase.ts, packages/@react-aria/calendar/src/useCalendarCell.ts, packages/@react-aria/calendar/src/useCalendarGrid.ts, packages/@react-aria/calendar/src/useRangeCalendar.ts, packages/@react-aria/calendar/src/utils.ts, packages/@react-spectrum/calendar/test/Calendar.test.js, packages/@react-spectrum/calendar/test/RangeCalendar.test.js, packages/@react-spectrum/datepicker/test/DatePickerBase.test.js, packages/@react-spectrum/datepicker/test/DateRangePicker.test.js
Moved the full selected range description in RangeCalendar to the first and last selected cell rather than an `aria-describedby` on the grid, which it seems no screen reader actually announces. Considered moving it to the `aria-label` of the grid so that it is announced when entering any cell within the grid, but this is not announced on VO iOS. Putting it on cells and grid is too verbose, so just went for the cells.
Fixed crash in aria useDateRangePicker docs where dragging an already selected range but ending on the original value threw a "body is undefined" error.
=> Calendar final testing updates

packages/@react-aria/dnd/src/DragManager.ts, packages/@react-aria/interactions/src/usePress.ts
dont want to expose isVirtualPointerEvent to users so copied it over to DragManager instead
RSP
=> Removing export of isVirtualPointerEvent from usePress

packages/@react-spectrum/list/src/ListView.tsx
This reverts commit 004180c9ea22ef71f2c3783eab735bf1481b73a7.
Closes
=> Revert "removing transitionDuration prop (#3059)"

packages/@internationalized/number/src/NumberParser.ts, packages/@internationalized/number/test/NumberParser.test.js
Closes https://github.com/adobe/react-spectrum/issues/3114
=> Fix NumberParser mistakenly returning arab code

packages/@react-spectrum/list/stories/ListView.stories.tsx
Closes 
First row of the "/listview--selection-single-checkbox-disabled" story should be disabled now
RSP
=> Fixing selection: single, disabled ListView story

packages/@react-spectrum/list/src/styles.css
Before:
After:
Go to ListView -> Drag and Drop -> Drag Between Lists (Root only) story
When performing a drag, verify that row dividers are not above the root drop indicator focus ring as shown above.
=> Fix ListView rows above focus ring

packages/@adobe/react-spectrum/src/index.ts
Closes 
Found internally to be missing, `import {ActionMenu} from '@adobe/react-spectrum';` should work as advertised here https://react-spectrum.adobe.com/react-spectrum/ActionMenu.html
=> Add ActionMenu to monopackage

packages/@react-aria/interactions/src/useFocus.ts, packages/@react-aria/interactions/src/useFocusWithin.ts
found during testing
Goto the useFocus and useFocusWithin pages in the aria docs.
Confirm the "API" section's method signature has "props".
RSP
=> Fixes missing 'props' from API sections of useFocus and useFocusWithin in aria-docs

packages/@react-spectrum/buttongroup/src/ButtonGroup.tsx
Closes 
Go to the "three buttons, footer" story and resize your window in such a way that the buttongroup in the dialog is vertically oriented. Close the dialog and note that there isn't a brief flicker of the dialog layout changing
Sample storybook where this issue happens for comparison: https://reactspectrum.blob.core.windows.net/reactspectrum/b5db74d40c139192c709193ee976dfc945d505b6/storybook/index.html?path=/story/dialog--three-buttons-footer&providerSwitcher-toastPosition=bottom
RSP
=> Fix dialog flicker on close for "three buttons, footer" story for React 18

packages/@react-spectrum/tabs/test/Tabs.test.js, packages/@react-stately/tabs/package.json, packages/@react-stately/tabs/src/useTabListState.ts
Closes 
Found in testing session
One outstanding question, should we select anything if all tabs are disabled? should it display anything in the tab panel? This PR gets us back to the state we had before which was yes to both of those questions, but I don't feel like we adequately considered this back when we implemented it.
Load up the story `/story/tabs--all-disabled`
it should render, the first tab should be selected, focus should go immediately to the tab panel
unit tests should cover the cases
=> Fix Tabs with every key disabled

packages/@react-aria/table/src/index.ts, packages/@react-aria/table/src/useTableColumnHeader.ts, packages/@react-spectrum/table/src/Resizer.tsx, packages/@react-spectrum/table/src/TableView.tsx, packages/@react-spectrum/table/src/TableView_DEPRECATED.tsx, packages/@react-spectrum/table/src/index.ts, packages/@react-spectrum/table/stories/HidingColumnsAllowsResizing.tsx, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-spectrum/table/test/Table.test.js, packages/@react-stately/layout/src/index.ts, packages/@react-stately/table/src/TableCollection.ts, packages/@react-stately/table/src/index.ts, packages/@react-stately/table/src/useTableColumnResizeState.ts, packages/@react-stately/table/src/useTableState.ts, packages/@react-stately/table/test/useTableColumnResizeState.test.ts, packages/@react-types/table/src/index.d.ts
We have to release Table for React 18 support, but column resizing isn't ready for a full release yet. Commenting it out for now, revert this PR after release.
=> Comment out column resizing code for release

packages/@adobe/spectrum-css-temp/components/table/index.css, packages/@react-spectrum/table/src/table.css
Same fix like #2695 for Table Component for better Browser Support and to eliminate eslint errors.
https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content
>### flex-start
>The items are packed flush to each other toward the edge of the alignment container depending on the flex container's main-start side. This only applies to flex layout items. **For items that are not children of a flex container, this value is treated like start.**
>### flex-end
>The items are packed flush to each other toward the edge of the alignment container depending on the flex container's main-end side. This only applies to flex layout items. **For items that are not children of a flex container, this value is treated like end.**
=> Changed justify-content: end to flex-end & start to flex-start for better Browser Support

packages/@react-aria/selection/src/useSelectableItem.ts, packages/@react-spectrum/list/src/ListViewItem.tsx, packages/@react-spectrum/list/stories/ListView.stories.tsx, packages/@react-spectrum/list/test/ListView.test.js, packages/@react-stately/dnd/src/useDraggableCollectionState.ts
Closes 
Fixes the following bugs:
- disabled rows are focusable when swiping left/right during a drag session
- drag into folder story: dropping items into the folder and then dragging the folder itself reflects the incorrect number of dragged items
In https://reactspectrum.blob.core.windows.net/reactspectrum/f8982cb86e88a39851a081bca7ba4f1767fb105f/storybook/index.html?path=/story/listview-drag-and-drop--drag-between-lists&providerSwitcher-toastPosition=bottom:
1. Focus an item in the second list
2. Drag a item from the first list to the second list via your mouse/touch
3. After the insert, focus should be on the newly inserted item
In https://reactspectrum.blob.core.windows.net/reactspectrum/f8982cb86e88a39851a081bca7ba4f1767fb105f/storybook/index.html?path=/story/listview-drag-and-drop- …
=> ListView dnd testing followups

packages/@internationalized/date/src/calendars/JapaneseCalendar.ts, packages/@internationalized/date/tests/manipulation.test.js, packages/@react-aria/calendar/src/utils.ts, packages/@react-aria/datepicker/package.json, packages/@react-aria/datepicker/src/useDateSegment.ts, packages/@react-spectrum/calendar/src/CalendarBase.tsx, packages/@react-spectrum/datepicker/test/DatePicker.test.js, packages/@react-stately/datepicker/src/useDateFieldState.ts, packages/dev/parcel-transformer-docs/DocsTransformer.js
Depends on #3167.
This adds support for entering an era in DatePicker by typing the first letter. This enables users of mobile devices to select an era when up and down arrow keys are not available.
=> Allow entering era in date picker by typing

packages/@internationalized/date/src/calendars/EthiopicCalendar.ts, packages/@internationalized/date/src/calendars/HebrewCalendar.ts, packages/@internationalized/date/src/calendars/IndianCalendar.ts, packages/@internationalized/date/src/calendars/IslamicCalendar.ts, packages/@internationalized/date/src/calendars/JapaneseCalendar.ts, packages/@internationalized/date/src/calendars/PersianCalendar.ts, packages/@internationalized/date/src/calendars/TaiwanCalendar.ts, packages/@internationalized/date/src/conversion.ts, packages/@internationalized/date/tests/conversion.test.js, packages/@internationalized/date/tests/manipulation.test.js
This fixes a bug found in testing related to #3149.
> default story - enter year 9999, change to japanese calendar
> it'll go to year 7981
> open the calendar and keyboard navigate to the cells
> press and hold down, it should eventually stop with the "next" button disabled, but this does not happen, instead it infinitely loops through the year 7981 (RS)
This was because we limit to 9999 in the Japanese calendar, but when calling onChange we convert to the Gregorian calendar and it gets clamped, thus making the effective maximum 7981 rather than 9999 Japanese.
I tried to remove the limits entirely, but this causes other issues, especially when hitting the actual maximum of the JS Date object. Instead, I've just changed the limits of each calendar so the maximum year is always 9999 …
=> Update year limits for all calendars to match 9999 gregorian

packages/@react-aria/datepicker/src/useDateSegment.ts, packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-spectrum/datepicker/test/DatePicker.test.js
Another small date picker bug found in testing: when pressing the up/down arrow on the BC era segment, it disappears and focus is lost. Now we shift focus to the previous or next segment (depending on the format). Try Latvian to have the era appear first.
=> Shift focus when era is removed while focused in DatePicker

packages/@internationalized/date/src/calendars/EthiopicCalendar.ts, packages/@internationalized/date/tests/conversion.test.js, packages/@react-spectrum/datepicker/test/DatePicker.test.js, packages/@react-stately/datepicker/src/useDateFieldState.ts
Bugs found in #3208 and #3213.
* Fix changing the era in Ethiopic dates. This was due to year being clamped to >= 1 when constructing CalendarDate.
* When the era field appears (e.g. due to changing the year field), we should mark it valid when the year is already valid.
=> Fix bugs with eras in DatePicker

packages/@react-aria/datepicker/src/useDateSegment.ts
This appears to have been a regression in the last release. Using the keyboard with VO on iOS, nothing happened when pressing a key. VO seems not to fire input events if `user-select: none` is present. This was changed here: https://github.com/adobe/react-spectrum/pull/3149/files#diff-91623cb4379cd8f4595bcf1861d171e23c8e3f161bed841f3d4a713471efc8f0. The original intent was to prevent the text selection menu (e.g. copy/paste) from coming up on long press, but I guess we can't really prevent that.
=> Fix entering dates with keyboard using VoiceOver on iOS

packages/@react-aria/datepicker/src/useDateSegment.ts, packages/@react-spectrum/datepicker/src/styles.css
Closes 
Remove a prevent default that wasn't working to prevent Android text selection of segment and context menu.
Also fixes iOS because pointer-events none is necessary (DatePicker with TimeField in a tray)
=> Fix FF date segment typing

packages/@react-aria/datepicker/src/useDateSegment.ts, packages/@react-spectrum/list/src/styles.css, packages/@react-spectrum/list/stories/ListView.stories.tsx
Closes 
1. In FF, go to the root drop ListView story and try dragging an item from list1 to list 2 via mouse. The root drop indicator for the lists should not persist upon leaving the list
2. Make the list quiet via controls and perform a root drop. The list should have a ring around it when it is the drop target
RSP
=> Fixing stuck FireFox ListView root drop indicator 

packages/@react-aria/calendar/src/useCalendarCell.ts
Fixes an issue seen in the docs, and in apps with page scrolling.
Reproduction steps:
1. Open https://react-spectrum.adobe.com/react-spectrum/DatePicker.html
2. Tab to the calendar button in the first date picker example, and press Enter.
3. See that it scrolls the whole page to the bottom.
This seems to be due to positioning code running after focusing of the cell. Workaround is to prevent default browser scrolling, but scroll into view manually so we only adjust the immediate scroll parent rather than the whole page.
This does break another case, where if you focus a cell and scroll the calendar off screen, then press an arrow key it doesn't scroll back into view. However, we have this issue in other components already and it's a less visible problem than scrolling the whole page to the …
=> Fix issue with page scrolling when opening calendar popover

packages/@react-types/list/src/index.d.ts
Closes 
Dnd docs won't be live for some time so the types shouldn't link to them until they are ready
RSP
=> Removing broken DnD links from ListView types

packages/@react-aria/dnd/src/DragManager.ts, packages/@react-aria/dnd/test/dnd.test.js
Previously when using VO on touch, no drop target was set when initiating a drag session. Now, the first drop target is set, so the user can immediately navigate drop targets when the drag session starts.
On iOS Safari with VoiceOver enabled:
1. Go to ListView -> Drag and Drop -> Drag within list (Reorder)
2. Start dragging an item
3. A drop indicator should appear, and you should be able to swipe left/right to navigate between drop items. (Previously there was no initial drop target).
=> DnD: Focus initial drop target when using iOS VO

packages/@react-aria/overlays/package.json, packages/@react-aria/overlays/src/calculatePosition.ts, yarn.lock
Reduces bundle size by ~1.8 KB.
=> Remove dom-helpers dependency from @react-aria/overlays

package.json, packages/dev/docs/pages/react-aria/getting-started.mdx, packages/dev/docs/pages/react-stately/getting-started.mdx, packages/dev/docs/src/HeaderInfo.js, packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js, yarn.lock
This updates the React Aria and React Stately examples to use the mono-packages rather than the individual packages, similar to how we have been doing it for React Spectrum. This simplifies the examples and reduces the number of packages people need to install.
Questions:
- How should we handle the `version` shown at the top of the page? In RSP, people have been confused since this doesn't match the mono package version.
- How should we expose what individual package a hook is part of?
- Why did we only do this in the production docs rather than PR/local builds before? For now I turned that off so I could test, but not sure what the reason was.
=> Use mono-packages for docs examples

packages/@react-aria/tabs/src/useTab.ts, packages/@react-spectrum/tabs/src/Tabs.tsx, packages/@react-stately/tabs/src/useTabListState.ts, packages/@react-types/tabs/src/index.d.ts
Fixes the aria docs example for isDisabled to disable all tabs (this PR will need to be merged into that one). This is done by attaching isDisabled to the state object. Also updates Spectrum Tabs to use the new Aria API.
=> Fix isDisabled in tabs

packages/@react-aria/menu/src/useMenuTrigger.ts
Fixes a regression found in #3264. MenuTrigger with menuTrigger=longpress would open both when long pressing and pressing normally. This was due to onPress being added in useOverlayTrigger. So now we override that at the useMenuTrigger level.
=> Fix menu trigger longpress

packages/@react-spectrum/dialog/stories/DialogTrigger.stories.tsx
Found during testing story improvement to prevent flipping on the popover placement stories.
goto dialog trigger stories, find the popover placement, shrink the browser so the popover has fit issues and see that it doesn't flip and renders to the correct placement.
RSP
=> Adding shouldFlip=false to the popover placement stories

packages/@adobe/spectrum-css-temp/components/textfield/index.css, packages/@adobe/spectrum-css-temp/components/textfield/skin.css, packages/@react-spectrum/label/intl/ar-AE.json, packages/@react-spectrum/label/intl/en-US.json, packages/@react-spectrum/label/package.json, packages/@react-spectrum/label/src/Field.tsx, packages/@react-spectrum/label/src/ReadOnlyField.tsx, packages/@react-spectrum/textfield/src/TextArea.tsx, packages/@react-spectrum/textfield/src/TextField.tsx, packages/@react-spectrum/textfield/src/TextFieldBase.tsx, packages/@react-spectrum/textfield/stories/TextArea.stories.js, packages/@react-spectrum/textfield/stories/Textfield.stories.js, packages/@react-types/label/src/index.d.ts
This reverts commit 94b3845182bb0df861febcc8dea395f5d0c92e76. Now that the release is done, we want this stuff back
RSP
=> Restore reverted ReadOnly textfield/textarea work

packages/@react-aria/grid/src/useGrid.ts, packages/@react-aria/table/src/useTable.ts, packages/@react-aria/table/test/useTable.test.tsx
Closes #3349 
1- Pass an id to useTable props 
2- the returning gridProps should have this id instead of a generated one
=> fix(#3349): useTable: Passing down provided id to useTable and useGrid

packages/@react-aria/interactions/src/usePress.ts, packages/@react-spectrum/table/test/Table.test.js
Closes #2599. Closes #2619.
Slightly different version of the fix in #2619 (test and partial fix reused). This fixes scrolling and selection when pressing Space when focused on a link in a TableView, while letting Enter trigger the link natively. Two fixes:
1. Use `currentTarget` rather than `target` to check whether to handle a keyboard event. This ensures the check for link handling doesn't apply when the table row is handling an event that propagated up from a link (e.g. Space key). This is the same as in #2619.
2. Stop propagation on native HTML links during keydown, even when we don't otherwise handle the event, because the browser will handle it natively and we don't want TableView to also handle it. This is different from #2619 in that the link handles it rather than the table. I …
=> Stop propagation when pressing Enter on a native link

packages/@react-spectrum/list/src/DragPreview.tsx, packages/@react-spectrum/list/src/styles.css
Closes 
Try dragging multiple ListView rows in the ListView drag stories. The badge shouldn't stretch to fill remaining space in the grid
RSP
=> Fixing ListView drag preview badge

packages/@react-aria/dnd/src/DragManager.ts, packages/@react-aria/dnd/src/ListDropTargetDelegate.ts, packages/@react-aria/dnd/src/index.ts, packages/@react-aria/dnd/src/useDrop.ts, packages/@react-aria/dnd/src/useDropIndicator.ts, packages/@react-aria/dnd/src/useDroppableCollection.ts, packages/@react-aria/dnd/src/useDroppableItem.ts, packages/@react-aria/dnd/stories/DroppableGrid.tsx, packages/@react-aria/dnd/stories/DroppableListBox.tsx, packages/@react-aria/dnd/stories/Reorderable.tsx, packages/@react-aria/dnd/stories/VirtualizedListBox.tsx, packages/@react-aria/dnd/stories/dnd.css, packages/@react-aria/dnd/test/dnd.test.js, packages/@react-aria/dnd/test/useDroppableCollection.test.js, packages/@react-spectrum/list/src/ListView.tsx, packages/@react-stately/layout/src/ListLayout.ts, packages/@react-stately/virtualizer/src/Virtualizer.ts, packages/@react-types/shared/src/dnd.d.ts
This fixes a few bugs found while writing drag and drop docs:
* When starting a drag with the keyboard, the nearest drop target (positionally) is focused by default rather than the first one on the page.
* When pressing a modifier key while dragging to change the drop operation, the cursor sometimes did not update correctly. Also, if `getDropOperation` returns an operation that isn't allowed, the drag is now canceled.
* Drop target state would sometimes get stuck because of the logic with counting the number of times onDragEnter and onDragLeave are called. Instead, we now use `relatedTarget` to determine if we're in a nested target, similar to how `useFocusWithin` is implemented.
* Moved `getDropOperationForPoint` into a `DragTargetDelegate` interface to make it reusable, and implemented …
=> Drag and drop bug fixes

packages/@react-stately/layout/src/ListLayout.ts
Closes #3400
Go to any combobox story and do the following:
1. Type in something that will open the menu
2. Attempt to move the cursor left/right via the arrow keys. You should be able to now
RSP
=> Fix ComboBox left/right arrows so they move the input cursor when the menu is open

packages/@react-types/shared/src/dom.d.ts
=> Add className to DOMAttributes interface

packages/@react-spectrum/datepicker/src/Input.tsx
Closes #3357
Test that DatePicker and other Date components that use Input still work. Original issue couldn't be reproduced on our end but issue submitter confirmed applying a similar fix resolved the issue on their end
RSP
=> Prevent resize error when DatePicker input ref is undefined

packages/@react-spectrum/datepicker/intl/en-US-.json, packages/@react-spectrum/datepicker/src/DatePicker.tsx, packages/@react-spectrum/datepicker/src/DateRangePicker.tsx
=> Localize TimeField label in DatePicker and DateRangePicker

packages/@react-spectrum/datepicker/src/DatePicker.tsx, packages/@react-spectrum/datepicker/src/DateRangePicker.tsx, packages/@react-stately/datepicker/src/useDatePickerState.ts, packages/@react-stately/datepicker/src/useDateRangePickerState.ts, packages/@react-types/datepicker/src/index.d.ts
Fixes #3117
It never worked, so this removes it from the TS definition as well.
=> Remove millisecond granularity from date/time pickers

packages/@react-aria/gridlist/docs/anatomy.svg, packages/@react-aria/gridlist/docs/useGridList.mdx, packages/@react-aria/selection/src/useSelectableItem.ts, packages/@react-aria/selection/src/useSelectableList.ts, packages/@react-spectrum/list/docs/anatomy.svg
A few small updates to the `useGridList` docs:
* Restructure the "Features" section into categories that can be more easily scanned.
* Make examples a little prettier, and move to using collapsed CSS in the example to reduce styling noise.
* Add interactive elements to most examples to highlight this as the main feature. Also move the note about using listbox to the top of the page.
* More examples.
* Fix `disabledBehavior` in `useSelectableList`.
* Fix dark mode in anatomy diagrams.
=> useGridList docs refinements

packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/interactions/test/usePress.test.js
This makes usePress work better with HTML `<input>` elements, which have default keyboard behavior. For example, checkboxes toggle when the space key is pressed. Previously this was [somewhat broken](https://codesandbox.io/s/musing-architecture-r1v5dx?file=/src/App.js), in that onPressStart would only be triggered on key up due to the browser firing a virtual onClick event.
In #3380, I changed usePress to look at the currentTarget rather than target when determining whether to handle an event. This caused TableView's select all checkbox to stop working, because the event would bubble to the cell and get handled there (with preventDefault).
Now we allow the space key for checkboxes and other input elements to trigger onPressStart on key down, but do not call `preventDefault`, allowing the …
=> Fix usePress with HTML input elements

packages/@react-types/calendar/src/index.d.ts
=> Restore aria labeling props for Spectrum Calendar/RangeCalendar props

packages/@react-spectrum/list/docs/ListView.mdx
Closes [no-issue]
Update ListView docs to reflect that accepted content includes illustrations and not icons.
Look at website artifact
=> Update ListView docs

packages/@react-spectrum/actiongroup/src/ActionGroup.tsx
Broke in https://github.com/adobe/react-spectrum/pull/3416. Should still pass `tsc-strict`.
=> Fix ActionGroup 'More' icon not rendering

packages/@react-spectrum/list/src/DragPreview.tsx, packages/@react-spectrum/list/src/ListView.tsx, packages/@react-spectrum/list/src/styles.css
Go to a ListView -> Drag and Drop story and use controls to change density.
Check that drag previews for compact and spacious are correct.
=> Fix ListView drag preview styles for density

packages/@react-spectrum/dnd/src/useDragHooks.ts, packages/@react-spectrum/list/src/ListViewItem.tsx
If a listview was only draggable, the dragged row element and drag handle was focusable via TalkBack since we only removed the tabindexes from the rows if the list was droppable. Now we do the same if the list is draggable
1. Go to the "drag out of list" story in ListView drag and drop.
2. Begin a drag via TalkBack and ensure that the row containing the dragged row can't be focused during the drag operation
RSP
=> Hide dragging ListView row from Talkback during virtual drag

packages/@react-spectrum/overlays/stories/Modal.stories.tsx
Closes
Found during testing of focus PR #3385. The "open modal" button didn't work on mobile because the button was in a button group that is replaced by the dismiss button in a popover on mobile.
Goto to the Modal -> unmountingTrigger story and confirm that the popover has the "Open modal" button on both Desktop and Mobile.
Should tests how focus is managed on mobile with Voiceover.
RSP
=> Improving Modal unmounting trigger story for mobile

packages/@adobe/spectrum-css-temp/components/badge/skin.css
Validated against the XD file and checked with storybook accessibility plugin. These should all be static colors that don't change with the theme.
=> Update badge colors to pass contrast minimums

packages/@react-stately/dnd/src/useDroppableCollectionState.ts
This fixes the flaky drop indicator behavior where sometimes it sticks around even when exiting a list. This was due to drag events firing faster than react re-renders, thereby breaking our equality check. Need to store the target in a ref in addition to state so we always have the updated one.
=> Fix sticky drop indicator when exiting list

packages/@react-aria/dnd/src/useDrag.ts
TalkBack fires pointer events on the center of the `currentTarget`, not `target`. In the case of the default dnd story, there is a nested span.
=> Fix dragging in Android Talkback

packages/@react-spectrum/autocomplete/src/MobileSearchAutocomplete.tsx, packages/@react-spectrum/autocomplete/src/searchautocomplete.css, packages/@react-spectrum/combobox/src/combobox.css
Found while testing #3383.
This adds a missing class to SearchAutocomplete so the text truncates with an ellipsis rather than wrapping on mobile.
Also noticed that the ellipsis was not quite aligned with the vertically centered text, so fixed that too (also in combobox).
=> Fix text truncation in mobile SearchAutocomplete

packages/@adobe/spectrum-css-temp/components/badge/index.css, packages/@react-spectrum/badge/chromatic/Badge.chromatic.tsx, packages/@react-spectrum/badge/stories/Badge.stories.tsx
=> Fix badge padding, order, and icon size

packages/@react-spectrum/table/src/TableView.tsx
Closes
Found during testing, but pre-existing issue. In Firefox, an element with overflow auto or scroll is a tab stop. This caused an empty table to be tabbed too twice.
In FireFox, go to any TableView story with no content (renderEmptyState, isLoading, etc.) and tab into the TableView. It should only stop once on the table body during keyboard tab navigation.
RSP
=> TableView overlay auto tab stop Firefox fix

packages/@react-aria/menu/docs/useMenu.mdx
This was originally added in #3308, but due to subsequent merge issues, it seems to have been lost.
=> Add missing styled example to useMenu docs

packages/@react-spectrum/datepicker/src/DateField.tsx, packages/@react-spectrum/datepicker/src/TimeField.tsx
Small bug found in https://github.com/adobe/react-spectrum/pull/3521: when clicking on the label for DateField and TimeField, it would focus the contextual help button rather than the first date segment. This was due to using FocusManager around the entire field, rather than only the segments.
=> Fix clicking on DateField and TimeField label with contextual help

packages/@adobe/spectrum-css-temp/components/icon/ui-icons.css
Minor style fix for alignment of icon in drag buttons on ListView items.
Old:
New:
=> Improve ListView item drag button icon alignment

packages/@react-aria/dnd/src/useDroppableCollection.ts, packages/@react-spectrum/list/test/ListViewDnd.test.js
Test DnD stories: When dropping on an item (i.e. ListView with folder), focus should then go to that item, instead of going to the list itself.
=> DnD: Focus an item after it has been dropped on

packages/@react-aria/dnd/src/useDroppableCollection.ts, packages/@react-aria/dnd/src/useDroppableItem.ts, packages/@react-aria/dnd/src/utils.ts
Closes 
Test the ListView-> Drag and Drop -> Util Handlers -> drag within list (reorder) story with a mobile screen reader. Only the insertion indicators between the rows should be focusable when performing a drag operation
RSP
=> Properly hide invalid drop targets in reorderable only ListViews

packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@adobe/spectrum-css-temp/components/table/index.css, packages/@react-spectrum/table/src/TableView.tsx
Closes 
allows resizing, header cell button has a 2px focus ring around it, except the top is only 1px it looks like (RS)
allowsResizing, column divider is offset by .5px with resizer (DG)
focus ring width is shortened by width of resizer. looks esp weird with dividers (DG)
The divider sticks out a bit above the resizer nubbin. See screenshot row 6 (DL)
Also included List/Menu Section fix
Section Titles seem a bit too close to the divider with too much trailing whitespace? Note, this spacing didn't change, but perhaps is more noticeable with descenders? (RS)
=> TableView cosmetic fixes from testing session

packages/@adobe/spectrum-css-temp/components/fieldlabel/index.css
As found in testing, this fixes wrapping of labels in mobile Safari.
Test instructions:
1. Go to DateRangePicker, defaultVaue, zoned in iOS safari
2. Open the tray
3. See that the label of the time fields no longer wraps.
I also already ran chromatic on this and saw no changes.
=> Fix wrapping of field label in Safari

packages/@react-aria/dnd/src/useDrop.ts, packages/@react-types/form/src/index.d.ts, packages/@react-types/shared/src/dnd.d.ts
=> Types audit for release

packages/@react-aria/dnd/src/DragManager.ts, packages/@react-aria/dnd/test/dnd.test.js
This reverts #3283. As discussed in testing, moving focus immediately after starting a drag only announces the "navigate to a drop target" message, not that you've already moved to a target, so you might think you need to navigate and miss the first target.
=> Revert "DnD: Focus initial drop target when using iOS VO (#3283)"

packages/@react-aria/aria-modal-polyfill/src/index.ts, packages/@react-aria/live-announcer/src/LiveAnnouncer.tsx
When clicking on the right or left chevron, there should be an aria-live announcement that announces the newly displayed month. This is what occurs when opening the picker initially and reading through; however after you close and reopen the picker, it will no longer announce when clicking the chevron. If you remount the component by refreshing the page, it will work again as described above. I'm using VoiceOver on Mac in Chrome and in Safari.
When you first open the Calendar overlay in the [DatePicker Example](https://react-spectrum.adobe.com/react-spectrum/DatePicker.html#example), the LiveAnnouncer will not have initialized, because there has never been a need to announce anything. When you then navigate between months, a LiveAnnouncer region gets added at the start of the DOM, and is …
=> fix(#3559): DatePicker: aria-live not announcing new months

packages/@react-aria/visually-hidden/src/VisuallyHidden.tsx, packages/@react-aria/visually-hidden/test/VisuallyHidden.test.tsx
Closes https://github.com/adobe/react-spectrum/issues/3571
=> Support nested focusable elements in VisuallyHidden with isFocusable option

packages/@react-spectrum/list/src/RootDropIndicator.tsx
Closes 
1. Test the root drop ListView DnD stories. You should be able to swipe onto the root drop indicator via iOS VO
RSP
=> Fix root drop interaction for iOS VO

packages/@adobe/spectrum-css-temp/components/fieldlabel/index.css, packages/@react-spectrum/labeledvalue/chromatic/LabeledValue.chromatic.tsx
Found in testing.
Go to LabeledValue -> Contextual Help story and enable side label position via controls.
Verify that label and contextual help are now aligned.
=> Fix LabeledValue contextual help alignment for side label

packages/@react-aria/dnd/stories/DroppableListBox.tsx, packages/@react-aria/dnd/stories/VirtualizedListBox.tsx
Closes 
Test the DnD stories again, with a focus on ones that have the droppable listbox. They should accept drops again
RSP
=> Fix DnD stories so the droppable listbox actually works

packages/@react-spectrum/dnd/docs/dnd.mdx
=> Fixing directory drop for docs low level DnD api example

packages/@adobe/spectrum-css-temp/components/underlay/index.css, packages/@react-spectrum/dialog/src/DialogTrigger.tsx, packages/@react-spectrum/menu/src/MenuTrigger.tsx, packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx, packages/@react-spectrum/overlays/src/Popover.tsx, packages/@react-spectrum/overlays/src/Underlay.tsx, packages/@react-spectrum/picker/src/Picker.tsx, packages/@react-types/overlays/src/index.d.ts
Reverts adobe/react-spectrum#3475
We decided to revert this temporarily due to the issue with added padding when scrollbars are enabled. Will return later after some refactoring to use new overlay hooks in RSP.
=> Revert "Prevent scrolling while popovers are open"

packages/@react-spectrum/form/test/Form.test.js, packages/@react-spectrum/overlays/src/Overlay.tsx
Closes 
Found in testing session
=> Provider shouldn't disable buttons inside dialogs

packages/@react-aria/selection/src/useTypeSelect.ts
The previous value (500ms) is a bit too tight, and makes keyboard navigation through long lists of items with similar prefixes difficult.
Increasing the buffer to 1 second.
Closes #3500
* Implement a component that leverages useTypeSelect()
* For this example we can use the [document example for useSelect()](https://react-spectrum.adobe.com/react-aria/useSelect.html#example)
* See example below
* Click/Keyboard focus on the select
* Type at different rates to observe behavior
* For example "M", "I", "S", "S" (should result in Mississippi)
* Observe that after 1 second, the typeahead buffer is clear and you can start again
Example for testing purposes:
```tsx
<Select label="US States/Territories">
<Item>Alaska</Item>
<Item>Alabama</Item>
<Item>Arkansas</Item>
<Item>Arizona</Item> …
```
=> increase useTypeSelect() debounce buffer rate to 1000ms

packages/@react-aria/dnd/docs/useDraggableCollection.mdx, packages/@react-aria/dnd/docs/useDroppableCollection.mdx, packages/@react-aria/dnd/src/DragManager.ts
Fixes the keyboard order of drop targets. Previously, when tabbing through drop targets, you'd get to the end of the page and go back to the initial dragged element, and then go back to the drop targets before that which was weird. Also, in NVDA, when using virtual cursor mode, starting a drag wouldn't move you to the nearest drop target (fine), but tabbing would take you to the start of the page. Now, we shuffle the order of the drop targets so the first one is the nearest to the initial drag target.
Also fixed the root drop indicator not being accessible with iOS VO in examples.
=> Fix dnd issues in docs examples

packages/@react-aria/dnd/src/DragManager.ts
found in API audit, this isn't a public function
Closes
=> Mark isVirtualDragging private

packages/@react-aria/breadcrumbs/src/useBreadcrumbs.ts
Just a small and baby correction on a word in `useBreadCrumbs.ts` :eyes:
Closes
=> Correction of a mistake in useBreadCrumbs.ts

packages/@react-types/shared/src/dom.d.ts
=> Avoid widening "type" prop of TextInputDOMProps

packages/@adobe/spectrum-css-temp/components/table/index.css
Closes 
Appears to be a parcel bug, reverting so people's builds can work again. Once this is merged, I'll create a PR to add them back and we can fix whatever is going on there.
=> Fix build revert custom resize icons

packages/@react-stately/table/src/index.ts, packages/@react-stately/tree/src/index.ts
=> Export TableCollection and TreeCollection

packages/@adobe/spectrum-css-temp/components/actiongroup/index.css, packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@adobe/spectrum-css-temp/components/button/skin.css, packages/@react-spectrum/button/chromatic/Button.chromatic.tsx, packages/@react-spectrum/button/src/Button.tsx, packages/@react-spectrum/button/stories/Button.stories.tsx, packages/@react-spectrum/button/stories/ToggleButton.stories.tsx, packages/@react-spectrum/provider/test/Provider.test.js, packages/@react-spectrum/story-utils/src/GeneratePowerset.tsx, packages/@react-types/button/src/index.d.ts
Depends on #3604.
This updates Button to support the new `accent` variant, `fill` and `outline` styles, and `staticColor` options. `isQuiet` is also deprecated. The CSS has been rewritten to simplify it using variables.
ActionButton now has a more contrasting selected state. It also now always has a halo focus ring.
=> Button and ActionButton design updates

packages/@react-aria/overlays/src/usePopover.ts
This fixes an issue found in tested where extra padding was added to the page to account for scrollbars when unnecessary. This was due to measuring before the max-height was added to the popover, thus overflowing the page. Now we wait for a layout effect after positioning to enable preventing scroll.
=> Wait until after a layout effect to prevent scroll in popovers

packages/@adobe/spectrum-css-temp/components/colorwheel/index.css
Closes https://github.com/adobe/react-spectrum/issues/1605
Check if ColorWheel still gets stretched out inside a Form
```
<Form>
<ColorWheel/>
</Form>
```
The example below demonstrates that the issue is gone regardless of whether it's wrapped in a Flex (or div)
=> issue-1605: use two selectors to avoid css overwrite

packages/@react-spectrum/numberfield/stories/NumberField.stories.tsx, packages/@react-spectrum/numberfield/test/NumberField.test.js, packages/@react-stately/numberfield/src/useNumberFieldState.ts
Closes https://github.com/adobe/react-spectrum/issues/2216
Check if setting `null` to value resets `NumberField` to blank, I've added a storybook example & a test for this in the PR.
Before - 
After clicking the Reset button -
=> issue-2216: setting null to value should reset NumberField to blank

packages/@react-spectrum/list/test/ListViewDnd.test.js, packages/@react-stately/data/src/useListData.ts, packages/@react-stately/data/test/useListData.test.js
Specifically fix it for cases where the user is reordering a set of sequential items (3 items or more) and is moving it to a drop position one below the last item being moved. Addresses the comment  made here https://github.com/adobe/react-spectrum/pull/3423#discussion_r982907881
Go to the ListView DnD reorder stories and select the top three items. Drag them after the fourth item and verify that the items are reordered correctly. 
To contrast, here is a broken example: https://reactspectrum.blob.core.windows.net/reactspectrum/842a0ed0ace6e17adee425286056456d0061d9a1/storybook/index.html?path=/story/listview-drag-and-drop-util-handlers--drag-within-list-reorder&providerSwitcher-toastPosition=bottom
Selecting and moving the top three items down one item actually moves them down two items …
=> Fix useListData so that reorder operations are correctly inserted at the correct index

packages/@react-aria/dnd/src/useDrop.ts
Previously, I noticed that sometimes dropping items on iPad would cause Safari to do a google search for the dropped data. I have not been able to reproduce this after adding `preventDefault` in the onDragEnter and onDragLeave events.
=> Add preventDefault to onDragEnter and onDragLeave for iPad

packages/@react-spectrum/table/src/TableView.tsx
Closes 
This fixes the case where the Tray must animate out before focus can be sent to the Resizer. Animating out is 350ms, so we wait 400ms to be safe.
Other changes were deemed too sweeping before release. We explored adding onExited (and other transition props) to all our triggers so we could know when to move focus after the FocusScope was unmounted. We also explored adding isExiting to Overlays so that we can end focus containment as a component is animating out.
Both of these added API's and changed core functionality that we didn't feel comfortable putting in the release with so little testing.
Using a mobile device, go to a Table story with resizing columns. Try to enter resizing mode via touch interactions.
=> Fix mobile column resizing

packages/@adobe/spectrum-css-temp/components/fieldlabel/index.css, packages/@adobe/spectrum-css-temp/components/textfield/index.css, packages/@react-spectrum/textfield/chromatic/TextArea.chromatic.js, packages/@react-spectrum/textfield/src/TextFieldBase.tsx
Seems to have broken in https://github.com/adobe/react-spectrum/pull/3521
For labelPosition: top, when a fixed height is provided, the textarea doesn't fill the height of its container.
In Storybook, go to TextArea -> Custom height with label
Verify that textarea now fills its container.
Double check other TextArea stories and height behavior when typing.
Ensure that quiet TextArea grows to a max of the specified height when typing, and the help text is just below the line.
=> Fix TextArea not using full height when custom height provided

packages/@react-spectrum/tabs/stories/Tabs.stories.tsx
found during testing
Goto the Tabs -> Collapse behavior story and try to remove all the tabs. You can no longer so that. There must always be one tab.
RSP
=> Preventing tabs storybook collapse behavior from having no items

packages/@react-aria/overlays/src/useCloseOnScroll.ts, packages/@react-aria/overlays/src/useOverlayPosition.ts, packages/@react-aria/overlays/src/usePopover.ts, packages/@react-spectrum/menu/test/MenuTrigger.test.js, packages/@react-spectrum/picker/test/Picker.test.js
On iPad, tapping on a button to open a popover did not work. It immediately closed due to page scrolling caused by usePreventScroll. We don't need this anymore, so disable it by setting `onClose` to `null`.
=> Do not close overlays on scroll

packages/@react-aria/selection/src/useSelectableItem.ts, packages/@react-spectrum/picker/stories/Picker.stories.tsx, packages/@react-stately/table/src/useTableState.ts
Closes 
Fix issues where useSelect aria docs pickers would focus a disabled item if you clicked on it. It also fixes an issue where Combobox would close if you clicked on a disabled item.
=> Fix disabled item behavior in collections

packages/@react-aria/overlays/src/usePreventScroll.ts, packages/@react-aria/overlays/test/usePreventScroll.test.js
Closes https://github.com/adobe/react-spectrum/issues/3782
Some additional regression history for the prevent scroll issue: this issue was present with in the [original PR](https://github.com/adobe/react-spectrum/pull/3475) that introduced preventing scroll when popovers were open (note that said behavior was also [reverted](https://github.com/adobe/react-spectrum/pull/3583) until the new overlay hooks update happened). Prior to this open popovers didn’t prevent page scroll which is why this DialogContainer issue wasn’t a thing previously
Test the "Dialog triggered by a menu item" example in the DialogContainer docs on all browsers and platforms. You should be able to scroll after closing the final dialog
RSP
=> Properly restore original page scrollability for DialogContainer case

.storybook/preview.js
Fixes the error often seen in storybook when saving a file: "rendered more hooks than during the previous render".
=> Fix error during React Fast Refresh in storybook

.chromatic/main.js, .storybook/main.js, .storybook/preview.js, package.json, yarn.lock
I think this was causing an infinite loop sometimes when saving a file in CSF-based stories. I think it was trying to serialize some circular object. I don't see anywhere we are using this plugin anyway, so removing...
=> Remove storybook addon links

packages/@adobe/spectrum-css-temp/components/table/skin.css
Spectrum hasn't updated the xd file for column resizing yet, so just matching the old colors as closely as possible for now.
=> Improve contrast of resizer in dark mode

packages/@react-spectrum/combobox/docs/ComboBox.mdx, packages/@react-spectrum/picker/docs/Picker.mdx
There is not an associated Git Issue.
This is merely updating documentation to remove a phrase that may be offensive to some.  By changing the documentation example very slightly, this is more inclusive.
There are no test instructions, this is merely updating documentation
=> combobox: changing example to be more inclusive

.eslintignore, yarn.lock
At some point our yarn lock has gotten out of date. This is what running yarn install on a clean repo gives. I'm also updating an eslint ignore entry so we stop getting errors about this generated file
=> Fix out of date yarn lock and lint ignore

packages/@react-aria/focus/src/FocusScope.tsx
Simplification of #3878.
It works by creating the tree nodes during render (top down), and passing them down via context. In a layout effect (bottom up), it adds itself to its parent and to the tree. If the parent is already in the tree, then we consider `activeScope` as the parent.
=> Create FocusScope nodes top down and add them bottom up

packages/@react-aria/aria-modal-polyfill/test/index.test.js, packages/@react-aria/selection/test/useSelectableCollection.test.js, packages/@react-spectrum/autocomplete/test/SearchAutocomplete.test.js, packages/@react-spectrum/combobox/test/ComboBox.test.js, packages/@react-spectrum/contextualhelp/test/ContextualHelp.test.js, packages/@react-spectrum/datepicker/test/DatePickerBase.test.js, packages/@react-spectrum/dialog/src/DialogTrigger.tsx, packages/@react-spectrum/dialog/test/DialogTrigger.test.js, packages/@react-spectrum/form/test/Form.test.js
Closes #3905
Test the DialogTrigger and DatePicker/RangePicker stories. They should now render their defined mobileType/trays only when the screen width of your device is less than 700px rather than if the window width is less than 700px 
RSP
=> Make DialogTrigger use screen width to determine if mobile or not

package.json
The new token is an npm automation token which isn't supported by our version of lerna: https://github.com/lerna/lerna/issues/2788. This just ignores the auth check for now.
=> Fix publishing nightly

packages/@react-aria/interactions/src/useInteractOutside.ts
Closes https://github.com/adobe/react-spectrum/issues/3933
Go to the docs useModalOveraly page, follow steps outlined in Issue that this PR closes
=> Fix interact outside false positive

packages/@react-aria/landmark/src/index.ts, packages/@react-aria/landmark/src/useLandmark.ts, packages/@react-aria/landmark/stories/Landmark.stories.tsx, packages/@react-aria/landmark/test/useLandmark.test.tsx, packages/@react-spectrum/toast/stories/Toast.stories.tsx
This adds a new `LandmarkController` API, which enables programmatically navigating the landmark sequence. It can be used to ensure landmark keyboard listeners are registered even if nothing has called `useLandmark` (eg in the case of an iframe where an outer app has landmarks). You can also call methods similar to the ones in the `FocusManager` API to navigate through the landmarks programatically. This is a nicer way to trigger navigations rather than manually dispatching the F6 key, which should continue to work even if we ever change the exact keyboard interface. Once a `LandmarkController` is disposed, and no other controllers or landmarks are registered, the keyboard listeners are removed.
=> Add LandmarkController API

.eslintrc.js, packages/@react-aria/landmark/package.json, packages/@react-aria/landmark/src/useLandmark.ts, packages/@react-aria/landmark/test/useLandmark.test.tsx
This ensures that there is only ever a single `LandmarkManager` instance on the page, even if there are multiple copies or different versions loaded. This is necessary so their global keyboard listeners do not conflict.
It is implemented by attaching the current instance to the `document` under a hidden symbol. If multiple different versions are loaded, the newest one replaces the older ones. We must ensure that the minimal API in the `LandmarkManagerApi` and `Landmark` interfaces never contain breaking changes so that registering landmarks from an older version of `useLandmark` against a newer version of `LandmarkManager` continues to work.
=> Make LandmarkManager a global singleton

packages/@react-aria/table/src/useTableColumnResize.ts, packages/@react-stately/table/src/useTableColumnResizeState.ts
=> Remove unnecessary `onColumnResize/Start/End` from useTableColumnResizeState

package.json, yarn.lock
Closes #4010
1. Open https://reactspectrum.blob.core.windows.net/reactspectrum/96cd5e6bb2ce928ebc8f1cec0b612e6e336ad9a2/storybook/index.html?path=/story/switch--default&providerSwitcher-express=false
2. Switch to Accessibility Tab in the Storybook Add-Ons panel
3. Verify that there are 0 Violations. (There will be 1 Incomplete warning to manually verify color contrast compliance.)
=> fix(#4010): Update axe-core version for Storybook Accessibility panel to ^4.6.3

packages/@react-spectrum/tag/src/TagGroup.tsx, packages/@react-spectrum/tag/stories/TagGroup.stories.tsx
For improving accessibility, so there is a better indicator of an error than just the text's red color.
=> TagGroup: always show error icon when displaying error message

packages/@react-spectrum/table/src/TableView.tsx
Closes 
Use any of the table resize stories. Test that the table is only centered in the viewport if the resizer is still out of view after moving it with Left/Right arrows
RSP
=> Center the table in the viewport if resizer is still out of view

packages/@react-spectrum/menu/stories/ActionMenu.stories.tsx
Closes #4023 
1. Open https://reactspectrum.blob.core.windows.net/reactspectrum/9e92106b3067ba326d34bf35274d3fcc2c5dc1b7/storybook/index.html?path=/story/actionmenu--dynamic&providerSwitcher-express=false&providerSwitcher-toastPosition=bottom
2. Focus ActionMenu button.
3. Press Space, Enter or ArrowDown to expand Menu
4. Last item in Menu, "Paste", will have focus.
5. Press ArrowUp to move focus to previous menu item, "Copy."
6. Focus does not move, because the items have the same key, so only the last item receives focus.
1. Open https://reactspectrum.blob.core.windows.net/reactspectrum/96175f786204872d5cbf648940e6d6760482edc3/storybook/index.html?path=/story/actionmenu--dynamic&providerSwitcher-express=false&providerSwitcher-toastPosition=bottom
2. Focus ActionMenu button.
3. Press …
=> fix(#4023): ActionMenu: Items in Dynamic storybook story all have the same key which breaks interaction

packages/@react-aria/table/src/useTableColumnResize.ts
Found when writing aria sandbox example. Div element is too restrictive since a button could be used instead
RSP
=> Broaden allowed triggerRef elements for table column resizer

packages/@react-stately/combobox/src/useComboBoxState.ts, packages/@react-stately/combobox/test/useComboBoxState.test.js
Closes https://github.com/adobe/react-spectrum/issues/2181
1. Go to a combobox story and type in the field in such a way that you have a list that is much shorter than the original list
2. Click right below the menu so that it closes it
3. No option should be selected
RSP
=> Prevent ComboBox item selection if menu is closing 

packages/@react-aria/tag/src/useTag.ts, packages/@react-spectrum/tag/src/TagGroup.tsx, packages/@react-types/tag/src/index.d.ts
=> Adding descriptions to Tag related interfaces

.storybook/custom-addons/provider/register.js
https://github.com/adobe/react-spectrum/blob/e9f08177302590b4bf8c650dda579a15f0c5ffcb/.storybook/custom-addons/provider/register.js#L113-L114
should be
```tsx
<label htmlFor="express">Express: </label>
<input type="checkbox" id="express" name="express" onChange={onExpressChange} checked={values.express} />
```
Closes #4067 
1. Open [Storybook](https://reactspectrum.blob.core.windows.net/reactspectrum/1676f4a74d0a3d86de7fdb1a6e74f17ecb23d559/storybook/index.html?path=/story/accordion--default)
2. Mouse click on the "Express:" `label` or the "express" checkbox input in the Provider settings toolbar above the story.
3. Mouse clicking the `label` should toggle the checkbox when the label is properly associated with the input using `htmlFor` and a proper IDREF.
=> fix(#4067): Storybook Provider addon: Express input:checkbox requires id to be labelled by htmlFor prop

packages/@react-aria/table/stories/example-resizing.tsx, packages/@react-spectrum/table/src/TableView.tsx, packages/@react-stately/layout/src/TableLayout.ts
Closes 
Change request from code audit for release
=> Explain Proxy in TableView

packages/@react-spectrum/combobox/src/MobileComboBox.tsx, packages/@react-spectrum/combobox/test/ComboBox.test.js
=> fix(#4078): MobileComboBox: searchbox should not have aria-expanded property

packages/@react-aria/datepicker/src/useDatePicker.ts
Closes https://github.com/adobe/react-spectrum/issues/3969
Go to the DatePicker stories and make sure the accessiblity tab doesn't warn about duplicate ids. Also check the useDatePicker docs and make sure the presentational field div doesn't have the same id as the group
RSP
=> Get rid of dupe id in DatePicker/useDatePicker

packages/@adobe/react-spectrum/package.json, packages/@adobe/react-spectrum/src/index.ts, packages/@internationalized/date/src/CalendarDate.ts, packages/@react-aria/button/src/useToggleButton.ts, packages/@react-aria/listbox/src/index.ts, packages/@react-aria/listbox/src/useListBox.ts, packages/@react-aria/menu/src/index.ts, packages/@react-aria/overlays/src/useOverlayTrigger.ts, packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx, packages/@react-types/color/src/index.d.ts, packages/@react-types/listbox/src/index.d.ts, packages/@react-types/tabs/src/index.d.ts, packages/react-aria/src/index.ts, packages/react-stately/src/index.ts
=> Code changes from docs-ts branch

packages/@adobe/spectrum-css-temp/components/tags/index.css, packages/@react-spectrum/tag/src/TagGroup.tsx
- Uses span instead of label since we aren't labelling a form element
- Uses `gap` so that the tags line up with the label
Test TagGroup label is span, and left-most tags align vertically with the label above.
=> Fix TagGroup label alignment

packages/@react-stately/tag/src/index.ts
=> Explicitly define the exports from react-stately/tag

examples/rsp-next-ts/package.json, examples/rsp-next-ts/pages/_app.tsx, examples/rsp-next-ts/pages/index.tsx, packages/@react-aria/landmark/src/useLandmark.ts, packages/@react-aria/landmark/test/useLandmark.ssr.test.js, packages/@react-spectrum/toast/src/ToastContainer.tsx, packages/@react-spectrum/toast/test/ToastContainer.ssr.test.js, packages/@react-stately/toast/src/useToastState.ts
This fixes two issues using Toast in Next.js
1. `use-sync-external-store` doesn't have package.json exports, so it doesn't work in ESM. I filed a PR here to fix it https://github.com/facebook/react/pull/26230 but for now we can import explicitly from `use-sync-external-store/shim/index.js`.
2. `useSyncExternalStore` has an "optional" third argument called `getServerSnapshot` which isn't really optional because it errors if it isn't provided on the server. So now I have implemented it. Also added SSR tests to catch this.
=> Fix toast ESM build and SSR support

packages/@react-aria/tag/src/useTag.ts, packages/@react-aria/tag/src/useTagGroup.ts, packages/@react-spectrum/tag/src/Tag.tsx, packages/@react-spectrum/tag/src/TagGroup.tsx
Updating the returned props from `useTagGroup` and `useTag` to better reflect the roles of the elements they are used for. This better matches out existing APIs (i.e. `useGridList`) and makes it more clear to the user what roles are being used.
=> Update useTagGroup and useTag returned prop names

packages/@react-spectrum/slider/stories/RangeSlider.stories.tsx
Closes #4188 
1. Open https://reactspectrum.blob.core.windows.net/reactspectrum/c16b909d9ea6b53bdfec53d08aa16f663bdbbeea/storybook/index.html?path=/story/slider-rangeslider--default
2. Inspect the div with role="group" that wraps the RangeSlider control
3. I should be labeled using `aria-label` and not have `aria-labelledby`.
=> fix(#4188): RangeSlider Default storybook example is labeled twice

packages/@react-types/form/src/index.d.ts
Closes #4208 
Verify that `label` is not listed as a prop in Form documentation: https://reactspectrum.blob.core.windows.net/reactspectrum/ac82aa5dfd1e59654194ae56d00260b08e78d84f/docs/react-spectrum/Form.html#props
=> fix(#4208): Form includes label prop inherited from SpectrumLabelableProps that goes unused

packages/react-aria-components/docs/ProgressBar.mdx
Closes 
Especially try in dark mode
=> Aria component Progressbar contrast

packages/@react-aria/listbox/docs/useListBox.mdx, packages/@react-aria/listbox/src/useOption.ts, packages/@react-aria/menu/docs/useMenu.mdx, packages/@react-spectrum/menu/docs/Menu.mdx, packages/react-aria-components/docs/ComboBox.mdx, packages/react-aria-components/docs/Dialog.mdx, packages/react-aria-components/docs/ListBox.mdx, packages/react-aria-components/docs/Menu.mdx, packages/react-aria-components/docs/Popover.mdx, packages/react-aria-components/docs/Select.mdx, packages/react-aria-components/package.json, packages/react-aria-components/src/ComboBox.tsx, packages/react-aria-components/src/ListBox.tsx, packages/react-aria-components/src/Menu.tsx, packages/react-aria-components/src/Popover.tsx, packages/react-aria-components/src/Select.tsx, packages/react-aria-components/src/utils.tsx, packages/react-aria-components/test/ListBox.test.js, packages/react-aria-components/test/Menu.test.js
Depends on #4212.
* Fixes animation issue with Select popover
* Switches to using `--trigger-width` as a CSS custom property for both ComboBox and Select popovers for consistency
* Fixes animation of side modal example in Chrome, which previously got stuck open. This was due to an ordering issue where child animations completed before parents.
* Fix all docs examples with select all from displaying `a,l,l`
* Fix question mark in circle character on Windows - switched to i in circle. No font seems to support the question mark.
* Fixed some high contrast styling
* Fixes isFocused in useOption to only be true when the collection is actually focused.
* Added an isFocusVisible return value to useOption which works with virtual focus, and allows us to get rid of another dependency in aria …
=> Fixes for Aria Components

Makefile, packages/react-aria-components/package.json
Adds it as a parcel target in the build command, and adds missing dependency.
=> Fix nightly build of React Aria Components

packages/@internationalized/date/src/CalendarDate.ts
ZonedDateTime.offset takes milliseconds not seconds (as was in comments).
Closes
=> Update comment to properly reflect the units

packages/@react-aria/tag/src/useTag.ts, packages/@react-spectrum/tag/src/Tag.tsx
Previously, preventing focus of the remove button was handled in React Spectrum. This handles that in `useTag` instead so the same behavior applies to components created with the hooks.
=> TagGroup: Prevent focus of remove button via hook

packages/@react-aria/table/src/useTableColumnResize.ts
Closes 
Test the "Doc Example" story in the useTable stories. Make sure the "Press Enter to start resizing" only announces for keyboard screen readers
RSP
=> Prevent keyboard specific Table column resizing announcement on iOS Voiceover

packages/@react-aria/tag/src/useTag.ts, packages/@react-spectrum/tag/test/TagGroup.test.js
Removal of tags via keyboard should only happen via `Backspace` or `Delete`. `Space` should be reserved for potential future support for selection.
=> TagGroup: don't remove tags on Space press

packages/@react-aria/table/docs/useTable.mdx
Based on #3982.
This is a slightly simpler implementation of the column resizing example that doesn't require overriding the CSS table layout to use flex. This way we can simply reuse the TableRowGroup, TableHeaderRow, TableRow, and TableCell components from before instead of reimplementing them with minor styling changes.
It works by adding an additional div wrapper around the table element that scrolls. The table itself is set to `width: fit-content` and `table-layout: fixed` to ensure it always takes the widths defined on the column headers. Then the browser automatically handles setting the widths of the cells in the body based on the header widths, and the entire table grows when the widths get bigger (overflowing in the parent wrapper).
You do lose the sticky headers, but in this …
=> Simplify aria table resizing docs example
