packages/@react-spectrum/link/stories/Link.stories.tsx
Closes https://jira.corp.adobe.com/browse/RSP-1524
=> (RSP-1524) Removing primary story from Link

packages/@react-spectrum/icon/README.md, packages/@react-spectrum/textfield/stories/TextArea.stories.js, packages/@react-spectrum/textfield/stories/Textfield.stories.js, packages/@spectrum-icons/color/stories/IconsColor.stories.tsx, packages/@spectrum-icons/workflow/stories/IconsWorkflow.stories.tsx
=> Fix some stories using unsafe_style

.circleci/config.yml, .storybook-v3/config.js, package.json, yarn.lock
Was using 150% CPU just idling. Also adds story sorting from #152 as requested by @snowystinger.
=> Upgrade storybook to stop it from going crazy

packages/@react-spectrum/dialog/stories/Dialog.stories.tsx, packages/@react-spectrum/dialog/stories/DialogTrigger.stories.tsx
Closes https://jira.corp.adobe.com/browse/RSP-1591
Go to the isDismissable Dialog/DialogTrigger stories and test that you can tab to the 'X' button
=> (RSP-1591) Fixing isDismissable dialog stories so you can tab to 'X' button

packages/@react-spectrum/dialog/src/Dialog.tsx
Closes https://jira.corp.adobe.com/browse/RSP-1590
=> (RSP-1590) Replacing top dialog div with section

packages/@react-spectrum/listbox/src/ListBoxOption.tsx, packages/@react-spectrum/menu/src/MenuItem.tsx
Looks like they were broken by #263
=> Fix slots for MenuItem and ListBoxItem

packages/@react-aria/collections/src/CollectionItem.tsx, packages/@react-aria/selection/src/useTypeSelect.ts, packages/@react-spectrum/progress/docs/ProgressBar.mdx, packages/@react-spectrum/progress/docs/ProgressCircle.mdx, packages/@react-spectrum/sidenav/src/SideNavSection.tsx, packages/@react-spectrum/test-utils/src/slots.js, packages/@react-stately/collections/src/Item.ts, packages/@react-stately/collections/src/Section.ts, packages/@react-stately/toast/src/timer.ts
=> Add copyrights

packages/@react-aria/menu/README.md, packages/@react-spectrum/actiongroup/README.md, packages/@react-spectrum/menu/README.md, packages/@react-stately/actiongroup/README.md
A few files were in the wrong places and caused the build to fail
Added some new README's
As for why the diff looks weird
there were readme's leftover from some component renames
so the folder were left behind as well
and the parcel build was picking them up, but blowing up
because there was no code there
so i moved them to their renamed homes
i don't know how it decided which files mapped to which new ones given that i just created new ones and deleted the old ones, but looks like git tried to be smart about it and call them renames
the end result looks right to me, the right files/directories are gone, and the right new ones exist
it just made really weird diffs
Closes
=> Cleanup so build works

packages/@react-spectrum/searchfield/src/SearchField.tsx, packages/@react-spectrum/searchfield/test/SearchField.test.js
Closes https://jira.corp.adobe.com/browse/RSP-1599
=> Remove clear button in Search if readOnly

packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx, packages/@react-spectrum/picker/stories/Picker.stories.tsx
Fill in some missing actions
I'm not sure what the third line is asking for. When I go to breadcrumbs max items 4 and open the menu and select something, I see the correct onAction
Closes https://jira.corp.adobe.com/browse/RSP-1632
=> Storybook cleanup

packages/@react-aria/menu/src/useMenuTrigger.ts, packages/@react-aria/menu/test/useMenuTrigger.test.js
=> MenuTrigger fixes

packages/@adobe/spectrum-css-temp/components/dropdown/index.css
Ported from https://github.com/adobe/spectrum-css/commit/b58006883978837ff32e9bb49ff14d5ff233edd8
=> Fix RTL in Picker

packages/@adobe/spectrum-css-temp/components/actiongroup/index.css, packages/@adobe/spectrum-css-temp/components/actiongroup/vars.css, packages/@react-spectrum/actiongroup/src/ActionGroup.tsx
=> Making actiongroup css package

packages/@react-aria/overlays/src/calculatePosition.ts, packages/@react-aria/overlays/test/calculatePosition.test.js, packages/@react-aria/overlays/test/useOverlayPosition.test.js
It was already accounted for in the position
=> Fix max-height of popovers when there is an offset

.circleci/config.yml
Same thing as previously done, throw hardware at it.
Closes
=> Maybe speed up initial build step

packages/@adobe/spectrum-css-temp/components/dialog/index.css
Keep changing grid until it works
Closes
=> Fix dialog dismiss button some more

scripts/bumpVersions.js
Lerna always tries to bump every package, even private ones and ones that have never been published. This implements a script to bump versions in a more controlled manner. It fetches from the npm registry whether each package is already published, and only bumps the version for the ones that are. Then, it promps the user to confirm the version bumps, writes the package.jsons, commits, and tags each package.
=> Add script to bump package versions

packages/dev/docs/src/Layout.js, packages/dev/docs/src/docs.css, packages/dev/docs/src/resourceCard.css
Closes https://jira.corp.adobe.com/browse/RSP-1685
Make sure the docs resource card svgs look okay.
Make sure the docs h1 and h2 tags look okay.
Also, IllustratedMessage docs should look okay. (a different pr)
RSP
=> cleaning up docs css to not impact react-spectrum components

packages/@react-aria/breadcrumbs/docs/useBreadcrumbs.mdx, packages/@react-aria/breadcrumbs/src/useBreadcrumbItem.ts, packages/@react-aria/breadcrumbs/src/useBreadcrumbs.ts, packages/@react-aria/breadcrumbs/test/useBreadcrumbItem.test.js, packages/@react-aria/focus/docs/FocusRing.mdx, packages/@react-aria/focus/docs/FocusScope.mdx, packages/@react-aria/focus/docs/useFocusRing.mdx, packages/@react-aria/focus/src/FocusRing.tsx, packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-aria/interactions/docs/useFocusVisible.mdx, packages/@react-aria/interactions/docs/useHover.mdx, packages/@react-aria/interactions/src/DOMPropsContext.ts, packages/@react-aria/interactions/src/useFocusVisible.ts, packages/@react-aria/interactions/src/useHover.ts, packages/@react-aria/link/docs/useLink.mdx, packages/@react-aria/link/src/useLink.ts, packages/@react-aria/link/test/useLink.test.js, packages/@react-aria/separator/docs/useSeparator.mdx, packages/@react-aria/separator/src/useSeparator.ts, packages/@react-aria/tooltip/src/useTooltipTrigger.ts, packages/@react-aria/utils/docs/mergeProps.mdx, packages/@react-aria/utils/src/mergeProps.ts, packages/@react-aria/visually-hidden/docs/VisuallyHidden.mdx, packages/@react-spectrum/breadcrumbs/src/BreadcrumbItem.tsx, packages/@react-spectrum/link/src/Link.tsx, packages/@react-types/breadcrumbs/src/index.d.ts, packages/@react-types/shared/src/events.d.ts, packages/dev/docs/src/docs.css, packages/dev/parcel-transformer-docs/DocsTransformer.js
* useBreadcrumbs
* useLink
* useSeparator
* FocusRing
* FocusScope
* useFocusRing
* useFocusVisible
* useHover
* VisuallyHidden
* mergeProps
=> More react-aria docs

packages/@react-aria/combobox/src/useComboBox.ts, packages/@react-stately/combobox/src/useComboBoxState.ts, packages/@react-stately/menu/src/useMenuTriggerState.ts
Just wanted an isolated review of this fix
Closes
=> Fix controlled combobox open

packages/@react-spectrum/table/src/Table.tsx, packages/@react-spectrum/table/src/TableLayout.ts, packages/@react-spectrum/table/stories/HidingColumns.tsx, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-spectrum/table/test/Table.test.js, packages/@react-stately/collections/src/CollectionBuilder.ts, packages/@react-stately/collections/src/ListLayout.ts, packages/@react-stately/collections/src/types.ts, packages/@react-stately/grid/src/Column.ts, packages/@react-stately/grid/src/GridCollection.ts, packages/@react-stately/grid/src/Row.ts
Recreating #453 since it was a bit too hastily merged.
=> Support adding and removing columns in Table

packages/@react-aria/collections/src/CollectionView.tsx, packages/@react-spectrum/combobox/src/ComboBox.tsx, packages/@react-spectrum/listbox/src/ListBoxBase.tsx, packages/@react-stately/collections/src/CollectionManager.ts, packages/@react-stately/collections/src/useCollectionState.ts
Closes https://jira.corp.adobe.com/browse/RSP-1729
=> Disable animations in combobox

package.json, packages/@react-aria/actiongroup/src/useActionGroup.ts, packages/@react-spectrum/actiongroup/src/ActionGroup.tsx, packages/@react-spectrum/actiongroup/test/ActionGroup.test.js, yarn.lock
Closes https://jira.corp.adobe.com/browse/RSP-1770
=> Fix tab index so we can tab into actiongroups

packages/@react-spectrum/utils/src/styleProps.ts
These are all the units supported for length
I'll add some unit tests later today hopefully
Closes https://jira.corp.adobe.com/browse/RSP-1785
=> giving provider height 100vh translates to a spectrum variable

Makefile, packages/@react-spectrum/table/src/Table.tsx
Build storybook with production env for faster react, and fix a useCallback dependency so we aren't measuring things on scroll.
=> Make table fast again

packages/@react-spectrum/actiongroup/stories/ActionGroup.stories.tsx
=> Fix actiongroup stories so their actions make more sense in storybook

packages/@adobe/spectrum-css-temp/components/radio/skin.css
Closes https://jira.corp.adobe.com/browse/RSP-1796
=> (RSP-1796) Fixing invalid radio halo ring and updating focus ring when radio is checked

packages/@react-aria/focus/src/FocusScope.tsx
Add option to call focus with scroll
First stab at this bug, I've no idea what I'm doing. It does fix it, but i'm unsure the implications
Closes https://jira.corp.adobe.com/browse/RSP-1797
=> Allow scrolling in a dialog

packages/@react-spectrum/switch/docs/Switch.mdx
=> fixing switch examples in docs

packages/@react-spectrum/progress/docs/ProgressBar.mdx, packages/@react-spectrum/progress/docs/ProgressCircle.mdx
Closes (no jira/issues)
Check that the progress bar and progress circle links to spectrum goto the new pages not the deprecated ones.
RSP
=> updating links to spectrum progress bar/circle pages

packages/dev/docs/src/Layout.js
=> Launch integration for adobe analytics

.circleci/config.yml
=> Make docs build by giving them more hardware

packages/@react-spectrum/form/stories/Form.stories.tsx
=> Add textarea to form story

packages/@react-aria/radio/src/useRadioGroup.ts
=> Call focus on radio on keypress so it scrolls when out of view

packages/@react-spectrum/listbox/stories/ListBox.stories.tsx
no jira
semantic generative story has selection in name
rsp
=> Listbox adding selection mode to story name

packages/@react-spectrum/dialog/stories/Dialog.stories.tsx
=> remove autoFocus from Dialog renderHero Story

packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@adobe/spectrum-css-temp/components/checkbox/index.css, packages/@adobe/spectrum-css-temp/components/radio/index.css, packages/@adobe/spectrum-css-temp/components/toggle/index.css
=> add comments to CSS for bug fix

packages/@react-spectrum/actiongroup/stories/ActionGroup.stories.tsx
no jira
confirm story is renamed
RSP
=> Renaming a story to the propname

packages/@react-spectrum/actiongroup/stories/ActionGroup.stories.tsx, packages/@react-spectrum/actiongroup/stories/styles.css
Add a breakpoint and some styles so that we don't have to scroll to see everything
Closes
=> Actionbutton mobile friendly storybook

packages/@react-spectrum/button/docs/Button.mdx
no jira
Goto the button docs
Confirm all the variant links work
RSP
=> Updating the button view guidelines links

packages/@react-spectrum/link/docs/Link.mdx, packages/@react-spectrum/picker/docs/Picker.mdx
=> Minor doc copy fixes for Picker and Link

packages/@react-spectrum/layout/stories/Grid.stories.tsx, packages/@react-types/view/src/view.d.ts
Brings types in line with what's actually supported.
=> Remove HTMLAttributes from View types

packages/@react-aria/searchfield/src/useSearchField.ts, packages/@react-aria/searchfield/test/useSearchField.test.js
=> Mobile prevent leaving input on clear

packages/dev/docs/src/Layout.js, packages/dev/docs/src/docs.css
=> Random perf improvements for the docs

packages/dev/docs/src/attachToToC.js
=> Wrap toc calculation in a raf to avoid reflow

packages/@react-aria/utils/src/useId.ts
=> Change useId prefix

packages/dev/docs/src/Layout.js
=> Load analytics script after page load

packages/@react-spectrum/table/stories/CRUDExample.tsx
Fix error class Keys should be unique so that components maintain their identity across updates
Closes https://github.com/adobe-private/react-spectrum-v3/pull/502
=> Fix error class Keys should be unique

packages/@react-spectrum/breadcrumbs/src/BreadcrumbItem.tsx
Until we figure out how to support Headings
Waiting for https://github.com/adobe-private/react-spectrum-v3/pull/642
=> Remove support for slots in Breadcrumbs

packages/@react-aria/focus/src/useFocusable.ts
=> Make useFocusable ref required.

.circleci/config.yml
=> Don't deploy docs on master

packages/@react-spectrum/illustratedmessage/docs/IllustratedMessage.mdx
Closes https://jira.corp.adobe.com/browse/RSP-1826
Visit the react spectrum illustrated message page and see the new errors.
RSP
=> adding error illustrations as examples

packages/@react-aria/interactions/test/usePress.test.js, packages/@react-aria/sidenav/src/useSideNavItem.ts
https://github.com/adobe-private/react-spectrum-v3/pull/502
Closes
=> Fix errors of class Unknown event handler property

packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/virtualizer/src/ScrollView.tsx, packages/@react-spectrum/picker/test/Picker.test.js, packages/@react-stately/data/test/useAsyncList.test.js, packages/@react-stately/virtualizer/src/Virtualizer.ts, packages/@react-stately/virtualizer/src/useVirtualizerState.ts
Can't perform a React state update on an unmounted component as noted here:
https://github.com/adobe-private/react-spectrum-v3/pull/502
Closes
=> Fix error class no updates on unmounted components

.github/ISSUE_TEMPLATE/Bug_Report.md, .github/ISSUE_TEMPLATE/Feature_Request.md, .github/PULL_REQUEST_TEMPLATE.md
=> Updates to pr/issue templates

packages/dev/docs/src/docs.js
Closes https://jira.corp.adobe.com/browse/RSP-1854
=> Remove h3 from breadcrumbs in prop dialogs

packages/dev/docs/src/Layout.js, packages/dev/docs/src/client.js
Closes https://jira.corp.adobe.com/browse/RSP-1856
Goto the docs
Confirm that the header doesn't have an id.
Confirm that the theme switcher is there.
RSP
=> Docs remove id attribute from the header

packages/dev/docs/pages/contribute.mdx
New contribution guide with all the info
=> Contribute page

packages/@react-spectrum/button/docs/ActionButton.mdx
Better spot to show the import as an example
=> Move edit import in docs

packages/dev/parcel-transformer-mdx-docs/package.json, yarn.lock
So people don't need to configure ssh keys to install
=> Replace git+ssh dependencies with http

packages/dev/docs/src/docs.css
Closes https://jira.corp.adobe.com/browse/RSP-1855
Docs:
Do the code and examples and page background look okay in dark theme?
RSP
=> adjusting the docs dark theme background colors

packages/dev/docs/src/Image.js
They were broken after the parcel upgrade.
=> Fix hero image urls

packages/dev/docs/src/docs.css, packages/dev/docs/src/docs.js
#663 with just the changes to make the popovers open with the enter key in Firefox
=> Minimal changes to make docs popovers work in Firefox

packages/@react-aria/interactions/docs/useFocus.mdx, packages/@react-aria/interactions/docs/useFocusWithin.mdx, packages/@react-aria/interactions/docs/useHover.mdx, packages/@react-aria/interactions/docs/usePress.mdx, packages/@react-aria/searchfield/docs/useSearchField.mdx, packages/@react-aria/select/docs/useSelect.mdx, packages/dev/docs/src/docs.css
Limit scrolling on some examples
add margin to sidenav
Fix typo
=> Doc updates from audit

packages/dev/docs/src/client.js, packages/dev/docs/src/docs.css, packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js
Mostly improvements for mobile
=> More docs updates

NOTICE.txt
=> Add icons to our Notice

packages/@react-aria/label/docs/useLabel.mdx
=> Update package import in useLabel

packages/@adobe/spectrum-css-temp/components/well/index.css, packages/@react-aria/label/docs/useLabel.mdx, packages/@react-spectrum/breadcrumbs/docs/Breadcrumbs.mdx, packages/@react-spectrum/dialog/docs/AlertDialog.mdx, packages/@react-spectrum/dialog/docs/Dialog.mdx, packages/@react-spectrum/dialog/docs/DialogTrigger.mdx, packages/@react-spectrum/dialog/src/DialogTrigger.tsx, packages/@react-spectrum/form/docs/Form.mdx, packages/@react-spectrum/layout/docs/Grid.mdx, packages/@react-spectrum/link/docs/Link.mdx, packages/@react-spectrum/listbox/docs/ListBox.mdx, packages/@react-spectrum/meter/docs/Meter.mdx, packages/@react-spectrum/picker/docs/Picker.mdx, packages/@react-spectrum/progress/docs/ProgressBar.mdx, packages/@react-spectrum/progress/docs/ProgressCircle.mdx, packages/@react-spectrum/text/src/Keyboard.tsx, packages/@react-spectrum/text/src/Text.tsx, packages/@react-spectrum/textfield/docs/TextArea.mdx, packages/@react-spectrum/textfield/docs/TextField.mdx, packages/@react-spectrum/view/docs/View.mdx, packages/@react-types/actiongroup/src/index.d.ts, packages/@react-types/dialog/src/index.d.ts, packages/@react-types/progress/src/index.d.ts, packages/dev/docs/pages/react-spectrum/layout.mdx, packages/dev/docs/pages/react-spectrum/styling.mdx, packages/dev/docs/pages/react-spectrum/theming.mdx, packages/dev/docs/src/ExampleThemeSwitcher.js
Things I found while reading the RSP docs on mobile. Haven't gotten to aria and stately yet. Will come in separate PRs.
=> Docs copy fixes and improvements for mobile

packages/@react-aria/dialog/docs/useDialog.mdx, packages/@react-aria/overlays/docs/useOverlayTrigger.mdx
=> fix: some typos

yarn.lock
Closes https://github.com/adobe/uxp-optimized/network/alert/yarn.lock/lodash/open
=> Resolve lodash to a new higher value

packages/@react-spectrum/listbox/docs/ListBox.mdx
Closes [794](https://github.com/adobe/react-spectrum/issues/794)
-  ✅  Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ N/A ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ N/A ] Filled out test instructions.
- ✅   Updated documentation (if it already exists for this component).
- [ N/A ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)
N/A
Adobe
=> ISSUE-794: Fix ListBox docs typo

packages/@react-aria/visually-hidden/package.json, packages/@react-stately/calendar/package.json, packages/@react-stately/collections/package.json, packages/@react-stately/layout/package.json, packages/@react-stately/splitview/package.json, packages/@react-stately/virtualizer/package.json, scripts/lint-packages.js
=> Ensure react is a peer dependency instead of a dependency

packages/@adobe/spectrum-css-temp/components/textfield/skin.css, packages/@react-spectrum/textfield/src/TextFieldBase.tsx
=> Fix active state applying while textfield is disabled

CONTRIBUTING.md
Just updating the link to the PR template.
=> Fix broken link to pull request template

CONTRIBUTING.md
Fix broken link to code of conduct of contributing.md
=> Fix broken link to code of conduct

packages/@react-aria/tabs/src/useTabs.ts, packages/@react-spectrum/tabs/src/Tabs.tsx, packages/@react-spectrum/tabs/stories/Tabs.stories.js, packages/@react-spectrum/tabs/test/Tabs.test.js, packages/@react-types/tabs/src/index.d.ts
Closes 
Found in testing session
=> Fix disabled tabs being navigable with keyboard

packages/dev/docs/pages/blog/building-a-button-part-1.mdx
=> minor grammar fixes to blog post

packages/@react-spectrum/combobox/src/ComboBox.tsx, packages/@react-spectrum/picker/src/Picker.tsx
Closes https://github.com/adobe/react-spectrum/issues/943
=> Fix mobile Tray scrolling for async Pickers

packages/@react-aria/button/src/index.ts, packages/@react-aria/button/src/useButton.ts, packages/@react-aria/button/src/useToggleButton.ts, packages/@react-aria/focus/src/useFocusable.tsx, packages/@react-aria/selection/src/useSelectableCollection.ts, packages/@react-aria/selection/src/useSelectableItem.ts, packages/@react-aria/selection/src/useSelectableList.ts, packages/@react-aria/visually-hidden/docs/VisuallyHidden.mdx, packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx, packages/@react-spectrum/button/docs/ToggleButton.mdx, packages/@react-spectrum/button/src/ActionButton.tsx, packages/@react-spectrum/button/src/ToggleButton.tsx, packages/@react-spectrum/button/test/ToggleButton.test.js, packages/@react-types/button/src/index.d.ts, packages/@react-types/textfield/src/index.d.ts
Various docs and cleanup for the release. See commit messages.
=> Release cleanup

packages/@react-aria/switch/docs/useSwitch.mdx
=> Update docs for swtich to use ref in example

packages/dev/docs/pages/releases/2020-09-02.mdx
=> Release notes for 20200902

packages/@react-aria/searchfield/src/useSearchField.ts, packages/@react-aria/textfield/src/useTextField.ts
=> fix useSearchField & useTextField inputRef type

packages/@adobe/react-spectrum/src/index.ts
=> Don't export types from monopackage

packages/@react-aria/actiongroup/src/ActionGroupKeyboardDelegate.ts, packages/@react-aria/selection/src/ListKeyboardDelegate.ts, packages/@react-aria/selection/src/useSelectableCollection.ts, packages/@react-aria/tabs/src/TabsKeyboardDelegate.ts, packages/@react-spectrum/actiongroup/stories/ActionGroup.stories.tsx, packages/@react-spectrum/actiongroup/test/ActionGroup.test.js, packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx, packages/@react-spectrum/menu/test/MenuTrigger.test.js, packages/@react-spectrum/picker/test/Picker.test.js, packages/@react-spectrum/tabs/stories/Tabs.stories.js, packages/@react-spectrum/tabs/test/Tabs.test.js, packages/@react-stately/layout/src/ListLayout.ts
=> Fix keyboard navigation for collection and list items with falsy keys 

packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@react-spectrum/breadcrumbs/stories/Breadcrumbs.stories.tsx, packages/@react-spectrum/listbox/stories/ListBox.stories.tsx
Had to bring back inherit so that it wouldn't break outside of a display flex
had to include width 100% so that listbox would render by default
Brought back the large testing story so we could verify all of those as well
Closes
=> Test resizing of listbox

packages/@adobe/spectrum-css-temp/components/colorloupe/skin.css, packages/@adobe/spectrum-css-temp/components/colorslider/index.css, packages/@adobe/spectrum-css-temp/components/colorslider/skin.css, packages/@adobe/spectrum-css-temp/components/colorslider/vars.css, packages/@react-aria/color/package.json, packages/@react-aria/color/src/index.ts, packages/@react-aria/color/src/useColorSlider.tsx, packages/@react-aria/color/src/useColorWheel.ts, packages/@react-aria/slider/src/useSlider.ts, packages/@react-aria/slider/src/useSliderThumb.ts, packages/@react-aria/slider/test/useSlider.test.js, packages/@react-aria/slider/test/useSliderThumb.test.js, packages/@react-spectrum/color/package.json, packages/@react-spectrum/color/src/ColorSlider.tsx, packages/@react-spectrum/color/src/ColorThumb.tsx, packages/@react-spectrum/color/src/index.ts, packages/@react-spectrum/color/stories/ColorSlider.stories.tsx, packages/@react-spectrum/color/test/ColorSlider.test.tsx, packages/@react-stately/color/package.json, packages/@react-stately/color/src/Color.ts, packages/@react-stately/color/src/useColorSliderState.ts, packages/@react-stately/color/test/Color.test.js, packages/@react-types/color/src/index.d.ts, packages/@react-types/slider/src/index.d.ts
Closes https://github.com/adobe/react-spectrum/issues/1119
Includes https://github.com/adobe/spectrum-css/pull/1034
=> Colorslider

packages/@spectrum-icons/workflow/chromatic/Workflow.chromatic.tsx
Stories for color icons
Closes
=> Chromatic stories for icons

packages/@react-spectrum/tooltip/test/TooltipTrigger.test.js, packages/@react-stately/tooltip/src/useTooltipTriggerState.ts
=> Fix #1177: Use delay value if passed in as prop

packages/dev/docs/pages/react-aria/getting-started.mdx
Closes https://github.com/adobe/react-spectrum/issues/1251
=> Fix docs typo in react-aria getting started

packages/@react-aria/tabs/src/useTabs.ts, packages/@react-spectrum/button/src/FieldButton.tsx, packages/@react-spectrum/tabs/package.json, packages/@react-spectrum/tabs/src/Tabs.tsx, packages/@react-stately/tabs/README.md, packages/@react-stately/tabs/index.ts, packages/@react-stately/tabs/package.json, packages/@react-stately/tabs/src/index.ts, packages/@react-stately/tabs/src/useTabsState.ts, packages/@react-types/tabs/src/index.d.ts
=> Collapsible tabs review followup

.chromatic/config.js, .storybook/config.js
Closes #1269 
Perform a fresh install and run storybook, should build without errors
Adobe Analytics
=> Updating unresolved package 'storybook-chromatic' reference to recommended 'chromatic'

packages/@react-spectrum/button/src/ClearButton.tsx
Add class for isDisabled on ClearButton
Closes
=> Fix ClearButton disabled style

packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-spectrum/dialog/test/Dialog.test.js
Reverts adobe/react-spectrum#1195
=> Revert "Adding raf to focusElement so Firefox can tab into dialog iframe"

packages/@react-aria/combobox/src/useComboBox.ts, packages/@react-spectrum/combobox/docs/ComboBox.mdx, packages/@react-spectrum/combobox/src/ComboBox.tsx, packages/@react-spectrum/combobox/src/MobileComboBox.tsx, packages/@react-types/combobox/src/index.d.ts
Closes
dependent on https://github.com/adobe/react-spectrum/pull/1176
=> ComboBox docs

packages/dev/docs/src/HeaderInfo.js, packages/dev/docs/src/Layout.js, packages/dev/docs/src/VersionBadge.js, packages/dev/docs/src/docs.css, packages/dev/parcel-optimizer-ssg/SSGOptimizer.js, packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js
Closes #1263 
Add a mdx for an alpha component to test
RSP
=> Add alpha label component for docs

packages/@react-spectrum/tooltip/docs/Tooltip.mdx, packages/@react-types/tooltip/src/index.d.ts
=> Fixing tooltip docs links

packages/@react-spectrum/utils/src/useDOMRef.ts
=> added new useUnwrapDOMRef

packages/@react-types/text/src/heading.d.ts
Closes https://github.com/adobe/react-spectrum/issues/1348
=> Give default to Heading level docs

packages/@adobe/spectrum-css-temp/components/slider/index.css, packages/@react-aria/slider/src/useSlider.ts, packages/@react-spectrum/slider/src/SliderBase.tsx
Fix right clicking on the track
Fix clicking on ends of slider
Closes
=> Slider fixes for clicking

packages/@react-aria/slider/src/useSliderThumb.ts
=> Fix Don't focus thumb on right click

packages/@react-spectrum/slider/src/SliderBase.tsx
The thumb min and max change while dragging if there are multiple thumbs.
=> Fix wrapping based on min and max values

packages/@react-aria/color/src/useColorSlider.ts, packages/@react-aria/color/src/useColorWheel.ts, packages/@react-aria/color/test/useColorWheel.test.tsx, packages/@react-aria/slider/docs/useSlider.mdx, packages/@react-aria/slider/src/useSlider.ts, packages/@react-aria/slider/src/useSliderThumb.ts, packages/@react-aria/slider/stories/StoryMultiSlider.tsx, packages/@react-aria/slider/stories/StoryRangeSlider.tsx, packages/@react-aria/slider/stories/StorySlider.tsx, packages/@react-aria/slider/test/useSlider.test.js, packages/@react-aria/slider/test/useSliderThumb.test.js, packages/@react-spectrum/color/src/ColorSlider.tsx, packages/@react-spectrum/color/src/ColorWheel.tsx, packages/@react-spectrum/slider/src/RangeSlider.tsx, packages/@react-spectrum/slider/src/SliderBase.tsx, packages/@react-spectrum/slider/src/SliderThumb.tsx, packages/@react-stately/slider/src/useSliderState.ts, packages/@react-types/color/src/index.d.ts, packages/@react-types/slider/src/index.d.ts
=> Slider API audit

packages/@adobe/spectrum-css-temp/vars/spectrum-large.css, packages/@adobe/spectrum-css-temp/vars/spectrum-medium.css
=> Updating tooltip width to match updated Spectrum value

yarn.lock
fixes console message asking to update it
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```
Closes
=> Update can i use database

packages/@react-spectrum/toast/stories/Toast.stories.tsx
=> added missing ToastProviders

packages/@react-aria/combobox/src/useComboBox.ts, packages/@react-spectrum/combobox/test/ComboBox.test.js
=> Disable autocorrect suggestions in combobox

.circleci/config.yml
=> Removing v2 setup from v3 build

packages/@react-aria/combobox/src/useComboBox.ts, packages/@react-aria/interactions/src/useFocusVisible.ts, packages/@react-aria/listbox/src/useOption.ts, packages/@react-aria/overlays/src/usePreventScroll.ts, packages/@react-aria/selection/src/useSelectableCollection.ts, packages/@react-aria/utils/src/index.ts, packages/@react-aria/utils/src/platform.ts
=> Centralize platform/browser checks in one place

packages/@react-aria/numberfield/src/useNumberField.ts, packages/@react-spectrum/numberfield/test/NumberField.test.js
=> Numberfield only change in response to vertical scrolling

packages/@react-aria/grid/package.json, packages/@react-aria/table/package.json, packages/@react-stately/grid/package.json, packages/@react-stately/layout/package.json, packages/@react-stately/table/package.json, packages/@react-types/grid/package.json
=> Fix imports (grid/table)

packages/@adobe/spectrum-css-temp/components/stepper/index.css, packages/@adobe/spectrum-css-temp/components/stepper/skin.css, packages/@react-spectrum/numberfield/src/NumberField.tsx, packages/@react-spectrum/numberfield/src/StepButton.tsx, packages/@react-spectrum/numberfield/stories/NumberField.stories.tsx
=> Readonly and inputgroup styles

packages/dev/docs/src/client.js
Regression from #1448.
This code is very brittle. We should turn this into an actual component using our hooks at some point.
=> Fix hamburger menu in docs

packages/@react-aria/combobox/docs/anatomy.svg
Fixes it being clipped on mobile
=> Fix viewBox of combobox anatomy diagram

packages/@react-stately/color/test/useColor.test.js
=> fixing useColor test

packages/@react-stately/virtualizer/src/Virtualizer.ts
Closes https://github.com/adobe/react-spectrum/issues/1485
=> Fix ComboBox item sizing inconsistency

scripts/buildWebsite.js
=> Fix docs prod build missing file

.circleci/config.yml
=> Increase the resource class for docs prod

packages/@react-spectrum/slider/package.json
Partially addresses #1642 
Look at the package.json peer dependency change in `@react-spectrum/slider`
Adobe Research incubation project
=> [slider] update react peer dependency version to include v17

packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@adobe/spectrum-css-temp/vars/spectrum-large.css, packages/@adobe/spectrum-css-temp/vars/spectrum-medium.css, packages/@react-spectrum/combobox/src/combobox.css
Closes https://github.com/adobe/react-spectrum/issues/1601
=> Renaming css var to fix menu item sizing in docs in mobile

packages/@react-stately/data/src/useTreeData.ts, packages/@react-stately/data/test/useTreeData.test.js
=> fix(#1097) useTreeData update method causing infinite loop

rfcs/2020-v3-dnd.md
Moves the RFC out of dropbox and into the repo. Attempted to convert the videos to gifs so they are embedded by GitHub.
[Rendered](https://github.com/adobe/react-spectrum/blob/dnd-rfc/rfcs/2020-v3-dnd.md)
=> Add drag and drop RFC to the repo

packages/@react-aria/dnd/src/DragManager.ts
TS was complaining about these properties, which really should have been private anyway.
=> Fix build of @react-aria/dnd package

packages/@adobe/spectrum-css-temp/vars/spectrum-medium.css
=> Fixing Menu item heights again

packages/@react-stately/data/src/index.ts, packages/react-stately/src/index.ts
Closes https://github.com/adobe/react-spectrum/issues/1612
- `yarn test`
=> Add ListData interface to react-stately

packages/@react-aria/virtualizer/src/Virtualizer.tsx, packages/@react-spectrum/listbox/test/ListBox.test.js, packages/@react-spectrum/table/src/Table.tsx, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-spectrum/table/test/Table.test.js
Closes https://github.com/adobe/react-spectrum/issues/1691
=> Fix Table so it loads enough items to fill its height

packages/@react-spectrum/form/stories/Form.stories.tsx, packages/@react-spectrum/form/test/Form.test.js
This is to test that all components send the right state in their request, it can be checked in the URL after hitting enter to submit or the submit button
Closes
=> Allow form submission default in storybook

patches/@parcel+transformer-typescript-types+2.0.0-nightly.359.patch
https://github.com/parcel-bundler/parcel/pull/6057
=> Patch parcel to fix generated TS types

packages/@react-aria/menu/package.json, packages/@react-aria/tooltip/package.json, packages/react-aria/package.json, packages/react-stately/package.json
Closes https://github.com/adobe/react-spectrum/issues/1779
=> Fix peer deps in react-aria & react-stately

packages/@adobe/spectrum-css-temp/components/tabs/index.css
And also disable text selection of tabs because it's weird.
=> Fix transition of tab icons on hover

packages/@adobe/spectrum-css-temp/components/barloader/index.css, packages/@react-spectrum/progress/src/ProgressBarBase.tsx
Add moz prefix that wasn't being auto generated for us
Closes
=> Fix Progressbar Style

packages/@react-aria/grid/src/useGridCell.ts, packages/@react-aria/grid/src/useGridRow.ts, packages/@react-aria/selection/src/useSelectableCollection.ts, packages/@react-aria/table/src/useTable.ts, packages/@react-spectrum/table/src/table.css
=> Removing text selection in Table

packages/@react-spectrum/tabs/src/Tabs.tsx
Closes 
fixes issues found here: https://github.com/adobe/react-spectrum/pull/1812
=> Fix passthrough of Tabs style props

packages/@react-spectrum/combobox/docs/ComboBox.mdx
Closes 
Followup to https://github.com/adobe/react-spectrum/pull/1683
=> Updating ComboBox docs with input text update on async list fetch

packages/@react-aria/numberfield/docs/useNumberField.mdx, packages/@react-spectrum/numberfield/docs/NumberField.mdx, packages/dev/docs/pages/blog/how-we-internationalized-our-numberfield.mdx
=> Clarify which chinese numbering system we use

packages/@react-spectrum/tabs/docs/Tabs.mdx
=> Update imports in usage docs for Tabs

packages/@react-spectrum/actionbar/stories/ActionBar.stories.tsx, packages/@react-spectrum/icon/docs/IconTable.tsx, packages/@react-spectrum/table/src/TableView.tsx, packages/@react-spectrum/table/src/index.ts, packages/@react-spectrum/table/stories/CRUDExample.tsx, packages/@react-spectrum/table/stories/HidingColumns.tsx, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-spectrum/table/test/Table.test.js
=> Renaming Table to TableView

packages/@react-aria/combobox/test/useComboBox.test.js, packages/@react-spectrum/combobox/src/ComboBox.tsx, packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx, packages/@react-spectrum/combobox/test/ComboBox.test.js, packages/@react-stately/combobox/src/useComboBoxState.ts, packages/@react-stately/combobox/test/useComboBoxState.test.js, packages/@react-types/combobox/src/index.d.ts
Closes https://github.com/adobe/react-spectrum/issues/1927
=> Removing isOpen and defaultOpen from ComboBox

.gitignore, packages/@react-aria/tabs/docs/anatomy.svg, packages/@react-aria/tabs/docs/useTab.mdx, packages/@react-aria/tabs/docs/useTabList.mdx, packages/@react-aria/tabs/package.json, packages/@react-aria/tabs/src/useTab.ts, packages/@react-aria/tabs/src/useTabList.ts, packages/@react-aria/tabs/src/useTabPanel.ts, packages/@react-aria/tabs/src/utils.ts, packages/@react-spectrum/tabs/docs/Tabs.mdx, packages/@react-stately/numberfield/src/useNumberFieldState.ts, packages/@react-stately/tabs/docs/useTabListState.mdx, packages/@react-stately/tabs/src/index.ts, packages/@react-stately/tabs/src/useTabListState.ts, packages/dev/docs/src/PropTable.js, packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js
Closes https://github.com/adobe/react-spectrum/issues/1256
=> Tab hook docs

.eslintrc.js, packages/@react-aria/dnd/test/dnd.test.js, packages/@react-spectrum/actiongroup/test/ActionGroup.test.js, packages/@react-spectrum/breadcrumbs/test/Breadcrumbs.test.js, packages/@react-spectrum/combobox/test/ComboBox.test.js, packages/@react-spectrum/menu/test/Menu.test.js, packages/@react-spectrum/table/test/Table.test.js, packages/dev/eslint-plugin-rsp-rules/index.js, packages/dev/eslint-plugin-rsp-rules/package.json, packages/dev/eslint-plugin-rsp-rules/rules/act-events-test.js, packages/dev/eslint-plugin-rsp-rules/rules/no-getByRole-toThrow.js
Includes a fixer and fixes the files where there is an error
Closes
=> Lint for expect getByRole toThrow

packages/@react-stately/tabs/docs/useTabListState.mdx
Closes 
File name was changed so path was changed and the link wasn't updated
=> Fix broken docs link

packages/@react-types/select/src/index.d.ts
=> Remove isReadOnly from Picker

packages/@react-aria/grid/src/useGridCell.ts, packages/@react-spectrum/table/test/Table.test.js
=> Fixing textfield keyboard navigation when in a dialog opened from a table 

packages/@react-aria/focus/src/useFocusRing.ts
=> Fixing disabled ActionButtons so autoFocus doesn't apply a focus ring

packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx
=> Remove duplicate story from ComboBox

.circleci/config.yml
Closes 
Easy attempt at fixing deploy step, it seems to have worked. Possibly ended support for the earlier version?
=> Use a newer azure cli version

yarn.lock
Closes 
`with npx browserslist@latest --update-db`
=> updated browser list

packages/@react-spectrum/table/src/table.css
=> Fix table height within flex

scripts/buildWebsite.js
=> Fix prod build of docs as well

packages/@react-types/provider/src/index.d.ts, packages/@react-types/shared/src/style.d.ts
=> Support undefined for custom types

packages/@react-aria/button/src/useButton.ts, packages/@react-aria/interactions/src/usePress.ts, packages/@react-spectrum/button/test/Button.test.js
Closes 
Testing a different route
=> [WIP] - Make form submission fix in usePress instead of in useButton

packages/@internationalized/number/README.md
Closes https://github.com/adobe/react-spectrum/issues/2039
=> Fix NumberParser partial number documentation to match tests

packages/@react-spectrum/searchwithin/package.json, packages/@react-spectrum/searchwithin/src/SearchWithin.tsx
=> Fix SearchWithin label alignment in Form

packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-stately/data/src/useAsyncList.ts, packages/@react-stately/data/test/useAsyncList.test.js
=> Enable propagation of all value through useAsyncList methods

packages/@react-spectrum/datepicker/test/DatePicker.test.js
Fixes date picker tests, which are failing today because it is the last day of the month. 😉
=> Fix datepicker tests

.eslintrc.js, packages/@internationalized/date/src/manipulation.ts, packages/@react-aria/button/src/useButton.ts, packages/@react-aria/button/src/useToggleButton.ts
Closes #2245.
```
yarn lint
```
Adobe RSP
=> Add TS no-redeclare ESLint rule

packages/@react-aria/numberfield/docs/useNumberField.mdx
Closes https://github.com/adobe/react-spectrum/issues/2298
=> Add refs for buttons in useNumberField docs

packages/@adobe/spectrum-css-temp/components/helptext/index.css, packages/@react-spectrum/label/src/Field.tsx, packages/@react-spectrum/label/src/HelpText.tsx, packages/@react-types/shared/src/inputs.d.ts
=> Fix helptext should not align

packages/@adobe/spectrum-css-temp/components/table/index.css
=> Fix sort icon in mobile tables

packages/@react-spectrum/tooltip/docs/Tooltip.mdx
=> Fix Tooltip docs

scripts/buildWebsite.js
=> Hack around Parcel bug when building textfield docs

packages/@react-spectrum/combobox/docs/ComboBox.mdx, packages/@react-spectrum/numberfield/docs/NumberField.mdx, packages/@react-spectrum/picker/docs/Picker.mdx, packages/@react-spectrum/searchfield/docs/SearchField.mdx, packages/@react-spectrum/textfield/docs/TextArea.mdx, packages/@react-spectrum/textfield/docs/TextField.mdx
=> Add HelpText examples to docs

packages/@react-spectrum/list/test/ListView.test.js, packages/@react-stately/virtualizer/src/Virtualizer.ts
Closes https://github.com/adobe/react-spectrum/issues/2537
=> Fix ListView arrow navigation scrolling

packages/@react-aria/datepicker/src/useDateSegment.ts, packages/@react-spectrum/datepicker/src/DatePicker.tsx, packages/@react-spectrum/datepicker/src/index.css
Some fixes for issues found in testing. See commits.
=> DatePicker bug fixes

packages/@react-aria/combobox/stories/useComboBox.stories.tsx
=> Add useComboBox shouldFocusWrap story

packages/@react-stately/data/docs/useAsyncList.mdx
=> fix issue #1878, added async to the sort function

packages/@react-aria/breadcrumbs/docs/useBreadcrumbs.mdx
Originally opened by https://github.com/i-am-the-slime
https://github.com/adobe/react-spectrum/pull/2648
=> Fix typo in useBreadCrumbs docs

packages/@react-aria/ssr/docs/useIsSSR.mdx
Closes 
check useIsSSR page in react-aria portion of docs
RSP
=> undo fix of false positive from docs-differ

packages/@react-aria/grid/src/useHighlightSelectionDescription.ts, packages/@react-spectrum/table/test/Table.ssr.test.js
Closes #2747
```
yarn test:ssr Table.ssr
```
Adobe/RSP
=> Fix TableView SSR

packages/@adobe/react-spectrum/src/index.ts, packages/@react-spectrum/provider/src/Provider.tsx, packages/@react-types/provider/src/index.d.ts
=> Exporting useProvider from RSP monopackage

packages/dev/docs/pages/react-spectrum/ssr.mdx
Closes https://github.com/adobe/react-spectrum/issues/2780
=> Clarify that locale is not an imported variable

packages/@react-spectrum/contextualhelp/package.json, packages/@react-spectrum/contextualhelp/src/ContextualHelp.tsx, packages/@react-types/contextualhelp/src/index.d.ts
=> ContextualHelp: Update type descriptions and forwardRef

packages/@react-spectrum/menu/docs/MenuTrigger.mdx
=> Adding long press section to MenuTrigger docs

packages/@react-spectrum/provider/docs/Provider.mdx
=> useProvider docs

packages/@react-spectrum/sidenav/package.json, packages/@react-types/sidenav/package.json
Sidenav deps got messed up, fixed now?
RSP
=> Fix lint from publish

packages/@react-spectrum/searchwithin/test/SearchWithin.test.js
Closes 
looks like a debug statement slipped through in a unit test
=> Remove debug statement

packages/@react-aria/grid/intl/ru-RU.json, packages/@react-aria/grid/intl/sr-SP.json
Closes https://github.com/adobe/react-spectrum/issues/2864
=> fix ru-RU and sr-SP translations in @react-aria/grid

packages/@react-aria/overlays/package.json, packages/@react-aria/overlays/src/DismissButton.tsx, packages/@react-aria/overlays/test/DismissButton.test.tsx
Closes https://github.com/adobe/react-spectrum/issues/2866
=> Allow custom messages on DismissButton

packages/@react-spectrum/form/stories/Form.stories.tsx, packages/@react-types/combobox/src/index.d.ts
Closes #2879
Lint should pass
RSP
=> Adding "name" to combobox props

packages/@react-aria/landmark/src/useLandmark.ts, packages/@react-aria/landmark/test/useLandmark.test.tsx
Looking into using a custom event for landmark focus, discussed in https://github.com/adobe/react-spectrum/pull/2750#discussion_r812249194.
=> Landmarks: custom event for focus

packages/@react-types/color/src/index.d.ts
Closes 
https://github.com/adobe/react-spectrum/issues/2296
=> Fix Colorfield Types for controlled clearing of field

packages/@react-aria/landmark/stories/Landmark.stories.tsx
=> Aria label landmarks with something more unique

packages/@react-aria/landmark/src/useLandmark.ts, packages/@react-aria/landmark/test/useLandmark.test.tsx
=> Cleanup landmark listeners on unmount

.circleci/config.yml
Ref: https://github.com/Azure/azure-cli/issues/21477
=> Fix production deploy to azure

packages/@react-spectrum/list/src/ListView.tsx
=> Fix indentation

packages/@react-spectrum/dnd/package.json
=> Removing extraneous dependecies from spectrum dnd package

packages/@adobe/spectrum-css-temp/components/dialog/index.css, packages/@react-spectrum/dialog/src/Dialog.tsx
Closes 
From a conversation with @ktabors this is for consideration on his branch that this is pointed towards.
=> Suggested fixes for Dialog CSS

packages/@react-spectrum/calendar/test/RangeCalendar.test.js
=> Fix RangeCalendar test

packages/dev/docs/pages/releases/2022-03-21.mdx
=> March patch release notes

packages/@react-spectrum/contextualhelp/docs/ContextualHelp.mdx
see new link to spectrum design docs on ContextualHelp page
RSP
=> adding contextualhelp spectrum docs link

.circleci/comment.js, .github/actions/branch/action.yml, .github/actions/branch/index.js, .github/workflows/pr-comment.yaml
Will need to be merged into main to fully test but I did some testing on a fresh repo + a fork for the action. The full circleci comment modifications will need to be tested post merge but I tested the logic in the try catch separately 
RSP
=> Adding action to generate branch for forks + build comment for forks

.github/workflows/pr-comment.yaml
=> Updating trigger conditions for getting build link on fork PR

scripts/changelog.js
=> Include user links in change logs

packages/@react-spectrum/dialog/chromatic/Dialog.chromatic.tsx, packages/@react-spectrum/menu/chromatic/MenuTrigger.chromatic.tsx, packages/@react-spectrum/menu/chromatic/MenuTriggerRTL.chromatic.tsx, packages/@react-spectrum/picker/chromatic/Picker.chromatic.tsx
Closes 
This should allow us to get a green light on main again for our baselines
=> Remove invalid chromatic stories

.storybook/custom-addons/provider/index.js, packages/@react-aria/landmark/stories/Landmark.stories.tsx
Closes 
Followup to https://github.com/adobe/react-spectrum/pull/2988
=> Add parameter to control when stories are wrapped with main

.github/actions/permissions/action.yml, .github/actions/permissions/index.js, .github/workflows/pr-comment.yaml
=> Check permissions of user before attempting to create branch

packages/@react-spectrum/list/src/DragPreview.tsx, packages/@react-spectrum/list/src/ListView.tsx
Closes #3067
Test in storybook at [ListView -> draggable rows](https://reactspectrum.blob.core.windows.net/reactspectrum/c53f68d98f4e863e3707c60ea2d83e543a622e12/storybook/index.html?path=/story/listview--draggable-rows)
- Drag preview height should match row height
- Styles in drag preview for RTL should be correct (match item's)
- Corners of drag preview should be rounded
=> ListView drag preview follow-ups

packages/@react-aria/select/docs/useSelect.mdx, packages/@react-aria/select/src/useSelect.ts
Closes #3061
You can use same Code Sample from the original issue.
No
=> Fix generic issue with SelectAria to follow useSelect<T>

packages/@react-aria/numberfield/docs/useNumberField.mdx
=> Fix typo in useNumberField doc

packages/@react-aria/selection/src/useSelectableItem.ts, packages/@react-spectrum/list/test/ListView.test.js
Found in https://github.com/adobe/react-spectrum/pull/3103#pullrequestreview-966486480
=> Prevent onAction on mouse up when deselecting

packages/@adobe/spectrum-css-temp/components/table/index.css, packages/@react-spectrum/list/src/ListView.tsx, packages/@react-spectrum/list/src/styles.css, packages/@react-spectrum/table/src/TableView.tsx, packages/@react-spectrum/table/src/TableView_DEPRECATED.tsx
Closes https://github.com/adobe/react-spectrum/issues/3072
Fixes issues found in testing session
=> Fix scroll bar detection list and table view

packages/@react-spectrum/list/src/styles.css
=> isQuiet ListView with children missing chevron

packages/@react-spectrum/link/stories/Link.stories.tsx
Related to #3056
Following format used in #3129
Check that Link stories match existing.
=> CSF 3 Link

packages/@react-aria/list/package.json, packages/@react-types/list/package.json
=> Audit React 18 peer deps

packages/@react-stately/table/src/useTableState.ts
Closes 
Should be reverted after release
=> Comment out more API's related to resize for the moment

packages/@react-aria/calendar/docs/useCalendar.mdx, packages/@react-aria/calendar/docs/useRangeCalendar.mdx, packages/@react-aria/datepicker/docs/useDatePicker.mdx, packages/@react-aria/datepicker/docs/useDateRangePicker.mdx
This updates the aria docs for the changes in #3149.
=> Update ARIA docs for calendar changes

packages/@react-spectrum/menu/src/ActionMenu.tsx, packages/@react-spectrum/menu/stories/ActionMenu.stories.tsx
Closes #3178
Typescript issue so you'll have to pull locally. Try reverting the export and check for typescript errors in the action menu stories 
RSP
=> Update ActionMenu export

packages/@internationalized/date/src/DateFormatter.ts
Work around https://bugs.webkit.org/show_bug.cgi?id=241564
=> Work around Safari bug with ethiopic calendar

packages/@react-aria/datepicker/docs/useDateField.mdx, packages/@react-aria/datepicker/docs/useDatePicker.mdx, packages/@react-aria/datepicker/docs/useDateRangePicker.mdx, packages/@react-aria/datepicker/docs/useTimeField.mdx, packages/@react-spectrum/datepicker/docs/DateField.mdx, packages/@react-spectrum/datepicker/docs/DatePicker.mdx, packages/@react-spectrum/datepicker/docs/DateRangePicker.mdx, packages/@react-spectrum/datepicker/docs/TimeField.mdx
=> Update wording of docs for placeholders in DatePicker components

packages/@react-types/shared/src/dnd.d.ts
Follow up from previous dnd docs PR
RSP
=> Removing explicit time callout from drop activation description

packages/@internationalized/date/README.md
This just fixes some broken links
=> Fix broken links in readme

packages/@react-aria/utils/src/platform.ts
=> fix(@react-aria/utils): handle empty navigator.userAgentData.platform

packages/@internationalized/date/src/manipulation.ts, packages/@internationalized/date/tests/manipulation.test.js
Closes #3313 
Unit test should cover it
RSP
=> Fix CalendarDateTime add and subtract operations

packages/@react-spectrum/list/src/styles.css
Closes 
Found in testing session
Go to any ListView story with actions, they should all be aligned
=> fix listview action alignment

packages/@react-spectrum/dialog/stories/DialogTrigger.stories.tsx
=> Fix DialogTrigger story typos

packages/@react-aria/table/src/useTableColumnHeader.ts
=> remove accidental console log

.circleci/config.yml, examples/rsp-cra-18/package.json
=> Fixing circleci PR comment trigger so it happens only on non-main branches

packages/@react-aria/gridlist/src/useGridList.ts
Closes 
sanity test ListView
RSP
=> Removing getRowText prop from useGridList

packages/@react-aria/table/src/useTableColumnHeader.ts
Mark hasMenu as private, to be renamed later
=> Mark hasMenu as private

packages/dev/docs/pages/releases/2022-08-26.mdx
Release notes for Aug 26th 2022 release
=> August release notes

packages/dev/docs/pages/releases/2022-08-26.mdx
=> Add patch to release notes

packages/dev/docs/pages/react-spectrum/ssr.mdx
=> Add @react-spectrum/list and @spectrum-icons/illustrations to SSR config docs

packages/@react-spectrum/textfield/docs/TextArea.mdx
=> Update TextArea docs to remove outdated resizing info

packages/@react-spectrum/labeledvalue/chromatic/LabeledValue.chromatic.tsx
Closes 
no value meant the chromatic stories weren't showing anything meaningful
=> Fix labeled value chromatic stories

packages/@react-spectrum/labeledvalue/docs/LabeledValue.mdx, packages/@react-spectrum/labeledvalue/docs/types.ts, packages/@react-spectrum/labeledvalue/src/LabeledValue.tsx, packages/@react-spectrum/labeledvalue/stories/LabeledValue.stories.tsx, packages/@react-spectrum/labeledvalue/test/LabeledValue.test.js, packages/dev/docs/src/types.js
Also fixes the aria labeling props which weren't actually passed through.
=> Add documentation for LabeledValue

packages/@react-aria/dialog/package.json, packages/@react-aria/dialog/src/useDialog.ts, packages/@react-aria/overlays/package.json, packages/@react-aria/overlays/src/Overlay.tsx, packages/@react-aria/overlays/src/index.ts, packages/@react-aria/overlays/src/useModalOverlay.ts, packages/@react-aria/overlays/src/usePopover.ts, packages/@react-spectrum/overlays/test/Tray.test.js, packages/@react-stately/datepicker/src/useDatePickerState.ts, packages/@react-stately/datepicker/src/useDateRangePickerState.ts
This is the code from #3347, but without any docs changes.
=> New overlay hooks, code only

packages/@react-spectrum/dnd/docs/dnd.mdx, packages/@react-spectrum/dnd/src/index.ts, packages/@react-spectrum/dnd/src/useDragAndDrop.ts, packages/@react-spectrum/list/docs/ListView.mdx, packages/@react-spectrum/list/src/InsertionIndicator.tsx, packages/@react-spectrum/list/src/ListView.tsx, packages/@react-spectrum/list/src/ListViewItem.tsx, packages/@react-spectrum/list/src/RootDropIndicator.tsx, packages/@react-spectrum/list/stories/ListView.stories.tsx
=> Rename useDnDHooks and ListView dndHooks prop

packages/@react-spectrum/button/docs/Button.mdx, packages/@react-spectrum/button/src/Button.tsx
Closes 
Add icon-only entry for Button in docs
=> Add icon only docs for Button

packages/@react-aria/dnd/docs/dnd.mdx, packages/@react-aria/dnd/docs/useClipboard.mdx, packages/@react-aria/dnd/docs/useDrag.mdx, packages/@react-aria/dnd/docs/useDraggableCollection.mdx, packages/@react-aria/dnd/docs/useDrop.mdx, packages/@react-aria/dnd/docs/useDroppableCollection.mdx, packages/@react-spectrum/badge/docs/Badge.mdx, packages/@react-spectrum/dnd/docs/dnd.mdx, packages/@react-spectrum/labeledvalue/docs/LabeledValue.mdx, packages/@react-spectrum/labeledvalue/docs/types.ts
=> Enable docs for release

packages/dev/docs/pages/react-spectrum/index.mdx
Our themes are not yet considered API, so we cannot support custom theming yet. This is to clarify what we do offer.
Closes https://github.com/adobe/react-spectrum/issues/3370
=> Clarify RSP docs around theming

packages/@react-aria/dnd/src/utils.ts
Closes 
Directly edited the `node_modules` with this fix.
[codesandbox](https://codesandbox.io/p/github/Dev-CasperTheGhost/ssr-react-aia-dnd/draft/vibrant-panna?file=%2Fpages%2Findex.tsx&workspace=%257B%2522activeFileId%2522%253A%2522cl919iryl0001lth02pdr8kfm%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522cl919jg4p00dd2a693g23ejjq%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl919j0l800at2a69d26hgkd5%2522%252C%2522isMinim …
=> fix(@react-aria/dnd): add support for SSR

packages/@react-aria/selection/src/useSelectableItem.ts, packages/@react-spectrum/list/test/ListViewDnd.test.js
This reverts commit dec0fb0da0bbb7bbc29ecbad7435de7a9f11b67a.
Closes
=> Revert "ListView DnD: Fix dragging when selectionMode="none" (#3681)"

packages/@react-aria/selection/src/useSelectableCollection.ts, packages/@react-spectrum/list/stories/ListView.stories.tsx
=> Fix selectionMode none dragging

packages/@react-spectrum/table/src/TableView.tsx
=> remove resizer from dom when not in use

packages/@react-spectrum/table/src/TableView.tsx, packages/@react-spectrum/table/test/Table.test.js
Closes 
test should cover this
RSP
=> Make TableView accept a UNSAFE_className

packages/@react-spectrum/tag/src/TagGroup.tsx
=> Add description to TagGroup

packages/@adobe/spectrum-css-temp/components/button/skin.css, packages/@react-aria/overlays/src/usePopover.ts, packages/@react-spectrum/button/docs/Button.mdx, packages/@react-spectrum/dialog/docs/Dialog.mdx, packages/@react-spectrum/dialog/docs/DialogContainer.mdx, packages/@react-spectrum/dialog/docs/DialogTrigger.mdx, packages/@react-spectrum/provider/docs/Provider.mdx, packages/dev/docs/pages/react-spectrum/getting-started.mdx, packages/dev/docs/pages/react-spectrum/styling.mdx, packages/dev/docs/src/template.mdx, packages/dev/parcel-transformer-docs/DocsTransformer.js
* Discourages use of `isKeyboardDismissDisabled` in `usePopover`
* Updates button docs for new variants
* Adds docs for `colorVersion`
=> Docs updates for release

packages/@react-aria/menu/docs/useMenu.mdx
=> Fix useMenu complex items example

packages/@react-stately/dnd/docs/useDraggableCollectionState.mdx, packages/@react-stately/dnd/docs/useDroppableCollectionState.mdx
=> React Stately docs for drag ad drop

packages/@adobe/spectrum-css-temp/components/inputgroup/index.css, packages/@adobe/spectrum-css-temp/components/inputgroup/skin.css, packages/@adobe/spectrum-css-temp/components/tabs/skin.css
=> Fix Tabs collapsed focusring

scripts/buildWebsite.js
=> Fix docs prod build

.circleci/config.yml
=> Remove PR commenting for now so builds pass

packages/@react-aria/overlays/src/calculatePosition.ts, packages/@react-aria/overlays/stories/UseOverlayPosition.stories.tsx, packages/@react-aria/overlays/test/calculatePosition.test.js
This reverts commit e5d6994580636623cf89e120487b42c44cb8e78b.
We wanna discuss the desired behavior for this a bit more, reverting for this release
RSP
=> Revert "@react-aria/overlays - Fix overlay position clamping (#3756)"

packages/@adobe/spectrum-css-temp/components/fieldlabel/index.css
=> Fix labeled value label position side CSS specificity

packages/@react-aria/table/src/useTableColumnResize.ts, packages/@react-aria/table/stories/example-resizing.tsx, packages/@react-aria/table/test/tableResizingTests.tsx, packages/@react-spectrum/table/src/Resizer.tsx, packages/@react-spectrum/table/src/TableView.tsx, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-types/table/src/index.d.ts
=> Table resizing api audit fixes

packages/@react-spectrum/actionbar/docs/ActionBar.mdx, packages/@react-spectrum/list/docs/ListView.mdx, packages/@react-spectrum/table/docs/TableView.mdx
=> Revert Actionbar docs release

packages/@adobe/spectrum-css-temp/components/tags/index.css, packages/@react-spectrum/tag/src/Tag.tsx, packages/@react-spectrum/tag/stories/TagGroup.stories.tsx
Check new stories under TagGroup: 'with avatar', and 'with avatar + onRemove'
RSP
=> TagGroup: Avatar support

packages/@react-spectrum/tabs/src/Tabs.tsx
Closes 
We were early returning in our check of tab dimensions changing
=> Fix Tabline resizing

packages/@react-aria/utils/src/scrollIntoView.ts, packages/@react-aria/virtualizer/src/ScrollView.tsx, packages/@react-aria/virtualizer/src/Virtualizer.tsx, packages/@react-spectrum/table/src/TableView.tsx
=> (DNM) Use scrollview scrollend to determine when it is safe to scrollIntoViewport 

packages/@react-spectrum/tag/src/TagGroup.tsx, packages/@react-spectrum/tag/test/TagGroup.test.js
=> TagGroup: fix to call onAction with no arguments

packages/@react-aria/select/src/HiddenSelect.tsx, packages/@react-aria/select/test/HiddenSelect.test.tsx
=> Fix invalid value for HiddenSelect fallback inputs

packages/dev/docs/pages/react-spectrum/theming.mdx
=> Update color schemes link in docs

packages/@react-aria/table/src/useTableColumnResize.ts, packages/@react-stately/table/src/useTableColumnResizeState.ts
=> Adding descriptions for the table resizing hooks

packages/@react-aria/autocomplete/src/useSearchAutocomplete.ts, packages/@react-spectrum/autocomplete/stories/SearchAutocomplete.stories.tsx, packages/@react-spectrum/autocomplete/test/SearchAutocomplete.test.js
=> Fix SearchAutocomplete to call onClear

packages/@adobe/spectrum-css-temp/components/checkbox/skin.css
Closes https://github.com/adobe/react-spectrum/issues/4029
=> Fix WHCM Checkbox from audit

packages/@react-aria/table/src/useTableColumnResize.ts, packages/@react-aria/table/stories/example-resizing.tsx, packages/@react-spectrum/table/src/Resizer.tsx
=> Adding type=range to resizer aria props

packages/@react-types/list/package.json
=> Remove unneeded dep in @react-types/list

packages/@react-spectrum/avatar/docs/Avatar.mdx
This enables the avatar docs in production and makes a couple minor wording changes.
=> Publish avatar docs

packages/@react-aria/tooltip/docs/useTooltipTrigger.mdx
Closes 
Will need to wait for the code changes to go out before releasing the docs
RSP
=> Revert tooltip close delay docs changes

packages/@react-spectrum/listbox/src/ListBoxOption.tsx, packages/@react-spectrum/listbox/test/ListBox.test.js
=> Add support for custom data attributes to ListBox Item

packages/@react-spectrum/listbox/src/ListBoxOption.tsx, packages/@react-spectrum/listbox/test/ListBox.test.js
=> Fix ListBox Item to avoid overriding item id with a custom id

packages/@react-aria/calendar/src/useCalendarCell.ts
Closes https://github.com/adobe/react-spectrum/issues/4135
=> Fix additional character appended to Calendar cells in various locales

packages/react-aria-components/docs/Select.mdx
=> Aria component Select disabled more obvious

packages/@react-spectrum/numberfield/test/NumberField.test.js
Closes 
Noticed a few things slipped by us when reviewing https://github.com/adobe/react-spectrum/pull/4161
=> Cleanup NumberField tests

packages/@internationalized/date/docs/ZonedDateTime.mdx
=> Update code sample to match description

packages/@react-spectrum/tag/chromatic/TagGroup.chromatic.tsx
Closes 
We are nearing release for these components, we should make sure we don't regress as we fix last minute bugs.
This PR is not meant to be exhaustive in chromatic stories. Just get us started
https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=501
=> Create chromatic stories for tags

packages/@adobe/spectrum-css-temp/components/tags/index.css
=> Fix missed classname

packages/@react-aria/tag/src/useTagGroup.ts
From https://github.com/adobe/react-spectrum/pull/4154#discussion_r1146731283
=> Update useTagGroup description

packages/@react-aria/tag/intl/en-US.json, packages/@react-aria/tag/src/useTag.ts, packages/@react-spectrum/tag/test/TagGroup.test.js
Closes #4278 
Check screen reader announcements for onRemove TagGroup story.
=> useTagGroup: add description and update 'remove' translation string

packages/@react-spectrum/table/src/DragPreview.tsx, packages/@react-spectrum/table/src/InsertionIndicator.tsx, packages/@react-spectrum/table/src/RootDropIndicator.tsx
=> TableView DnD: Add headers

packages/@react-aria/slider/docs/useSlider.mdx
Closes https://github.com/adobe/react-spectrum/issues/4256
=> Update Slider docs to match comment to table

packages/@react-stately/combobox/src/useComboBoxState.ts, packages/react-aria-components/docs/GridList.mdx, packages/react-aria-components/test/ComboBox.test.js
=> Fix combobox section filtering and Firefox gap issue

packages/@react-aria/color/src/useColorField.ts, packages/@react-aria/numberfield/src/useNumberField.ts
Closes https://github.com/adobe/react-spectrum/issues/3985
=> Fix our formatted field's validation

packages/react-aria-components/src/Table.tsx
=> Fix: Table Header does not support className Prop

examples/rsp-next-ts/package.json
=> Pin test NextJS app to 13.2.4 to avoid mjs issue

packages/@react-spectrum/table/src/TableView.tsx, packages/@react-spectrum/table/src/table.css
Fixes cases where drop target styles would potentially get overridden by default styles.
=> TableView DnD: improve css specificity

packages/@react-spectrum/button/stories/Button.stories.tsx, packages/@react-spectrum/button/stories/LogicButton.stories.tsx
=> Fix Button CSF story defaults

examples/rsp-cra-18/package.json, examples/rsp-next-ts/package.json, examples/rsp-webpack-4/package.json
=> Add caret to tag versions in test app package json for verdaccioPkgSize

packages/@react-aria/focus/src/FocusScope.tsx
=> Restore original getFocusableTreeWalker signature

packages/@adobe/react-spectrum/src/index.ts, packages/@react-spectrum/menu/src/MenuDialogTrigger.tsx, packages/@react-spectrum/menu/src/index.ts
=> Exporting MenuDialogTrigger props

packages/@react-aria/calendar/src/useCalendarGrid.ts, packages/react-aria-components/src/Calendar.tsx, packages/react-aria-components/test/Calendar.test.js
=> Add weekdayStyle prop to CalendarGrid

packages/@adobe/spectrum-css-temp/components/tags/skin.css, packages/@react-aria/tag/docs/useTagGroup.mdx
=> Fixing TagGroup remove button styles for hover and aria docs

packages/react-aria-components/src/Table.tsx, packages/react-aria-components/test/Table.test.js
=> Fix RAC Table cell render props

packages/react-aria-components/src/Collection.tsx
Fixes drag and drop examples in the docs.
=> Only insert new items into collections after receiving props

packages/react-aria-components/docs/Tabs.mdx
Originally from #4540, but then reverted in 600bff46f77558d68aff7ea2c002873653f0330d because it was merged before the docs got pulled out.
=> RAC Tabs docs changes

packages/@react-aria/ssr/src/SSRProvider.tsx
=> Fix SSRProvider return type

packages/@react-aria/ssr/src/SSRProvider.tsx
=> Fix icon build

examples/rsp-next-ts/pages/_app.tsx
Closes 
We'll revisit on monday.
=> Ignore TS error for the weekend so we get builds

packages/dev/docs/src/Layout.js
=> Remove edit button from a releases and blogs

packages/@react-spectrum/inlinealert/package.json, packages/@react-types/inlinealert/package.json
=> Unmark inlinealert package as private

packages/@react-aria/dialog/docs/useDialog.mdx
=> Fix typo in useDialog example

packages/react-aria-components/docs/Calendar.mdx, packages/react-aria-components/docs/RangeCalendar.mdx
=> Update RAC Calendar docs: change visibleDuration months from 2 to 3

packages/@react-spectrum/datepicker/src/Input.tsx, packages/@react-spectrum/datepicker/src/styles.css
=> Fix DateField lineheight

packages/@react-aria/button/src/index.ts, packages/react-aria/src/index.ts
Closes https://github.com/adobe/react-spectrum/discussions/4783
=> export `AriaButtonOptions` from `react-aria` and `@react-aria/button` packages

packages/@react-spectrum/menu/docs/Menu.mdx
=> fix link in menu docs

packages/@adobe/spectrum-css-temp/components/table/index.css, packages/@react-spectrum/table/src/TableViewBase.tsx, packages/@react-stately/table/src/useTreeGridState.ts
=> Fix click focus and transform overlap for expandable row chevron

.circleci/.npmrc, .npmrc
Not sure if we are still using this. Let's see if it breaks anything.
=> Remove old config

packages/react-aria-components/src/ListBox.tsx, packages/react-aria-components/test/ListBox.test.js
Closes https://github.com/adobe/react-spectrum/issues/4828
`yarn test packages/react-aria-components/test/ListBox.test.js`
=> Pass proper props into Section component when used in a ListBox

packages/@react-aria/tabs/src/useTabPanel.ts, packages/react-aria-components/test/Tabs.test.js
Closes https://github.com/adobe/react-spectrum/issues/4781
`yarn test pacakges/react-aria-components/test/Tabs.test.js`
=> Update TabPanel ID on tab click

.github/ISSUE_TEMPLATE/Bug_Report.yml, .github/ISSUE_TEMPLATE/Documentation.yml, .github/ISSUE_TEMPLATE/Feature_Request.yml
removes tags from being added when new issues are submitted
=> remove tags

packages/react-aria-components/docs/FileTrigger.mdx
=> Fix Typo in FileTrigger Docs

packages/@adobe/spectrum-css-temp/components/popover/index.css, packages/@react-spectrum/menu/src/ContextualHelpTrigger.tsx, packages/@react-spectrum/menu/src/Menu.tsx, packages/@react-spectrum/menu/src/MenuTrigger.tsx
=> Fix menu clipping corners

.circleci/comment.js
Adds a link to Storybook to the circleci comment.
=> Add a link to storybook

packages/react-aria-components/src/Modal.tsx, packages/react-aria-components/test/Dialog.ssr.test.js
Closes https://github.com/adobe/react-spectrum/issues/4921
Unit tests cover it
=> Fix RAC Modal in SSR

package.json
This should let Lerna publish the package, including nightlies.
=> add RAC Tailwind plugin to workspaces in package.json

packages/@react-spectrum/menu/docs/Menu.mdx, packages/@react-spectrum/menu/docs/MenuTrigger.mdx
=> Move ContextualHelpTrigger docs to Menu

packages/@react-spectrum/picker/stories/Picker.stories.tsx
Add a story for testing https://github.com/adobe/react-spectrum/pull/4949
RSP
=> Add aria labelling combination story for Picker

packages/react-aria-components/docs/GridList.mdx, packages/react-aria-components/docs/GridListAnatomy.svg, packages/react-aria-components/docs/ListBox.mdx, packages/react-aria-components/docs/ListBoxAnatomy.svg, packages/react-aria-components/docs/Table.mdx, packages/react-aria-components/docs/TableAnatomy.svg
Adds dnd and column resizing features to anatomy diagrams and updates labels to match names used by RAC (instead of hooks). Also updates feature list of components to include newer features we added.
=> Update Table, GridList, and ListBox anatomy diagrams

packages/@react-aria/overlays/docs/usePopover.mdx, packages/react-aria-components/docs/Popover.mdx
Closes https://github.com/adobe/react-spectrum/issues/5039
=> Fix popover tips in FF

packages/@react-spectrum/menu/docs/Menu.mdx
=> Bump Unavailable MenuItem badge to beta version

packages/tailwindcss-react-aria-components/README.md
=> add README.md to Tailwind plugin package

packages/@react-aria/gridlist/docs/useGridList.mdx, packages/@react-aria/listbox/docs/useListBox.mdx, packages/@react-spectrum/list/docs/ListView.mdx, packages/@react-spectrum/table/docs/TableView.mdx, packages/react-aria-components/docs/GridList.mdx, packages/react-aria-components/docs/ListBox.mdx
=> Update keyboard pattern links

packages/react-aria-components/docs/Breadcrumbs.mdx
=> Updating Breadcrumb Link copy from Link api update

packages/react-aria-components/docs/DatePicker.mdx, packages/react-aria-components/docs/DateRangePicker.mdx, packages/react-aria-components/docs/Group.mdx, packages/react-aria-components/docs/Tabs.mdx, packages/react-aria-components/docs/TimeField.mdx, packages/react-aria-components/docs/react-aria-components.mdx
Found in testing and a couple others.
=> Minor docs improvements

.circleci/config.yml, examples/rsp-next-ts-17/next.config.js, examples/rsp-next-ts/next.config.mjs
=> Fix NextJS verdaccio build

.circleci/comment.js
=> Fix build link for RSP+tailwind example

packages/@react-spectrum/menu/src/ContextualHelpTrigger.tsx
=> Fix Unavailable MenuItem props

packages/@react-spectrum/button/docs/Button.mdx, packages/@react-spectrum/button/src/Button.tsx, packages/@react-spectrum/button/stories/Button.stories.tsx, packages/@react-spectrum/button/test/Button.test.js, packages/@react-types/button/src/index.d.ts
=> Remove UNSAFE_ from isPending prop and enable docs

examples/rsp-cra-18/src/App.tsx, examples/rsp-cra-18/src/JournalEntries.tsx
=> Fix CRA 18 test app build

scripts/buildWebsite.js
Hopefully fixes media query compilation on older browsers that is breaking layout on small devices in Safari
=> Copy browserslist into prod website build

packages/react-aria-components/docs/SearchField.mdx
Closes #5249 
- n/a Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- n/a Filled out test instructions.
- n/a Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)
n/a
n/a
=> RAC: replace value with state when destructuring SearchFieldRenderProps

packages/@react-stately/slider/package.json, packages/@react-stately/slider/src/useSliderState.ts
Closes 
Noticed while poking around in some other code
=> Fix stately import from aria

packages/@react-aria/ssr/src/SSRProvider.tsx, packages/@react-aria/ssr/src/index.ts, packages/@react-aria/utils/src/useId.ts
=> Don't export canUseDom

packages/@adobe/spectrum-css-temp/components/menu/skin.css, packages/@react-spectrum/menu/src/ContextualHelpTrigger.tsx, packages/@react-spectrum/menu/src/Menu.tsx
Closes 
Found during testing session.
=> Fix iOS and Safari menu styles

packages/react-aria-components/src/Table.tsx, packages/react-aria-components/stories/index.stories.tsx
=> RAC: allow children in Table Column Reszier

packages/react-aria-components/docs/Breadcrumbs.mdx, packages/react-aria-components/docs/Calendar.mdx, packages/react-aria-components/docs/ComboBox.mdx, packages/react-aria-components/docs/DatePicker.mdx, packages/react-aria-components/docs/DateRangePicker.mdx, packages/react-aria-components/docs/Dialog.mdx, packages/react-aria-components/docs/GridList.mdx, packages/react-aria-components/docs/Group.mdx, packages/react-aria-components/docs/ListBox.mdx, packages/react-aria-components/docs/Menu.mdx, packages/react-aria-components/docs/Modal.mdx, packages/react-aria-components/docs/NumberField.mdx, packages/react-aria-components/docs/Popover.mdx, packages/react-aria-components/docs/ProgressBar.mdx, packages/react-aria-components/docs/Select.mdx, packages/react-aria-components/docs/Table.mdx, packages/react-aria-components/docs/Tabs.mdx, packages/react-aria-components/docs/TagGroup.mdx, packages/react-aria-components/docs/Toolbar.mdx
moved some things around, simplified popovers, etc.
=> A few more RAC docs CSS simplifications

packages/@react-aria/toolbar/docs/useToolbar.mdx, packages/@react-aria/toolbar/src/useToolbar.ts, packages/react-aria-components/docs/Toolbar.mdx, packages/react-aria-components/src/Toolbar.tsx
A few updates to the toolbar docs, expanding the content a little bit.
=> Toolbar docs updates

packages/react-aria-components/docs/ComboBox.mdx, packages/react-aria-components/docs/Group.mdx, packages/react-aria-components/docs/Modal.mdx, packages/react-aria-components/docs/Select.mdx, packages/react-aria-components/docs/Table.mdx
=> Docs css fixes

packages/@react-aria/actiongroup/src/useActionGroup.ts
=> Reduce dom checks for toolbar

packages/dev/docs/pages/react-aria/forms.mdx, packages/dev/docs/pages/react-spectrum/forms.mdx
Tested the examples locally and found some issues. I used the Zod API incorrectly, Next.js server actions must be async functions, and had the wrong type for remix actions.
=> Fix Next.js and Remix form examples

examples/rsp-cra-18/src/BodyContent.tsx
=> Fix CRA app build

packages/@react-spectrum/steplist/src/StepListContext.ts, packages/@react-spectrum/steplist/src/StepListItem.tsx, packages/@react-spectrum/steplist/test/StepList.test.tsx, tsconfig.json
=> TS Strict Mode steplist

packages/@internationalized/date/src/DateFormatter.ts, packages/@internationalized/date/src/manipulation.ts, packages/@internationalized/date/src/queries.ts, packages/@internationalized/date/src/string.ts, packages/@internationalized/number/src/NumberFormatter.ts, packages/@internationalized/number/src/NumberParser.ts, tsconfig.json
=> TS Strict internationalized

packages/@adobe/spectrum-css-temp/components/inputgroup/index.css, packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx, packages/@react-spectrum/combobox/src/ComboBox.tsx
Closes 
Discussed in testing session
=> Match alignment defaults

packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/interactions/test/usePress.test.js, packages/@react-spectrum/button/stories/Button.stories.tsx
=> Adjust usePress order of keyup events

packages/@react-stately/checkbox/src/useCheckboxGroupState.ts, tsconfig.json
=> TS Strict Checkbox State

packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@react-aria/progress/src/useProgressBar.ts, packages/@react-spectrum/button/src/Button.tsx, packages/@react-spectrum/progress/test/ProgressCircle.test.js
=> Wrap pending in button

packages/react-aria-components/src/ListBox.tsx, packages/react-aria-components/stories/index.stories.tsx, packages/react-aria-components/test/ListBox.test.js
Closes https://github.com/adobe/react-spectrum/issues/5602
=> Fix Aria label on sections

scripts/buildWebsite.js
Some missing dependencies for the new homepage. I think this is everything but I didn't run verdaccio locally.
=> Fix prod/verdaccio docs build

packages/react-aria-components/stories/Calendar.stories.tsx, packages/react-aria-components/stories/DateField.stories.tsx, packages/react-aria-components/stories/DatePicker.stories.tsx, packages/react-aria-components/stories/ListBox.stories.tsx, packages/react-aria-components/stories/Menu.stories.tsx, packages/react-aria-components/stories/Modal.stories.tsx, packages/react-aria-components/stories/NumberField.stories.tsx, packages/react-aria-components/stories/Select.stories.tsx, packages/react-aria-components/stories/Slider.stories.tsx, packages/react-aria-components/stories/TagGroup.stories.tsx, packages/react-aria-components/stories/TimeField.stories.tsx, packages/react-aria-components/stories/Tooltip.stories.tsx, packages/react-aria-components/stories/index.stories.tsx
related to https://github.com/adobe/react-spectrum/issues/5514
As per the [comment](https://github.com/adobe/react-spectrum/pull/5620#issuecomment-1874383392), each PR when merged, is resulting in conflicts. 
Therefore, I have consolidated all the current PRs.
PR List
- Closes https://github.com/adobe/react-spectrum/pull/5617
- Closes https://github.com/adobe/react-spectrum/pull/5616
- Closes https://github.com/adobe/react-spectrum/pull/5615
- Closes https://github.com/adobe/react-spectrum/pull/5586
- Closes https://github.com/adobe/react-spectrum/pull/5585
- Closes https://github.com/adobe/react-spectrum/pull/5577
- Closes https://github.com/adobe/react-spectrum/pull/5576
Confirm that nothing has changed by looking at the storybook.
=> refactor：isolate stories for various components 

packages/dev/docs/src/StarterKits.js
The starter cards didn't wrap and caused horizontal scrolling on mobile. 🙈
=> Fix starter links on mobile

packages/react-aria-components/src/index.ts
=> Expose FieldErrorContext from RAC

starters/docs/README.md
Would be good to mention this since CSS Nesting isn't fully supported yet.
=> Update RAC starter README to include how to support CSS Nesting in prouction

packages/@react-spectrum/datepicker/test/DateField.test.js, packages/@react-spectrum/datepicker/test/DatePicker.test.js, packages/@react-spectrum/datepicker/test/DateRangePicker.test.js
=> Fix tests so they don't fail in Febuary

packages/@react-types/color/src/index.d.ts, packages/@react-types/numberfield/src/index.d.ts
=> Move isWheelDisabled to aria props interface

packages/@react-spectrum/dnd/src/useDragAndDrop.ts, packages/react-aria-components/src/useDragAndDrop.tsx
=> Replace comma operator with semicolon for better readability

packages/@adobe/spectrum-css-temp/components/dropdown/index.css
=> Make sure the quiet picker conforms to the user set width

packages/react-aria-components/src/Menu.tsx, packages/react-aria-components/stories/Menu.stories.tsx, packages/react-aria-components/test/Menu.test.js
Closes https://github.com/adobe/react-spectrum/issues/5858
Adds support for using `SubmenuTrigger` as a child of `Section`.
Test new story
=> [RAC] Support for submenus within sections

packages/@adobe/react-spectrum/README.md, packages/@react-aria/dnd/docs/useDrag.mdx, packages/@react-aria/dnd/docs/useDraggableCollection.mdx, packages/@react-spectrum/listbox/src/ListBoxBase.tsx, packages/@react-stately/virtualizer/src/Virtualizer.ts, packages/@react-types/shared/src/collections.d.ts, packages/dev/docs/pages/react-aria/components.mdx, packages/dev/docs/pages/react-spectrum/index.mdx, packages/react-aria-components/docs/DatePicker.mdx, packages/react-aria-components/docs/DateRangePicker.mdx
=> Fix various typos

packages/@react-aria/test-utils/package.json, packages/@react-spectrum/test-utils/package.json, scripts/buildWebsite.js
=> Get rid of dev/utils from website prod build

packages/@react-stately/data/src/useTreeData.ts, packages/@react-stately/data/test/useTreeData.test.js
Closes #5948
Run test
Internal tool
=> fix useTreeData root move map

packages/react-aria-components/src/Tabs.tsx, packages/react-aria-components/test/Tabs.test.js
Closes https://github.com/adobe/react-spectrum/issues/5973
=> Add data-focused to Tabs

scripts/compareAPIs.js
=> Fix fork point on main build

packages/@react-aria/selection/src/useSelectableCollection.ts, packages/react-aria-components/test/ListBox.test.js
Closes https://github.com/adobe/react-spectrum/issues/2407
Test case should cover the desired interaction.
=> Fix collection Escape handling

starters/tailwind/package.json
=> Add override for types/mime to tailwind starter to fix build

packages/@adobe/spectrum-css-temp/components/illustratedmessage/index.css
Closes #6039 
[chromatic link
](https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=726)
all the changes in chromatic are to be expected with this update
=> Fix Illustrated Message styling

packages/@react-spectrum/calendar/test/RangeCalendar.test.js
=> Updating RangeCalendar touch swipe test names for clarity

packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@adobe/spectrum-css-temp/components/menu/skin.css, packages/@react-spectrum/menu/src/ContextualHelpTrigger.tsx, packages/@react-spectrum/menu/src/SubmenuTrigger.tsx
=> Fix submenu offset in docs

packages/@react-spectrum/menu/docs/Menu.mdx, packages/react-aria-components/docs/Menu.mdx
=> Remove pre-release badges for submenu

packages/@react-aria/overlays/src/Overlay.tsx, packages/@react-spectrum/overlays/src/Overlay.tsx
Closes 
pointed out in review
https://github.com/adobe/react-spectrum/pull/6141#discussion_r1581637661
=> unstable portal container for react-aria

packages/@react-spectrum/color/stories/ColorSwatchPicker.stories.tsx
=> Add story with multiple rows in ColorSwatchPicker

packages/@react-aria/dnd/docs/useClipboard.mdx, packages/@react-aria/dnd/docs/useDrag.mdx, packages/@react-aria/dnd/docs/useDrop.mdx
https://reactspectrum.blob.core.windows.net/reactspectrum/99f439b1e44dca54a96513b760628deb0f410899/docs/react-aria/useDrag.html#disabling-dragging
https://reactspectrum.blob.core.windows.net/reactspectrum/99f439b1e44dca54a96513b760628deb0f410899/docs/react-aria/useDrop.html#disabling-dropping
https://reactspectrum.blob.core.windows.net/reactspectrum/99f439b1e44dca54a96513b760628deb0f410899/docs/react-aria/useClipboard.html#disabling-copy-and-paste
=> Add docs for disabling useDrag, useDrop, and useClipboard

packages/@adobe/react-spectrum/src/index.ts, packages/react-aria/src/index.ts, packages/react-stately/src/index.ts
=> Add Submenu to monopackages

packages/dev/docs/pages/react-spectrum/testing.mdx
=> Temporarily remove mention of disabling virtualization in docs

packages/@adobe/react-spectrum/src/index.ts
=> add ContextualHelpTrigger to monopackage

packages/react-aria-components/src/Menu.tsx, packages/react-aria-components/test/Menu.test.js
Closes #5748
The added unit-test passes (previously it did not)
=> Ensure `Menu` component has the `data-rac` data attribute

packages/react-aria-components/src/Breadcrumbs.tsx, packages/react-aria-components/stories/Breadcrumbs.stories.tsx, packages/react-aria-components/test/Breadcrumbs.test.js
=> feat(RAC): support render props in Breadcrumbs

packages/@react-aria/toast/docs/useToast.mdx, packages/@react-aria/toast/src/useToast.ts
=> Update toast aria docs

scripts/verdaccio.sh, starters/tailwind/src/Breadcrumbs.tsx
=> Fix tailwind build on main

.github/workflows/pr-comment.yaml
=> fix github action

.github/actions/branch/action.yml, .github/actions/permissions/action.yml
=> Finish moving github actions to node 18

packages/@react-aria/tag/src/useTag.ts, packages/react-aria-components/src/TagGroup.tsx, packages/react-aria-components/stories/TagGroup.stories.tsx, packages/react-aria-components/test/TagGroup.test.js
Closes https://github.com/adobe/react-spectrum/discussions/6682
=> Fix taggroup disabled onremove

packages/@react-spectrum/table/src/TableViewLayout.ts
Fixes two issues found in testing:
1. TableView async loading, loading spinner is out of view instead of centered.
2. Buttons in hide header columns had clipped focus rings.
=> Fix TableLayout issues

packages/react-aria-components/docs/ColorField.mdx
=> Fix crash in controlled ColorField docs examples

packages/dev/docs/pages/react-spectrum/forms.mdx
=> Fix RSP form example

packages/@react-types/slider/src/index.d.ts
Closes https://github.com/adobe/react-spectrum/issues/6727
=> Remove unused prop on slider thumb

packages/@react-spectrum/tree/src/TreeView.tsx
=> fix(RSP): remove hover events from SpectrumTreeViewItemProps

packages/@react-aria/overlays/src/useOverlayPosition.ts
Test opening menu in RAC docs, as well as existing overlays.
=> fix(RAC): fix Menu flash when opening

packages/react-aria-components/src/GridList.tsx, packages/react-aria-components/src/TagGroup.tsx, packages/react-aria-components/stories/GridList.stories.tsx, packages/react-aria-components/test/GridList.test.js
Closes https://github.com/adobe/react-spectrum/issues/6757
=> Fix rendering TagGroup inside GridList

.circleci/config.yml, scripts/verdaccioPkgSize.js
Closes 
Testing the verdaccio build
=> Fix verdaccio build

packages/@react-spectrum/picker/intl/en-US.json, packages/@react-spectrum/picker/test/Picker.test.js
Closes https://github.com/adobe/react-spectrum/issues/4816
=> Update Picker placeholder to be shorter

packages/@react-spectrum/s2/src/TagGroup.tsx, packages/@react-spectrum/s2/stories/TagGroup.stories.tsx
=> TagGroup Actions

packages/@react-spectrum/s2/package.json
=> Remove private from s2 so we can get nightlies

.circleci/config.yml, .github/workflows/nightly.yaml
=> Make it so we can trigger nightly from github actions

package.json
=> Fix command for nightly publish

packages/@react-spectrum/s2/package.json
=> Add public publishConfig so nightly can successfully publish

packages/@react-spectrum/s2/src/Avatar.tsx, packages/@react-spectrum/s2/src/Meter.tsx, packages/@react-spectrum/s2/src/Tabs.tsx, packages/@react-spectrum/s2/src/TagGroup.tsx
=> types: fix S2 types/defaults

packages/@react-spectrum/s2/src/Breadcrumbs.tsx
=> update breadcrumbs to handle breadcrumb context overrides

.storybook-s2/docs/Migrating.jsx, packages/@react-spectrum/s2/stories/StyleMacro.stories.tsx, packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/badge.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/well.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/badge.test.ts, packages/dev/codemods/src/s1-to-s2/__tests__/well.test.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/changes.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/codemod.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/styleProps.ts
Thanks to @ktabors for noticing these were missing.
Check tests and new story for style macro well-equivalent.
=> feat: codemods for Badge and Well

packages/react-aria-components/src/Select.tsx, packages/react-aria-components/test/Select.test.js
=> fix: Select when label is numeric 0

.circleci/config.yml
=> Temporarily switch azure docker version to fix build deploy step

.circleci/config.yml
=> Fix nightly

packages/dev/parcel-transformer-s2-icon/package.json, yarn.lock
=> Fix icon builder dependencies

.circleci/config.yml
Updates CircleCI config to try replacing Azure CLI with AzCopy to enable multithreaded file copying and hopefully cut down build times.
=> Improve build times with azcopy

.circleci/comment.js, .circleci/config.yml
A wildcard in the middle of the path isn't support by AzCopy, so this fixes the verdaccio deploy step.
Check [this commit ](https://github.com/adobe/react-spectrum/commit/f8bd2de41195c77160c5c4e9368e190143afd991#comments) for working links
=> Fix verdaccio deploy step

packages/@react-spectrum/icon/docs/workflow-icons.mdx
Closes https://github.com/adobe/react-spectrum/issues/5433
=> Clarify Icons docs

packages/react-aria-components/docs/Button.mdx
Closes 
Unfortunately it was reproducing the Tech Preview as well. This just reverts us to the previous working and more verbose state.
=> Fix pending animation docs safari

packages/react-aria-components/src/Breadcrumbs.tsx
=> Fix RAC Breadcrumbs data selector docs

packages/@react-spectrum/s2/src/Card.tsx, packages/@react-spectrum/s2/src/Table.tsx
=> Audit fix: Remove hover props from s2

packages/@react-spectrum/s2/chromatic/Card.stories.tsx, packages/@react-spectrum/s2/chromatic/CardView.stories.tsx, packages/@react-spectrum/s2/chromatic/Table.stories.tsx
=> S2 chromatic table

packages/dev/docs/pages/releases/2024-09-30.mdx
=> add Accordion breaking changes to release notes

packages/@react-spectrum/s2/src/Meter.tsx
=> feat: support label position side in meter

packages/react-aria-components/src/GridList.tsx, packages/react-aria-components/src/Table.tsx, packages/react-aria-components/test/GridList.test.js, packages/react-aria-components/test/Table.test.js
Closes https://github.com/adobe/react-spectrum/issues/7075
=> fix: add Checkbox default slot to GridList and Table

packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/dialog.test.ts.snap, packages/dev/codemods/src/s1-to-s2/src/codemods/transforms.ts
Related to https://github.com/adobe/react-spectrum/pull/7219
=> fix: dialog codemod close function

packages/tailwindcss-react-aria-components/src/index.js, packages/tailwindcss-react-aria-components/src/index.test.js
Closes https://github.com/adobe/react-spectrum/issues/7224
=> feat: support pending in RAC tailwind plugin

packages/@react-spectrum/accordion/chromatic/Disclosure.stories.tsx
=> chore: Fix chromatic build dupe stories

scripts/extractStarter.mjs
=> chore: Get rid of UNSTABLE prefix for Disclosure on tailwind docs build

starters/tailwind/src/TagGroup.tsx, starters/tailwind/stories/TagGroup.stories.tsx
this allows the styles defined in isDisabled to be applied
Closes #7245
- https://github.com/adobe/react-spectrum/issues/7245
View the TagGroup story for the tailwind starter project
refs #7246
=> fix(tailwind): correct disabled tag styles

packages/@adobe/react-spectrum/package.json, packages/@adobe/react-spectrum/src/index.ts, packages/react-aria/package.json, packages/react-aria/src/index.ts, yarn.lock
=> chore: add accordion to monopackage

packages/@react-aria/disclosure/docs/useDisclosure.mdx, packages/@react-spectrum/accordion/docs/Accordion.mdx, packages/react-aria-components/docs/Disclosure.mdx, packages/react-aria-components/docs/DisclosureGroup.mdx
=> docs: update accordion and disclosure group docs

packages/@react-spectrum/s2/src/ActionButton.tsx, packages/@react-spectrum/s2/src/DropZone.tsx, packages/@react-spectrum/s2/src/Radio.tsx, packages/@react-spectrum/s2/src/StatusLight.tsx
bug fixes:
- DropZone: no horizontal padding between dropzone and replace message on mobile/ipad
- RadioGroup: emphasized radio's flash white when selected
- ActionButton: fix truncating
- I actually fixed this before but it somehow got reverted or went missing? idk
-  StatusLight svg gets caught off on iOS
Not a bug but design updates:
- Add sizes S, M, L to DropZone
=> fix: miscellaneous s2 bug fixes

packages/dev/docs/src/BasePage.js, packages/dev/docs/src/Layout.js
Fixes indexing issues seen in search console
Closes
=> chore: Add rel canonical to documentation pages

packages/@react-spectrum/datepicker/test/DatePicker.test.js
Closes 
Noticed Main was failing today
=> fix: Make us resilient to time changes in datepicker tests

packages/react-aria-components/docs/DisclosureGroupAnatomy.svg
=> docs: fix disclosure group anatomy svg from clipping on mobile

packages/@react-spectrum/s2/chromatic/ToggleButton.stories.tsx, packages/@react-spectrum/s2/src/ToggleButton.tsx, packages/@react-spectrum/s2/stories/ToggleButton.stories.tsx
=> fix: ensure text truncates in s2 toggle button

packages/@react-spectrum/s2/package.json, packages/@react-spectrum/s2/src/Meter.tsx, packages/@react-spectrum/s2/style/spectrum-theme.ts, packages/dev/parcel-transformer-s2-icon/package.json, yarn.lock
=> chore: update s2 tokens

packages/@react-aria/progress/docs/useProgressBar.mdx, packages/react-aria-components/docs/ProgressBar.mdx
=> docs: fix typo on progress bar page

.storybook-s2/docs/Migrating.jsx, packages/@react-aria/accordion/src/useAccordion.ts, packages/@react-aria/disclosure/package.json, packages/@react-aria/disclosure/src/useDisclosure.ts, packages/@react-spectrum/accordion/src/Accordion.tsx, packages/@react-stately/disclosure/package.json, packages/dev/docs/pages/react-aria/components.mdx, packages/react-aria-components/docs/Disclosure.mdx, packages/react-aria-components/docs/DisclosureGroup.mdx, packages/react-aria-components/package.json, packages/react-aria-components/src/Disclosure.tsx, packages/react-aria/package.json, packages/react-aria/src/index.ts, packages/react-stately/package.json, packages/react-stately/src/index.ts, yarn.lock
=> fix: Accordion release audit

packages/@react-spectrum/s2/stories/CustomDialog.stories.tsx, packages/@react-spectrum/s2/stories/Popover.stories.tsx
=> chore: Update custom dialog examples to be more generic

packages/@react-spectrum/accordion/docs/Accordion.mdx, packages/@react-spectrum/accordion/docs/Disclosure.mdx, packages/@react-spectrum/color/docs/ColorArea.mdx, packages/@react-spectrum/color/docs/ColorField.mdx, packages/@react-spectrum/color/docs/ColorPicker.mdx, packages/@react-spectrum/color/docs/ColorSlider.mdx, packages/@react-spectrum/color/docs/ColorSwatch.mdx, packages/@react-spectrum/color/docs/ColorSwatchPicker.mdx, packages/@react-spectrum/color/docs/ColorWheel.mdx, packages/@react-spectrum/dropzone/docs/DropZone.mdx, packages/@react-spectrum/filetrigger/docs/FileTrigger.mdx, packages/@react-spectrum/icon/docs/custom-icons.mdx
=> chore: Update "version added" for remaining RSP components

packages/dev/docs/pages/releases/2024-11-20.mdx
=> docs: fix release notes typo

packages/react-aria-components/docs/ComboBox.mdx
Closes https://github.com/adobe/react-spectrum/issues/7387
=> fix: Combobox docs example

packages/react-aria-components/docs/Calendar.mdx, packages/react-aria-components/docs/advanced.mdx
Closes #7432 
View documentation preview
N/A
=> docs: don't use hooks conditionally in docs

packages/@react-spectrum/s2/chromatic/ColorWheel.stories.tsx, packages/@react-spectrum/s2/chromatic/Combobox.stories.tsx, packages/@react-spectrum/s2/chromatic/ContextualHelp.stories.tsx, packages/@react-spectrum/s2/chromatic/Dialog.stories.tsx, packages/@react-spectrum/s2/chromatic/Disclosure.stories.tsx, packages/@react-spectrum/s2/chromatic/DropZone.stories.tsx, packages/@react-spectrum/s2/chromatic/Forms.stories.tsx, packages/@react-spectrum/s2/chromatic/IllustratedMessage.stories.tsx, packages/@react-spectrum/s2/chromatic/InlineAlert.stories.tsx, packages/@react-spectrum/s2/chromatic/Link.tsx, packages/@react-spectrum/s2/chromatic/Menu.stories.tsx, packages/@react-spectrum/s2/chromatic/Meter.stories.tsx, packages/@react-spectrum/s2/chromatic/NumberField.stories.tsx, packages/@react-spectrum/s2/chromatic/Picker.stories.tsx, packages/@react-spectrum/s2/chromatic/RadioGroup.stories.tsx, packages/@react-spectrum/s2/chromatic/RangeSlider.stories.tsx, packages/@react-spectrum/s2/chromatic/SearchField.stories.tsx, packages/@react-spectrum/s2/chromatic/SegmentedControl.stories.tsx, packages/@react-spectrum/s2/chromatic/Slider.stories.tsx, packages/@react-spectrum/s2/chromatic/StatusLight.stories.tsx, packages/@react-spectrum/s2/chromatic/Switch.stories.tsx, packages/@react-spectrum/s2/chromatic/Tabs.stories.tsx, packages/@react-spectrum/s2/chromatic/TextField.stories.tsx, packages/@react-spectrum/s2/chromatic/ToggleButton.stories.tsx, packages/@react-spectrum/s2/chromatic/ToggleButtonGroup.stories.tsx, packages/@react-spectrum/s2/chromatic/Tooltip.stories.tsx, packages/@react-spectrum/s2/stories/ComboBox.stories.tsx, packages/@react-spectrum/s2/stories/Dialog.stories.tsx, packages/@react-spectrum/s2/stories/Picker.stories.tsx, packages/@react-spectrum/s2/stories/Tooltip.stories.tsx
Closes 
Noticed that chromatic was broken after the fast refresh pr
=> fix: chromatic s2 stories

.storybook-s2/docs/Illustrations.jsx
=> docs(S2): fix copied path of gradient illustrations

scripts/buildPublishedAPI.js, scripts/buildWebsite.js
Closes 
Forgot to copy yarn plugins into our temp directories
=> fix: build website

starters/tailwind/src/Menu.tsx
Closes #7507
Run Tailwind starter storybook and test Menu with Sections story.
=> fix(docs): MenuSection in RAC Tailwind starter

packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@react-spectrum/menu/src/MenuItem.tsx
Closes https://github.com/adobe/react-spectrum/issues/7571
=> fix: explicitly set content-box on unavailable icon in Menu

packages/@react-spectrum/s2/src/CloseButton.tsx
=> fix(s2): Improve high contrast mode in CloseButton

packages/react-aria-components/src/Calendar.tsx
=> chore(RAC): remove internal contexts from RAC Calendar

packages/@react-spectrum/dnd/docs/dnd.mdx
=> fix: typo in dnd docs

package.json, packages/@react-aria/collections/package.json, packages/@react-aria/dnd/test/dnd.test.js, packages/@react-aria/landmark/package.json, packages/@react-aria/meter/package.json, packages/@react-aria/switch/package.json, packages/@react-aria/test-utils/package.json, packages/@react-spectrum/list/test/ListView.test.js, packages/@react-spectrum/table/test/TreeGridTable.test.tsx, packages/@react-spectrum/test-utils/package.json, packages/@react-spectrum/toast/package.json, packages/@react-stately/layout/package.json, packages/@react-stately/toast/package.json, packages/react-aria-components/package.json, yarn.lock
Closes https://github.com/adobe/react-spectrum/issues/7583, closes https://github.com/adobe/react-spectrum/issues/7644
also updates our user event version, this makes it a little easier to tell when a click event is a virtual pointerType
=> chore: update dependencies

packages/@react-aria/gridlist/src/useGridList.ts, packages/react-aria-components/test/GridList.test.js, packages/react-aria-components/test/ListBox.test.js
Closes https://github.com/adobe/react-spectrum/issues/7105
=> feat: GridList autoFocus

package.json, yarn.lock
Closes 
Chromatic is yelling at us to update :)
=> chore: update chromatic dependency

CODE_OF_CONDUCT.md, CONTRIBUTING.md
=> chore: updating the code of conduct to newer version

packages/@react-spectrum/s2/src/Badge.tsx
Closes https://github.com/adobe/react-spectrum/issues/7696
=> fix: S2 Badge context

packages/@react-spectrum/s2/src/SegmentedControl.tsx, packages/@react-spectrum/s2/src/Skeleton.tsx, packages/@react-spectrum/s2/src/Tooltip.tsx
=> fix(s2): SSR fixes

packages/@react-spectrum/s2/src/TableView.tsx
Noticed while working on #7785 that hovering over the column headers in an S2 TableView caused the collection to update. That's because `TableColumn` was consuming a context that was set when the `TableHeader` was hovered. We can avoid this by showing/hiding the column dividers in CSS instead of via context.
=> fix: Avoid triggering collection updates when hovering over S2 TableView headers

starters/tailwind/src/Autocomplete.tsx, starters/tailwind/src/Menu.tsx, starters/tailwind/stories/Autocomplete.stories.tsx
=> docs(Autocomplete): Add Autocomplete to RAC Tailwind starter kit

packages/@react-spectrum/s2/src/Picker.tsx
Same fix as #7492 but applied to Picker as well as Menu.
=> fix: Fix S2 Picker press scaling

packages/@react-aria/autocomplete/docs/useAutocomplete.mdx, packages/@react-aria/autocomplete/src/index.ts, packages/@react-aria/autocomplete/src/useAutocomplete.ts, packages/@react-stately/autocomplete/docs/useAutocompleteState.mdx, packages/@react-stately/autocomplete/src/index.ts, packages/@react-stately/autocomplete/src/useAutocompleteState.ts, packages/react-aria-components/src/Autocomplete.tsx
=> docs: add initial Autocomplete hook docs

packages/react-aria-components/docs/Autocomplete.mdx
=> fix: autocomplete starter

packages/@react-spectrum/s2/stories/TableView.stories.tsx
=> chore: make table resizing less choppy in storybook

packages/react-aria-components/docs/examples/command-palette.mdx
=> docs(RAC): improve command palette example mobile experience

packages/@react-aria/dnd/src/useClipboard.ts, packages/@react-aria/dnd/test/useClipboard.test.js
=> chore(useClipboard): rename "type" to "action" in getItems details

packages/@react-aria/textfield/src/useTextField.ts, packages/@react-spectrum/s2/src/Menu.tsx, packages/@react-spectrum/s2/src/StatusLight.tsx, packages/@react-stately/data/docs/useTreeData.mdx, packages/@react-stately/data/src/useTreeData.ts, packages/@react-stately/data/test/useTreeData.test.js, packages/@react-types/searchfield/src/index.d.ts, packages/@react-types/shared/src/dom.d.ts, packages/@react-types/textfield/src/index.d.ts, packages/react-aria-components/src/Table.tsx, packages/react-aria-components/src/Tree.tsx, packages/react-aria-components/src/index.ts, packages/react-aria-components/stories/Tree.stories.tsx
=> chore: Api audit

packages/@react-aria/toast/src/useToast.ts, packages/react-aria-components/package.json, packages/react-aria-components/src/Toast.tsx, yarn.lock
=> fix: make Toasts announce when rendered in NVDA

packages/@adobe/spectrum-css-temp/components/checkbox/index.css, packages/@adobe/spectrum-css-temp/components/toggle/index.css
=> fix: Double click event on rsp toggling components

packages/@react-aria/autocomplete/src/useAutocomplete.ts, packages/@react-stately/list/src/useListState.ts, packages/react-aria-components/src/Autocomplete.tsx, packages/react-aria-components/src/ListBox.tsx, packages/react-aria-components/src/Menu.tsx
=> chore: Rename filterFn in useAutocomplete to filter

packages/@react-aria/datepicker/src/useDateSegment.ts, packages/@react-spectrum/datepicker/chromatic/DateField.stories.tsx
Closes 
chromatic: https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=916
=> fix: correctly render dates in hebrew calendar

packages/@react-aria/landmark/src/index.ts, packages/@react-aria/landmark/src/useLandmark.ts, packages/@react-aria/landmark/stories/Landmark.stories.tsx, packages/@react-aria/landmark/test/useLandmark.test.tsx, packages/@react-spectrum/toast/stories/Toast.stories.tsx, packages/react-aria/src/index.ts
=> chore: make useLandmark controller unstable

packages/@react-stately/layout/src/GridLayout.ts, packages/@react-stately/layout/src/ListLayout.ts, packages/@react-stately/layout/src/TableLayout.ts
https://github.com/adobe/react-spectrum/pull/7886#discussion_r1985494793
=> fix: Dnd gap copy paste error

packages/@react-stately/toast/src/useToastState.ts, packages/@react-stately/toast/test/useToastState.test.js
Closes https://github.com/adobe/react-spectrum/issues/7908
=> fix(toast): pass wrapUpdate through useToastState

packages/react-aria-components/src/index.ts
=> fix: re-export QueuedToast

packages/react-aria-components/src/ColorWheel.tsx
=> fix: ColorWheel track click

packages/@react-spectrum/s2/intl/ar-AE.json
=> chore: Add missing intl string to fix chromatic build

packages/react-aria/src/index.ts
Closes https://github.com/adobe/react-spectrum/issues/8126
=> chore: add portal provider to react-aria monopackage

packages/@react-spectrum/color/src/ColorSlider.tsx
=> fix ColorSlider className

packages/@react-spectrum/s2/src/Modal.tsx
=> fix(s2): Update dialog sizes

packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@adobe/spectrum-css-temp/components/tags/index.css
Closes https://github.com/adobe/react-spectrum/pull/8194#issuecomment-2868411110
=> fix: Make tag remove focus ring a circle

packages/@react-spectrum/s2/src/ActionButton.tsx, packages/@react-spectrum/s2/src/Button.tsx, packages/@react-spectrum/s2/src/TagGroup.tsx
accent and negative step down on hover in dark mode instead of stepping up
=> fix(s2): Fix exceptions to baseColor in Button and Tag backgrounds

packages/@react-aria/test-utils/src/table.ts, packages/@react-spectrum/s2/src/TableView.tsx, packages/@react-spectrum/s2/stories/TableView.stories.tsx, packages/@react-spectrum/s2/test/TableView.test.tsx
=> chore: remove unstable from column menus

.storybook-s2/docs/Migrating.jsx, packages/@react-spectrum/s2/chromatic/Picker.stories.tsx, packages/@react-spectrum/s2/src/Picker.tsx, packages/@react-spectrum/s2/stories/Picker.stories.tsx, packages/@react-spectrum/s2/test/Picker.test.tsx, packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/picker.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/picker.test.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/components/Picker/transform.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/shared/transforms.ts
=> chore: update S2 picker "isLoading" API to "loadingState" for consistency  

packages/@react-aria/focus/src/FocusScope.tsx
Closes 
https://github.com/adobe/react-spectrum/pull/7764#discussion_r2092928082
=> fix: add missing backwards compatibility for types

packages/@react-aria/dnd/src/DragManager.ts, packages/@react-aria/dnd/src/useDrop.ts, packages/@react-aria/dnd/src/useDropIndicator.ts, packages/@react-aria/dnd/src/useDroppableCollection.ts, packages/@react-aria/dnd/src/useDroppableItem.ts, packages/@react-stately/data/test/useTreeData.test.js, packages/@react-stately/dnd/src/useDroppableCollectionState.ts, packages/@react-types/shared/src/dnd.d.ts, packages/react-aria-components/example/index.css, packages/react-aria-components/src/Tree.tsx, packages/react-aria-components/src/useDragAndDrop.tsx, packages/react-aria-components/stories/Tree.stories.tsx
This reverts commit b7f8ed1a9a311d89719b1a746b0a58204841b21a.
Closes
=> feat(RAC): Revert "fix: Revert "feat(RAC): Tree drag and drop (#7692)" (#8243)"

packages/react-aria-components/src/Select.tsx, packages/react-aria-components/test/Select.test.js
=> fix(RAC): Select autoFocus

packages/react-aria-components/docs/ComboBox.mdx, packages/react-aria-components/docs/Menu.mdx, packages/react-aria-components/docs/Select.mdx
Closes https://github.com/adobe/react-spectrum/issues/6873, https://github.com/adobe/react-spectrum/issues/8008
=> docs: fix broken links and styling

packages/@internationalized/date/src/string.ts, packages/@internationalized/date/tests/string.test.js
Closes https://github.com/adobe/react-spectrum/issues/8079
=> fix: invalid date parsing

scripts/buildPublishedAPI.js
=> fix: tsdiffer

packages/@react-spectrum/s2/src/Tabs.tsx
Closes https://github.com/adobe/react-spectrum/issues/8308
=> fix: update bar bellow the tab when text changes

packages/@react-stately/virtualizer/src/Size.ts
Closes https://github.com/adobe/react-spectrum/issues/8332
React won't replace style properties in an object if the value is invalid. https://codesandbox.io/p/sandbox/387hfk note that the background color IS replaced, but the height is not in this codesandbox. That's what was happening in our ScrollView https://github.com/adobe/react-spectrum/blob/9786f69a1cb6b9a9158fcef4dbb9881faefac016/packages/%40react-aria/virtualizer/src/ScrollView.tsx#L257 when content size had a negative value.
I've made this hopefully impossible by making sure that a Size is always valid >= 0
```
export function App() {
const { contains } = useFilter({ sensitivity: 'base' });
// Create a large dataset for virtualized autocomplete
const items = Array.from({ length: 2000 }, (_, i) => ({
id: i,
name: `Option ${i}`, …
```
=> fix: Height adjustment for Virtualized layout

packages/react-aria-components/docs/Tree.mdx
=> docs: add version badge to tree dnd docs + fix render props example

packages/@react-spectrum/autocomplete/test/SearchAutocomplete.test.js, packages/@react-stately/layout/src/ListLayout.ts, packages/@react-stately/tree/src/useTreeState.ts, packages/react-aria-components/src/Tree.tsx, packages/react-aria-components/src/index.ts, packages/react-aria-components/stories/Tree.stories.tsx, packages/react-aria-components/test/Tree.test.tsx
This reverts commit 6bbacb80ae53e8565fe6ac8d31003f5b57e7bd7d.
Will need to test ListLayout outside of tree some more before this goes in
Closes
=> chore: Revert "feat: Tree multiple level loading support (#8299)"

packages/@react-aria/selection/src/ListKeyboardDelegate.ts, packages/react-aria-components/example/index.css, packages/react-aria-components/src/Tree.tsx, packages/react-aria-components/stories/Tree.stories.tsx, packages/react-aria-components/test/Tree.test.tsx
This reverts commit 2aa18518f267f6fafd9225d8bc867db2d2c9a747.
Closes
=> chore: Revert "Revert "feat: focus loading indicator in rac tree (#8270)" (#8336)"

packages/@internationalized/number/src/NumberParser.ts, packages/@react-aria/numberfield/src/useNumberField.ts, packages/@react-aria/spinbutton/src/useSpinButton.ts
Closes https://github.com/adobe/react-spectrum/issues/6678
RSP
=> fix: support full width characters in Numberfield

packages/react-aria-components/docs/examples/account-menu.mdx
Closes https://github.com/adobe/react-spectrum/issues/8412
RSP
=> chore: Remove mentions of Dialog from Account Menu doc example

packages/@react-spectrum/s2/stories/TableView.stories.tsx
Fixed the generated code samples for most of the stories in treeview so that they're actually useful. I only did it for some stories because you can use the other stories to figure out how to write them
Decided to write all the "show code" stuff at the bottom of the file so that it doesn't clutter the rest of it
=> docs(s2): fix generated code in storybook docs for tableview

packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@react-spectrum/s2/src/Menu.tsx
Closes https://github.com/adobe/react-spectrum/issues/8343
=> fix: set text alignment for keyboard component

packages/@react-spectrum/s2/src/Switch.tsx
Closes 
https://react-spectrum.adobe.com/s2/index.html?path=/docs/switch--docs (ar-AE)
=> fix(s2): Fix Switch in RTL locales

packages/@react-aria/textfield/src/useTextField.ts
This reverts commit 769d725534a64ae741ec9a10e9e27d23a8e24aab.
Closes
=> chore: Revert "feat: Prevent onChange from firing in TextFields while user is typing via IME (#8519)"

.storybook-s2/docs/Migrating.jsx, packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/datefield.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/datepicker.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/daterangepicker.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/timefield.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/datefield.test.ts, packages/dev/codemods/src/s1-to-s2/__tests__/datepicker.test.ts, packages/dev/codemods/src/s1-to-s2/__tests__/daterangepicker.test.ts, packages/dev/codemods/src/s1-to-s2/__tests__/timefield.test.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/components/DateField/transform.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/components/DatePicker/transform.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/components/DateRangePicker/transform.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/components/TimeField/transform.ts
=> chore: S2 Date migrations

.circleci/config.yml
Closes 
Our vdocs job fails a lot intermittently, add a single retry so that hopefully we get a few more successful builds while we are working on fixing the flakiness
=> fix: Circle retry job

scripts/compareAPIs.js
Closes 
The white text on green was hard to read, so darkened the green background for contrast
=> fix: tsdiff more readable

.github/labeler.yml, .github/workflows/labeler.yml
Closes 
https://github.com/actions/labeler
Can't verify until it's on main :-/ I don't know if it'll remove the label if the translations are reverted
=> chore: needs translation auto labeler

packages/@react-spectrum/combobox/docs/ComboBox.mdx, packages/@react-spectrum/list/docs/ListView.mdx, packages/@react-spectrum/listbox/docs/ListBox.mdx, packages/@react-spectrum/menu/docs/MenuTrigger.mdx, packages/@react-spectrum/picker/docs/Picker.mdx, packages/@react-spectrum/table/docs/TableView.mdx, packages/@react-spectrum/tabs/docs/Tabs.mdx, packages/@react-spectrum/tree/docs/TreeView.mdx, packages/dev/docs/pages/react-aria/testing.mdx, packages/dev/docs/pages/react-spectrum/testing.mdx, packages/react-aria-components/docs/ComboBox.mdx, packages/react-aria-components/docs/GridList.mdx, packages/react-aria-components/docs/ListBox.mdx, packages/react-aria-components/docs/Menu.mdx, packages/react-aria-components/docs/Select.mdx, packages/react-aria-components/docs/Table.mdx, packages/react-aria-components/docs/Tabs.mdx, packages/react-aria-components/docs/Tree.mdx
=> docs: move test utils badge to beta

package.json, yarn.lock
=> chore: upgrade chromatic cli

packages/dev/s2-docs/pages/s2/ActionBar.mdx, packages/dev/s2-docs/pages/s2/ActionButton.mdx
=> chore: add docs for actionbutton pending

packages/@react-stately/select/src/useSelectState.ts
Closes 
https://github.com/adobe/react-spectrum/pull/8734#discussion_r2355620874
=> fix: Select value cannot be forcefully cleared
