adobe/react-spectrum

packages/@adobe/spectrum-css-temp/components/accordion/skin.css
Closes 
Found here https://www.chromatic.com/test?appId=5f0dd5ad2b5fc10022a2e320&id=6421ce82dacf8a735dc70f65
The CSS in this file did not reflect the actual dom structure and since the color should always be the same as the text we can make the previous specificity winner the default and use inherit instead of specifying colors directly for the chevron
=> fix chromatic accordion

packages/@react-spectrum/dialog/chromatic/Dialog.chromatic.tsx, packages/@react-spectrum/dialog/stories/DialogTrigger.stories.tsx
Discovered in testing. The default containerPadding set by the story was 0 which made it look like we broke the container padding calculations. Older builds of the storybook didn't have controls setup which made this change in behavior confusing. 
Test the DialogTrigger stories and verify that containerPadding is respected
RSP
=> Updating stories for containerPadding

packages/@react-aria/tag/src/useTag.ts, packages/@react-spectrum/tag/src/Tag.tsx, packages/@react-types/tag/src/index.d.ts
=> useTag: remove isFocused prop

Makefile, packages/@react-aria/interactions/package.json, packages/@react-aria/interactions/src/useFocusVisible.ts, packages/@react-aria/ssr/src/SSRProvider.tsx, packages/@react-spectrum/combobox/test/ComboBox.test.js, packages/react-aria-components/package.json, packages/react-aria-components/src/Collection.tsx
This fixes some issues I found while testing React Aria Components with Next.js:
* Adds a Node ESM build to the package like our others
* Skips rendering a portal in collection components on the server and during hydration because portals aren't supported by React in SSR
* Only returns true from `useIsSSR` during initial hydration. Previously, it would return true when any component first mounted within an SSRProvider, even after hydration. This was breaking overlay positioning, and caused the error in combobox with ariaHideOutside where the popoverRef wasn't defined yet due to an SSR check on mount. Fixes #3293. Fixes #3787.
* Makes `useInteractionModality` check `useIsSSR` and return `null` if it is on the server or hydrating. This was causing a hydration warning to sometimes appear in …
=> Fix SSR issues with React Aria Components

packages/@react-aria/dnd/src/useDraggableItem.ts, packages/@react-aria/dnd/src/useDropIndicator.ts, packages/@react-aria/grid/src/useGridSelectionAnnouncement.ts, packages/@react-aria/table/src/useTable.ts, packages/@react-spectrum/table/stories/TableDnDExamples.tsx, packages/@react-spectrum/table/stories/TableDnDUtilExamples.tsx, packages/@react-spectrum/table/test/TableDnd.test.js, packages/@react-stately/table/src/TableCollection.ts, packages/@react-types/shared/src/collections.d.ts, packages/react-aria-components/src/Table.tsx
When a `textValue` is not explicitly provided to the `<Row>` component, this generates it based on the row header columns within that row. We already had this for our custom selection announcements, but not in drag and drop, so this moves the `getRowText` function that we had in `useTable` into `TableCollection` in order to allow it to be reused. A new `getTextValue` method is added to the `Collection` interface to allow collections to generate a text value for their nodes dynamically if they need to.
For now there are two implementations: one in the old TableCollection in stately, and the other in react-aria-components. Eventually we'll consolidate this when moving to the new collections in spectrum.
=> Generate table row textValue from row header cells by default

packages/@react-spectrum/table/package.json, packages/@react-spectrum/table/src/TableView.tsx, packages/@react-stately/table/src/useTableState.ts, packages/@react-types/table/src/index.d.ts
- moves `SpectrumTableProps` back to @react-types to remain backwards-compatible. Adds @deprecated.
- fixes dependencies on types
=> TableView DnD: fix types and dependencies

packages/@react-aria/focus/src/useHasTabbableChild.ts, packages/@react-aria/table/package.json, packages/@react-aria/table/src/useTableColumnResize.ts, packages/@react-aria/table/stories/example-docs.tsx, packages/@react-spectrum/table/src/Resizer.tsx
Closes 
From audit
Test TableView resizing and the useTable "docs example" stories. Resizing should work as expected, the input should still be visually hidden, and focusing/blurring the input should still enter/exit resize mode
RSP
=> Automatically providing visually hidden styles to the resizer input

packages/@react-aria/overlays/src/calculatePosition.ts, packages/@react-aria/overlays/src/useOverlayPosition.ts, packages/@react-aria/overlays/test/calculatePosition.test.js, packages/@react-aria/overlays/test/useOverlayPosition.test.js, packages/@react-spectrum/overlays/src/Popover.tsx, packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx
Closes 
From audit
Overlay positioning should still work as expected
RSP
=> Updating prop names for overlay position options

packages/@react-stately/combobox/src/useComboBoxState.ts
Closes 
1. Go to the "static items" combobox story. 
2. Click on the input and type 'a'
3. Backspace so 'a' is deleted. Visible focus shouldn't appear in the menu still
4. Press arrow down/up. Visible focus should appear on the first/last item
RSP
=> Fix combobox visible focus styling when opening the menu via keyboard

packages/@react-aria/autocomplete/src/index.ts, packages/@react-aria/autocomplete/src/useSearchAutocomplete.ts, packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx, packages/@react-types/autocomplete/src/index.d.ts
- removes `value` and `defaultValue` from prop types, since we use `inputValue` and `defaultInputValue` instead (found by @ktabors)
- fixes `SearchAutocompleteProps` to extend `SearchFieldProps` instead of `AriaSearchFieldProps`. Had to move `AriaSearchAutocompleteProps` to `@react-types` to avoid a circular dependency.
I can break this out if we only want to get bullet one in now.
=> SearchAutocomplete: fix types

packages/@react-spectrum/datepicker/stories/DateRangePicker.stories.tsx, packages/@react-spectrum/datepicker/test/DatePicker.test.js, packages/@react-spectrum/datepicker/test/DateRangePicker.test.js, packages/@react-stately/datepicker/src/useDatePickerState.ts, packages/@react-stately/datepicker/src/useDateRangePickerState.ts
Fixes #3187.
This fixes an issue where setting the controlled value of a `DatePicker` or `DateRangePicker` to null with `granularity="minute"` did not clear the calendar or time fields within the popover. This was because we never reset our state for partial selection (e.g. only date or time) when we have a complete value entered. The fix is to reset those when we emit onChange.
=> Fix clearing date picker by setting value to null

packages/react-aria-components/docs/react-aria-components.mdx, packages/react-aria-components/src/index.ts
This adds an overview page for React Aria Components, which describes what the library is, its status, and general info about how to install and use it. Eventually most of this will move to the general React Aria getting started page and other concepts pages, but while we are in alpha, we'll keep it on a separate page.
Also re-exported `SSRProvider` from `react-aria-components` since that will be needed for use in SSR environments.
=> Add overview page for React Aria Components

.circleci/comment.js, .circleci/config.yml, examples/rac-tailwind/package.json, examples/rac-tailwind/src/App.js, examples/rac-tailwind/src/index.html, examples/rac-tailwind/src/style.css, scripts/verdaccio.sh
This builds the React Aria Components + Tailwind example in CI on main as part of the verdaccio build. This way we can get a link to a build of that app. I'm thinking about potentially linking to such a build from the docs as an example temporarily as well but not sure.
=> Build RAC Tailwind example in Verdaccio

packages/react-aria-components/docs/react-aria-components.mdx
The link was to `TooltipTrigger.html`, which doesn't exist.
=> Fix Tooltip link on react-aria-components docs

packages/@react-spectrum/datepicker/docs/DateField.mdx
Avoid error thrown when no date available to format:
> An error occurred while rendering the example.
=> Docs: fix DateField events example

packages/@react-aria/aria-modal-polyfill/package.json, packages/@react-aria/aria-modal-polyfill/src/index.ts, packages/@react-aria/overlays/src/ariaHideOutside.ts, yarn.lock
Reverts adobe/react-spectrum#4314
This PR broke our Menu unavailable items. We'll need to revisit it.
=> Revert "fix(#4313): ariaHideOutside/aria-modal-polyfill: use inert instead of aria-hidden where supported"

packages/@react-stately/select/src/index.ts, packages/react-stately/src/index.ts
Closes https://github.com/adobe/react-spectrum/issues/4460
Replaces https://github.com/adobe/react-spectrum/pull/4475 because the CLA got stuck
=> Fix: SelectStateOptions is not exported in .d.ts

packages/@react-spectrum/actiongroup/src/ActionGroup.tsx, packages/@react-spectrum/actiongroup/stories/ActionGroup.stories.tsx, packages/@react-spectrum/actiongroup/test/ActionGroup.test.js, packages/@react-spectrum/menu/src/MenuItem.tsx
In ActionGroup, if the menu is collapsed, then it doesn't currently pass along DOM attributes of <Item/> to the menu items.
This fixes that.
Much like the unit test says, if you add a data-testid="hello" prop to the <Item/> component of an <ActionGroup/> that is collapsed, those attributes will now be passed down to the DOM.
Adobe Workfront
=> Item props for action group menu

packages/@react-spectrum/overlays/src/Modal.tsx, packages/@react-spectrum/overlays/src/Tray.tsx
Closes 
We have no use case to support adding to Tray or Modal right now
=> Restrict shouldContainFocus access in types

packages/react-aria-components/src/Select.tsx, packages/react-aria-components/test/Select.test.js
Closes #4398
If no item is selected and a placeholder is provided, the button should use that as it's label instead of the default.
=> RAC Select: propagate placeholder to Button label

.circleci/config.yml, package.json, packages/react-aria-components/src/Collection.tsx, packages/react-aria-components/src/Table.tsx
Fixes #4390
This runs our tests against the new [React Canary](https://react.dev/blog/2023/05/03/react-canaries) versions in CI. Next.js is using the canary version in their latest version, and this is now an officially supported setup by the React team.
As reported in #4390, the React Aria Components collection implementation was broken in the canary versions of React because our hack of using the `multiple` prop to pass through an object to the underlying fake DOM node no longer works. This is fixed by using a callback ref to imperatively set the props ourselves. This seems cleaner anyway and also fixes the issue in Next.js.
=> Fix RAC collections in React canary versions

packages/@react-aria/tooltip/src/useTooltip.ts, packages/@react-spectrum/tooltip/stories/TooltipTrigger.stories.tsx, packages/@react-spectrum/tooltip/test/Tooltip.test.js, packages/@react-spectrum/tooltip/test/TooltipTrigger.test.js
This reverts commit b677593429205473d8ed1af016f4ff101eaae0c1.
After a team discussion, we've decided to address this in all of our portalled components using something like https://github.com/facebook/react/issues/11387#issuecomment-1548827669
and provide guidance in our FAQ on how to ignore events that come through a portal.
Closes
=> Revert "stop propagation of clicks on tooltips (#4479)"

packages/react-aria-components/src/Select.tsx
SelectValue should always be provided in some fashion to the Button
Closes 
RSP
=> Remove extraneous children set on Select's button context

packages/@react-aria/tag/src/useTagGroup.ts
onRemove accepts a `Set` now, update the var to be plural.
See TagGroup props for onRemove in the docs 
RSP
=> Update `onRemove` type in `useTagGroup`

packages/react-aria-components/src/Checkbox.tsx, packages/react-aria-components/src/RadioGroup.tsx, packages/react-aria-components/src/Switch.tsx
Not really sure why it would matter anymore now that CSS can make any element block or inline, but the HTML validator still fails if you put a `<div>` inside a `<label>`. So for Checkbox, Radio, and Switch, use a `<span>` to render the VisuallyHidden instead of a div.
=> Use span for VisuallyHidden when inside a <label>

packages/@react-spectrum/inlinealert/chromatic/InlineAlert.chromatic.tsx
Closes 
Noticed in chromatic that the long content wasn't rendering https://www.chromatic.com/test?appId=5f0dd5ad2b5fc10022a2e320&id=646fa09c5605027e487f21cb
=> Fixes for Inline Alert

packages/@react-spectrum/actionbar/docs/ActionBar.mdx, packages/@react-spectrum/avatar/docs/Avatar.mdx, packages/@react-spectrum/tag/docs/TagGroup.mdx
Missing monopackage version in rsp docs
=> Add 'since' version to new releases docs

.circleci/config.yml, .github/workflows/prod-docs.yaml
This changes the production docs deploy to run when we publish a release (from Github releases), or by triggering a Github Action manually, which kicks off a circle ci build. This way we can merge documentation changes without them going to prod immediately.
=> Trigger production docs deploy manually

packages/@adobe/spectrum-css-temp/components/inlinealert/index.css, packages/@react-spectrum/form/stories/Form.stories.tsx, packages/@react-spectrum/inlinealert/src/InlineAlert.tsx, packages/@react-spectrum/inlinealert/stories/InlineAlert.stories.tsx, packages/@react-types/inlinealert/src/index.d.ts
- Fixes background to match Spectrum designs
- Removes extra stories
- Adds dynamic story, and adds to Form story
- Updates some 'In-line' in descriptions to 'Inline' to match docs
=> InlineAlert: Fix background color and clean up stories

.eslintignore, examples/rac-tailwind/package.json, examples/rac-tailwind/src/AnimatedCalendar.tsx, examples/rac-tailwind/src/App.js, examples/rac-tailwind/tsconfig.json, examples/rac-tailwind/yarn.lock, packages/@react-aria/calendar/src/useCalendarCell.ts
This adds a new example to the Tailwind project - an animated Calendar built with Framer Motion. On touch screens, you can also swipe to move between months. It works by rendering 3 months at a time, and animating the transformX. The months that aren't visible are marked `inert` so they aren't focusable or visible to screen readers. I want to move this to the docs somewhere at some point but for now this was the most convenient place to test it out.
I had to fix one bug to support this setup: the scroll into view code would try to scroll cells in out of view months to the center, resulting in weird results. This was because there might be two different cells in the DOM representing the same date. The out of view one would not actually be focused due to `inert`, but we still tried to …
=> Add AnimatedCalendar example with framer-motion

packages/@react-stately/flags/README.md, packages/@react-stately/flags/index.ts, packages/@react-stately/flags/package.json, packages/@react-stately/flags/src/index.ts
Problem: we need a way to develop new features for existing, non-pre release components like Table and Menu. We want to be able to release these new features for teams to test before they are stable, without breaking anything in existing apps.
Solution: feature flags! We'll keep them in the `@react-stately/flags` package as exported booleans. Any package that wants to put code behind these flags will import this package and check the flags in an if statement. This might mean enabling new things, or even swapping out the entire implementation of something. An app can also import this package, and call a function to to enable some features they want to try out.
This approach is the easiest because the flags can be accessed from anywhere. However, one downside is that flags are enabled for …
=> Setup package for feature flags

packages/react-aria-components/docs/Popover.mdx, packages/react-aria-components/src/Popover.tsx, packages/react-aria-components/test/Popover.test.js
This allows the RAC `Popover` component to be used standalone, outside a `DialogTrigger`, the same way as we already support for `Modal`. This means you can pass the `isOpen` and `onOpenChange` props directly to the popover, as well as the `triggerRef` prop to indicate which element to position it relative to. This enables more complex use cases, such as programmatically showing popovers (e.g. coach marks). The `isOpen` prop is also useful for integration with animation libraries like Framer Motion. It's also nice to have consistency between Modal and Popover here.
=> Add support for standalone RAC popovers

packages/@adobe/spectrum-css-temp/components/stepper/index.css
Specificity of form selector that sets `width: 100%` should override the one for NumberField `isMobile`. Switched to setting a variable rather than the `inline-size` property directly so the specificity is always the same regardless of if it is mobile or desktop.
=> Fix width of number field within a form

packages/@internationalized/date/src/string.ts, packages/@internationalized/date/tests/string.test.js
Closes https://github.com/adobe/react-spectrum/issues/4659
This should not throw an error with the new code:
parseAbsolute('2021-03-14T02:00-08:00', 'America/Los_Angeles')
parseAbsolute('2021-11-07T01:00-0800', 'America/Los_Angeles')
parseAbsolute('2021-11-07T01:00-08', 'America/Los_Angeles')
parseAbsolute('2021-11-07T01:00+0000', 'America/Los_Angeles')
parseZonedDateTime('2020-02-03T12:24:45-08:00[America/Los_Angeles]')
parseZonedDateTime('2020-02-03T12:24:45-0800[America/Los_Angeles]')
=> ASSETS-25282: Fix UTC offset format acceptance in date parsers

packages/@react-aria/tag/src/useTagGroup.ts, packages/react-aria-components/docs/TagGroup.mdx, packages/react-aria-components/docs/react-aria-components.mdx, packages/react-aria-components/src/TagGroup.tsx, packages/react-aria-components/src/index.ts, packages/react-aria-components/test/TagGroup.test.js
This adds `TagGroup` to React Aria Components. The API looks like this:
```jsx
<TagGroup selectionMode="multiple">
<Label>Categories</Label>
<TagList>
<Tag>News</Tag>
<Tag>Travel</Tag>
<Tag>Gaming</Tag>
<Tag>Shopping</Tag>
</TagList>
</TagGroup>
```
We use a separate `Tag` component rather than `Item` here due to the additional `allowsRemoving` render prop. A remove button can be added with `<Button slot="remove">` (slot prop just in case there are other buttons).
=> Add TagGroup component to RAC

packages/react-aria-components/src/DropZone.tsx, packages/react-aria-components/src/FileTrigger.tsx
Fixes file upload dialog that was found during testing. It should no longer tab through the input twice.
Also removes some comments and unused stuff
Test FileTrigger Button, FileTrigger Link
you should only be able to tab to either the button/link and not the input
=> rac dropzone fix file upload dialog

packages/react-aria-components/docs/DatePicker.mdx, packages/react-aria-components/docs/DateRangePicker.mdx, packages/react-aria-components/src/DatePicker.tsx
It was a task from the project board.
Dependent on changes from #4616. Merging into that branch to show the changes.
Goto RAC DatePicker and DateRangePicker docs.
For the invalid and min/max examples, when the dates are invalid there is now a visual indicator (besides color).
RSP
=> Adding invalid icon to RAC DatePicker and DateRangePicker

packages/@react-aria/datepicker/src/useDatePicker.ts, packages/@react-aria/datepicker/src/useDateRangePicker.ts, packages/@react-spectrum/datepicker/stories/DateField.stories.tsx, packages/@react-spectrum/datepicker/stories/DatePicker.stories.tsx, packages/@react-spectrum/datepicker/stories/DateRangePicker.stories.tsx, packages/@react-spectrum/datepicker/stories/TimeField.stories.tsx, packages/@react-spectrum/datepicker/test/DatePickerBase.test.js, packages/@react-stately/datepicker/src/useDateFieldState.ts, packages/@react-stately/datepicker/src/utils.ts, packages/@react-types/datepicker/src/index.d.ts
Closes #4668
This adds a `shouldForceLeadingZeros` prop to DatePicker, DateRangePicker, DateField, and TimeField which forces leading zeros to always show in the month, day, and hour fields, regardless of the locale preference. This was also requested in #4247. We would discourage overriding this across all locales, but it can be useful to configure in some scenarios.
=> Add shouldForceLeadingZeros prop to DatePicker

packages/react-aria-components/src/Modal.tsx, packages/react-aria-components/src/Popover.tsx, packages/react-aria-components/test/Dialog.test.js, packages/react-aria-components/test/Popover.test.js
`isOpen` and `defaultOpen` props on Popover and Modal should override the state passed from DialogTrigger. This will allow using animation libraries like Framer Motion's AnimatePresence within components like DatePicker. cc. @RobinMalfait
=> Make RAC overlay open props override DialogTrigger state

packages/react-aria-components/src/DropZone.tsx, packages/react-aria-components/src/index.ts
export types for dropzone and fileTrigger
omit ref and hasDropButton from DropZone props
=> export types and omit props from dropzone

packages/@react-spectrum/tag/docs/TagGroup.mdx
found in testing
The TagGroup docs avatar and icon examples didn't set textValue on the <Item /> so they didn't announce their labels with VO.
Turn on VO.
Goto the TagGroup docs page.
Goto the With icons and With avatar examples.
Confirm that the TagGroup item labels announce.
RSP
=> TagGroup docs fixing avatar and icon examples

.parcelrc, package.json, yarn.lock
Appears that since the Parcel upgrade ~3 weeks ago, icons have been missing in some docs examples, e.g. https://react-spectrum.adobe.com/react-spectrum/ToggleButton.html#events. Looks like it was caused by the new minifier (SWC). Switching back to Terser for now appears to fix it. Will investigate the underlying issue later.
=> Switch back to terser minifier

packages/dev/docs/src/client.js
The example on https://react-spectrum.adobe.com/react-aria/react-aria-components.html and in blog posts like https://react-spectrum.adobe.com/blog/drag-and-drop.html do not render because the code crashes while trying to render the edit page button which isn't present for those pages.
=> Fix error when edit page button is missing

packages/@react-stately/datepicker/src/useTimeFieldState.ts
Fixing an issue Yihui found with DatePicker -> Date Time Value Zoned. Caused by #4715 
I added tests for this code in TimeField where the bug was, but this occurred when opening a DatePicker. Do we need a test there too? The TimeField in picker does not show the time zone.
Goto DatePicker - > Date Time Value Zoned
Open the picker
The picker opens and there is no error
RSP
=> Fixing a null date with DatePicker

packages/react-aria-components/example/index.css, packages/react-aria-components/src/RadioGroup.tsx, packages/react-aria-components/stories/index.stories.tsx, packages/react-aria-components/test/RadioGroup.test.js
Resolved issue with RadioGroup tab navigation within Dialog Component.
RadioGroup tab focus now complies with implementation of roving tabindex in accordance with [a11y radio guidelines](https://www.w3.org/TR/wai-aria-practices-1.1). 
Followed suggestion from @LFDanLu per https://github.com/adobe/react-spectrum/issues/4746#issuecomment-1629758418. Added Storybook examples from RadioGroup and RadioGroup in Dialog. Added tests to cover both use cases.
No change to documentation needed. 
Closes #4746 
1. Open Storybook
2. Select RadioGroup Example under React Aria Components
4. Tab to first radio, observe has focus
5. Tab again, observe focus no longer in RadioGroup
6. Repeat steps 2 - 5 for RadioGroup in Dialog Example
Run newly added tests in `react-aria-components/test/RadioGroup.test.js` …
=> fix [RAC]: RadioGroup/Dialog Focus

packages/@react-aria/checkbox/src/useCheckboxGroupItem.ts, packages/@react-aria/radio/src/useRadio.ts, packages/react-aria-components/test/CheckboxGroup.test.js, packages/react-aria-components/test/RadioGroup.test.js
The `aria-describedby` set by the group was overriding the manually provided one from props. Now they get combined. I kinda just chose an order here (props one comes first), but can change it if there is a good reason.
=> Allow custom aria-describedby on checkbox and radio group items

packages/react-aria-components/src/Checkbox.tsx, packages/react-aria-components/src/RadioGroup.tsx, packages/react-aria-components/src/index.ts, packages/react-aria-components/test/RadioGroup.test.js
* Renders the label for CheckboxGroup and RadioGroup as a span rather than a `<label>` since it isn't labeling a native input. That's how we do it in RSP, but it slipped through in RAC.
* Adds `RadioContext` so you can send props to an individual Radio rather than only to the entire group. This could be used to implement a wrapper to support a "description" slot for a radio similar to [this example](https://codesandbox.io/s/rac-optionfield-zkdr6w?file=/src/App.js) for checkbox.
=> RAC Radio and Checkbox improvements

packages/react-aria-components/docs/Checkbox.mdx, packages/react-aria-components/docs/ComboBox.mdx, packages/react-aria-components/docs/Meter.mdx, packages/react-aria-components/docs/NumberField.mdx, packages/react-aria-components/docs/ProgressBar.mdx, packages/react-aria-components/docs/TextField.mdx, packages/react-aria-components/src/Calendar.tsx, packages/react-aria-components/src/Checkbox.tsx, packages/react-aria-components/src/ComboBox.tsx, packages/react-aria-components/src/DateField.tsx, packages/react-aria-components/src/DatePicker.tsx, packages/react-aria-components/src/Meter.tsx, packages/react-aria-components/src/NumberField.tsx, packages/react-aria-components/src/ProgressBar.tsx, packages/react-aria-components/src/RadioGroup.tsx, packages/react-aria-components/src/SearchField.tsx, packages/react-aria-components/src/Select.tsx, packages/react-aria-components/src/TextField.tsx
- removes `showOptional` for tables in favor of fixing types from being optional to `| undefined`.
- updates some selectors to show enumerated values
Check docs for correct render props and updated selectors in table.
=> RAC: docs improvements for render props

packages/react-aria-components/src/RadioGroup.tsx
`value` should not be required in the context, only in the props.
=> Fix RadioContext type definition

packages/@adobe/spectrum-css-temp/components/button/skin.css
Closes #4141 
In SearchField, SearchAutocomplete, Mobile SearchAutocomplete, and MobileCombobox, the clear button should keep a transparent background in High Contrast Mode, so that it's background doesn't overlap surrounding elements. This helps prevent the following:
Check clear button in HCM in SearchField, SearchAutocomplete, Mobile SearchAutocomplete, and MobileCombobox components.
RSP
=> HCM: fix Clear button background to be transparent

packages/@adobe/spectrum-css-temp/components/button/skin.css
Closes #4054, #4052, #4022
For both ActionButton and ToggleButton, in storybook with HCM enabled:
- Test the text color during hover (you should be able to see text in light/lightest themes)
- Test staticColor="white" and staticColor="black" and ensure border changes color on hover
RSP
=> HCM: ActionButton/ToggleButton hover state color fixes

packages/@adobe/spectrum-css-temp/components/button/skin.css
Closes #4099
Checked the XD file and it didn't define "and" or "or" LogicButtons looking different when disabled. Updated the "or" button to mirror the "and" button. It made sense to keep the structure of the CSS rather than combine them into one rule.
Confirm that a disabled OR LogicButton looks okay inside and outside of HCM in all themes.
RSP
=> HCM Fixing disabled or LogicButton

packages/@react-aria/aria-modal-polyfill/package.json, packages/@react-aria/aria-modal-polyfill/src/index.ts, packages/@react-aria/overlays/src/ariaHideOutside.ts, yarn.lock
Speed up ariaHideOutside on large pages
Regarding [#4492](https://github.com/adobe/react-spectrum/pull/4492#issue-1700631071), I need more detail to understand what about this PR breaks unavailable menu items.
Closes #4313 
This should help with speed in hiding things from the screen reader. Best places to try this are in the docs with Drag and Drop.
=> fix(#4313): ariaHideOutside/aria-modal-polyfill: use inert instead of aria-hidden where supported

packages/@adobe/spectrum-css-temp/components/barloader/skin.css
Closes #4105
Fixing fill style for HCM ProgressBar and adding support for overBackground and Meter fill colors.
Check the ProgressBar and Meter in HCM to confirm fill is properly overridden.
RSP
=> HCM ProgressBar/Meter fill color fix

packages/react-aria-components/docs/ComboBox.mdx, packages/react-aria-components/docs/GridList.mdx, packages/react-aria-components/docs/ListBox.mdx, packages/react-aria-components/docs/Menu.mdx, packages/react-aria-components/docs/Select.mdx, packages/react-aria-components/docs/Table.mdx, packages/react-aria-components/docs/Tabs.mdx, packages/react-aria-components/docs/TagGroup.mdx
=> Fix broken links to react-stately Collections and Selection pages

packages/@react-spectrum/searchfield/docs/SearchField.mdx
adding https://spectrum.adobe.com/page/search-field/ to SearchField docs
=> update SearchField docs with Spectrum link

packages/@react-spectrum/inlinealert/docs/InlineAlert.mdx
This was causing the docs page for InlineAlert to show the import coming from the monopackage, even though this package is still RC.
=> Fix InlineAlert docs package data import

packages/@internationalized/date/docs/CalendarDate.mdx, packages/@internationalized/date/docs/CalendarDateTime.mdx, packages/@internationalized/date/docs/Time.mdx, packages/@internationalized/date/docs/ZonedDateTime.mdx
Closes [#4826 - @internationalized documentation typos](https://github.com/adobe/react-spectrum/issues/4826)
Adobe Globalization team - internal I18n audit
=> Fixing various documentation typos 

packages/@adobe/spectrum-css-temp/components/link/skin.css
Fixes regression from https://github.com/adobe/react-spectrum/pull/4799, since Safari doesn't support `forced-colors: none`.
The secondary variant should now use the inherited color in Safari, like previous behavior.
Test that link colors are across themes, and in HCM. Check across browsers. 
Reference: https://spectrum.adobe.com/page/link/#Windows-high-contrast-mode
=> Fix secondary link color in Safari

packages/@react-aria/table/package.json, packages/@react-aria/table/src/useTable.ts, packages/@react-aria/table/src/useTableHeaderRow.ts, packages/@react-aria/table/src/useTableRow.ts
=> Adding feature flag check for expandable table rows in aria hooks

packages/@react-aria/ssr/package.json, packages/@react-aria/ssr/src/SSRProvider.tsx, packages/@react-aria/ssr/test/SSRProvider.test.js
Fixes #4851
This ensures that we do not add a random prefix to ids generated by `useId` in test environments with React 18. Previously it was possible to use `SSRProvider` to ensure this, but `SSRProvider` is now a noop in React 18, and we determine whether we are SSRing in another way. But that's not set in a test environment. This will check whether the `NODE_ENV` environment variable is set to "test" and won't add a random prefix if so.
=> Do not add random prefix to ids during tests in React 18

packages/@react-types/shared/src/collections.d.ts
Expandable rows TableView and its related hooks use `UNSTABLE_expandedKeys` so they don't even use the Expandable
type
RSP
=> Remove extraneous 'all' from Expandable type

packages/@react-aria/table/src/useTableColumnResize.ts
Closes 
Test table column resizing via an Android device in Chrome or via Chrome dev tool emulation. Focusing the column resizer via the "resize column" option in the resizable column dropdown menu should work
RSP
=> Prevent unexpected column resizer input blur when focused via dropdown menu 

packages/@react-aria/aria-modal-polyfill/src/index.ts, packages/@react-aria/overlays/src/ariaHideOutside.ts, yarn.lock
Reverts https://github.com/adobe/react-spectrum/pull/4773
Because the fix in https://github.com/adobe/react-spectrum/pull/4879 may need more testing, we may want to revert this until after the upcoming release.
=> Revert "fix(#4313): ariaHideOutside/aria-modal-polyfill: use inert instead of aria-hidden where supported (#4314)

packages/@react-aria/overlays/src/useOverlay.ts
In collaboration with @LFDanLu
Fixes #4922, fixes #4130, fixes #4384, fixes https://github.com/adobe/react-spectrum/issues/4533
When debugging #4922, we found a Chrome bug where extraneous blur events are fired with `relatedTarget = null` when navigating with the VoiceOver cursor (via Control + Option + Arrow keys). https://bugs.chromium.org/p/chromium/issues/detail?id=1473752 Note that this affects more than just DatePicker - it also affects any button contained within a Popover.
In addition, Chrome and Firefox fire blur events with `relatedTarget = null ` when switching tabs, which causes overlays to close.
This changes the logic in `useOverlay` to not close in those cases. We haven't thought of a case where `relatedTarget` was `null` where we _wouldn't_ want to close the overlay. …
=> Do not close overlays on blur if relatedTarget is null

packages/@react-aria/aria-modal-polyfill/src/index.ts, packages/@react-aria/overlays/src/ariaHideOutside.ts, packages/@react-aria/overlays/src/usePopover.ts, yarn.lock
…se inert instead of aria-hidden where supported (#4314) #4881 (#4883)"
This reverts commit be501251a2012b2c1401e79940cbb39151c84d9d.
Issue found where you can no longer tab from a open Picker dropdown to adjacent focusable elements
RSP
=> Revert fix(#4313): ariaHideOutside/aria-modal-polyfill: use inert instead of aria-hidden

packages/@react-aria/datepicker/src/useDatePickerGroup.ts
Closes #4384 
Go to DatePicker (whether in storybook or the docs)
Open up the Popover
Focus on either the prev/next button for the months
Press left/right arrow key
The popover should not close
=> Prevent event bubbling through portal in useDatePickerGroup

packages/@react-spectrum/menu/src/MenuItem.tsx, packages/@react-spectrum/menu/test/MenuTrigger.test.js, yarn.lock
No issue, found when working on SubMenus. Haven't chased down when exactly this broke, but I'm guessing for quite some time since we've grabbed MenuTrigger's onClose from the context for quite some time
EDIT: look like it is from https://github.com/adobe/react-spectrum/commit/263db83002000d6deed33b6eb1341e76f6609f42#diff-c6950c5a4d27483b1efb744dd50d6789949274bc656dcd6229371ba8b30f6e7a, we introduced `onClose` to the MenuProps then.
Unit tests should suffice
RSP
=> Fix MenuItem so user provided onClose is actually called

packages/@react-aria/interactions/test/usePress.test.js, packages/@react-aria/utils/src/isVirtualEvent.ts
Might close #3945 
Opened to investigate the problem. Adds a check (which Devon suggested) to `isVirtualPointerEvent` to see if it's `!isAndroid()` when the event width and height are 0.
Go to [this page](https://reactspectrum.blob.core.windows.net/reactspectrum/c73d2d6b473a7a149b7ef35ea5962b6ae8e2a9a8/docs/react-aria/usePress.html#example) on the docs
Press the button that says "Press me!"
Should say 'press with touch' (if on mobile without screenreader)
=> Adds check to detect Android pointer type as touch

scripts/convertAnatomy.js
After you export an SVG from XD, run this script pointing at the file and hard coded colors will be replaced by the closest variable. Also fixes the font family syntax.
=> Add a script to convert anatomy SVGs to use CSS variables

packages/@react-spectrum/dropzone/intl/en-US.json, packages/@react-spectrum/dropzone/package.json, packages/@react-spectrum/dropzone/src/DropZone.tsx
There is still a hard-coded aria-label within RAC DropZone but given that we do not yet have translations set up for RAC Components and users can override this aria-label, we decided to leave it be. 
However, a translation for the filled message in RSP DropZone has been created.
=> Add translations to RSP Dropzone

packages/dev/docs/src/Layout.js, packages/react-aria-components/docs/Checkbox.mdx, packages/react-aria-components/docs/CheckboxGroup.mdx, packages/react-aria-components/docs/RadioGroup.mdx
Closes 
There are a few more instances in the calendar components where the darker red is used, however, due to contrast, it's not as easy to fix. We can revisit another time, I think they look fine.
=> Fix some RAC docs colors

packages/@react-types/button/src/index.d.ts
I removed the documentation for isPending but didn't hide the prop itself, so this PR corrects that.
=> Hide `UNSTABLE_isPending` prop from docs

packages/react-aria-components/docs/Menu.mdx, packages/react-aria-components/docs/Table.mdx, packages/react-aria-components/src/Collection.tsx, packages/react-aria-components/src/GridList.tsx, packages/react-aria-components/src/ListBox.tsx, packages/react-aria-components/src/Menu.tsx, packages/react-aria-components/src/Table.tsx, packages/react-aria-components/src/TagGroup.tsx, packages/react-aria-components/src/index.ts
Exposes the `selectionMode` render prop as a data attribute. Mainly to fix the Menu selection examples which used to use `aria-checked` to reserve space for the checkmark even when not selected, but this broke after the move to data attributes.
=> Add data-selection-mode attribute

packages/@react-aria/breadcrumbs/docs/useBreadcrumbs.mdx, packages/react-aria-components/docs/Breadcrumbs.mdx, packages/react-aria-components/src/Breadcrumbs.tsx, packages/react-aria-components/src/index.ts, packages/react-aria-components/test/Breadcrumbs.test.js
* Remove default `<nav>` landmark. Not all breadcrumbs should be landmarks. Instead, I added an example in the docs explaining how to create a landmark. This also solved the problem of `Breadcrumbs` rendering two elements, making it hard to style. #4885
* Remove support for breadcrumbs as a heading. We removed this from React Spectrum many years ago (https://github.com/adobe/react-spectrum/pull/642), but never removed it from React Aria. The accessibility doesn't seem correct anyway (e.g. `aria-current` on a heading element?). I also removed the example from the hooks docs.
* Switch from using the `<Item>` component to a `<Breadcrumb>` component. Item had too many props and data attributes that didn't apply to breadcrumbs.
=> Update RAC breadcrumbs API

packages/@react-spectrum/menu/chromatic/MenuTrigger.chromatic.tsx, packages/@react-spectrum/menu/docs/ActionMenu.mdx, packages/@react-spectrum/menu/docs/Menu.mdx, packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx, packages/@react-spectrum/tabs/stories/Tabs.stories.tsx, packages/dev/docs/pages/blog/introducing-react-spectrum.mdx, packages/dev/docs/pages/react-spectrum/layout.mdx
Closes https://github.com/adobe/react-spectrum/issues/4814
Menus, pickers, and tabs in RSP do not need icons with a specified size, they will override it. This lead to confusion as to why the prop wasn't being respected when set to some other value.
=> Remove unnecessary props from docs

packages/react-aria-components/src/DateField.tsx, packages/react-aria-components/src/ListBox.tsx, packages/tailwindcss-react-aria-components/src/index.js, packages/tailwindcss-react-aria-components/src/index.test.js
* Added `group-` and `peer-` modifiers for each variant. Tailwind doesn't do this by default: https://tailwindcss.com/docs/plugins#parent-and-sibling-states
* Audited for missing states
* Fixed some modifiers that conflict with builtin Tailwind ones
=> Add missing variants to Tailwind plugin

.storybook/test-runner.js, packages/@react-spectrum/datepicker/src/DatePickerSegment.tsx
investigated, turns out it is a legitimate color contrast problem: https://github.com/orgs/adobe/projects/19/views/39?pane=issue&itemId=37780001
Closes 
RSP
=> Remove erroneous accessibility color contrast ignore rule

packages/@react-aria/select/src/useSelect.ts, packages/@react-spectrum/picker/stories/Picker.stories.tsx, packages/@react-spectrum/picker/test/Picker.test.js, packages/@react-spectrum/searchwithin/test/SearchWithin.test.js, packages/@react-spectrum/tabs/test/Tabs.test.js, packages/react-aria-components/test/Select.test.js
Reverts 50b1e19c9b9e0b9aa6e7277ca9ac0e61c5635a6f since this is a breaking change, many of our components use `useLabels` and thus expect that the aria-label and aria-labelledby will be merged and announced as such. Additionally, our RSP components differ from native implementations since we handle creating and linking the visible label and the changes from the commit mentioned above breaks when a visible label and an aria-labelledby is provided (the visible label no longer is announced, just the aria-labelledby).
Broken experience: https://reactspectrum.blob.core.windows.net/reactspectrum/d7148894b9e05acc251fc9096975cf7d9060a063/storybook/index.html?path=/story/picker--labelled-by&args=label:Visible+label&providerSwitcher-express=false
New experience 
Recommendation for how to address in …
=> Revert fix: useSelect trigger label (#4949) and fix example story

packages/react-aria-components/docs/Breadcrumbs.mdx, packages/react-aria-components/docs/Button.mdx, packages/react-aria-components/docs/Link.mdx, packages/react-aria-components/src/Link.tsx, packages/react-aria-components/test/Breadcrumbs.test.js, packages/react-aria-components/test/Link.test.js
Closes https://github.com/orgs/adobe/projects/19/views/32?pane=issue&itemId=25877582
Depends on #4993
This updates the RAC `Link` API to just have `href` and other link props directly on it rather than cloning its child. With the `RouterProvider` added in #4993 this will support client side routers the same way as our other components, meaning there is no need to support wrapping a router Link component.
=> Update RAC Link API

packages/@react-aria/link/docs/useLink.mdx, packages/@react-aria/link/src/useLink.ts, packages/@react-aria/utils/src/index.ts, packages/@react-aria/utils/src/openLink.tsx, packages/@react-spectrum/breadcrumbs/test/Breadcrumbs.test.js, packages/@react-spectrum/combobox/test/ComboBox.test.js, packages/@react-spectrum/link/docs/Link.mdx, packages/@react-spectrum/link/src/Link.tsx, packages/@react-spectrum/link/stories/Link.stories.tsx, packages/@react-spectrum/link/test/Link.test.js, packages/@react-spectrum/list/test/ListView.test.js, packages/@react-spectrum/listbox/test/ListBox.test.js, packages/@react-spectrum/picker/test/Picker.test.js, packages/@react-spectrum/table/test/Table.test.js, packages/@react-types/link/src/index.d.ts, packages/react-aria-components/docs/Link.mdx, packages/react-aria-components/src/Link.tsx, packages/react-aria-components/stories/index.stories.tsx, packages/react-aria-components/test/Link.test.js
Depends on #5078 
This updates the RSP `Link` API to match RAC. It accepts an `href` prop and uses the router passed to the `Provider` to handle client side routing instead of wrapping a native/custom link component. The old API is still supported for backward compatibility if no `href` prop is provided.
This also adds tests for `RouterProvider` in components that support it, and updates the `useLink` hook to support custom routers.
=> Add RouterProvider tests and update RSP Link API

packages/@react-aria/utils/src/openLink.tsx
We previously checked if `link.target` was empty or equal to `_self` to determine if we should client navigate. But Firefox also defaults this to `_parent` for links inside iframes, unlike in other browsers which return an empty string. This PR switches us to use `getAttribute` instead of the property to avoid this.
=> Fix client navigation check in Firefox

packages/@react-aria/overlays/src/usePopover.ts
Reverts adobe/react-spectrum#5109
This caused flickering during animations on iOS, where the overlay would briefly flip to the opposite side of the trigger. This is due to the iOS-specific scroll prevention code which unfortunately can affect overlay positioning. We would really need to wait until after animations to turn off scroll prevention to avoid this. The easiest way to do that at the moment is to wait until the popover unmounts.
https://github.com/adobe/react-spectrum/assets/19409/1a5b1913-ef20-4c69-b61a-3fedb90252f1
=> Revert "fix #5019 Popover prevents scroll only when it's opened"

packages/@react-aria/selection/src/ListKeyboardDelegate.ts, packages/react-aria-components/src/ListBox.tsx
=> Fix typeahead in RAC ListBox

packages/tailwindcss-react-aria-components/src/index.js, packages/tailwindcss-react-aria-components/src/index.test.js
I noticed that some states like `focus-visible` were overriding others like `selected`. That is because of the extra `[data-rac]` part of the selector, which raises a rule like `.focus-visible\:bg-red[data-rac][data-focus-visible]` to a specificity of (0, 3, 0) whereas `.selected\:bg-red[data-selected]` only has (0, 2, 0).
This PR uses `:where([data-rac])` instead to ensure that is not taken into account in the specificity.
=> Fix specificity of tailwind generated selectors

packages/@react-spectrum/dropzone/docs/DropZone.mdx
A few minor docs updates for DropZone from the release audit @dannify and I did.
* Inlining the filled message inside the illustrated message instead of outside, since I didn't notice it before
* Combine `isFilled` and `filledSrc` into a single state
* replace "drop zone" with the component name "DropZone"
=> DropZone docs release audit

packages/react-aria-components/src/DateField.tsx, packages/react-aria-components/src/DatePicker.tsx, packages/react-aria-components/test/DateField.test.js, packages/react-aria-components/test/DatePicker.test.js, packages/react-aria-components/test/DateRangePicker.test.js
Was making some examples and came across the following issues:
* DateSegment was missing `data-hovered`, `data-focused`, and `data-focus-visible` states. Also the native versions of these didn't work with the tailwind plugin because the element has `data-rac`.
* `data-open` was missing in DatePicker and DateRangePicker, which is useful for styling while the popover is open similar to what you can do in ComboBox and Select.
=> Add missing DatePicker states

packages/react-aria-components/src/Table.tsx, packages/react-aria-components/test/Table.ssr.test.js
Fixes #5140
During SSR, the collection is updated during render because effects don't run on the server. Therefore, each time a new collection node is rendered, it calls `updateCollection`. If the first column doesn't have `isRowHeader` this will result in an error. The easiest fix is just to suppress this error on the server. If none of the columns have `isRowHeader`, it will happen on the client instead.
=> Fix error during SSR when first Table column is not a row header

packages/@react-aria/utils/src/useViewportSize.ts, packages/@react-aria/utils/test/useViewportSize.ssr.test.tsx
Closes #5057
Added `isSSR` check for `getViewportSize` at SSR mode.
=> Fix useViewportSize for SSR environment

packages/@react-aria/overlays/src/calculatePosition.ts
Fixes popover positioning with contextual help trigger, and left/right placement.
=> Fix overlay positioning when portal container is not body

packages/tailwindcss-react-aria-components/src/index.js, packages/tailwindcss-react-aria-components/src/index.test.js
Fixes #5165
This was a regression caused by #5147. `getSelector` returns an array, so we need to map this for the group variants. Would be good to get this fixed in the release.
=> Fix Tailwind plugin group variant regression

packages/react-aria-components/README.md
Status paragraph was copied over from the docs (which were updated in 4e5128368f305fe8c6670642ca5ffdf06a7c458f) to README for them to match. Most importantly, to highlight React Aria Components is in **beta**, not **alpha**.
=> Make react-aria-components README match the docs

packages/@react-aria/interactions/docs/useMove.mdx
Closes #5189 
In live docs, test dragging the circle to the edge of the container, continue dragging mouse past, then release the mouse. Next, try to drag the circle again in the opposite direction. You'll see that it still requires coming back by this offset despite the mouseUp. PR fixes this behavior.
=> Fix useMove docs example

packages/react-aria-components/docs/DropZone.mdx, packages/react-aria-components/docs/FileTrigger.mdx
Closes #5262 
Set FileTrigger to allow multiple files as dropZone does and adjusted surrounding text.
`<br/>` added to avoid this previous behavior with long file names and/or multiple files.
If anyone more familiar with the styling of the docs would like to do this in CSS please do.
Unsure if my use of `<Text slot="label">` is appropriate.
`/react-aria/DropZone.html#filetrigger`
=> add onDrop to DropZone docs FileTrigger example & adjust behavior

packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@adobe/spectrum-css-temp/components/menu/skin.css, packages/@react-spectrum/menu/src/ContextualHelpTrigger.tsx, packages/@react-spectrum/menu/src/Menu.tsx, packages/@react-spectrum/menu/src/MenuTrigger.tsx
Closes 
Pulled out from https://github.com/adobe/react-spectrum/pull/4976
=> Fix double filter dropshadow menu unavailable

packages/tailwindcss-react-aria-components/package.json
in the tailwind plugin package, point `package.json#types` to https://github.com/adobe/react-spectrum/blob/main/packages/tailwindcss-react-aria-components/src/index.d.ts
=> fix package.json#types field in tailwind plugin

packages/react-aria-components/docs/Dialog.mdx, packages/react-aria-components/docs/Modal.mdx, packages/react-aria-components/docs/Popover.mdx, packages/react-aria-components/docs/examples/destructive-dialog.mdx, packages/react-aria-components/docs/examples/framer-modal-sheet.mdx, packages/react-aria-components/src/Dialog.tsx, packages/react-aria-components/stories/animations.stories.tsx, packages/react-aria-components/stories/index.stories.tsx, packages/react-aria-components/test/Dialog.ssr.test.js, packages/react-aria-components/test/Dialog.test.js, packages/react-aria-components/test/Popover.test.js
The `<Heading>` component can be used inside a `<Dialog>` to set the aria label for the dialog. However, if you had multiple headings inside the dialog contents they would all receive the aria labelling props from the dialog. This changes the API to require an explicit `slot="title"` prop to be added to the instance of the heading you want to use as the title. In addition it adds a warning if you have a dialog with no title slot or explicit aria labelling props.
After adding the warning I found that we had a bunch of unlabeled dialogs in our examples/tests, mostly in popovers. To fix these, I made dialogs within a `<DialogTrigger>` be labeled by the trigger element as a fallback, in case no title slot or aria labelling props are provided. Standalone popovers will need to do this manually, …
=> Use explicit "title" slot for RAC dialogs, and improve aria labelling

packages/dev/docs/pages/react-aria/forms.mdx, packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js
The prod docs puts its files in different locations so CSS importing wasn't working in the prod docs for the react aria forms page
=> Fix importing CSS on forms guide in prod docs

packages/@react-aria/form/src/useFormValidation.ts
Fixes useDateField/useDatePicker examples in the docs, which do not render a native `<input>` and therefore have no `inputRef`. They still call `useFormValidation` and then crash inside there.
=> Do not crash in useFormValidation if ref is undefined

packages/react-aria-components/src/Table.tsx
Found by @yihuiliao in testing: `hoverProps` should go on the column resizers' outer div instead of the hidden input.
In storybook, check that actions are fired when column resizers are hovered: https://reactspectrum.blob.core.windows.net/reactspectrum/f34fa78bc961a2c005508261219df9e772a01703/storybook/index.html?path=/story/react-aria-components--table-example&providerSwitcher-express=false
=> RAC: Fix Table column resizer hover events

packages/@adobe/spectrum-css-temp/components/menu/index.css, packages/@adobe/spectrum-css-temp/components/textfield/index.css, packages/@react-spectrum/text/src/Keyboard.tsx, yarn.lock
Fixes #5310
Upstream fix: https://github.com/parcel-bundler/lightningcss/commit/b4bbe4726aa82612d6208485f710a151dd96facc
This also bumped the caniuse/mdn compat data. Looks like a bunch of logical properties are no longer compiled as well. Overall compiled + minified CSS size dropped by ~600 KB.
=> Bump lightningcss

packages/@react-aria/checkbox/docs/useCheckboxGroup.mdx, packages/@react-aria/combobox/docs/useComboBox.mdx, packages/@react-aria/numberfield/docs/useNumberField.mdx, packages/@react-aria/radio/docs/useRadioGroup.mdx, packages/@react-aria/searchfield/docs/useSearchField.mdx, packages/@react-aria/select/docs/useSelect.mdx, packages/@react-aria/textfield/docs/useTextField.mdx, packages/dev/docs/pages/react-aria/forms.mdx
Realized we didn't have any docs for form validation in the hooks. Added a small section at the end of the forms guide describing the overall setup for the hooks, and updated the pages where we already had help text in the examples. Don't want to spend too much more time on it right now.
=> Add basic validation docs for hooks

packages/react-aria-components/src/Slider.tsx, packages/react-aria-components/test/Slider.test.js
filtering dom props was breaking this. now filtering the hover props manually.
=> Fix clicking on track to move slider in RAC

packages/@react-spectrum/dropzone/src/DropZone.tsx
Hover event props are available to RAC DropZone, but we don't necessarily want them in RSP DropZone at this time. Since `SpectrumDropZoneProps` extends `DropZoneProps`, we need to omit them from the prop types, and filter them out of the props.
We may want to add these back later, but this should be a larger discussion as more RSP components begin wrapping RAC components.
=> Fix DropZone hover event props

packages/@react-aria/toast/docs/useToast.mdx
Looks like it was broken when we switch to React.createRoot which imports from `react-dom/client` instead of `react-dom`.
=> Fix useToast example in docs

packages/@react-spectrum/button/src/Button.tsx, packages/@react-spectrum/button/test/Button.test.js
Closes 
Needs cleanup, but check if this accomplishes what we need in terms of announcements across different AT and browser combinations.
I expect it to read the regular button label when focused. Then when it enters pending, I expect it to read the button label again, followed by the pending string (we could put a comma here to add a pause to the AT). When it exits pending, it reads the button label once more.
Might need to do some id merging to make sure we didn't clobber anything.
=> Alternative pending label approach

packages/@react-aria/datepicker/src/useDatePicker.ts, packages/@react-spectrum/datepicker/src/DatePicker.tsx, packages/react-aria-components/test/DatePicker.test.js
Closes https://github.com/adobe/react-spectrum/issues/5405
To test this change, please follow these steps:
- Navigate to the DatePicker component in the storybook.
- Check the Calendar Button within the DatePicker and confirm that it appears disabled in the DOM.
=> fix: Propagate isDisabled prop from DatePicker to popover Button

packages/@react-aria/tabs/src/useTab.ts, packages/@react-spectrum/tabs/test/Tabs.test.js, packages/react-aria-components/test/Tabs.test.js
Closes https://github.com/adobe/react-spectrum/issues/5312
To test this change, please follow these steps:
- Navigate to the Tabs component in the storybook.
- Verify that each Tab component now correctly includes its specified aria-label in the DOM.
=> fix: labelable option to Tab props for aria-label support

packages/@react-spectrum/checkbox/src/Checkbox.tsx, packages/@react-spectrum/checkbox/src/CheckboxGroup.tsx
Closes #5378 
After investigating this a bit more, I don't think this is a css specificity issue. It seemed that when the `isDisabled` prop was provided to`<CheckboxGroup>`, that value was not passed to the individual `<Checkbox>` components, resulting in the absence of the `is-disabled` class in their classnames. Therefore, if you wanted to the disabled styles to be applied to a selected checkbox in a checkbox group, you would also have to directly pass `isDisabled` to that specific checkbox. 
Looking back at the commit history, it appears that this "broke" with this PR (https://github.com/adobe/react-spectrum/pull/3827). However, if you go commit before it (which is https://github.com/adobe/react-spectrum/pull/3962), you'll notice that the styling might be correct, but the `is-disabled` …
=> Fix selected checkbox fill color when checkbox group is disabled

packages/react-aria-components/docs/ComboBox.mdx, packages/react-aria-components/docs/DatePicker.mdx, packages/react-aria-components/docs/DateRangePicker.mdx, packages/react-aria-components/docs/Menu.mdx, packages/react-aria-components/docs/Select.mdx, packages/react-aria-components/src/ComboBox.tsx, packages/react-aria-components/src/DatePicker.tsx, packages/react-aria-components/src/Dialog.tsx, packages/react-aria-components/src/Menu.tsx, packages/react-aria-components/src/Popover.tsx, packages/react-aria-components/src/Select.tsx, packages/react-aria-components/test/ComboBox.test.js, packages/react-aria-components/test/DatePicker.test.js, packages/react-aria-components/test/DateRangePicker.test.js, packages/react-aria-components/test/Menu.test.js, packages/react-aria-components/test/Popover.test.js, packages/react-aria-components/test/Select.test.js
Several of our docs examples have overrides for popovers and things within popovers like listbox that are specific to the triggering component, e.g. combobox or select. These are currently using `@layer` and just overriding for the whole page, but if this CSS were reused on a page with another component containing a popover the overrides would clash.
This introduces a new `trigger` prop to the `Popover` component, which is reflected as the `data-trigger` attribute on the DOM element. This allows style overrides to be scoped based on the trigger component so they don't clash. Normally this would be done by nesting selectors but due to portals that's not possible. The `data-trigger` attribute allows that to be emulated.
=> Add data-trigger to Popover to style based on trigger component

packages/@react-aria/autocomplete/docs/useSearchAutocomplete.mdx, packages/@react-aria/combobox/docs/useComboBox.mdx, packages/@react-aria/listbox/docs/useListBox.mdx, packages/@react-aria/menu/docs/useMenu.mdx, packages/@react-aria/table/docs/useTable.mdx
Closes https://github.com/adobe/react-spectrum/issues/5356
Updates docs to clarify that React Aria hooks don't perform virtualization, but do work with virtualized lists.
=> React Aria Docs: update to clarify virtualization support

packages/dev/docs/pages/react-aria/getting-started.mdx, packages/dev/docs/src/ResourceCard.js, scripts/buildWebsite.js
Note that the actual zip file is only built when deploying the prod docs (or verdaccio), so won't work on PR builds.
=> Add starter kit download link to the docs

packages/@adobe/spectrum-css-temp/components/steplist/index.css, packages/@react-spectrum/steplist/src/StepListItem.tsx
Closes 
~This is super dumb, but doing the space ends up with a no-height line, so alignment is wrong again.
Every other character seems to be announced. So we have to do this trick~ https://stackoverflow.com/questions/46815260/hide-a-pseudo-element-from-a-screenreader
Adjusts element we point to for announcement of marker such that it doesn't include the psuedo element
=> Fix extra char read by AT

package.json, packages/@react-aria/focus/package.json, packages/@react-aria/utils/package.json, packages/@react-spectrum/provider/package.json, packages/@react-spectrum/utils/package.json, packages/dev/docs/package.json, yarn.lock
=> Upgrade clsx to v2.0.0

.parcelrc-build, Makefile, packages/@adobe/react-spectrum/src/index.ts, packages/dev/parcel-optimizer-react-client/ReactClientOptimizer.js, packages/dev/parcel-optimizer-react-client/package.json
Closes #5340
This adds React's `"use client"` directive at the top of the built files for React Aria Components and React Spectrum packages so that they can be rendered from a server component directly without needing to wrap in your own client component. That's convenient especially for things like `<Provider>` which can now go in a Next.js layout component which is typically a server component.
=> Add "use client" to components in build for Next.js app dir

packages/react-aria-components/src/GridList.tsx, packages/react-aria-components/src/Table.tsx, packages/react-aria-components/test/GridList.test.js, packages/react-aria-components/test/ListBox.test.js, packages/react-aria-components/test/Table.test.js
Table and GridList were not rendering children of custom `<DropIndicator>` elements, which might be needed to render custom visuals (e.g. svgs).
=> Render children in DropIndicators

packages/@react-aria/overlays/src/DismissButton.tsx
Noticed that the dismiss button in popovers was not working on iOS VO on the new homepage. Looks like it was caused by Tailwind's CSS reset which removes the default padding from buttons. That caused it to be zero width/height, which iOS VO will ignore. This adds an inline width and height property to ensure it is always set. Should not affect anything because it's inside a VisuallyHidden already.
=> Ensure DismissButton has a height so it works with iOS VO

packages/@react-stately/combobox/src/useComboBoxState.ts
Issue can be seen in the docs or storybook. If you select an item, and then click the button to open the listbox repeatedly, the collection changes while the menu is animating closed causing a flicker. It can even cause the popover to flip depending on the scenario. Original fix was in #4060 but this extends it to use the original collection rather than the filtered collection if `showAllItems` is true.
=> Prevent flicker from all items to filtered collection when combobox is animating closed

packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@react-aria/utils/src/index.ts, packages/@react-spectrum/button/src/Button.tsx
Closes #5519
1. Open https://reactspectrum.blob.core.windows.net/reactspectrum/399b9f9af6f93a7b8f93327aa70aa7d31d9a4fd5/storybook/iframe.html?providerSwitcher-express=false&scrolling=false&providerSwitcher-locale=&providerSwitcher-theme=&providerSwitcher-scale=&args=isPending:true&id=button--pending-spinner&viewMode=story in Firefox on Windows using NVDA or JAWS.
2. Verify that clicking each of the buttons in the example announces using the buttons accessibility name and "pending" once when the `isProgressVisible` state enters.
3. Verify that the Controlled example is named "Controlled pending" when `isPending` is set to `true` in the Actions panel 
4. Repeat using Chrome and Microsoft Edge on Windows, and using Chrome and Safari with VoiceOver on macOS.
5. Note that using Safari with …
=> #5519 [a11y] Button announces multiple times when status changes to isPending

packages/@adobe/spectrum-css-temp/components/actiongroup/index.css, packages/@react-spectrum/actiongroup/src/ActionGroup.tsx
Closes https://github.com/orgs/adobe/projects/19/views/4?pane=issue&itemId=46694245
Try the actiongroup stories with overflow="collapse" and buttonLabelBehavior="hide"
RSP
=> Fix ActionGroup icon padding when overflow="collapse" and buttonLabelBehavior="hide"

packages/@react-aria/combobox/src/useComboBox.ts, packages/@react-aria/grid/src/GridKeyboardDelegate.ts, packages/@react-aria/selection/src/ListKeyboardDelegate.ts, packages/@react-aria/selection/src/useSelectableCollection.ts, packages/@react-spectrum/tabs/src/Tabs.tsx
[Escapes](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape_static) our strings used in query selectors. Keys may be strings that are invalid as selectors, so we want to avoid errors like: `"Failed to execute 'querySelector' on 'Element': '[data-key="Apple""]' is not a valid selector."`
Smoke test affected components.
=> Escape strings used in query selectors

packages/react-aria-components/example/index.css, packages/react-aria-components/src/ListBox.tsx, packages/react-aria-components/src/Table.tsx, packages/react-aria-components/stories/index.stories.tsx, packages/react-aria-components/stories/utils.tsx, packages/react-aria-components/test/ListBox.test.js, scripts/extractStarter.mjs
Closes https://github.com/adobe/react-spectrum/issues/5488
onCellAction isn't ready for GA
Test the RAC stories in storybook and make sure `data-hovered` never shows up when using keyboard focus only in a listbox, especially in ComboBox and Select where focusOnHover is true. Also check docs to make sure onCellAction isn't mentioned anywhere
RSP
=> Fix hover in RAC ListBox and remove onCellAction

packages/tailwindcss-react-aria-components/src/index.js, packages/tailwindcss-react-aria-components/src/index.test.js
Two fixes for tailwindcss-react-aria-components:
1. Respect the `hoverOnlyWhenSupported` option in the tailwind config, which wraps native `:hover` selectors with a `@media (hover: hover)` media query so they don't apply on touch devices.
2. Make the `placeholder-shown:` variant work with the RAC `Input` component, which has `data-rac` but doesn't apply `data-placeholder`. In this case, we want both the native and the RAC version to apply without the `data-rac` check because they never overlap on the same elements.
=> Respect Tailwind hoverOnlyWhenSupported, and fix placeholder-shown with Input

packages/@react-aria/menu/src/useMenuTrigger.ts, packages/@react-spectrum/menu/src/context.ts, packages/@react-stately/combobox/package.json, packages/@react-stately/combobox/src/useComboBoxState.ts, packages/@react-stately/menu/src/index.ts, packages/@react-stately/menu/src/useMenuTriggerState.ts, packages/@react-stately/menu/src/useSubmenuTriggerState.ts, packages/@react-stately/select/package.json, packages/@react-stately/select/src/useSelectState.ts, packages/react-stately/src/index.ts
=> Separate menutrigger state

packages/@react-spectrum/button/docs/Button.mdx
=> Button docs: Remove pre-release version badge for isPending

packages/react-aria-components/src/TextField.tsx
Was missing a `/*#__PURE__*/` comment on the forwardRef call, causing it to never be tree-shaken.
=> Fix tree shaking of TextField component

packages/dev/optimize-locales-plugin/LocalesPlugin.d.ts
this pr updates types to allow passing a readonly array to the optimize-locales plugin options, e.g.:
```ts
const locales = ["de", "en"] as const
// ...
optimizeLocales.webpack({ locales })
```
=> allow passing readonly array to LocalesPlugin

packages/react-aria-components/src/DateField.tsx
To make it easier to style the disabled state, add `isDisabled` render prop and `data-disabled` attribute to `DateSegment`. Extracted from #5666
=> Add isDisabled render prop to DateSegment

packages/react-aria-components/src/Popover.tsx
Hello, I've noticed that the default value of `props.offset` for `<Popover>` component is actually `8` not `0` as [the current docs states](https://react-spectrum.adobe.com/react-aria/Popover.html#props).
https://github.com/adobe/react-spectrum/blob/80fcbf54206ca1ffb011f28fabcfc982d97bca5f/packages/react-aria-components/src/Popover.tsx#L126-L130
This PR corrects the default value of `props.offset` to 8 by re-defining the `offset` prop and omitting the originally inherited one from `PositionProps` (as a minor consequence of this, the order of the prop table in the docs is a little different)
I'm not sure if this is the best way to override the default value of some inherited props, so let me know if there's a better way.
Thanks.
1. Visit http://localhost:1234/react-aria/Popover.html#props …
=> [Docs] Fix <Popover> offset prop default value

packages/@react-spectrum/table/stories/TableDnD.stories.tsx, packages/@react-spectrum/table/stories/TableDnDExamples.tsx, packages/@react-spectrum/table/test/TableDnd.test.js, packages/@react-stately/table/src/TableCollection.ts
Closes https://github.com/adobe/react-spectrum/issues/4895
The fix ensures that when rowHeader is not present, the drag preview displays the content of the first element, excluding checkboxes and dragButtons.
1. Visit http://localhost:9003/?path=/story/tableview-drag-and-drop--drag-out-of-table-without-table-header&args=selectionStyle:highlight&providerSwitcher-express=false&strict=true
2. In the Table, drag a row.
3. Verify that the text from the first column ("First name") of the dragged row is displayed in the drag preview.
=> Fix drag preview not displaying text in TableView

packages/react-aria-components/package.json, packages/react-aria-components/src/Meter.tsx, packages/react-aria-components/src/ProgressBar.tsx, packages/react-aria-components/stories/Meter.stories.tsx, packages/react-aria-components/stories/ProgressBar.stories.tsx, packages/react-aria-components/stories/styles.css
Closes Found in testing session, can set a RAC progressbar or meter to an overflowing value which can cause funny rendering in the starter kit
Note, this is the same way we solve it in RSP https://github.com/adobe/react-spectrum/blob/4ae2831f9487958511c88b9ebe672b5650042d7e/packages/%40react-spectrum/progress/src/ProgressBarBase.tsx#L47
We could have useProgressBar return the clamped value since there is no stately associated with it, but that felt a little strange.
Check in RAC starter kit using a min value larger than value.
Check in Storybook RAC stories for two new stories, Meter and ProgressBar
=> Fix RAC progressbar and meter overflow

packages/@react-aria/selection/src/ListKeyboardDelegate.ts, packages/react-aria-components/stories/ComboBox.stories.tsx
Closes #5680
Hello, this PR includes a minimal fix for #5680 and a ComboBox story for an async-loading example.
1. Visit http://localhost:9003/?path=/story/react-aria-components--combo-box-async-loading-example&providerSwitcher-express=false&strict=true
2. Test the behavior described in the issue #5680.
=> Fix ComboBox async loading runtime error

packages/@adobe/spectrum-css-temp/components/button/skin.css
Closes #5691 
1. Open [Button > ActionButton >  Default Storybook Example](https://reactspectrum.blob.core.windows.net/reactspectrum/d98a689d6f3089695b6ea084bcd782f40059decb/storybook/index.html?path=/story/button-actionbutton--default&args=isQuiet:true&providerSwitcher-express=false) in Google Chrome or MS Edge.
2. In the Storybook Add Ons panel, set Controls > isQuiet to `true`.
3. Open Developer Tools and under the Customize and control DevTools menu button, the vertically oriented ellipsis in the upper right of the Developers Tools toolbar, select More tools > Rendering, and under Emulate CSS media feature forced-colors select `forced-colors: active`.
4. The enabled and disabled ActionButtons with `isQuiet === true` should display a border.
Enabled and Disabled Quiet ActionButtons add …
=> fix(#5691): [WHCM] ActionButton restore border for isQuiet and isQuiet + isDisabled states

packages/@react-aria/combobox/intl/fr-FR.json, packages/@react-spectrum/autocomplete/intl/es-ES.json, packages/@react-spectrum/combobox/intl/es-ES.json, packages/@react-spectrum/picker/intl/es-ES.json, packages/@react-spectrum/picker/intl/it-IT.json
1) Fix for https://github.com/adobe/react-spectrum/issues/5749
2) Additional linguistic fix from internal testing
3) Corrected couple of ellipse on it, es to make it consistent with others in same locale
=> Translations Update, please integrate

packages/@react-aria/interactions/src/index.ts, packages/@react-aria/interactions/src/useFocusVisible.ts, packages/@react-aria/interactions/test/useFocusVisible.test.js
Closes 
Discussed in testing
Renamed function to be clearer about what its purpose is. Also return a new clean up function allowing people to disconnect an iframe whenever they like without needing to unmount it
=> iFrame focus tracking setup rename

packages/react-aria-components/docs/RadioGroup.mdx
…
Looks like the default selected value in the example is an empty string, which is not the same as null. https://github.com/adobe/react-spectrum/pull/4985/files#diff-26ddea7c3bd0c2b48179af98635706a6391a01b59c936e8b497d1843a97ff202R71-R78
A more robust solution might be to validate whether the default value is one of the possible values within the radio group, but that's a bit more complicated.
Closes #5747 
1. Open https://reactspectrum.blob.core.windows.net/reactspectrum/1c8634f70d2124e57d72b2c8b8251ac0c6c4d9ad/docs/react-aria/RadioGroup.html#controlled-value
2. Verify that pressing Tab key can focus the first RadioButton in the Controlled value story.
=> fix(#5747): [react-aira: RadioGroup]: No tabindex/Can't keyboard focus to input until value is checked

packages/react-aria-components/src/utils.tsx
Closes #5764
For Form components, the property "id", was missing, so had to extend the DOMProps with SharedDOMProps.
=> Typescript: Update RAC DOMProps to extend SharedDOMProps

packages/react-aria-components/src/Calendar.tsx
Closes #3975
- [ x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ x] Filled out test instructions.
Check the storybook link locally: http://localhost:9003/?path=/story/react-aria-components--calendar-example&providerSwitcher-express=false&strict=true, select date 2024-JAN-3, open dev toolbar and inspect the selected div element. Navigate to DEC-27 __using the "up" arrow key__. With the fix applied, the element does not have `data-focus-visible`. Without the fix, the attribute is there even if the date is disabled.
=> Fix focusVisible & calendar issue #3975

.github/PULL_REQUEST_TEMPLATE.md
This PR updates the ARIA Practices link in the Pull Request template to the latest version. The previous link still redirects to the latest page, but it is more convenient to link directly to the updated resource!
=> Update ARIA Practices link in PR template to the latest version

packages/@react-aria/interactions/docs/useFocusVisible.mdx, packages/@react-aria/interactions/src/useFocusVisible.ts
=> Docs for addWindowFocusTracking

packages/react-aria-components/docs/Menu.mdx
Noticed the submenu examples had aria-labels that repeated their content. That's because we use the `textValue` as the `aria-label` of the submenu. The `textValue` doesn't get set automatically because of the function child, so this sets it in the `MyItem` reusable wrapper.
=> Automatically set MenuItem textValue from children if it is a string

packages/react-aria-components/src/ListBox.tsx, packages/react-aria-components/stories/ListBox.stories.tsx, packages/react-aria-components/test/ListBox.test.js
Closes https://github.com/adobe/react-spectrum/issues/5638
1. Visit http://localhost:9003/?path=/story/react-aria-components--list-box-hover&providerSwitcher-express=false&strict=true
2. Hover over the elements labeled "hover."
3. Check the "Actions" tab in Storybook for logged events.
Unit test were also added.
=> Add support for hover events in ListBox Option component

packages/@react-aria/utils/src/filterDOMProps.ts, packages/@react-types/shared/src/dom.d.ts, packages/react-aria-components/stories/Link.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/5633
As I mentioned in my comment below, I'm undecided about supporting the `title` attribute. 
I would like to hear your thoughts on this.
https://github.com/adobe/react-spectrum/issues/5633#issuecomment-1948396448
1. Visit http://localhost:9003/?path=/story/react-aria-components--link-example&providerSwitcher-express=false&strict=true
2. Check that the hrefLang attribute is specified.
=> Add hrefLang attribute to Link

packages/react-aria-components/docs/DatePicker.mdx, packages/react-aria-components/docs/DateRangePicker.mdx, packages/react-aria-components/src/DatePicker.tsx, packages/react-aria-components/stories/DatePicker.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/5883
Hello, this PR adds `--trigger-width` CSS variable as a popover inline style, so that users can match the width of the popover containing the calendar to that of the input group with said variable. 
The changes contained in this PR make direct references to those components already well supporting the `--trigger-width` such as [Select](https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/Select.tsx#L96-L107), [Menu](https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/Menu.tsx#L48-L58), and [Combobox](https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/ComboBox.tsx#L149-L164). …
=> Add `--trigger-width` support for DatePicker & DateRangePicker

packages/@react-types/radio/src/index.d.ts, packages/react-aria-components/stories/RadioGroup.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/5871
http://localhost:9003/?path=/story/react-aria-components--radio-group-controlled-example&providerSwitcher-express=false&strict=true
=> Add null type to Radiogroup `value` prop.

packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-aria/focus/stories/FocusScope.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/5904
I've tested with several languages, but found that not many languages present completion with the Tab key. Therefore, I have confirmed the behavior only with "Chinese Pinyin - Simplified", "Japanese - Kana", and Google IME - Japanese.
1. Open OS keyboard settings.
2. Add "Chinese Pinyin - Simplified", "Japanese - Kana", and [Google IME - Japanese](https://www.google.co.jp/ime/).
1. Navigate to the [MDN input search example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search).
2. In the second input field, type "a" to trigger a set of suggestions.
3. Press the Tab key three times to cycle through different suggestions.
4. Now, visit the [FocusScope Storybook …
=> fix: enhance FocusScope to support tab completion for IMEs

packages/dev/docs/pages/react-aria/home/ExampleApp.tsx, starters/tailwind/src/ListBox.tsx, starters/tailwind/src/Menu.tsx, starters/tailwind/src/Popover.tsx, starters/tailwind/stories/Menu.stories.tsx
This was removed from https://github.com/adobe/react-spectrum/pull/5648 before the last release.
Test docs homepage and tailwind starter storybook.
=> Add RAC submenu to homepage and tailwind starter

packages/@react-spectrum/dropzone/src/DropZone.tsx
Found during audit, pretty sure we don't want these props in RSP DropZone
=> Omit className and style prop in RSP DropZone

packages/@react-aria/textfield/src/useFormattedTextField.ts, packages/@react-spectrum/form/stories/Form.stories.tsx
=> Fix trigger onSubmit on enter for NumberField

packages/@react-spectrum/toast/docs/Toast.mdx, packages/@react-spectrum/toast/src/ToastContainer.tsx, packages/@react-spectrum/toast/src/toastContainer.css, packages/@react-spectrum/toast/test/ToastContainer.test.js, packages/@react-stately/toast/src/useToastState.ts, packages/@react-stately/toast/test/useToastState.test.js
Closes
Do we want to add additional animations to this?
Goto a Toast story and add a Toast.
- Toast should be added from the bottom.
- Multiple toasts can be shown at the same time.
- Toasts are sorted by order added.
- Toast has enter and exit animations.
- Toast should exit by timeout if defined or by close button (unless there is an action).
RSP
=> Show all toasts

packages/react-aria-components/src/TextField.tsx, packages/react-aria-components/test/TextField.test.js
Closes https://github.com/adobe/react-spectrum/issues/5930
http://localhost:1234/react-aria/TextField.html#textfield-2
=> Add readonly & required data attributes to `<TextField />`

packages/@react-aria/dnd/src/useClipboard.ts, packages/@react-aria/dnd/src/useDrop.ts, packages/@react-spectrum/dropzone/src/DropZone.tsx, packages/react-aria-components/src/DropZone.tsx, packages/react-aria-components/stories/Dropzone.stories.tsx, packages/react-aria-components/test/DropZone.test.js
Closes https://github.com/adobe/react-spectrum/issues/5938
To enable the `isDisabled` prop in DropZone, I've extended `isDisabled` support to several internal hooks. This update activates `isDisabled` for React Spectrum's DropZone as well. If this implementation poses no issues, I plan to add unit tests for it in React Spectrum's DropZone. I welcome any feedback.
1. Visit http://localhost:9003/?path=/story/react-aria-components--dropzone-with-render-props&providerSwitcher-express=false&strict=true.
2. In the Controls tab, set isDisabled to true.
3. Verify that drag-and-drop with the mouse is disabled.
4. Verify that pasting from the clipboard is not possible.
5. Verify that the DropZone cannot receive focus.
=> Add support for DropZone isDisabled prop

packages/@react-aria/tabs/docs/useTabList.mdx
Closes https://github.com/adobe/react-spectrum/issues/5972
1. Open the `useTabList` documentation page.
2. Hover over any tab in the examples.
3. Verify the cursor is now the default style, not text.
=> Update cursor style to default for Tabs in docs

packages/@adobe/spectrum-css-temp/components/helptext/index.css
Closes 
Go to the http://localhost:9003/?path=/story/textfield--with-description&args=isDisabled:true&providerSwitcher-express=false&strict=true story and disable it via controls. Hovering over the text shouldn't display the text cursor
RSP
=> Use default cursor for help text on disabled elements

packages/@react-aria/overlays/test/useModal.test.js
React changed the format of their `console.error` calls to include multiple arguments, breaking our spy. This makes it more resilient.
=> Fix test in react canary

packages/@react-aria/radio/docs/useRadioGroup.mdx
Closes https://github.com/adobe/react-spectrum/issues/6056
Hey guys I have one question.
Would it be better to just add the empty string (`''`) check over here?
https://github.com/adobe/react-spectrum/blob/9390151edf56eefcec0aa5635f34643affe10640/packages/%40react-aria/radio/src/useRadio.ts#L82-L92
to something like this?
```diff
let tabIndex: number | undefined = -1;
- if (state.selectedValue != null) {
+ if (state.selectedValue != null && state.selectedValue !== '') {
if (state.selectedValue === value) {
tabIndex = 0;
}
} else if (state.lastFocusedValue === value || state.lastFocusedValue == null) {
tabIndex = 0;
}
if (isDisabled) {
tabIndex = undefined;
}
```
http://localhost:1234/react-aria/useRadioGroup.html#controlled-value …
=> [Docs] Fix the controlled RadioGroup example

packages/@adobe/spectrum-css-temp/components/commons/focus-ring.css, packages/@adobe/spectrum-css-temp/components/textfield/skin.css
Closes #5931 
1. Open https://reactspectrum.blob.core.windows.net/reactspectrum/47d523e79482bdf96c426b1f55813d624021c431/storybook/iframe.html?scrolling=false&providerSwitcher-locale=&providerSwitcher-theme=&providerSwitcher-scale=&providerSwitcher-express=false&args=&id=textfield--default&viewMode=story in Google Chrome or Microsoft Edge
2. Using DevTools, set Rendering > Emulate CSS media feature forced-colors to forced-colors: active. It may also be helpful to set Rendering > Emulate CSS media feature prefers-color-scheme to prefers-color-scheme: dark, which will make the Highlight color a more pronounced cyan, instead than the purple that renders with forced-colors: active and prefers-color-scheme: light.
3. Set keyboard focus to the TextField input.
4. Notice that when the input …
=> fix(#5931): TextField/TextArea: fix outline thickness with forced-colors: active

packages/@internationalized/message/src/MessageDictionary.ts, packages/@internationalized/message/test/MessageDictionary.test.js, packages/@internationalized/string/src/LocalizedStringDictionary.ts, packages/@internationalized/string/test/LocalizedStringDictionary.test.js, packages/dev/optimize-locales-plugin/empty.js, packages/dev/parcel-resolver-optimize-locales/empty.js
Closes https://github.com/adobe/react-spectrum/issues/6069
Install Spectrum changes in https://stackblitz.com/edit/stackblitz-starters-6dzpek?file=readme.md and see if issue is still there.
Adobe Workfront
=> fix: gracefully treat locales removed by optimize-locales-plugin

packages/@adobe/react-spectrum/src/index.ts, packages/@react-spectrum/textfield/src/index.ts
Closes #6089 
`@adobe/react-spectrum` exports SpectrumTextFieldProps but not for TextArea.
Re-exports `SpectrumTextAreaProps`, `ItemProps`, `SectionProps` from `@adobe/react-spectrum`.
=> fix: exporting types for SpectrumTextAreaProps, ItemProps, SectionProps

packages/dev/docs/pages/react-aria/index.mdx
There's an extra closing span tag in the Tailwind tab of https://react-spectrum.adobe.com/react-aria/#example-1:
I took the screenshots with the code element zoomed out to show all of the arrow function's code.
Run `yarn start:docs`, and go to http://localhost:1234/react-aria/index.html#example-1. Click the `Tailwind` tab, and you shouldn't see the extra closing span tag anymore.
=> Remove extra closing span tag

packages/@react-aria/interactions/test/useFocusVisible.test.js, packages/@react-aria/overlays/stories/useModal.stories.tsx, packages/@react-aria/overlays/test/useModal.test.js, packages/dev/test-utils/src/testSSR.js, scripts/setupTests.js
Closes 
For the moment, we have a few too many things to fix. So because it's a deprecation warning, I'm just silencing it for now.
Things we'll need to do at some point.
Clean up remaining `import {render as ReactDOMRender} from 'react-dom';`
Dynamically swap out which act we use depending on if it's in the `react` module.
Upgrade user event and rtl once they have support?
errors are now handled differently https://github.com/facebook/react/pull/28627 we may need more error boundaries in tests, for now I've remove the check for console.error on the one which failed. I tested in the browser and it still logs the error. I've left the manual story in for the moment.
=> Fix react canary tests

packages/react-aria-components/stories/Popover.stories.tsx, packages/react-aria-components/stories/Tooltip.stories.tsx
Closes 
Found in testing, popover and tooltip RAC stories for arrow boundary offset were not displaying the overlay arrow
=> Fix story's svgs in FF

packages/react-aria-components/example/index.css, packages/react-aria-components/src/FieldError.tsx, packages/react-aria-components/stories/TextField.stories.tsx, packages/react-aria-components/test/TextField.test.js
=> Render nothing if isInvalid and no error message is provided

packages/@internationalized/date/src/calendars/PersianCalendar.ts, packages/@internationalized/date/tests/conversion.test.js, packages/@internationalized/date/tests/queries.test.js
Closes #5960, closes #3757, closes #6077, closes #5946, closes #5062.
This fixes two issues with the Persian to Gregorian and Gregorian to Persian date conversion.
1. Dates were sometimes off by one in months greater than 6, which resulted in 30 being displayed as the first day of the month.
2. The leap year calculation wasn't quite right, resulting in an incorrect number of days in the month.
This ports the code from [ICU](https://github.com/unicode-org/icu/blob/main/icu4j/main/core/src/main/java/com/ibm/icu/util/PersianCalendar.java) to perform the conversion and adds tests from all of the issues/PRs that have been raised for this issue.
1. Open calendar stories
2. Change calendar system to Persian
3. Navigate forward/backward by month and verify that months always start with 1, not 30 …
=> Fix Persian/Gregorian calendar conversion

package.json, packages/react-aria-components/test/Tabs.test.js, starters/docs/package.json, yarn.lock
types/mime dep is pulled in via starters example storybook, just need to pin to older version for now
Closes
=> Update browserlist and pin types/mime to fix build

packages/@adobe/spectrum-css-temp/components/illustratedmessage/skin.css
Updates the colors to match the figma design. 
Turns out the XD design is outdated and uses v5 colors so when reviewing, please look at the S1 figma designs instead
=> Fix Illustrated Message Colors

packages/@react-types/form/src/index.d.ts, packages/react-aria-components/src/Checkbox.tsx, packages/react-aria-components/src/ComboBox.tsx, packages/react-aria-components/src/DateField.tsx, packages/react-aria-components/src/DatePicker.tsx, packages/react-aria-components/src/Form.tsx, packages/react-aria-components/src/NumberField.tsx, packages/react-aria-components/src/RadioGroup.tsx, packages/react-aria-components/src/SearchField.tsx, packages/react-aria-components/src/Select.tsx, packages/react-aria-components/src/TextField.tsx, packages/react-aria-components/test/Form.test.js
Adds `validationBehavior` prop to RAC Form, which can propagate to child form elements via context. An individual form component's `validationBehavior` provided via prop will get precedence over the Form's.
=> RAC: Add validationBehavior to Form

packages/@react-types/label/src/index.d.ts
=> fix(#6109): SpectrumFieldProps should return labelProps that can be spread on a label or React-Spectrum Label

packages/react-aria-components/src/RadioGroup.tsx, packages/react-aria-components/stories/RadioGroup.stories.tsx, packages/react-aria-components/test/RadioGroup.test.js
Closes https://github.com/adobe/react-spectrum/issues/6054, https://github.com/adobe/react-spectrum/issues/6123
~~To implement the behavior described in https://github.com/adobe/react-spectrum/issues/6054#issuecomment-2000575049, I needed to pass `tabbable: true` to `getFocusableTreeWalker()`. This behavior is tested by the unit test, but hard to tell in the story.~~
~~Not sure if we still need to expose individual `inputRef`s for each `<Radio />` inside the group as done in https://github.com/adobe/react-spectrum/pull/5967.~~
~~Oh and should we document this behavior somewhere in the docs?~~
~~Let me know what you guys think!~~
This PR exposes `inputRef` through props in `<Radio>`, practically the same as https://github.com/adobe/react-spectrum/pull/5967.
- Visit …
=> Allow passing inputRef to RAC `<Radio>`

.circleci/config.yml
Closes 
Unblock development on main to give us space to fix React Canary version. This should be regarded as a very temporary fix.
While looking at https://github.com/adobe/react-spectrum/pull/6144 I noticed that storybook doesn't render at all. So we'll have tests and storybook to fix at a minimum.
Looks like to fix storybook we'll need to upgrade to storybook 7 https://github.com/storybookjs/storybook/issues/18331#issuecomment-1162957861
=> Detach React Canary development from Main

packages/@react-spectrum/numberfield/test/NumberField.test.js, packages/@react-stately/utils/src/number.ts
Closes [Issue#6112](https://github.com/adobe/react-spectrum/issues/6112)
Test with the same steps in the issue above
=> fix: correct floating precision in snapValueToStep

packages/@react-spectrum/combobox/src/ComboBox.tsx
Closes https://github.com/adobe/react-spectrum/issues/2154
The approach aligns with best practices for managing side effects in React, as illustrated in the [official documentation](https://react.dev/learn/synchronizing-with-effects#putting-it-all-together).
=> Fix timer cleanup on ComboBox unmount

packages/react-aria-components/src/Tooltip.tsx, packages/react-aria-components/stories/Tooltip.stories.tsx
Found during testing
Confirm that shouldFlip prop works with Tooltip.
The RAC "tooltip arrow boundary offset example" story should also show all the tooltips without flipping.
RSP
=> RAC Tooltip missing support of prop shouldFlip

packages/react-aria-components/src/TextField.tsx, packages/react-aria-components/test/TextField.test.js
Closes #6125
`yarn jest TextField`
=> Exclude id from TextField DOMProps

packages/@react-aria/focus/src/isElementVisible.ts, packages/@react-aria/select/src/HiddenSelect.tsx, packages/@react-aria/select/test/HiddenSelect.test.tsx
We should skip HiddenSelect element in Picker when tree walking to determine the next or previous focusable element. However, we should not use [data-a11y-ignore], which is used to exclude elements from aXe automated accessibility tests.
Per comments: https://github.com/adobe/react-spectrum/pull/6116#discussion_r1544017444
Closes #6130 
1. Open TableView focusable cells example: https://reactspectrum.blob.core.windows.net/reactspectrum/b783832dd2ff7bf0a85ee30f1233ef9ce370b661/storybook/iframe.html?scrolling=false&providerSwitcher-locale=&providerSwitcher-theme=&providerSwitcher-scale=&providerSwitcher-express=false&args=&id=tableview--focusable-cells&viewMode=story
2. The example app consists of a TableView in which the last row has a Picker in the second cell.
3. Press Tab to navigate …
=> fix(#6130): Ignore HiddenSelect when tree walking

packages/@react-aria/selection/src/ListKeyboardDelegate.ts, packages/react-aria-components/stories/ListBox.stories.tsx, packages/react-aria-components/test/ListBox.test.js
Closes https://github.com/adobe/react-spectrum/issues/6168
While fixing the bug, I've noticed a horizontal grid ListBox also has the same issue when navigating left and right via keyboard ('arrowLeft' and 'arrowRight'). Included unit test covers both cases.
By the way, these bugs can be seen in the docs as well
* https://react-spectrum.adobe.com/react-aria/ListBox.html#vertical-grid
* https://react-spectrum.adobe.com/react-aria/ListBox.html#horizontal-grid
* http://localhost:9003/?path=/story/react-aria-components--list-box-grid
=> Fix ListBox (grid layout) keyboard navigation TypeError

packages/@react-spectrum/autocomplete/src/searchautocomplete.css, packages/@react-spectrum/autocomplete/stories/SearchAutocomplete.stories.tsx, packages/@react-spectrum/combobox/src/combobox.css
Removes the italics font when it says "Loading..." in ComboBox and "No results" in SearchAutocomplete
=> Remove italics from ComboBox and SearchAutocomplete

package.json, scripts/setupTests.js, yarn.lock
Closes 
Test clicking on ActionButton on localdev, make sure the native focus ring doesn't appear. This bug only happened on local so must be tested there
RSP
=> Revert browserlist bump to fix native focus rings appearing on ActionButton click

packages/dev/docs/pages/react-spectrum/ssr.mdx
This PR improve the SSR doc of Next.js and Remix.
=> Improve SSR doc for Next.js and Remix

packages/@react-spectrum/menu/docs/Menu.mdx, packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js
=> Fix various imports in the docs from being set to monopackage imports

packages/react-aria-components/src/GridList.tsx, packages/react-aria-components/src/Menu.tsx, packages/react-aria-components/src/Table.tsx, packages/react-aria-components/src/TagGroup.tsx, packages/react-aria-components/src/Tree.tsx, packages/react-aria-components/test/GridList.test.js, packages/react-aria-components/test/ListBox.test.js, packages/react-aria-components/test/Menu.test.js, packages/react-aria-components/test/Table.test.js, packages/react-aria-components/test/TagGroup.test.js, packages/react-aria-components/test/Tree.test.tsx
Support for hover event handlers were added to ListBox in https://github.com/adobe/react-spectrum/pull/5777, so this adds support for `onHoverStart`, `onHoverChange`, and `onHoverEnd` to all other RAC collection items for consistency. 
Check new tests.
RSP
=> RAC: add hover events to all collection items

packages/@react-aria/dnd/src/useDrag.ts, packages/@react-aria/dnd/stories/dnd.stories.tsx, packages/@react-aria/dnd/test/dnd.test.js
For parity with `useDrop` and `useClipboard`
Check [new story](https://reactspectrum.blob.core.windows.net/reactspectrum/78be891d80b00fe7d7b910a8f54ff4dd5b7e8ce2/storybook/index.html?path=/story/drag-and-drop--draggable-disabled&providerSwitcher-express=false) and tests
RSP
=> useDrag: add support for isDisabled

patches/@parcel+transformer-css+2.0.0-canary.1565.patch
Fixes an intermittent issue where focus rings appeared on mouse interaction. This seemed to appear on some PR builds and not others, and resulted in `:focus-visible` and `:hover` pseudo classes not being compiled to the `.focus-ring` and `.is-hovered` classes that we apply. The native `:focus-visible` pseudo class also applies on programmatic focus, which is why we see the issue.
The problem was caused by a patch we had applied to skip this compilation on the React Aria tailwind-based homepage. Since all files load this config from the same package.json file, mutating it caused unintentional changes when compiling files other than the one we were looking for. It appeared intermittent because files are compiled in a different order on each build. The fix is to clone the config and modify …
=> Fix intermittent focus ring compilation issue in docs

packages/@react-aria/menu/src/index.ts, packages/@react-aria/menu/src/useSubmenuTrigger.ts, packages/@react-spectrum/menu/src/ContextualHelpTrigger.tsx, packages/@react-spectrum/menu/src/Menu.tsx, packages/@react-spectrum/menu/src/SubmenuTrigger.tsx, packages/@react-stately/menu/src/index.ts, packages/@react-stately/menu/src/useMenuTriggerState.ts, packages/@react-stately/menu/src/useSubmenuTriggerState.ts, packages/react-aria-components/src/Menu.tsx
=> Submenu: remove `UNSTABLE_` prefix from Submenu hooks

packages/@react-spectrum/meter/chromatic/Meter.chromatic.tsx, packages/@react-spectrum/meter/docs/Meter.mdx, packages/@react-spectrum/meter/src/Meter.tsx, packages/@react-spectrum/meter/stories/Meter.stories.tsx, packages/@react-types/meter/src/index.d.ts
This adds the [`"informative"`](https://spectrum.adobe.com/page/meter/#Informative-variant) option to `variant`, and makes it the default. This is in line with Spectrum guidelines. Previously, `variant` was required and `"informative"` was not an option.
This is just a non-breaking Typescript change, since the correct styles were already there.
Check storybook and docs.
RSP
=> Meter: add support for informative variant

packages/@react-spectrum/overlays/src/Overlay.tsx
Fixes an issue found in testing yesterday where when closing a submenu while keyboard focused, the page would get scrolled to the bottom.
Open an RSP Submenu and navigate via keyboard, then close the submenu. You should no longer get scrolled to the bottom of the page.
=> Fix portal container assignment from context

packages/@react-types/shared/src/inputs.d.ts
Fixes #5739
Adds a default to the type parameter that we added to the `Validation` type for backwards compatibility with older releases that people might have been using in custom components.
=> Backwards compatibility for Validation type

packages/react-aria-components/docs/Form.mdx, packages/react-aria-components/src/index.ts
https://reactspectrum.blob.core.windows.net/reactspectrum/46e2823cd67090f84a9379b6955254bbd55ade45/docs/react-aria/Form.html#validation-behavior
=> export FormContext and document validationBehavior

packages/@adobe/spectrum-css-temp/components/button/index.css, packages/@react-spectrum/actiongroup/chromatic/ActionGroup.chromatic.tsx
Closes 
Test ActionGroup stories with overflowMode="collapse" and buttonLabelBehavior="hide" and make sure the icon only buttons aren't too wide
RSP
=> Increase specificity so that ActionGroup collapsed text only icons don't render extra padding

packages/@react-stately/datepicker/src/utils.ts
In our Next.js example app, when selecting a range in a DateRangePicker with reversed order, the page would crash with an error about a missing localized string. In that setup, the optimize-locales-plugin is used to remove all localized strings from the JS bundle, and they are injected into the page during SSR. However, this particular code used the dictionary imported from the JS bundle, and did not load the global dictionary from the window like other parts of the code.
=> Fix crash in DateRangePicker when using SSR optimized localized strings

packages/react-aria-components/docs/ColorArea.mdx, packages/react-aria-components/docs/ColorPicker.mdx, packages/react-aria-components/docs/Dialog.mdx, packages/react-aria-components/docs/Popover.mdx
Fixes 2 issues found in testing:
1. On iPhone, the ColorPicker had blue text at a small font size due to browser default styles.
2. The ColorPicker popover overflowed instead of scrolling. This was actually a problem with all popovers in the RAC docs (e.g. date picker with small browser viewport) as well. Please test all RAC components with popovers in the docs in addition to ColorPicker.
=> Fix styling of ColorPicker examples in RAC docs

packages/react-aria-components/docs/Form.mdx, packages/react-aria-components/src/Checkbox.tsx, packages/react-aria-components/src/ComboBox.tsx, packages/react-aria-components/src/DateField.tsx, packages/react-aria-components/src/DatePicker.tsx, packages/react-aria-components/src/Form.tsx, packages/react-aria-components/src/NumberField.tsx, packages/react-aria-components/src/RadioGroup.tsx, packages/react-aria-components/src/SearchField.tsx, packages/react-aria-components/src/Select.tsx, packages/react-aria-components/src/TextField.tsx
Noticed in audit. FormContext should work like the other contexts in RAC. It should be a slotted value accepting all Form props/ref. Form should consume it, and then also provide its own props via children (not every component does that part right now). Also added some examples to the advanced customization section of the docs.
=> Make FormContext match our other contexts

packages/react-aria-components/src/DropZone.tsx, packages/react-aria-components/stories/Dropzone.stories.tsx
Noticed that we added [support for isDisabled](https://github.com/adobe/react-spectrum/pull/5958
) for RAC DropZone but it wasn't added to the render props and also wasn't showing `data-disabled` in the docs as a result
=> Add isDisabled to RAC DropZone render props

packages/dev/docs/pages/react-spectrum/ssr.mdx
`next.config.js` only allows commonjs syntax, not ESM. And you need to install the glob package before you can use it.
=> Fix next.js config syntax

packages/react-aria-components/src/Breadcrumbs.tsx, packages/react-aria-components/stories/Breadcrumbs.stories.tsx, packages/react-aria-components/test/Breadcrumbs.test.js
For parity with RSP breadcrumbs: https://react-spectrum.adobe.com/react-spectrum/Breadcrumbs.html#props
Check [story](https://reactspectrum.blob.core.windows.net/reactspectrum/667d87586ef39bd10014cff4723f2ee11770c668/storybook/index.html?path=/story/react-aria-components--breadcrumbs-example&args=autoFocusCurrent:true&providerSwitcher-express=false), [docs prop table](https://reactspectrum.blob.core.windows.net/reactspectrum/667d87586ef39bd10014cff4723f2ee11770c668/docs/react-aria/Breadcrumbs.html#props),  and test.
=> RAC Breadcrumbs: add support for autoFocusCurrent

starters/tailwind/package.json
Closes https://github.com/adobe/react-spectrum/issues/6268
=> Update tailwind starter to use latest

.storybook/custom-addons/descriptions/register.js
Hey guys, I've noticed a warning previously not existed before SB7 is being printed when I open the browser inspector:
I searched around a bit, and it turned out `key` prop that had been fed into `<AddonPanel>` was now generating the warning so I removed it as recommended [here](https://github.com/storybookjs/storybook/pull/23792/files#diff-66fd0ef2f3df056f95276eb1d7f4ba662f32a1ed1a494f0b6c932ef1da9a832aR310-R314).
Releted Storybook issues:
* https://github.com/storybookjs/storybook/issues/23782
* https://github.com/storybookjs/storybook/pull/23792
* https://github.com/storybookjs/addon-designs/pull/207
=> [SB7] Remove deprecated key prop in descriptionAddon

packages/@react-stately/calendar/package.json, packages/@react-stately/calendar/src/types.ts, packages/@react-stately/calendar/src/useRangeCalendarState.ts, packages/@react-types/calendar/src/index.d.ts
=> ts-strict  calender fix types

packages/react-aria-components/stories/Popover.stories.tsx, packages/react-aria-components/stories/Tooltip.stories.tsx
I've noticed SB7 deprecated the use of `argTypes.defaultValue`, and it encourages users to use `args` instead.
This PR only contains `Popover` and `Tooltip` stories as these were the one contained in https://github.com/adobe/react-spectrum/pull/5936. 
However, a quick search shows that there are several other stories (`dnd.stories.tsx`, `Button.stories.tsx`, etc) also make use of `argTypes.defaultValue` (just wanted to bring awareness of this).
* https://github.com/storybookjs/storybook/issues/26076#issuecomment-1959762784
* https://storybook.js.org/docs/faq#why-are-my-args-no-longer-displaying-the-default-values (hashtag seems broken unfortunately)
=> [SB7] Move deprecated argTypes.defaultValue to args (Tooltip & Popover)

packages/react-aria-components/src/ListBox.tsx, packages/react-aria-components/src/Menu.tsx, packages/react-aria-components/test/ListBox.test.js, packages/react-aria-components/test/Menu.test.js
Related to #5748, follow-up to #6436 but for `Section`.
https://github.com/adobe/react-spectrum/pull/6436#issuecomment-2130061245
Use `Section` within a `Menu` or `ListBox`, ensure the rendered `<section>` has the `data-rac` data attribute.
=> Ensure `Section` has `[data-rac]` data attribute

packages/@react-stately/color/src/Color.ts, packages/@react-stately/color/src/useColorWheelState.ts, packages/@react-stately/color/test/Color.test.tsx
Closes https://github.com/adobe/react-spectrum/issues/6202
=> Fix: Hue Normalization

packages/react-aria-components/test/Calendar.test.js
Closes 
Apparently we can have 7 - 2 (prev/next) = 5 days worth of the previous month. This was only apparent today, though it also happened in Feb. I now set the test to a specific month so we have more predictability
=> Fix calendar test

packages/@react-aria/utils/src/useResizeObserver.ts, packages/@react-aria/virtualizer/src/ScrollView.tsx, packages/@react-spectrum/card/stories/GridCardView.stories.tsx
Fixes #5152
Virtualizer could sometimes crash when resizing due to scrollbars appearing and disappearing causing an infinite layout loop. This appeared to be fixed in some cases but still occurred in CardView. I believe I've finally gotten to the root of the issue. 🤞 
What happened was that the `updateSize` function changed on every render because the `useCallback` depended on `contentSize`. This function was then called from a `useLayoutEffect` after every render, and also passed into `useResizeObserver`. `useResizeObserver` has a `useEffect` in it which creates the `ResizeObserver`. This invalidates when the `onResize` function passed into it changes, which in this case was happening after every render. This meant we were creating and destroying ResizeObservers very frequently.
This …
=> Fix ResizeObserver crash in Virtualizer due to scrollbar flapping

packages/@react-aria/overlays/src/useOverlayPosition.ts
This fixes the performance issue introduced by #6451 when opening a ComboBox or Picker (or any virtualized collection inside a popover). Since virtualizer layout occurs during render, it can now occur prior to the popover being fully positioned. Without a max-height, this resulted in all collection items being rendered to the DOM. We already cap the max-height to the size of the viewport just before positioning, but didn't have any max-height before that (in the initial render). Adding `100vh` here fixes the problem. 🤞 that it doesn't break anything else.
=> Cap overlay max height to 100vh on initial render

packages/@react-spectrum/listbox/src/ListBoxBase.tsx, packages/@react-stately/layout/src/ListLayout.ts
Closes #6490
Alternative approach to #6490. Adds an option to `ListLayout` instead of modifying the collection.
=> Always render ListBox section headers in RSP for dividers

packages/@react-spectrum/table/src/TableViewBase.tsx, packages/@react-stately/layout/src/TableLayout.ts
Closes 
Found in testing
Go to any RSP resizable TableView, enter resizing mode through the column header menu. Nubbin should fully display and not be cut off.
=> Fix TableView resize nubbin

packages/@react-stately/list/src/useSingleSelectListState.ts
The `SingleSelectListState<T>.selectedItem` type should be nullable as the `useSingleSelectListState` is assigning it to null where there is no default `selectedKey` as seen below.
```tsx
let selectedItem = selectedKey != null
? collection.getItem(selectedKey)
: null;
```
=> fix: SingleSelectListState.selectedItem type should be nullable

packages/@react-aria/grid/src/useGridSelectionCheckbox.ts, packages/react-aria-components/stories/GridList.stories.tsx, packages/react-aria-components/test/GridList.test.js
Opening for feedback on behavior. When rendering a GridList or Table with `selectionBehavior="replace"` that also has checkboxes, clicking the checkboxes currently replaces the selection with that row (the same as clicking anywhere on the row). This PR changes the behavior so the checkbox always behaves like a checkbox, and toggles the selection, while clicking on the row still replaces the selection. This is kind of a hybrid between replace and toggle, and actually matches how Windows Explorer behaves as well.
[Storybook link for testing](https://reactspectrum.blob.core.windows.net/reactspectrum/c477443b87aa3e21bb63925a2a5a142fec81753f/storybook/index.html?path=/story/react-aria-components--grid-list-example&args=selectionMode:multiple;selectionBehavior:replace&providerSwitcher-express=fa …
=> Selection checkbox should always toggle regardless of selectionBehavior

packages/@react-spectrum/color/src/ColorSwatch.tsx
=> fix: prevent classname to be overwritten in color swatch component

packages/@react-aria/loading/README.md, packages/@react-aria/loading/index.ts, packages/@react-aria/loading/package.json, packages/@react-aria/loading/src/index.ts, packages/@react-aria/loading/src/useLoadOnScroll.ts, packages/@react-aria/virtualizer/package.json, packages/@react-aria/virtualizer/src/Virtualizer.tsx, packages/@react-spectrum/card/test/CardView.test.js, packages/@react-spectrum/combobox/test/ComboBox.test.js, packages/@react-spectrum/listbox/test/ListBox.test.js, packages/@react-spectrum/table/src/TableViewBase.tsx, packages/@react-spectrum/table/test/Table.test.js, packages/@react-stately/layout/src/TableLayout.ts, packages/react-aria-components/package.json, packages/react-aria-components/src/Table.tsx, packages/react-aria-components/src/TableLayout.ts, packages/react-aria-components/stories/Table.stories.tsx, packages/react-aria-components/test/Table.test.js
=> useLoadMore support in RAC Table

packages/@react-stately/layout/src/ListLayout.ts, packages/@react-stately/layout/src/TableLayout.ts, packages/react-aria-components/stories/ListBox.stories.tsx, packages/react-aria-components/stories/utils.tsx
Reported by @rostero1 in https://github.com/adobe/react-spectrum/pull/6518#issuecomment-2178438003
In ListLayout with variable row heights, sometimes a large empty space could appear at the end of the list. This was due to the `validRect` not being invalidated properly when the height of an item changed. When this occurs, all items after that item need to be repositioned.
For clarity, I've also renamed two properties:
* `lastValidRect` is now called `validRect` - this is the rectangle that is currently valid. We can reuse previously laid out items within this rectangle.
* `validRect` is now called `requestedRect` - this is the rectangle that has been requested for layout so far. After a layout pass, `validRect` will equal `requestedRect`.
=> Fix incremental layout with variable heights

packages/@react-stately/selection/src/SelectionManager.ts
Closes 
Found while testing https://github.com/adobe/react-spectrum/pull/6631 where selecting the first item in the Virtualized Table would cause the select all checkmark to render checked instead of indeterminate
=> Fix SelectAll logic for falsy keys

packages/@react-stately/layout/src/GridLayout.ts, packages/react-aria-components/stories/ListBox.stories.tsx
If `minItemSize` and `maxItemSize` were the same, no items would appear due to a divide by zero error.
=> Fix divide by zero in GridLayout

packages/dev/docs/pages/react-aria/routing.mdx, packages/dev/docs/pages/react-spectrum/routing.mdx
Fixes #6413
The types exposed by TanStack Router have changed since the docs were originally written.
This keeps `href` as a string. We could also consider typing it as an object as shown here but not sure if everyone would want that or not? https://github.com/adobe/react-spectrum/issues/6587#issuecomment-2224235268
=> Update TanStack Router example in docs

packages/@react-spectrum/actionbar/src/ActionBar.tsx, packages/@react-spectrum/actionbar/stories/ActionBar.stories.tsx, packages/@react-types/actionbar/src/index.d.ts
Closes #6528
Note: In ActionGroup `buttonLabelBehavior` defaults to `show`. ActionBar had it hardcoded to `collapse`, so that is its default in ActionBar.
ActionBar stories have control for `buttonLabelBehavior` to test the three states.
RSP
=> ActionBar expose ActionGroup's `buttonLabelBehavior` prop

packages/@react-aria/datepicker/src/useDateSegment.ts
Closes https://github.com/orgs/adobe/projects/19/views/4?pane=issue&itemId=70985842
This could occur when tapping on an already focused date segment. This moved the cursor between letters. Then when entering a character, Chrome would fire a composition event rather than a regular text entry event. Composition events are not cancelable, so chrome would mutate the DOM. Later, React would try to update the DOM but it was no longer in the expected state and this resulted in a crash.
Fix is to always collapse the selection to the start of the segment. We already did this on initial focus, but tapping on the segment again could change the selection. Now we listen for selection change events and collapse them if they are inside the segment.
=> Fix crash in TimeField on Android

packages/@react-spectrum/color/docs/ColorField.mdx, packages/@react-spectrum/color/test/ColorField.test.js, packages/@react-stately/color/src/useColorChannelFieldState.ts
Fixes crash when clearing a ColorField that displays a single channel, or when passing in a `null` controlled `value` prop. The behavior now is that a `null` value causes the field to be blank, and clearing it goes back to being blank. This will emit a `null` value via `onChange`, so if multiple channel fields are synced via the same value, clearing one of them will result in all of them being cleared. When inside a `ColorPicker`, we ignore null values (or we will after #6364), so in that case, the value will be reset back to the previous value instead.
=> Support null values in ColorField with channel prop

packages/@react-types/overlays/src/index.d.ts, packages/@react-types/tooltip/src/index.d.ts, packages/react-aria-components/src/Tooltip.tsx
Closes #6713
Make sure that RSP TooltipTrigger and RAC Tooltip have the default value 'top' for placement.
=> Update Tooltip docs to reflect correct default placement value

packages/@react-spectrum/listbox/test/ListBox.test.js, packages/@react-stately/virtualizer/src/Virtualizer.ts, packages/dev/docs/src/DocSearch.js
We saw this issue in doc search due to section keys changing. Virtualizer saw the child keys as already visible even though their parents changed and didn't create new views for them. Now we treat parent key changes the same way we treat deletes. The view will then be re-created under its new parent. Added a test for this case when a listbox item changes sections.
In doc search we also make this more efficient by using only the title as the key rather than including the index, so that when sections are re-ordered the keys remain consistent and views can be reused.
=> Fix virtualizer bug when an item changes parents

packages/@react-aria/collections/src/BaseCollection.ts, packages/@react-aria/collections/src/Document.ts, packages/@react-aria/collections/src/index.ts, packages/@react-aria/menu/src/useMenuTrigger.ts, packages/react-aria-components/src/Table.tsx, packages/react-aria-components/src/Tree.tsx
* Renamed `NodeValue` to `CollectionNode` as discussed in #6640.
* Removed empty import
=> 3.36 audit

packages/@react-aria/dnd/stories/VirtualizedListBox.tsx, packages/@react-aria/virtualizer/src/ScrollView.tsx, packages/@react-aria/virtualizer/src/Virtualizer.tsx, packages/@react-spectrum/listbox/src/ListBoxBase.tsx
The listbox in the async case and the Docs search on mobile were rendering with very small scroll rects, causing only a couple of items to be visible at a time even though there was actually more vertical real estate available. This was because of the `sizeToFit` logic [here](https://github.com/adobe/react-spectrum/blob/9b48ec5d528adeba1a96592945459726def7ba56/packages/%40react-aria/virtualizer/src/ScrollView.tsx#L166) being called by the ResizeObserver that would then set the height of the scroll rect to the content size at the time (placeholder height). Before the changes made in https://github.com/adobe/react-spectrum/pull/6508, `updateSize` would be called much more frequently when `contentSize` changed hence why this wasn't a problem before. We think that we actually don't need …
=> Get rid of sizeToFit to fix cases where listbox rect wasn't updating properly

packages/@react-stately/layout/src/GridLayout.ts
Reported by doc cloud. `getItem` can return `null`, and we didn't account for that. This would be caught by TS strict. I would have enabled it for this package but it was a bit much right before release...
=> Fix crash in GridLayout when a persisted key is deleted

packages/@spectrum-icons/color/package.json, packages/@spectrum-icons/ui/package.json, packages/@spectrum-icons/workflow/package.json, yarn.lock
Did not touch express since those are just svgs that we pre-process. The others are actual dependencies.
Closes https://github.com/adobe/react-spectrum/discussions/6028
=> Update icon packages for Apache 2 relicense

examples/rsp-next-ts/next.config.mjs, examples/rsp-next-ts/pages/_app.tsx, examples/rsp-next-ts/pages/index.tsx, scripts/buildI18n.js
RSP ColorSwatch uses RAC ColorSwatch and thus needs the i18n strings from RAC 
Run verdaccio locally and build the next app locally
RSP
=> Include RAC i18n strings with RSP LocalizedStringProvider

packages/dev/eslint-plugin-rsp-rules/rules/sort-imports.js, packages/dev/eslint-plugin-rsp-rules/test/sort-imports.test.js
Got tired of manually sorting imports. Now `eslint --fix` and the fix command in your ide can fix it automatically.
Note: view diff without whitespace changes for easier viewing.
=> Implement autofix for eslint sort imports rule

packages/react-aria-components/docs/Switch.mdx
No issue, sorry, just found that described prop is missing from the example
Check that docs have been updated
=> docs: add missing parameter to controlled Switch example 

packages/@adobe/spectrum-css-temp/components/inputgroup/skin.css, packages/@adobe/spectrum-css-temp/components/search/index.css
=> Fix ComboBox quiet readonly styling and SearchField padding right specificity 

packages/@adobe/spectrum-css-temp/components/table/skin.css, packages/@react-spectrum/table/src/TableViewWrapper.tsx, packages/@react-spectrum/table/stories/Table.stories.tsx
Closes [issue](https://github.com/orgs/adobe/projects/19/views/4?pane=issue&itemId=37183649)
Added control "disabledBehavior" to TableView stories.
Easiest to test is you set `selectionMode` to "multiple" because the checkboxes will be disabled in both modes.
Test with "dynamic with disabled keys" story.
Test DnD with "Drag between tables" story.
Didn't see a story to test expandable row with.
* Confirm "selection" is the default for TableView. (Should be opposite ListView with is "all".)
* Confirm "all" shows the cell content text as disabled.
* Confirm "all" prevents DnD, focus, hover, actions, etc.
RSP
=> Add prop disabledBehavior to RSP TableView api

packages/@react-spectrum/s2/src/Tabs.tsx, packages/@react-spectrum/s2/stories/Tabs.stories.tsx
A few things I found while reviewing the styles
Should we have some other overrides to make it easier to directly styles the tabPanel with things like `overflow` and `display`?
Closes
=> Tabs layout

.storybook-s2/docs/Illustrations.jsx, .storybook-s2/docs/Illustrations.mdx, .storybook-s2/preview.tsx, packages/dev/parcel-transformer-icon/IconTransformer.js
Adds a page to storybook similar to the list of icons, but for gradient and linear illustrations.
=> Add docs for S2 illustrations

.storybook-s2/docs/Migrating.jsx, packages/@react-spectrum/s2/src/NumberField.tsx, packages/@react-spectrum/s2/stories/NumberField.stories.tsx, packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/numberfield.test.ts.snap, packages/dev/codemods/src/s1-to-s2/src/codemods/changes.ts
The isCollapsed option was removed from the Figma designs since it is not accessible (hit targets too small). Added hideStepper option from v3 as well.
=> Remove isCollapsed from S2 NumberField and add hideStepper

packages/@react-spectrum/s2/src/Provider.tsx, packages/@react-spectrum/s2/src/page.macro.ts, packages/@react-spectrum/s2/src/style-utils.ts
A `<Provider>` with no `colorScheme` prop defined defaults to `light dark`. However, when `page.css` is imported, it defines the color scheme on the `<html>` element. In that case, the root Provider should take the color-scheme from the page rather than overriding it with `light dark`. A use case for this is when setting the locale but still using `page.css`.
This generates an additional very low specificity rule that defines default values for `--lightningcss-light` and `--lightningcss-dark`, the variables used to determine the color-scheme. When `page.css` is present, it overrides this rule. Provider does not set any color-scheme by default, and will then default to using one of these rules.
Since this is setting lightningcss variables it could affect content outside our Provider that …
=> Do not define a default color-scheme on Provider if one is defined at the page level

packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/multi-collection.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/multi-collection.test.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/transforms.ts
Previously, we were only checking implemented parent collection components of Items, so you may end up with a case like this:
```
<SearchAutocomplete label="Search with Autocomplete">
// TODO(S2-upgrade): Couldn't automatically detect what type of collection component this is rendered in. You'll need to update this manually.
<Item>Aerospace</Item>
</SearchAutocomplete>
```
but this is a valid case where we don't want to leave a comment.
=> Codemod: don't affect Items in unimplemented collection components

packages/@react-spectrum/s2/src/Dialog.tsx
(review without whitespace)
Simple fix for now is to reset `OverlayTriggerStateContext` in dialog contents so it doesn't pick up the `isOpen` state from the parent DialogTrigger, which is meant to only affect the trigger button. However this means that users can't use `OverlayTriggerStateContext` to control the dialog (e.g. close it). Maybe fine for now in S2, but this is documented in RAC so I did not make the change there.
Perhaps in the future we could add an `isExpanded` render prop to Button, Link, and other components that could trigger dialogs/menus/etc. That could be used to style this state. Right now we unfortunately conflate `isPressed` with `isExpanded` in PressResponder, and changing that would be breaking... This requires more thought.
=> Fix buttons in S2 dialogs stuck in hover state

packages/@react-spectrum/s2/src/ActionButton.tsx
turns out we were using `<Text>` from RAC and not from S2. you can't really tell in the stories that it's been fixed without applying a custom width to the buttons with longer text
=> fix: truncate text in S2 ActionButton

packages/@react-aria/selection/src/useSelectableCollection.ts, packages/@react-aria/tabs/src/TabsKeyboardDelegate.ts, packages/@react-spectrum/picker/intl/en-US.json, packages/@react-spectrum/picker/test/Picker.test.js, packages/@react-spectrum/table/src/TableViewWrapper.tsx, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-spectrum/tabs/test/Tabs.test.js, packages/@react-stately/collections/src/CollectionBuilder.ts, packages/@react-stately/toggle/src/useToggleState.ts, packages/@react-types/checkbox/src/index.d.ts
Includes changes from:
- https://github.com/adobe/react-spectrum/pull/6832
- https://github.com/adobe/react-spectrum/pull/6430
- https://github.com/adobe/react-spectrum/pull/6796
- https://github.com/adobe/react-spectrum/issues/5996
- https://github.com/adobe/react-spectrum/pull/3836
=> Revert reverts from before latest release

packages/@react-spectrum/tree/src/TreeView.tsx
Closes 
Test the TreeView docs and make sure the checkbox is properly centered in the row
RSP
=> Fix TreeView so that the row height always matches the chevron height

packages/@react-spectrum/tree/docs/TreeView.mdx
- adds `maxWidth` to examples
- dedupes `items` across examples to reduce clutter
=> docs: clean up TreeView docs

packages/dev/codemods/src/s1-to-s2/src/index.ts, packages/dev/codemods/src/s1-to-s2/src/utils/installPackage.ts
- Updates two links
- Fixes package install step, where `undefined` was getting used as an argument
1. `cd packages/dev/codemods && yarn build`
2. Change directories to an example app
3. `node ../../packages/dev/codemods/dist/index.js s1-to-s2`
4. Ensure the `@react-spectrum/s2` and `unplugin-parcel-macros` packages got properly installed, and the links are correct
=> fix: S2 upgrade assistant links and install step

packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx, packages/@react-spectrum/tooltip/test/TooltipTrigger.test.js
Closes [#6546](https://github.com/adobe/react-spectrum/issues/6546)
1. Add multiple tooltip triggers inside a scrollable container
2. Focus on a button to make the tooltip appear
3. Scroll the container, the tooltip should not stick to the screen on scroll
Adobe - DX - Campaign
=> Fix tooltip stuck to screen on scroll

package.json, yarn.lock
Fixes #4158
This updates Lightning CSS to use the new `[content-hash]` feature contributed by @rubberpants from the Analytics team. This enables multiple versions of React Spectrum's CSS to coexist on the same page without conflicts. Rather than hashing only the file name (which is the same between RSP versions), this uses the file contents as the hash so that whenever the CSS changes the class names also change.
=> Use content hashes in CSS modules

packages/@react-spectrum/s2/src/Card.tsx, packages/@react-spectrum/s2/src/CardView.tsx, packages/@react-spectrum/s2/stories/CardView.stories.tsx, packages/@react-stately/list/src/useListState.ts, packages/@react-stately/selection/src/SelectionManager.ts, packages/@react-types/shared/src/collections.d.ts, packages/react-aria-components/src/GridList.tsx, packages/react-aria-components/src/ListBox.tsx, packages/react-aria-components/src/Virtualizer.tsx
Three updates for S2 CardView:
1. The previous behavior when using the `Shift` key to select multiple items in Waterfall layout was a bit unpredictable. Shift selection normally adds all items in collection order between the first and last item you clicked on. With waterfall layout, this doesn't make sense because the items may be rendered out of order (according to the shortest column). Now the `LayoutDelegate` interface supports overriding the `getKeyRange` behavior of `SelectionManager`. WaterfallLayout uses this to implement a spacial algorithm that selects items contained by the rectangle formed between the first and last item you shift clicked on.
2. When switching layout options like t-shirt size and density, the entire CardView would be unmounted and re-mounted. This was due to …
=> Improve shift selection and responsive layout in S2 CardView

packages/@react-spectrum/s2/src/ProgressCircle.tsx, packages/@react-spectrum/s2/stories/ProgressCircle.stories.tsx
This updates the S2 ProgressCircle component to be implemented with SVG instead of divs. This simplifies it a lot because we can use the `<circle>` element and the `stroke-dasharray`/`stroke-dashoffset` properties to easily generate percentage-based arcs. Additionally, this brings the design in line with Spectrum's latest update, with rounded corners on the blue fill rather than straight edges, which were impossible to implement with the previous approach of using masking divs.
This also simplifies the indeterminate animation. Instead of manual keyframes, this uses two simultaneous animations on the circle fill element: one for the rotation, and one to adjust the `stroke-dashoffset` representing the percentage. I took the original keyframes and calculated the corresponding rotation and …
=> Implement S2 ProgressCircle with SVG

packages/@react-spectrum/s2/src/Card.tsx, packages/@react-spectrum/s2/src/CardView.tsx
Fixes a bug found during testing where in Safari the heights of the cards would become massive, only in the quiet variant, and this could result in a "maximum update depth exceeded" crash. That resulted from the cards getting larger and larger each render, triggering more renders, etc.
I don't quite understand the reason this happened, only in Safari, but the difference between quiet and non-quiet cards that seemed to cause it was `overflow: visible` vs `overflow: clip`. We need `visible` so the shadow on the preview shows. Adding `contain: layout` seems to fix this, but again, still not sure why exactly. I also noticed that the issue is fixed in Safari Tech Preview, even without this change. 🤷
=> Fix CardView quiet heights in Safari

packages/@react-spectrum/s2/src/Card.tsx, packages/@react-spectrum/s2/src/CardView.tsx
Three changes from conversation with design:
1. Make the white inner stroke for selected quiet cards with highlight selection more subtle, by making it partially transparent. I believe this still passes contrast, and it also matches the overlay around the checkbox when that appears.
2. Prevent the gap between the title and description from expanding when an action button is present. The action button is taller than a single line of text so it makes the grid row taller, making it appear like there's more space. Now the button overlaps the gap and doesn't change the height of the row.
3. When resizing a CardView with waterfall layout, the cards seemed to jump around since we always chose the shortest column to append to during layout and this could change due to small changes in text …
=> S2 Card updates

packages/@react-aria/disclosure/src/useDisclosure.ts, packages/@react-spectrum/accordion/chromatic/Accordion.stories.tsx, packages/@react-spectrum/accordion/src/Accordion.tsx, packages/@react-spectrum/accordion/stories/Accordion.stories.tsx, packages/@react-spectrum/s2/src/Accordion.tsx, packages/@react-spectrum/s2/src/Disclosure.tsx, packages/@react-spectrum/s2/stories/Accordion.stories.tsx, packages/@react-stately/disclosure/src/index.ts, packages/@react-stately/disclosure/src/useDisclosureGroupState.ts, packages/react-aria-components/src/Disclosure.tsx, packages/react-aria-components/src/index.ts
This adds a DisclosureGroup (aka Accordion) component to RAC. It allows a single Disclosure to be expanded by default, and an `allowsMultipleExpanded` prop to allow multiple. You can also control the `expandedKeys` similar to our other collection components. This brings parity with the existing Accordion alpha in S1.
(We discussed only supporting `expandedKey`, non-plural, but I thought of a use case for controlling multiple - e.g. if you have a multi-step process that starts all expanded and collapses each step after you completed it. This also matches the previous Accordion API in S1, and is more consistent with our other components. The downside is that it's slightly more annoying for single select usecases.)
Ideally there'd also be a `disallowCollapseAll` prop to force at least one to …
=> Add DisclosureGroup component to RAC

packages/@adobe/spectrum-css-temp/components/accordion/index.css, packages/@react-spectrum/accordion/docs/Accordion.mdx, packages/@react-spectrum/accordion/docs/Disclosure.mdx, packages/@react-spectrum/accordion/src/Accordion.tsx, packages/@react-spectrum/s2/src/Accordion.tsx, packages/@react-spectrum/s2/src/Disclosure.tsx, packages/@react-spectrum/tree/test/TreeView.test.tsx, packages/react-aria-components/docs/Checkbox.mdx, packages/react-aria-components/docs/Disclosure.mdx, packages/react-aria-components/docs/DisclosureGroup.mdx, packages/react-aria-components/docs/GridList.mdx, packages/react-aria-components/docs/Table.mdx, packages/react-aria-components/docs/Tree.mdx, packages/react-aria-components/src/Disclosure.tsx, packages/react-aria-components/src/Tree.tsx, packages/react-aria-components/src/index.ts, packages/react-aria-components/stories/Disclosure.stories.tsx, packages/react-aria-components/test/Tree.test.tsx
Basic docs just including a single example and props table for now. To be expanded later.
=> Add basic docs for Accordion, DisclosureGroup, Disclosure, and Tree

packages/@react-aria/interactions/docs/useMove.mdx
Closes https://github.com/adobe/react-spectrum/issues/4056
=> Fix useMove docs to be more clear when events start

packages/@react-spectrum/accordion/chromatic-fc/Accordion.stories.tsx, packages/@react-spectrum/accordion/chromatic/Accordion.stories.tsx, packages/@react-spectrum/s2/stories/Accordion.stories.tsx
found when running chromatic for testing
Run chromatic-fc and confirm the story matches the baseline, i.e. there is an expanded disclosure.
In chromatic the s1 and s2 accordion stories are separated and the s1 stories match baseline from a month ago.
RSP
=> fixes - Accordion Chromatic and Chromatic-FC regressions

packages/@react-spectrum/s2/src/Button.tsx, packages/@react-spectrum/s2/src/Content.tsx, packages/@react-spectrum/s2/src/Dialog.tsx, packages/@react-spectrum/s2/src/TagGroup.tsx, packages/@react-spectrum/s2/stories/CardView.stories.tsx
Dialog and TagGroup were using the wrong ImageContext. It got moved and probably had an old one due to merge conflicts.
LinkButton was never updated with the new `data-rsp-slot=text` attribute needed for the selector change.
=> Fix S2 Dialog, TagGroup, and LinkButton

packages/@react-spectrum/s2/src/Card.tsx
`undefined` was getting cast as a string and used as an id
Check Card/CardView stories and ensure no undefined id's
=> fix(Card): fix undefined id in Card

packages/@react-stately/selection/src/Selection.ts, packages/@react-stately/selection/src/SelectionManager.ts, packages/react-aria-components/test/ListBox.test.js
Closes https://github.com/adobe/react-spectrum/issues/7076
In the linked story, try doing 'Shift' key selection with a range that includes Item 0. Try with keyboard and mouse.
Before: https://reactspectrum.blob.core.windows.net/reactspectrum/e87ee28db0d1b4c6fda9064c3ad29a835f12a78e/storybook/index.html?path=/story/react-aria-components--virtualized-list-box-grid
After: https://reactspectrum.blob.core.windows.net/reactspectrum/62d1c065447ae50286f1fc9a32b02b56c8daa034/storybook/index.html?path=/story/react-aria-components--virtualized-list-box-grid
=> fix selection with falsy keys

packages/@react-spectrum/actionbar/docs/ActionBar.mdx, packages/@react-spectrum/actionbar/src/ActionBar.tsx, packages/@react-spectrum/actionbar/stories/ActionBar.stories.tsx, packages/@react-spectrum/actionbar/test/ActionBar.test.js
No associated Github issue
In ActionBar/DisabledKeys story, select a table row item and see that the Edit action button in the ActionBar is disabled.
=> Pass through ActionBar disabledKeys to ActionGroup

packages/@react-spectrum/s2/src/Icon.tsx, packages/@react-spectrum/s2/src/index.ts, packages/dev/parcel-transformer-s2-icon/IconTransformer.js
Realized we had a bug in the S2 icon transformer: it generated imports for SkeletonWrapper and useSkeletonIcon internal utilities that weren't exported, so couldn't be used in custom icons. Instead of exporting these, I added a single `createIcon` helper function that centralizes all of the icon logic in one place. This has the benefit that we export fewer internals, and also reduces bundle size since we aren't duplicating the same code in every icon.
=> Centralize S2 icon wrapper

package.json, yarn.lock
We have a resolution for "browserslist" at 4.23, but a recent Babel update now requires 4.24 where a new API was introduced. This broke the [production docs build](https://app.circleci.com/pipelines/github/adobe/react-spectrum/22644/workflows/c4151e11-88d2-4bc8-9af6-2b175592f352/jobs/354890), which does not have a lock file. Not sure exactly why we have a resolution (it was introduced with [Storybook 7](https://github.com/adobe/react-spectrum/pull/6150)), but this fixes it for now.
=> Bump browserslist resolution to 4.24

packages/@react-spectrum/s2/stories/Meter.stories.tsx
Closes 
S2 Meter docs story should have the proper width 
RSP
=> Fix Meter docs story so it renders with the proper width

.storybook-s2/preview.tsx
Reported in slack
Go to S2 storybook, switch to dark mode, and open "show code" for any component example in the docs
RSP
=> Temporary fix for S2 storybook crash when showing code in dark mode

packages/dev/ts-plugin/package.json, packages/dev/ts-plugin/src/index.js, tsconfig.json, yarn.lock
When TypeScript auto imports `@react-spectrum/s2/style` (or `../style` when working inside our repo), it does not include `with {type: 'macro'}` automatically, which causes runtime errors, so you always have to go manually add it. This adds a small TypeScript language server plugin to add the import attribute automatically. We can publish this as a package and others using macros can add it to their `tsconfig.json` to enable it in their projects as well.
=> TypeScript plugin to add macro import attribute to auto imports

packages/dev/docs/pages/react-aria/routing.mdx, packages/dev/docs/pages/react-spectrum/routing.mdx
In the integration of the `tanstack-router` package in the docs, the `router.buildLocation` should accept an object instead in order for client-side routing to work as expected.  
Reference:
https://github.com/TanStack/router/blob/main/packages/react-router/src/RouterProvider.tsx#L49
=> docs: fix tanstack router useHref example

packages/react-aria-components/src/Checkbox.tsx, packages/react-aria-components/test/Checkbox.test.js
Closes 
* https://github.com/adobe/react-spectrum/issues/7070
* Do i need to add reviewers manually?
=> fix: [RAC] Checkbox applies data attributes to both the input and the label

packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/interactions/stories/usePress.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/7157
Go to the "Link on press" story in the usePress stories. Verify that tapping on the Adobe logo in the story opens a new tab on all devices 
RSP
=> Fix usePress when taps happen on Links with non plain text content

packages/@internationalized/number/src/NumberParser.ts, packages/@internationalized/number/test/NumberParser.test.js
Closes https://github.com/adobe/react-spectrum/issues/7168
=> fix: update getSymbols in NumberParser to support roundingIncrement

packages/@react-aria/test-utils/src/table.ts, packages/@react-spectrum/table/test/TestTableUtils.test.js
Closes 
100 items was causing multiple interactions to take almost half a second to process. This is not accurate to real life as we have no virtualization in those tests.
In addition, we no longer have transitions on tables, so can remove the timeout for that in our test util. We can add it back in conditionally if we end up needing it.
=> Decrease timeouts in test utils

packages/@react-spectrum/s2/src/TableView.tsx
Reported in slack
Go to S2 table and test it when isQuiet and you scroll the row contents to the right. The text should not peek out from behind the checkbox
RSP
=> Mask the contents of a non-selected scrolled row for a quiet table

packages/react-aria-components/src/Dialog.tsx, packages/react-aria-components/test/Dialog.test.js
Related to #5748, like #6436 or #6452 but for `Dialog`.
Use `Dialog`, the rendered `<section>` doesn't have the `data-rac` attribute.
=> fix: ensure `Dialog` has the `data-rac` attribute

examples/s2-parcel-example/src/App.js, examples/s2-webpack-5-example/src/App.js
fix from testing
run the test apps
Click the "Check connectivity" button to open dialog
close the dialog
RSP
=> fix(examples): s2 dialog's weren't closing

packages/@react-aria/disclosure/docs/anatomy.svg, packages/@react-aria/disclosure/docs/useDisclosure.mdx, packages/@react-spectrum/accordion/docs/Accordion.mdx, packages/react-aria-components/docs/Disclosure.mdx, packages/react-aria-components/docs/DisclosureAnatomy.svg, packages/react-aria-components/docs/DisclosureGroup.mdx, packages/react-aria-components/docs/DisclosureGroupAnatomy.svg
done:
- actually i don't think this is an issue. it's showing how to build reusable wrapper and then it shows how to use it right underneath where we do actually render it
=> docs: follow-up on accordion docs from testing

packages/@react-aria/button/src/useButton.ts
Closes https://github.com/adobe/react-spectrum/issues/7207
pass `href` props to span tag which uses `useButton`
for example this codesandbox implements the span tag button (but this uses the `useButton` which is before correction)
https://codesandbox.io/p/sandbox/reverent-ives-hl88v2
=> fix: useButton href condition

starters/tailwind/stories/Menu.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/7242
Our tailwind starter 'Menu' component already renders a Popover:
https://github.com/adobe/react-spectrum/blob/37fbf024aa8483106b97b3f8a857bc74bfc58664/starters/tailwind/src/Menu.tsx#L19-L25
so we don't need to render a RAC popover in the submenu story. This was causing useSafelyMouseToSubmenu to not work properly.
Test moving mouse to submenu in tailwind starter storybook,
=> fix: tailwind starter submenu story

packages/@react-spectrum/s2/src/page.macro.ts, packages/@react-spectrum/s2/style/spectrum-theme.ts
This makes the S2 CSS significantly smaller by using `calc(X * var(--s2-scale))` to implement touch scaling instead of precalculating two separate rules for each value. The `--s2-scale` variable is set either when importing `page.css` or `Provider`.
=> refactor: Use calc to implement S2 touch scale

.storybook-s2/docs/Colors.jsx, .storybook-s2/docs/StyleMacro.jsx, .storybook-s2/docs/color.macro.ts
Adds a list of all of the color values available in the style macro, along with a description and examples of each of the typographic scales. Let's see if we can get people to stop using the `<Heading>` and `<Text>` components for everything. 😂 
Also added an example of the `focusRing` utility.
=> docs: Add docs for style macro color and typography values, and focus ring utility

packages/@react-spectrum/s2/src/ContextualHelp.tsx, packages/@react-spectrum/s2/src/Picker.tsx, packages/@react-spectrum/s2/src/ProgressBar.tsx
- prevent the focus ring around links from getting cut off in contextual help
- add outline to the picker button in hcm
- indeterminate progress bar loads from right to left in RTL
see tickets:
- https://github.com/orgs/adobe/projects/19/views/4?pane=issue&itemId=75558862
- https://github.com/orgs/adobe/projects/19/views/4?pane=issue&itemId=77272909
- https://github.com/orgs/adobe/projects/19/views/4?pane=issue&itemId=52424970
=> chore: more s2 bug fixes

packages/@adobe/spectrum-css-temp/components/accordion/index.css
Fixes chevron being hidden in apps that use 
```css
* {
box-sizing: border-box;
}
```
i.e. our Next.js example
=> fix: add `box-sizing: content-box` Accordion chevron

packages/@react-spectrum/s2/src/SegmentedControl.tsx
Fixes case where Segmented Control text was showing above any Dialog open on top of it.
=> fix: remove z-index from SegmentedControl text

examples/s2-parcel-example/src/Lazy.js, examples/s2-webpack-5-example/src/Lazy.js
Closes 
should fix the segmented control layout issues found in the example apps by applying isJustified since there's a custom width
=> chore: add isJustified to segmented control in s2 example apps

packages/@react-spectrum/style-macro-s1/src/style-macro.ts
Prefixes class names produced by the S1 style macro with `s1-` to avoid class name collisions with S2 style macro when used on the same page.
=> fix: prefix S1 style macro class names

packages/@internationalized/date/tests/conversion.test.js, packages/@internationalized/number/test/NumberParser.test.js
=> chore: test for time conversion edge case and fuzzy test numeral systems

packages/@react-spectrum/toast/stories/Toast.stories.tsx
=> fix: Toast examples in iframes

examples/rsp-cra-18/src/sections/NavigationExamples.tsx, examples/rsp-next-ts-17/pages/index.tsx, examples/rsp-next-ts/pages/index.tsx, packages/@adobe/react-spectrum/src/index.ts, packages/@react-spectrum/accordion/chromatic/Accordion.stories.tsx, packages/@react-spectrum/accordion/chromatic/Disclosure.stories.tsx, packages/@react-spectrum/accordion/docs/Accordion.mdx, packages/@react-spectrum/accordion/docs/Disclosure.mdx, packages/@react-spectrum/accordion/src/Accordion.tsx, packages/@react-spectrum/accordion/src/index.ts, packages/@react-spectrum/accordion/stories/Accordion.stories.tsx, packages/@react-spectrum/accordion/stories/Disclosure.stories.tsx, packages/@react-spectrum/accordion/test/Accordion.ssr.test.js, packages/@react-spectrum/accordion/test/Accordion.test.js, packages/@react-spectrum/s2/src/Disclosure.tsx, packages/@react-spectrum/s2/stories/Accordion.stories.tsx
- Updates v3 `DisclosureHeader` to be `DisclosureTitle` to match S2 API
- Updates S2 Disclosure JSDoc
- Remove controlled stories from S2 Accordion storybook docs build
=> fix: Accordion release fixes

packages/@react-aria/tag/docs/useTagGroup.mdx, packages/react-aria-components/docs/TagGroup.mdx
Closes 
[`useTagGroup`](https://react-spectrum.adobe.com/react-aria/useTagGroup.html) page had missed APG link about grid even though [`TagGroup`](https://react-spectrum.adobe.com/react-aria/TagGroup.html) has it, so I added it.
=> docs: add APG grid link to useTagGroup doc

packages/@react-types/shared/src/dom.d.ts
=> chore: Revert exactOptionalPropertyTypes id support

packages/react-aria-components/docs/Dialog.mdx, packages/react-aria-components/docs/Modal.mdx
Adds docs for `<Button slot="close">` within a RAC Dialog, added in #7352. This is a simpler way to create a close button without needing to manually wire up the close to the onPress via render props.
=> docs: Document RAC Dialog close button slot

.circleci/config.yml, examples/s2-parcel-example/src/App.js, examples/s2-vite-project/src/App.tsx, examples/s2-webpack-5-example/src/App.js, starters/tailwind/src/ToggleButton.tsx, starters/tailwind/src/ToggleButtonGroup.tsx, starters/tailwind/stories/ToggleButtonGroup.stories.tsx
=> chore: Add ActionButtonGroup and ToggleButtonGroup to example apps and tailwind starter kit

packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/actiongroup.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/actiongroup.test.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/changes.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/codemod.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/transforms.ts
* Converts `<ActionGroup selectionMode="none">` to `<ActionButtonGroup>`
* Converts `<ActionGroup selectionMode="single | multiple">` to `<ToggleButtonGroup>`
* Converts `key` to `id` where needed
* Converts dynamic collections (with `items` prop and function child) to `items.map`, adding implicit `key` and `id` props where needed
* Converts `onAction` on root to `onPress` function on each item that calls the original `onAction` with the key
* Converts `disabledKeys` on the root to `isDisabled` prop on each item
* Comments out props that aren't supported yet, related to collapse behavior
=> feat: Add codemod for ActionGroup

packages/@react-spectrum/datepicker/test/DatePicker.test.js
If the defaultValue is on daylight savings time and the user clears the value while in a time zone on standard time, the DatePicker's time zone will change to standard time. I think this is the correct behavior, however, the test is written to always expect "PDT" Pacific Daylight Savings Time, which means it will fail when we're on standard time.
Closes #7399 
Run `yarn test packages/@react-spectrum/datepicker/test/DatePicker.test.js` from the first Sunday in November to the second Sunday in March, and all tests should pass.
=> fix: DatePicker.test fails with daylight savings change (#7399)

packages/@internationalized/date/src/conversion.ts, packages/@internationalized/date/src/string.ts, packages/@internationalized/date/tests/conversion.test.js, packages/@internationalized/date/tests/string.test.js
Follow up from #6542. This handles BC dates in our parsing and stringification functions.
=> fix: Handle more BC date cases

packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-spectrum/color/src/ColorThumb.tsx, packages/@react-spectrum/color/test/ColorArea.test.tsx, packages/@react-spectrum/color/test/ColorPicker.test.js, packages/@react-spectrum/color/test/ColorSlider.test.tsx, packages/@react-spectrum/color/test/ColorWheel.test.tsx, packages/@react-spectrum/icon/src/Icon.tsx, packages/@react-spectrum/icon/src/UIIcon.tsx, packages/@react-spectrum/provider/src/Provider.tsx, packages/@react-spectrum/provider/src/index.ts, packages/@spectrum-icons/ui/scripts/generateIcons.cjs, packages/dev/test-utils/package.json, packages/dev/test-utils/src/renderOverride.js, yarn.lock
=> chore: revert export provider context

packages/@react-spectrum/s2/stories/Menu.stories.tsx
Makes the menu selection group story a more real-world example
=> docs: Improve Menu selection group story

packages/dev/docs/pages/releases/2024-11-20.mdx
=> docs: Add note about RAC Section deprecation to release notes

packages/@react-spectrum/s2/style/style-macro.ts
Closes 
Lost too much time to missing an import with type=macro. no one else should suffer the same
=> chore: throw when macros are called not as a macro

packages/@react-stately/calendar/src/useCalendarState.ts, packages/react-aria-components/test/Calendar.test.js
In Calendar, selecting an unavailable date with keyboard selected the previous available date. Now it does not change the selection.
Closes #5692
The issue itself and the modification can be tested on the Spectrum Calendar story page.
=> fix: In Calendar, selecting an unavailable date with keyboard should not change the current selection

packages/@adobe/spectrum-css-temp/components/accordion/index.css
Previously the style only affected the accordion when it was expanded.
=> fix(Accordion): add box-sizing: content-box Accordion chevron

examples/s2-parcel-example/src/App.js, examples/s2-parcel-example/src/Lazy.js, examples/s2-parcel-example/src/index.html, examples/s2-vite-project/src/App.tsx, examples/s2-vite-project/src/Lazy.tsx, examples/s2-webpack-5-example/src/App.js, examples/s2-webpack-5-example/src/Lazy.js
from testing
Changes:
- Updated popover example to use Popover. Do we want it styled like S1 popovers? The implemented minimal changes,
- Added an example of CustomDialog
- Changed ButtonGroup to have a maxWidth of the view width so the buttons will wrap on mobile.
- Added viewport metadata to the parcel example app
**Possible Bug**: If we don't define `size` on CustomDialog it takes the full screen width.
For the Popover and CustomDialog dialog changes those can be tested on desktop.
For the parcel example app please test on mobile for the viewport and ButtonGroup changes. The viewport test is pickers open below the trigger.
When testing the webpack app, is there a ResizeObserver error on scroll down? I thought it was related to the ButtonGroup change, but I removed the change and it …
=> fix: S2 examples Popover and add CustomDialog

packages/react-aria-components/src/Select.tsx
Closes https://github.com/adobe/react-spectrum/issues/7447
`Select` Component is not allowing to browser autofill to fill saved user values in the dropdowns. 
Issue - `autoComplete` property is not being passed by `Select` to child component `HiddenSelect`.
Ref - The same thing is done by [Picker](https://github.com/adobe/react-spectrum/blob/b0f15697245de74ebc99ab3d687f5eb3733d3a34/packages/%40react-spectrum/picker/src/Picker.tsx#L182C9-L182C21)
This PR fixes this bug.
There is no react aria form stories to test out the issue. But I have added a [sandbox link ](https://codesandbox.io/p/sandbox/hungry-dan-sv87ql) to check the issue.
=> FIX- #7447: Passing autoComplete prop from Select to underlying child component

packages/@react-aria/overlays/src/usePreventScroll.ts
Fixes #7131
See explanation of the issue: https://github.com/adobe/react-spectrum/issues/7131#issuecomment-2519060112
I can't reproduce the original issue that the touchend handler was added for described in the comments anymore. Maybe fixed in newer iOS versions. The onFocus handler seems to be sufficient now.
=> fix: Remove onTouchEnd handler in iOS usePreventScroll

packages/@react-spectrum/s2/src/Tabs.tsx, packages/react-aria-components/src/Tabs.tsx
Closes 
An infinite loop and wrong items in the tablist could occur if a collection was provided as a child of the TabPanel because we provide a Custom Collection Renderer context, which was leaking down into the TabPanels children. This stops that from happening unintentionally
This could be observed in the S2 Popover story for 'control center' where a menu was used inside a tabpanel
=> fix: Tabs infinite loop

packages/@react-aria/utils/src/scrollIntoView.ts, packages/react-aria-components/stories/Menu.stories.tsx
Closes #7037
I've added a new story `MenuScrollPaddingExample`.
Here's a video showing the fixed behavior. Menus don't have footers so I had to add a `div` outside with absolute positioning to demo the scroll bottom also working.
https://github.com/user-attachments/assets/29cd7eb1-bc14-4130-8bad-7fa8b996f058
=> fix(scrollIntoView): respect scroll padding

packages/@react-spectrum/utils/src/Slots.tsx, packages/@react-spectrum/utils/test/Slots.test.js
In many cases when SlotsProvider rerenders it triggers all context consumers in its subtree to rerender too even when the context value hasn't changed.
We have a drag to resize type interaction that was triggering all View and ActionGroup components to rerender on each update. I tracked it down to these two components using useSlotProps which reads from context. SlotsProvider rerendering doesn't keep a stable context value because it creates a new empty object each time.
I verified that this change stopped triggering these renders and reduced render time from 28ms to .5ms with 30-40 SlotsConsumers (through useSlotProps hook) in subtree. Exact savings will depend entirely on how many slot consumers are in the subtree and how expensive they are to render.
New unit tests will fail against …
=> fix: make empty SlotsProvider context stable

packages/@react-aria/utils/src/useGlobalListeners.ts, packages/@react-spectrum/s2/src/Menu.tsx
The refactor to usePress to remove the custom hit testing (#7427) broke S2's press scaling on menu triggers because menus open on mouse down, and when the underlay appears it covers the trigger button and the browser fires pointerleave immediately. This issue is unique to S2 because RAC already overrides `isPressed` on the trigger button to true, but in S2 we disabled that so that the press scaling doesn't get "stuck" while the menu is open. Now we can listen for pointerup on the document in onPressStart in S2 ourselves, and it should only remain scaled while the mouse is down.
One slight difference vs before is that if you mouse down on the button and drag away it remains in the scaled state instead of removing it like our other buttons. Is this ok or should we add more logic to handle …
=> fix: S2 menu press scaling

packages/@react-spectrum/s2/src/ActionButton.tsx, packages/@react-spectrum/s2/src/ActionButtonGroup.tsx, packages/@react-spectrum/s2/src/Button.tsx, packages/@react-spectrum/s2/src/CloseButton.tsx, packages/@react-spectrum/s2/src/Divider.tsx, packages/@react-spectrum/s2/src/Field.tsx, packages/@react-spectrum/s2/src/Link.tsx, packages/@react-spectrum/s2/src/Menu.tsx, packages/@react-spectrum/s2/src/Meter.tsx, packages/@react-spectrum/s2/src/ProgressBar.tsx, packages/@react-spectrum/s2/src/ProgressCircle.tsx, packages/@react-spectrum/s2/src/ToggleButton.tsx, packages/@react-spectrum/s2/src/bar-utils.ts, packages/@react-spectrum/s2/src/style-utils.ts, packages/@react-spectrum/s2/stories/Link.stories.tsx, packages/@react-spectrum/s2/stories/ProgressCircle.stories.tsx, packages/@react-spectrum/s2/stories/utils.tsx, packages/@react-spectrum/s2/style/spectrum-theme.ts, packages/@react-spectrum/s2/style/tokens.ts
This adds a new `staticColor="auto"` variant, alongside the existing white and black options. The auto variant automatically swaps between white and black based on the background color of the container it is placed within. The container must have the `--s2-container-bg` variable set for this to work, which we already set on the page, and in components like cards, modals, and popovers.
In the style macro theme, there is a new `transparent-overlay` series of colors at varying levels of opacity, which matches the `transparent-black` and `transparent-white` series but with a calc to automatically swap between them.
The `color` property also supports an `auto` option that does the same thing, but also includes `self(backgroundColor)` in addition to `var(--s2-container-bg)` so that it is based …
=> feat: Add staticColor="auto" variant

packages/@react-spectrum/s2/src/Menu.tsx, packages/@react-spectrum/s2/stories/Menu.stories.tsx
For cases where you have a menu of links but still need to display which one is selected.
Use the Publish and Export story, and set the selection mode in controls
=> fix(s2): Display checkmark on selected menu items that are links

.storybook-s2/docs/StyleMacro.jsx, packages/@react-spectrum/s2/src/InlineAlert.tsx
There is no max width defined in tokens anymore. Users can specify their own if needed.
=> fix(s2): Remove maxWidth from InlineAlert

packages/@react-aria/form/src/useFormValidation.ts, packages/react-aria-components/test/RadioGroup.test.js
Since disabled elements aren't natively validated by the browser, we would previously run into a case where if the last radio in a radio group was disabled, the error message for the radio group would be blank.
In the [S2 Form story](https://reactspectrum.blob.core.windows.net/reactspectrum/84769c9967497886225f8e7f2b00424078f3a257/storybook-s2/index.html?path=/story/form--example&args=isRequired:!true), submit the form. Verify that the radio group (Favorite pet) has an error message.
=> fix(form): skip native validation on disabled form elements

packages/@react-spectrum/s2/src/Field.tsx
In small width fields, the ContextualHelp would wrap to a new line if the widest checkbox item was smaller than the Label + ContextualHelp. 
Before:
After:
=> fix(S2): ContextualHelp in Field wrapping to new line

packages/@react-spectrum/s2/src/Button.tsx, packages/@react-spectrum/s2/style/index.ts, packages/@react-spectrum/s2/style/spectrum-theme.ts
=> feat: add gradient variants to Button

packages/react-aria-components/src/Button.tsx, packages/react-aria-components/test/Button.test.js
Closes 
from https://github.com/adobe/react-spectrum/issues/6197
This will disable implicit and explicit form submission for pending buttons of type="submit"
=> fix: disable form submission for isPending

packages/@react-spectrum/menu/test/MenuTrigger.test.js, packages/@react-spectrum/s2/test/Menu.test.tsx, packages/@react-spectrum/tree/docs/TreeView.mdx, packages/dev/docs/pages/blog/accessible-color-descriptions.mdx, packages/dev/docs/pages/blog/building-a-button-part-1.mdx, packages/dev/docs/pages/blog/building-a-button-part-2.mdx, packages/dev/docs/pages/blog/building-a-button-part-3.mdx, packages/dev/docs/pages/blog/building-a-combobox.mdx, packages/dev/docs/pages/blog/date-and-time-pickers-for-all.mdx, packages/dev/docs/pages/blog/drag-and-drop.mdx, packages/dev/docs/pages/blog/how-we-internationalized-our-numberfield.mdx, packages/dev/docs/pages/react-aria/home/ExampleApp.tsx, packages/dev/docs/pages/releases/2020-11-30.mdx, packages/dev/docs/pages/releases/2021-02-17.mdx, packages/dev/docs/pages/releases/2023-08-09.mdx, packages/react-aria-components/docs/Menu.mdx, packages/react-aria-components/test/Menu.test.tsx, starters/tailwind/stories/Menu.stories.tsx
fixit
check docs links
check examples where Twitter renamed to X
RSP
=> Fix: broken links in docs and renaming Twitter to X

packages/@react-spectrum/s2/src/Button.tsx
Closes 
Test pending/transition into pending state for both `genai` and `premium` gradient buttons with various `fillStyles` and `staticColors` set. 
RSP
=> fix: Update gradient buttons so that outline and fill styles are the same when pending

packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-spectrum/dialog/stories/Dialog.stories.tsx, packages/@react-spectrum/menu/test/MenuTrigger.test.js
Closes https://github.com/adobe/react-spectrum/issues/7471
Test the RAC Modal example in the docs with Talkback and make sure you can still move focus around via swipes. Will need smoke tests in general to make sure nothing else is broken, note that anything use case that would restore focus if focus escaped focus containment won't work in Android Chrome Talkback
RSP
=> fix: Fix Talkback focus cursor movement when inside Dialogs

packages/dev/optimize-locales-plugin/LocalesPlugin.js
=> fix: Use absolute path resolution for empty.js in locales plugin

packages/@react-spectrum/s2/src/ComboBox.tsx, packages/@react-spectrum/s2/src/Menu.tsx, packages/@react-spectrum/s2/src/Picker.tsx, packages/@react-spectrum/s2/style/spectrum-theme.ts
* Flips the link out icon in menu items in RTL locales. Found in testing and checked with design.
* Adds a prop to hide the link out icons in menu items, requested by shell. This is useful when all of the items in a menu open in a new tab, and an icon on every item looks silly. This prop is applied at the global menu level rather than on individual menu items.
* Updated the alignment of menu items in multi-section menus to reserve space for icons, selection indicators, etc. on a per-section basis rather than across the entire menu. For example in the selection group example the section without selection is now no longer indented due to the other sections. Same thing if one section has icons and another does not. This was also requested by shell.
=> feat: S2 Menu design updates

packages/@react-aria/autocomplete/src/useAutocomplete.ts, packages/@react-aria/selection/src/useSelectableCollection.ts, packages/react-aria-components/test/AriaAutocomplete.test-util.tsx, packages/react-aria-components/test/Autocomplete.test.tsx
Found when testing Autocomplete with S2 components
Tests should be sufficient, tested before and after the code changes to confirm that they caught the issues. If you want to test manually, the event leak can be tested by constructing a story in the S2 storybook using Autocomplete and seeing if the Storybook keyboard shortcuts like "O" aren't triggered when typing those letters in the Autocomplete. 
The backspacing issue can be tested in the "Autocomplete disabled key" RAC story. Type "r", backspace, and press ArrowDown. The first item should be focused at this point
RSP
=> fix: Autocomplete event leak and erroneous item focus after backspacing 

packages/react-aria-components/docs/Autocomplete.mdx, packages/react-aria-components/docs/SearchField.mdx, packages/react-aria-components/src/index.ts, scripts/extractStarter.mjs
This adds initial docs for the new RAC Autocomplete component. Just a single example and a prop table for now. More to come we progress.
=> docs: Add initial Autocomplete docs

packages/@react-spectrum/s2/src/CardView.tsx, packages/@react-spectrum/s2/src/TableView.tsx, packages/@react-spectrum/s2/src/Tabs.tsx, packages/@react-spectrum/s2/src/TabsPicker.tsx, packages/@react-stately/selection/src/types.ts, packages/react-aria-components/src/index.ts
=> chore: Update JSDocs and apis for release

packages/@react-spectrum/s2/src/ActionBar.tsx
Small fix from testing. Transitioning only the `transform` property prevents animating the width when scrollbars appear. Removed opacity animation because it isn't necessary since the table/cardview clips it.
=> fix(s2): Improve ActionBar transition when scrollbars are visible

packages/@react-aria/autocomplete/package.json, packages/@react-aria/autocomplete/src/useAutocomplete.ts, packages/@react-aria/interactions/src/createEventHandler.ts, packages/@react-aria/searchfield/src/useSearchField.ts, packages/@react-aria/textfield/src/useTextField.ts, packages/@react-types/color/src/index.d.ts, packages/@react-types/shared/src/dom.d.ts, packages/@react-types/textfield/src/index.d.ts, packages/react-aria-components/src/Autocomplete.tsx, packages/react-aria-components/test/Autocomplete.test.tsx, yarn.lock
=> fix: Properly clear Autocomplete wrapped SearchField when "x" button is pressed

packages/@adobe/spectrum-css-temp/components/tags/index.css, packages/@react-spectrum/tag/chromatic/TagGroup.stories.tsx, packages/@react-spectrum/tag/stories/TagGroup.stories.tsx
Previously if you tried to use Tags with icons and without icons in the same TagGroup, they would not be vertically aligned. This seems to be a valid use case within Spectrum guidelines, so we want to ensure they can be used together without being misaligned.
Check new story and chromatic.
=> fix(TagGroup): ensure Tags with and without icons are aligned vertically

packages/@react-aria/test-utils/src/menu.ts, packages/@react-aria/test-utils/src/types.ts, packages/@react-spectrum/combobox/docs/ComboBox.mdx, packages/@react-spectrum/list/docs/ListView.mdx, packages/@react-spectrum/listbox/docs/ListBox.mdx, packages/@react-spectrum/menu/docs/MenuTrigger.mdx, packages/@react-spectrum/picker/docs/Picker.mdx, packages/@react-spectrum/table/docs/TableView.mdx, packages/@react-spectrum/tabs/docs/Tabs.mdx, packages/@react-spectrum/tree/docs/TreeView.mdx, packages/react-aria-components/docs/GridList.mdx, packages/react-aria-components/docs/ListBox.mdx, packages/react-aria-components/docs/Menu.mdx, packages/react-aria-components/docs/Table.mdx, packages/react-aria-components/docs/Tabs.mdx, packages/react-aria-components/docs/Tree.mdx
=> chore: Update test util doc examples so they don't error out

packages/@react-spectrum/toast/docs/Toast.mdx, packages/@react-spectrum/toast/src/ToastContainer.tsx, packages/@react-spectrum/toast/stories/Toast.stories.tsx
Removed 'start' options to be in line with Spectrum guidelines.
=> fix(Toast): update toast placement options

.storybook-s2/docs/Icons.jsx, .storybook-s2/docs/Illustrations.jsx, .storybook-s2/docs/Intro.jsx, .storybook-s2/docs/MDXLayout.jsx, .storybook-s2/docs/Migrating.jsx, .storybook-s2/docs/StyleMacro.jsx, packages/@react-spectrum/s2/src/Skeleton.tsx, packages/@react-spectrum/s2/stories/ActionButton.stories.tsx, packages/@react-spectrum/s2/stories/unsafe.css, packages/@react-spectrum/s2/style/__tests__/style-macro.test.js, packages/@react-spectrum/s2/style/style-macro.ts
Due to several bugs in Safari's implementation of CSS cascade layers, we need to remove `all: revert-layer` from style macro generated CSS. This was added to prevent global CSS resets from overriding S2 styles. Unfortunately, these bugs prevent us from using this reliably. Instead we will recommend either removing global resets and applying the necessary styles locally, or manually adding your resets into a lower layer. See internal RSP v2 PR for this as well.
This also makes the `UNSAFE_overrides` layer we previously recommended unnecessary, because unlayered styles always win over layered ones.
You can see several places where I already had to deal with this, e.g. Storybook's default docs CSS winning over ours because it is unlayered. Luckily there is a way to disable that styling.
=> fix(s2): Remove `all: revert-layer` to avoid Safari bugs

packages/react-aria-components/docs/Autocomplete.mdx
1. Visit https://react-spectrum.adobe.com/react-aria/Autocomplete.html#anatomy
1. Click the `SearchField` link
=> RAC: Fix broken link in new `Autocomplete` docs

packages/@react-spectrum/s2/style/__tests__/style-macro.test.js, packages/@react-spectrum/s2/style/style-macro.ts
Extra `.` class left over from the `all: revert-layer` change. Now unused.
=> fix: Remove extra class from style macro

packages/@react-aria/interactions/src/useFocusVisible.ts, packages/@react-spectrum/s2/stories/Popover.stories.tsx, packages/@react-spectrum/s2/test/SearchField.test.tsx, packages/react-aria-components/src/Group.tsx
=> fix: (WIP) Fix autocomplete searchfield focus ring

packages/@react-aria/interactions/src/useFocusVisible.ts, packages/@react-aria/menu/src/useMenuItem.ts, packages/@react-spectrum/s2/stories/Popover.stories.tsx, packages/@react-spectrum/s2/test/SearchField.test.tsx, packages/react-aria-components/example/index.css, packages/react-aria-components/src/Menu.tsx, packages/react-aria-components/stories/utils.tsx, packages/react-aria-components/test/Autocomplete.test.tsx
Closes 
1. Navigate to https://reactspectrum.blob.core.windows.net/reactspectrum/5500dd71c424604132f88afcb3df3eb8335d991e/storybook-s2/index.html?path=/story/popover--autocomplete-popover
2. Open the Popover
3. Keyboard navigate the Autocomplete. Verify that a focus ring is visible around the menu items when keyboard navigating, but the ring disappears when hovering via mouse. The menu item focus ring should reappear when typing or navigating via keyboard.
4. Click into the SearchField and verify the focus ring on the SearchField disappears if previously present. Verify that typing in said field doesn't cause the SearchField's focus ring to come back.
Ignore the keyboard event leaks causing the storybook controls/bars from appearing/moving. This is known and will be handled when we make …
=> fix: add isFocusVisible useMenuItem and fix focusRing when typing in Autocomplete SearchField 

packages/@react-aria/button/src/useButton.ts, packages/@react-types/button/src/index.d.ts, packages/react-aria-components/test/Button.test.js
Closes #6159 
1. Render a `Button`
2. Add `aria-current` prop with a valid value (e.g., `"page"`)
3. The rendered `button` element should have the `aria-current` attribute with the assigned value
=> feat(Button): add support for `aria-current` prop

packages/@react-spectrum/s2/api-diff.md, packages/@react-spectrum/s2/chromatic/Badge.stories.tsx, packages/@react-spectrum/s2/src/Badge.tsx
Closes 
also fixes spelling from charteuse to chartreuse
=> feat: add overflowMode to S2 Badge

packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/interactions/test/usePress.test.js, packages/@react-aria/radio/src/useRadio.ts, packages/@react-aria/toggle/src/useToggle.ts
Fixes two issues introduced in usePress refactor:
1. Clicking on a RAC Radio, Checkbox, or Switch no longer focused the element. This is because usePress no longer programmatically focuses, and `useRadio`/`useToggle` include a `preventDefault` in the onClick handler on the label. RSP was not affected because there the native input is positioned on top of the label. Removing the preventDefault introduced the second problem...
2. On iOS, tapping the radio or toggle caused it to be triggered twice. Additionally, in testing we noticed that unexpected focus rings were appearing on listbox items in Tailwind examples on iOS. This was because our own click simulation that we trigger during `onPointerUp` in case the browser's click event is not fired was triggering in addition to the native …
=> fix: Fix focusing radio, checkbox, and switch on press

packages/@react-aria/select/src/HiddenSelect.tsx
Closes #7660
This pull request addresses the issue #7660, focusing on fixing the value assignment in the `HiddenSelect` component within the `@react-aria/select` package. The changes ensure that the `value` attribute now defaults to the current value of `selectRef` when `state.selectedKey` isn't set. This should enhance the native browser autocomplete.
- **File:** `packages/@react-aria/select/src/HiddenSelect.tsx`
- Updated the `value` property in the `useHiddenSelect` function to default to `props.selectRef?.current?.value` if `state.selectedKey` is unavailable.
- Checked that the `HiddenSelect` component now assigns the `value` attribute, and the fallback mechanism works as intended!
- Ensured that all existing functionality and behaviors are still intact and not affected by these …
=> fix(Select): HiddenSelect Component Auto-Completion Issue

packages/@react-spectrum/s2/src/Badge.tsx
=> fix: top/left align icon in s2 badge

packages/@react-aria/datepicker/src/useDateSegment.ts, packages/@react-spectrum/datepicker/src/utils.tsx, packages/@react-stately/datepicker/src/useDateFieldState.ts, packages/react-aria-components/docs/DateField.mdx, packages/react-aria-components/docs/DatePicker.mdx, packages/react-aria-components/docs/DateRangePicker.mdx
=> chore: follow-up for rtl date/time format

packages/@react-spectrum/s2/stories/Popover.stories.tsx
just prevents the story from crashing but doesn't actually fix the layout of contents inside the popover. that probably changed with the s2 tabs refactor. noticed it while i was trying to figure some stuff out with menu item focus rings.
currently on main: https://reactspectrum.blob.core.windows.net/reactspectrum/1ba8f01cec51a965205c068b1a46c333d5cf1a1b/storybook-s2/index.html?path=/story/popover--help-center
try opening the popover and see error being thrown
=> chore: add aria-label to custom popover story in s2

packages/@react-spectrum/s2/src/Image.tsx
In React < 19, we can use `fetchpriority` (lowercase) to avoid warnings.
=> feat: add fetchPriority prop to S2 Image

packages/@react-spectrum/datepicker/src/styles.css
Fixes stuff from testing.
In FF, in the DateRangePicker Granularity Second story, if you tab to the DateRangePicker, a cursor will appear. 
In Safari, between the dash separating the two datefields and the rightmost datefield, there's supposed to be padding but it appears to be missing. 
see chromatic:  https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=885
there seems to be one minor change which is the thickness of the dash in daterangepicker only in hebrew tho. i don't think that change is that bad for the tradeoffs we get. 
Make sure the two issues above are fixed and that the date/time formats are still in the correct order.
=> fix: respect padding and remove cursor in DateRangePicker

packages/@react-aria/dnd/src/useClipboard.ts, packages/@react-aria/dnd/test/useClipboard.test.js
Closes #7678
- [n/a] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)
onItems change for the useClipboard hook now offers type in the onItems function this can be console.log()'d when the hook is used 
Nothing just looking to work on some open source :)
=> feat: implemented details prop to the getItems function in the useClipboard hook

packages/react-aria-components/src/utils.tsx
An error was logged on my website because `Intl.ListFormat` was not available:
```
TypeError: undefined is not a constructor (evaluating 'new Intl.ListFormat()')
at c(./node_modules/react-aria-components/dist/utils.mjs:76:1)
at m(./node_modules/react-aria-components/dist/utils.mjs:87:1)
```
It seemed the site was accessed using Playwright, an automated browser. (https://github.com/microsoft/playwright, https://github.com/microsoft/playwright/issues/23978).
Out of curiousity, I checked which react-aria code was using `Intl.ListFormat` and it seemed that the code in utils that caused this should not have run, as the list is only needed in case of errors.
I refactored the code so the list of available slots is only compiled in case the requested slot is not available. This is a small speed …
=> Do not build list of available slots when no error

packages/@react-spectrum/s2/src/Menu.tsx, packages/@react-spectrum/s2/src/Picker.tsx, packages/@react-spectrum/s2/src/Popover.tsx
See https://github.com/orgs/adobe/projects/19/views/4?pane=issue&itemId=90609300 for an example
This happens not just with focus rings. Try with any component that uses a popover on main, make sure that scrolling appears by adjusting the height of the viewable area, and then see how items on the bottom will appear before they're actually on the popover. 
chromatic: https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=882
Try components like S2 Menu, Picker, Popover, Combobox, to make sure items and focus rings do not exceed the popover's borders.
=> fix: prevent menu item focus ring from exceeding popover boundaries

packages/@react-aria/collections/src/Hidden.tsx, packages/react-aria-components/src/Popover.tsx, packages/react-aria-components/stories/ComboBoxReproductions.stories.tsx, packages/react-aria-components/test/ComboBox.ssr.test.js
Closes https://github.com/adobe/react-spectrum/pull/7663#issuecomment-2632042270
Context https://github.com/adobe/react-spectrum/pull/7663#issuecomment-2613562862
=> feat: auto-adjust menu width for custom triggers

packages/@react-aria/collections/src/useCachedChildren.ts, packages/react-aria-components/src/Collection.tsx, packages/react-aria-components/src/Table.tsx
Closes #7656
I used Iterable on the columns collection. For dependencies its used in a few places that require arrays specifically, so I updated these to ReadonlyArray (which means Array or ReadonlyArray is accepted - if it is Array then only Array is accepted because you are saying you might modify the array if it is not Readonly).
n/a - Fixing Types.
Saxo Bank (Though this account and contribution is on my own time)
=> chore: correct Table/Collection array types

packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/styleProps.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/styleProps.test.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/styleProps.ts
Handles an issue found by @ktabors:
Previously:
```diff
-    <Flex alignItems="center" margin="10px 16px">
+    <div
+      className={style({
+        display: "flex",
+        alignItems: "center",
+        margin: "[10px]"
+      })}>
```
Now:
```diff
-    <Flex alignItems="center" margin="10px 16px">
+    <div
+      className={style({
+        display: "flex",
+        alignItems: "center",
+        marginY: "[10px]",
+        marginX: 16
+      })}>
```
Check snapshots
=> chore(codemod): handle margin/padding multi-value shorthands in style props codemod

packages/@react-spectrum/s2/stories/Form.stories.tsx, packages/react-aria-components/stories/Form.stories.tsx
Closes 
To test, you'll need to go to your browser's setting, find "Autofill", and save an address.
=> chore: add autofill stories

packages/@react-aria/autocomplete/src/useAutocomplete.ts, packages/react-aria-components/stories/Autocomplete.stories.tsx, packages/react-aria-components/test/Autocomplete.test.tsx
Closes https://github.com/adobe/react-spectrum/issues/7619
First bug of https://github.com/adobe/react-spectrum/issues/7619#issuecomment-2626073056
=> fix: Autocomplete 'tab' key forwarding

packages/@react-spectrum/s2/chromatic/Tabs.stories.tsx, packages/@react-spectrum/s2/chromatic/TreeView.stories.tsx, packages/@react-spectrum/s2/src/Tabs.tsx, packages/@react-spectrum/s2/src/TreeView.tsx, packages/@react-spectrum/s2/stories/Popover.stories.tsx, packages/@react-spectrum/s2/stories/Tabs.stories.tsx
Closes 
This fixes the Tab Panel layout in the Popover example in S2 and doesn't reinstate the requirement to utilize unsafe styles, as we had before. This should keep it closer to the original API. I'm still not 100% sold on it. I wish it were easier to make TabPanels auto-scroll regions by default, but we seem to need the flexibility afforded by not doing that.
It fixes the blue chevron and misaligned rows in iOS treeview s2.
Makes the external label for the tabs example a little more evident that that's what it is.
=> fix: testing session bugs treeview and tabs

packages/@react-types/button/src/index.d.ts
=> fix: ToggleButton Props should not include aria-current

packages/@react-spectrum/s2/src/Menu.tsx, packages/@react-spectrum/s2/src/Picker.tsx
Closes 
Test firefox (and other browsers) to make sure the menu items don't overlap with each other. Make sure the viewable area is as small as possible since that seems to be when it happens. 
Seems to happen mainly in stories where there are icons or images + text wrapping
=> fix: prevent menu items from overlapping in firefox

packages/react-aria-components/src/Dialog.tsx, packages/react-aria-components/src/index.ts
Some RenderProps types weren't being exported properly from the react-aria-components library.
=> react-aria-components: Expose missing RenderProps types

packages/@react-spectrum/radio/docs/RadioGroup.mdx
Closes 
reported internally
using value of an empty string makes it so you can't tab to the radiogroup at all, this is because an empty string could be a valid value for an individual radio. `null` should be used instead
=> fix: RadioGroup controlled example

packages/@react-spectrum/toast/src/ToastContainer.tsx
Prevents throwing this error: `Unhandled Rejection (AbortError): Old view transition aborted by new view transition`, which could be produced by rapidly opening and closing toasts. I could only reproduce this in iOS Safari.
On iOS Safari, try rapidly opening new toasts and closing existing toasts.
=> fix(Toast): catch startViewTransition error thrown for multiple transitions

packages/@react-aria/interactions/src/textSelection.ts
Noticed a small regression from the `usePress` refactor: text selection was no longer being canceled in Safari on desktop. For example when clicking quickly on an item in a GridList in the docs the text would be selected. This previously worked because `preventDefault` stops text selection, but after removing that we rely on setting `user-event` on pointer down. This worked in Chrome and Firefox, but Safari still doesn't support `user-select` and requires a prefixed `-webkit-user-select` property instead. Updated the code to detect the correct property to use.
=> fix: Canceling text selection in Safari broken after usePress refactor

packages/@react-aria/collections/src/BaseCollection.ts, packages/@react-aria/collections/src/Document.ts, packages/@react-types/grid/src/index.d.ts, packages/react-aria-components/src/Table.tsx, packages/react-aria-components/test/Table.test.js
In collaboration with @snowystinger 😄 
The extra traversal over all rows and cells introduced in #7638 caused a performance regression for large tables. Our S2 many rows and cells story took an extra ~20ms per collection update, and a table with 10,000 rows took an extra ~250ms per update.
We can avoid the extra traversal by computing `colIndex` and `colSpan` while building the document rather than as a separate pass. The downside is that this is done on all collections and not just tables but it's probably fine for now.
=> fix: Improve colSpan performance

packages/@react-aria/toast/src/useToastRegion.ts, packages/@react-aria/toast/stories/Example.tsx, packages/@react-aria/toast/stories/useToast.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/7024. Alternative to https://github.com/adobe/react-spectrum/pull/7681
After a toast has been removed, we check the pointer position on the next `pointermove` event. If it is now outside the toast region, we resume timers.
For discussion:
- The timers won't resume until the next `pointermove` after closing. This behavior seems good IMO. It gives the user time to process the new state and decide whether to move their pointer elsewhere or to the next toast (would cause another pause).
- There is some related but different behavior we may want to discuss: if you close a toast via touch, currently the next toast's remove button gets focused, causing the timer to pause. If the user scrolls or interacts with anything else outside the region, …
=> fix(toast): resume timers if pointer leaves region due to toast being removed

packages/@react-aria/collections/package.json, packages/@react-aria/collections/src/CollectionBuilder.tsx, packages/@react-aria/interactions/src/index.ts, packages/@react-aria/interactions/src/useFocusable.tsx, packages/@react-aria/tabs/src/useTab.ts, packages/@react-aria/tag/src/useTag.ts, packages/react-aria-components/stories/Tabs.stories.tsx, packages/react-aria-components/stories/TagGroup.stories.tsx, packages/react-aria-components/test/Tabs.test.js, packages/react-aria-components/test/TagGroup.test.js, yarn.lock
Closes https://github.com/adobe/react-spectrum/issues/6800, closes https://github.com/adobe/react-spectrum/issues/7303, closes #7289
Alternative implementation of #7289. Instead of making TooltipTrigger into a collection component, we can forward `FocusableContext` from the fake DOM tree into the real DOM tree. Tooltip itself will be rendered into the real DOM via a portal.
=> feat: Support tooltips on Tags and Tabs

packages/react-aria-components/src/NumberField.tsx
Closes 
a definitely correct part of https://github.com/adobe/react-spectrum/issues/6151
=> chore: Add isRequired to NumberField RenderProps

packages/@react-aria/radio/src/useRadio.ts, packages/@react-aria/toggle/src/useToggle.ts
Closes 
In https://github.com/adobe/react-spectrum/pull/7677, we removed the preventDefault on `onClick` which allowed the browser to focus the label but also caused a focus ring to appear by triggering a virtual click. This PR adds back the preventDefault but since we still need to focus the label, we do that through the ref instead
Related issues: https://github.com/adobe/react-spectrum/issues/3675
Related PRs: https://github.com/adobe/react-spectrum/pull/7542, https://github.com/adobe/react-spectrum/pull/7677, https://github.com/adobe/react-spectrum/pull/5525
Test Gridlist docs, virtualizer docs, S2 TreeView, S2 custom popover (specifically the switch in the popover) and make sure that the focus ring doesn't appear but that they are focused
=> fix: prevent focus visible on label (checkbox, switch, radio) 

packages/@adobe/spectrum-css-temp/components/inputgroup/skin.css, packages/@react-aria/combobox/package.json, packages/@react-aria/combobox/src/useComboBox.ts, packages/@react-aria/utils/src/useUpdateEffect.ts, packages/react-aria-components/docs/ComboBox.mdx, yarn.lock
Autocomplete introduced a change for virtual focus collections where we fire focus/blur events to move the focus ring. This also affects ComboBox - now when the virtual focus is on an item, the input loses its focus ring. However, when closing the ComboBox, the focus ring never shifted back to the input. We also need to better account for this state in the styles for the v3 ComboBox.
=> fix: Re-show focus ring on ComboBox input when closed

packages/@react-spectrum/s2/stories/TableView.stories.tsx, packages/@react-spectrum/table/docs/TableView.mdx, packages/react-aria-components/docs/Tree.mdx, packages/react-aria-components/stories/Tree.stories.tsx
Closes 
also fixes Tree chevron hit area in RAC docs and fixes rendering in Android RAC storybook
=> chore: Add colSpan examples to docs

packages/@react-aria/tree/src/useTreeItem.ts, packages/react-aria-components/test/Tree.test.tsx
=> fix: Add tree row label to expand/collapse button announcement

packages/@react-types/datepicker/src/index.d.ts
Found in testing. Seem to have slipped in without any use?
=> fix: remove overlay props from datefield type signature

packages/@react-spectrum/tree/src/TreeView.tsx
Closes 
original tried to fix a missing top border in https://github.com/adobe/react-spectrum/commit/c5851c83108d8c42d3e4b37f336bfb310df41cf9#comments but introduced an overlap between items resulting in too thick a border
this pr fixes both issues
=> fix: v3 TreeView border overlap

packages/@react-stately/layout/src/GridLayout.ts, packages/@react-stately/layout/src/ListLayout.ts, packages/@react-stately/layout/src/TableLayout.ts, packages/react-aria-components/stories/ListBox.stories.tsx
When using drag and drop reorder items in a grid or list with gaps between the items, the drop target would disappear when over the gap because we were looking for items under the mouse and there were none. This was broken by the recent refactor. Now instead of using `keyAtPoint`, we get the items in a small rectangle that's as wide as the gap, and then find the closest item to the mouse position within that rectangle.
=> fix: Fix virtualizer drag and drop with layout gaps

packages/@react-aria/overlays/src/usePopover.ts, packages/react-aria-components/docs/SearchField.mdx
Fixes the "Complex content" submenu example in the docs on iPad. This was closing due to a scroll event when the virtual keyboard appeared. Close on scroll is enabled for `isNonModal` popovers, but we should exclude submenus from this. Another reason to eventually split up `isNonModal` into multiple props.
Also fixed the search field overflowing the popover on iPad in that example.
=> fix: Prevent submenus from closing on scroll

packages/@react-aria/utils/src/useId.ts
Closes https://github.com/adobe/react-spectrum/issues/7882
We thought we could safely use this as every environment supports it
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry
https://caniuse.com/?search=FinalizationRegistry
But it's not supported in CloudFlare workers. In that case though, every request should result in the complete throwing away of any previous request making the memory leak a non-issue.
If any other environments come along without this feature, they'll also have the problem, but given how long it took for it to be reported, maybe it's not that big of a deal.
=> fix: Environment with no FinalizationRegistry

packages/react-aria-components/package.json, packages/react-aria-components/src/Toast.tsx, packages/react-aria-components/test/Toast.test.js, yarn.lock
Closes https://github.com/adobe/react-spectrum/issues/7879
Add a `portalContainer` to a `ToastReagion` and check if the toasts are renderer in it.
=> fix: Allow to configure the Toast portail container root

packages/react-aria-components/src/Separator.tsx, packages/react-aria-components/test/Separator.test.js
Closes https://github.com/adobe/react-spectrum/issues/7860
=> fix: pass aria labeling props in RAC Separator

packages/@react-aria/toast/src/useToast.ts, packages/@react-aria/toast/test/useToast.test.js
Closes #7916
N/A - unit tests should be enough?
Saxo Bank
=> Feat: Pass data attributes through on Toast

packages/@react-aria/collections/src/Document.ts, packages/react-aria-components/stories/Table.stories.tsx, packages/react-aria-components/test/Table.test.js
Fixes #6182, fixes #7535
There were two issues with our collection implementation with Suspense:
1. React sets `display: none` on items inside a suspense boundary, while the fallback is visible. We didn't implement this, so it resulted in the loading indicator being displayed alongside the existing items rather than replacing them. I fixed this by tracking whether an element is hidden. Hidden elements are kept in our fake DOM, but they are removed from the collection.
2. The previous transaction count could get out of sync with react if a render was aborted. Turned out we don't need this anymore after #7905, which now relies on React to queue the render instead. When triggering an update, we just return a clone of the previous collection, which forces React to re-render due to object …
=> fix: Support React Suspense in collections

packages/@react-spectrum/button/package.json, packages/@react-spectrum/checkbox/package.json, packages/@react-spectrum/divider/package.json, packages/@react-spectrum/dropzone/package.json, packages/@react-spectrum/filetrigger/package.json, packages/@react-spectrum/switch/package.json, packages/@react-spectrum/text/package.json, packages/@react-types/card/package.json, packages/@react-types/sidenav/package.json, packages/@spectrum-icons/color/package.json, packages/@spectrum-icons/ui/package.json, packages/@spectrum-icons/workflow/package.json, yarn.config.cjs, yarn.lock
Closes https://github.com/adobe/react-spectrum/issues/7909
I'm not sure why yarn didn't create warnings for us during install in our own project. I've added it as a constraint rule, so we'll know in the future if we violate this again.
I tested against the test repo listed in the original issue, I no longer get which I did get when using the starting state.
```
Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
```
upon `yarn install` and I checked the old pnp.cjs vs the new one, the line pointed out in the comment is now different and I *think* correct.
Steps to run against test repo:
1. in react spectrum, run `./scripts/verdaccio.sh`
2. wait until `Press a key to close server and cleanup` is displayed
3. go to test repo
4. 
``` …
```
=> fix: yarn peers

packages/react-aria-components/src/DateField.tsx
Found in testing. This Prop is Omited from `DateSegmentRenderProps`, but it was still being passed to the `useRenderProps` hook.
=> fix: exclude isEditable from DateSegment render prop values

packages/react-aria-components/src/Table.tsx
Closes 
https://github.com/adobe/react-spectrum/pull/7843/files#r2010690783
TL;DR
I moved this prop instead of copying it into the block above
=> fix: Add Table Cell id prop back into the Cell types

lib/jestResolver.js
Closes #7924
I know the core team is all on Mac - maybe check yarn test still works there.
Part of the fix taken from this suggestion: https://github.com/adobe/react-spectrum/issues/2429#issuecomment-1063212930
Saxo Bank
=> Fix: Windows development

packages/@internationalized/number/src/NumberParser.ts, scripts/checkGroupSeparators.mjs
Closes https://github.com/adobe/react-spectrum/issues/7866
Discussed with Adobe's globalization team and french CLDR contributor. The consensus was that periods are ambiguous. France started to have recommendations against using periods as group separators [in 1948](https://www.bipm.org/fr/committees/cg/cgpm/9-1948/resolution-7), however, it was still taught in schools for a long time. As a result, depending on age or where someone went to school, they may expect it to be the decimal or they may expect it to be the group separator. To get rid of the ambiguity, it was recommended that we remove period as an allowed character and expand the group separator characters to allow all kinds of spaces so that they can easily be typed out on a standard keyboard.
=> fix: French number parsing ambiguity

packages/@react-spectrum/s2/src/ButtonGroup.tsx
seems like we missed passing down props to button group in S2
=> fix: pass dom props to button group

packages/@react-aria/menu/src/useMenuTrigger.ts, packages/@react-spectrum/table/test/TableSizing.test.tsx
Closes 
Addresses an issue found while looking at https://github.com/adobe/react-spectrum/issues/7902
Ensure the Select has focus before opening the select menu so it can be restored by FocusScope on close. Note that this is the same behavior that keyboard and mouse have, for the same reason.
To reproduce, using a touch device:
Go to https://react-spectrum.adobe.com/react-aria/index.html and open the "modal" top right of the example. Put focus in one of the textfields, then open one of the Selects. After closing the Select, focus will be restored to the textfield, not the select's trigger, as expected.
Then do the same thing but on the docs built by this PR.
=> fix: mobile restore focus after a Select closes

packages/@react-types/shared/src/style.d.ts
`Grid` and `Flex` share the defaults doc strings set for `justifyContent`, `alignContent` and `alignItems`, from `BoxAlignmentStyleProps`. However, no such defaults are actually set by the components, they are just passthroughStyle props for grid and normalize flex-start/start flex-end/end for flex, but neither explicitly set the stated defaults. They resolve in as just `normal` computed styles by the browser.
The doc string is misleading, and should be removed. My guess was the defaults were written as such to reference the fast that a browsers "normal" setting behaves similar to the defaults mentioned, so maybe that's why they were added? Or maybe at one point those were the defaults? However, claiming to set a default in the doc string, when it is not in the component is confusing.
Doc …
=> docs: remove BoxAlignmentStyleProps unset "@default" from types

packages/@react-spectrum/s2/src/ActionButton.tsx, packages/@react-spectrum/s2/src/NotificationBadge.tsx, packages/@react-spectrum/s2/stories/ActionButton.stories.tsx
notes from design:
1. Notification badge cannot be used on a label-only quiet button. they are updating their guidelines to include this information
2. Remove the badge when an action button is disabled
3. No answers for static colors, they will workshop
4. Badges should be swapped with an indicator to avoid visual collision but they are exploring other options (probably something the app needs to do)
=> fix: S2 notification badge follow-ups

packages/@react-spectrum/s2/stories/Tooltip.stories.tsx
=> chore: Fix generated code sample for S2 TooltipTrigger docs

packages/@react-spectrum/s2/src/index.ts
Add missing export from S2 package
=> fix: export `SortDescriptor` type from S2

packages/@internationalized/date/docs/CalendarDate.mdx
```
let date = new CalendarDate(new BuddhistCalendar(), 2563, 4, 30);
```
The Gregorian calendar equivalent of the mentioned Buddhist calendar date should be April 30th. Currently it says April 4th in the docs.
=> fix: minor typo in CalendarDate docs

packages/@react-spectrum/s2/src/Divider.tsx
Closes 
This prevents the Divider from growing or shrinking in a flex container by default. It's come up internally a few times.
=> fix: Divider S2 better flex behaviour

packages/dev/parcel-resolver-optimize-locales/package.json, packages/dev/parcel-transformer-s2-icon/package.json, yarn.lock
From audit. Public Parcel plugins should not force people to upgrade to the latest version.
=> fix: Relax Parcel version range in public plugins

packages/@react-spectrum/s2/src/Disclosure.tsx
Updated from latest spectrum designs
Confirm the new Disclosure/Accordion button label sizes match the Spectrum update.
AIA
=> Refactor: Disclosure button label size update to match new sizes from Spectrum

packages/@react-spectrum/s2/chromatic/ActionButton.stories.tsx, packages/@react-spectrum/s2/chromatic/NotificationBadge.stories.tsx
=> chore: add notification badge to chromatic

packages/@react-aria/menu/docs/useMenu.mdx, packages/@react-spectrum/picker/docs/Picker.mdx, packages/@react-spectrum/text/docs/Keyboard.mdx, packages/dev/docs/pages/react-spectrum/layout.mdx, packages/react-aria-components/docs/ColorSlider.mdx, packages/react-aria-components/docs/ColorWheel.mdx, packages/react-aria-components/docs/FileTrigger.mdx, packages/react-aria-components/docs/Menu.mdx, packages/react-aria-components/docs/Tree.mdx
Updating outdated menu links, along with some typos while we're at it
=> docs: fix wrong links/typos

packages/@react-spectrum/s2/src/Card.tsx, packages/@react-spectrum/s2/src/ColorSwatchPicker.tsx, packages/@react-spectrum/s2/src/Content.tsx
Fixes places where `undefined` might show up as a class name in rendered S2 elements.
Open affected stories in dev tools and search for `undefined` to make sure it is no longer a class name.
=> fix(s2): fix undefined class name outputs

package.json
Was broken by toast change to css modules exclusions. Adding back stories here.
=> fix: UNSAFE_className story

packages/@internationalized/date/src/utils.ts
Closes [a relevant issue](https://github.com/adobe/react-spectrum/issues/6394)
The `copy` and `copyDateTime` seem to be unused and not exported outside of the package.
They also break Vercel deployments of the projects that use `@internationalized/date` for some reason (probably connected with the [heroui issue](https://github.com/heroui-inc/heroui/issues/3560)), that's why I made the fix.
All existing tests should pass.
=> Fix: circular dependency in @internationalized/date

packages/@react-aria/calendar/src/useCalendarBase.ts, packages/react-aria-components/test/Calendar.test.js
Applying the aria-details prop, which was not passed to the final `calendarProps`.
This PR fixes an issue where the aria-details was set in the RAC `Calendar` | `RangeCalendar`, but was not being applied to the rendered component.
=> fix: apply aria-details on the calendar

packages/@react-aria/grid/src/useGrid.ts, packages/@react-aria/grid/src/useGridRow.ts, packages/@react-aria/grid/src/utils.ts, packages/@react-aria/gridlist/src/useGridList.ts, packages/@react-aria/gridlist/src/useGridListItem.ts, packages/@react-aria/gridlist/src/utils.ts, packages/@react-aria/listbox/src/useListBox.ts, packages/@react-aria/tag/src/useTagGroup.ts, packages/@react-types/listbox/src/index.d.ts, packages/@react-types/table/src/index.d.ts, packages/react-aria-components/src/GridList.tsx, packages/react-aria-components/stories/GridList.stories.tsx, packages/react-aria-components/test/GridList.test.js, packages/react-aria-components/test/ListBox.test.js, packages/react-aria-components/test/Table.test.js, packages/react-aria-components/test/TagGroup.test.js, packages/react-aria-components/test/Tree.test.tsx
Closes https://github.com/adobe/react-spectrum/issues/7887
- Add `shouldSelectOnPressUp` prop to GridList following [ListBox](https://github.com/adobe/react-spectrum/blob/e4a90c9197ee6231a4eb38af6c0174b5d4d67500/packages/react-aria-components/src/ListBox.tsx)
- Add `shouldSelectOnPressUp` to GridList story
- download [StackBlitz](https://stackblitz.com/edit/vitejs-vite-9xgojtgi?file=src%2Fcomponents%2FSelect.tsx,src%2Fcomponents%2FGridListDropdown.tsx,src%2FApp.tsx) example from https://github.com/adobe/react-spectrum/issues/7887 and run the project in local
- build `react-aria-components` module from the PR branch and set up a yarn link
- link `react-aria-components` module in the StackBlitz project
- add `shouldSelectOnPressUp` prop as `true` to GridList
- follow the steps in …
=> Feat: add shouldSelectOnPressUp prop to collection components

packages/@react-spectrum/s2/src/Checkbox.tsx, packages/@react-spectrum/s2/src/Radio.tsx
Closes https://github.com/adobe/react-spectrum/issues/8081
=> fix: give radio/checkbox position relative so the hidden input is contained

examples/remix/app/root.tsx, examples/remix/package.json, examples/remix/vite.config.ts
Closes 
Looks like a recent-ish release of remix removed the unstable prefix, also with the new process.env variables, it broke the build
=> chore: update remix example

.github/ISSUE_TEMPLATE/Bug_Report.yml
=> chore: Add template for s2 with style macros

packages/@react-spectrum/s2/src/ContextualHelp.tsx, packages/@react-spectrum/s2/src/style-utils.ts
This is not allowed because it is truly unsafe. UNSAFE_className is not merged with the component's own styles, it is appended. So if someone passes in a style macro class that sets a property but the component also has a class setting the same property, both will be applied and result in undefined behavior depending on the order the CSS was loaded on the page.
=> refactor: Make it a TypeScript error to pass style macro to UNSAFE_className

packages/react-aria-components/src/index.ts
Hey, here's a simple addition to the RAC API: by exposing `useRenderProps`, RAC users can build their own components that integrate more seamlessly with other RAC components.
=> feat(RAC): Expose `useRenderProps` hook

packages/@react-aria/textfield/src/useTextField.ts, packages/@react-types/searchfield/src/index.d.ts, packages/@react-types/textfield/src/index.d.ts
=> fix: minor typo for enterKeyHint prop docs

packages/@react-spectrum/s2/style/spectrum-theme.ts
Just fix it
it's a property typo in style macros
Adobe
=> fix: spelling mistake in style macros list-style-type

packages/react-aria-components/docs/FileTrigger.mdx
Fixing a Typescript error in the FileType example, https://react-spectrum.adobe.com/react-aria/FileTrigger.html#example.
Copy the FileType "Example" into an IDE and confirm there are no TypeScript errors.
=> docs(RAC): FileType docs TypeScript fix

packages/@react-aria/overlays/src/PortalProvider.tsx
Closes 
There was a small issue in the `getContainer`'s typings. 
There is the following code
```
<PortalContext.Provider value={{getContainer: getContainer === null ? undefined : getContainer ?? ctxGetContainer}}>
```
Which means `getContainer` is intented to be null sometimes. There is a comment that also imply this: 
```
Can clear the context by passing null.
```
But at the moment, `getContainer` does not accept the null value.
before: 
```
(() => HTMLElement | null) | undefined
```
now: 
```
(() => HTMLElement | null) | null | undefined
```
=> fix: Correct the PortalProvider's getContainer typings

packages/@react-aria/collections/src/Document.ts, packages/react-aria-components/stories/Table.stories.tsx
Fixes #8094
This improves performance of collection updates that occur in React transitions, e.g. [startTransition](https://react.dev/reference/react/startTransition). The performance issue was caused by the following behavior described in the docs for [useSyncExternalStore](https://react.dev/reference/react/useSyncExternalStore):
> If the store is mutated during a [non-blocking Transition update](https://react.dev/reference/react/useTransition), React will fall back to performing that update as blocking. Specifically, for every Transition update, React will call getSnapshot a second time just before applying changes to the DOM. If it returns a different value than when it was called originally, React will restart the update from scratch, this time applying it as a blocking update, to …
=> fix: Improve performance of collection updates in React transitions

packages/@react-spectrum/s2/style/__tests__/style-macro.test.js, packages/@react-spectrum/s2/style/style-macro.ts
We're not quite ready to stabilize the style macro class names in this release since we are still playing with how the CSS is generated. For now, add a postfix based on the version number so that the class names don't conflict with any prior or future versions.
This is not optimal long term since it forces browser cache invalidation on every upgrade even if the css did not change. We will aim to remove this before S2 reaches 1.0.
=> chore: Temporarily add version postfix to style macro class names

packages/@react-spectrum/s2/src/ComboBox.tsx, packages/@react-spectrum/s2/src/Menu.tsx, packages/@react-spectrum/s2/src/Picker.tsx, packages/@react-spectrum/s2/src/TabsPicker.tsx
The listbox aria pattern does not allow headings. For now apply `role="presentation"` like we did in v3 using ts-ignore. Further API discussions to be had in the future.
=> fix(s2): Add role=presentation to ListBox section headings

packages/@adobe/spectrum-css-temp/components/accordion/index.css, packages/@react-spectrum/accordion/chromatic/Accordion.stories.tsx, packages/@react-spectrum/accordion/chromatic/Disclosure.stories.tsx, packages/@react-spectrum/accordion/stories/Accordion.stories.tsx, packages/@react-spectrum/accordion/stories/Disclosure.stories.tsx
Before:
After:
Check new stories:
- https://reactspectrum.blob.core.windows.net/reactspectrum/bc4a31946387368b9857890a509bed07a4d24cc1/storybook/index.html?path=/story/disclosure--wrapping-title&providerSwitcher-express=false
- https://reactspectrum.blob.core.windows.net/reactspectrum/bc4a31946387368b9857890a509bed07a4d24cc1/storybook/index.html?path=/story/accordion--with-wrapping-title&providerSwitcher-express=false
=> fix: Disclosure chevron appearance when title wraps

packages/@react-stately/data/src/useTreeData.ts, packages/@react-stately/data/test/useTreeData.test.js
Fixes a `RangeError: Maximum call stack size exceeded` error that could be reproduced by doing the following operations in the RAC Tree DnD stories:
1. Drag “Reports 1” to top of tree (above the first item)
2. Drag “Reports” to top of tree (above the first item)
=> fix(useTreeData): stale duplicate items when moving to root

packages/react-aria-components/stories/Select.stories.tsx
Pretty sure this is the same issue I encountered with S2 Picker where we fixed the Virtualized RAC Select but S2 Picker still wasn't scrolling into view. 
For details about this issue, see [comment](https://github.com/adobe/react-spectrum/pull/8110#discussion_r2076319076)
Test Async Virtualized Collection Rendered Select story and make sure the selected item scrolls into view
=> fix: selected item scrolls into view in rac select story

packages/@react-aria/dnd/src/DragManager.ts, packages/@react-aria/dnd/src/useDropIndicator.ts, packages/@react-aria/dnd/src/useDroppableCollection.ts, packages/@react-aria/dnd/src/useDroppableItem.ts, packages/@react-stately/dnd/src/useDroppableCollectionState.ts, packages/@react-types/shared/src/dnd.d.ts, packages/react-aria-components/example/index.css, packages/react-aria-components/src/Tree.tsx, packages/react-aria-components/src/useDragAndDrop.tsx, packages/react-aria-components/stories/Tree.stories.tsx
* Support onMove event, which allows moving between parents. onReorder now only allows reordering within the same parent.
* Fix accessibility of drop indicators (they should have role=row/gridcell instead of role=option)
* Fix dropping between the parent item and its first child
* Made ArrowLeft/ArrowRight to expand while dragging work while focused on the item rather than the drop indicator after it. Also fixed RTL
* Made the chevron visible to screen readers so mobile users can expand/collapse an item while dragging. For now, this is not tabbable (since keyboard users can use arrow keys to expand/collapse). This will be needed for other components, but needs further work on propagating the focus event so the focus ring becomes visible.
=> fix: Tree Dnd updates

packages/@react-aria/combobox/src/useComboBox.ts, packages/@react-aria/table/src/useTableSelectionCheckbox.ts, packages/@react-spectrum/autocomplete/test/SearchAutocomplete.test.js, packages/@react-spectrum/combobox/src/ComboBox.tsx, packages/@react-spectrum/combobox/test/ComboBox.test.js, packages/@react-spectrum/s2/src/TableView.tsx, packages/react-aria-components/src/Table.tsx, packages/react-aria-components/stories/Table.stories.tsx, packages/react-aria-components/test/Table.test.js
=> fix: Fix Table disabled state + Safari loadMore and scroll Combobox selected item into view when opening via click

packages/@react-aria/selection/src/useSelectableItem.ts
Closes https://github.com/adobe/react-spectrum/issues/8116
Pretty sure it broke in this commit? https://github.com/adobe/react-spectrum/pull/7561/commits/7fd803a4a85e03d605aa798b2ad1cbdb1cd5bcc6
Test RAC Combobox disabled options in the docs. You should not be able to select a disabled item. Would be good to check other collection components that contain selectable items that can be disabled
=> fix: prevent disabled item from receiving focus when clicked

.storybook-s2/docs/Migrating.jsx, packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/button.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/combobox.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/picker.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/__snapshots__/table.test.ts.snap, packages/dev/codemods/src/s1-to-s2/__tests__/button.test.ts, packages/dev/codemods/src/s1-to-s2/__tests__/combobox.test.ts, packages/dev/codemods/src/s1-to-s2/__tests__/picker.test.ts, packages/dev/codemods/src/s1-to-s2/__tests__/table.test.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/components/Button/transform.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/components/ComboBox/transform.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/components/Picker/transform.ts, packages/dev/codemods/src/s1-to-s2/src/codemods/components/TableView/transform.ts
Updates the S2 migration guide and codemods to be up to date for the upcoming release including:
- ComboBox: `onLoadmore` and `loadingState` are no longer commented out
- Picker: `onLoadmore` and `isLoading` are no longer commented out
- Button: `isPending` is no longer commented out
- TableView: `onLoadmore` and `loadingState` move from TableBody to TableView
=> chore(s2): update migration guide and codemods for release

packages/@react-spectrum/s2/src/ComboBox.tsx, packages/@react-spectrum/s2/stories/ComboBox.stories.tsx
Noticed in my local test app that the `defaultItems` prop stopped working in S2 ComboBox. It caused a React crash on "Functions are not valid as a react child", due to the if statement only checking for items and not defaultItems. Apparently we had no stories for this case, so I modified a couple.
=> fix: Fix crash on defaultItems in S2 Combobox

packages/@react-stately/data/src/useAsyncList.ts, packages/@react-stately/data/test/useAsyncList.test.js
The `loadingState` was typed but never passed
=> fix: pass `loadingState` to `useAsyncList`'s `load` function

package.json, packages/dev/docs/package.json, yarn.lock
Closes 
fixes a yarn install warning during default development for babel/eslint-parser being on an unsupported eslint version
fixes a yarn install warning that will happen when we move to react 19 default development, quicklink now extends it's accepted range to react 19
triggered making PR by https://github.com/GoogleChromeLabs/quicklink/pull/421
=> chore: fix yarn install warning

packages/@internationalized/number/src/NumberParser.ts, packages/@internationalized/number/test/NumberParser.test.js
Closes https://github.com/adobe/react-spectrum/issues/8199. Resolves issue of number string of +X% returning `NaN`, where X is a valid number (e.g. `"+0%", "+0.5%"`)
Added tests are included in existing NumberParser.test.js (lines 168-181). They can be run with `yarn jest NumberParser`.
None
=> fix: 0 decimals treated as zero when parsing with exceptZero

packages/dev/docs/pages/react-aria/routing.mdx
* Change href to use full tanstack router `ToOptions`
* Rename `to` param to `href` since it contains full ToOptions
The previous declarations using `to` doesn't allow for passing in `params`.
=> docs: fix tanstack router full ToOptions

packages/@react-aria/dnd/package.json, packages/@react-aria/dnd/src/DropTargetKeyboardNavigation.ts, packages/@react-aria/dnd/src/useDropIndicator.ts, packages/@react-aria/dnd/src/useDroppableCollection.ts, packages/@react-aria/dnd/test/DropTargetKeyboardNavigation.test.tsx, packages/@react-stately/dnd/src/useDroppableCollectionState.ts, packages/react-aria-components/src/Collection.tsx, packages/react-aria-components/src/Tree.tsx, packages/react-aria-components/src/Virtualizer.tsx, packages/react-aria-components/stories/Tree.stories.tsx, yarn.lock
Improves keyboard navigation in tree drag and drop so that it traverses through the before/after drop positions of each level of the tree in a predictable order. An item may now have more than one "after" drop indicator, one for each level of the tree up to the level of the next item. The code to implement this was somewhat complicated so I pulled it out into its own file that could be unit tested independently.
This also changes the drop indicators to have better labels. Instead of "Insert between X and Y" when those items are in different levels, it now will read "Insert before X" or Insert after Y" when it is the first or last item of a level.
Also realized that making the chevron of the original item the activate button broke the a11y tree, because then there are two visible rows for …
=> fix: Improve tree dnd keyboard navigation

packages/@react-spectrum/datepicker/src/utils.tsx, packages/@react-spectrum/datepicker/test/DateField.test.js, packages/@react-stately/datepicker/src/useDateFieldState.ts, packages/react-aria-components/test/DateField.test.js
Closes #8017
Some additional segment types are now returned by `Intl.DateTimeFormat#formatToParts`, including `'yearName'` and `'relatedYear'`. These are mainly returned for the Chinese calendar ([reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts#named_years)). `Intl.DisplayNames` does not accept these segment types as inputs causing a crash. In addition the rest of our code does not support these and treats them as non-editable. This PR maps these segments to known types to avoid the crash.
While we don't technically support the Chinese calendar in `@internationalized/date` and there is a bunch of other broken behavior at the moment, at least we don't crash on these segment types anymore.
=> fix: Don't crash on unknown segment types in DateField

packages/@react-stately/datepicker/src/useDateRangePickerState.ts, packages/react-aria-components/test/DateRangePicker.test.js
Fixes #6957
When a DateRangePicker with minute/second granularity does not have a TimeField in it, selecting a range appeared to do nothing. The popover would close but the selected date would not appear. This can be seen in the second example in this section of the docs: https://react-spectrum.adobe.com/react-aria/DateRangePicker.html#granularity
For React Spectrum we don't close on select when time fields are present. But this is not necessarily the case in RAC. This updates our logic to always set a placeholder time if one is not defined when selecting a date and the popover will close. This matches the behavior we already have in DatePicker.
=> fix: Set a placeholder time when closing a DateRangePicker with time granularity

packages/@react-aria/interactions/src/useInteractOutside.ts, packages/@react-aria/interactions/test/useInteractOutside.test.js, packages/@react-aria/overlays/test/useModalOverlay.test.js, packages/@react-aria/overlays/test/useOverlay.test.js
Fixes #7283, fixes #7116
Same workaround for https://issues.chromium.org/issues/40732224 as done in usePress - delay until click event instead of triggering during pointerup event.
Does not fix ComboBox - that is a separate problem. The popover closes on blur, which happens before the click event so by that point the user is clicking on the underlying element. This occurs across all browsers, not only Android.
=> fix: Tapping outside overlay triggers elements behind underlay on Android

packages/@react-aria/selection/src/useSelectableCollection.ts, packages/@react-spectrum/tag/test/TagGroup.test.js
Closes #8298 
Seems like the order that `scrollIntoView` and `scrolIntoViewport` matters so wrap it all in a raf
I can't seem to actually reproduce in our storybook but I can within our docs.
1. Go to V3 Combobox docs
2. Using the first example, resize the screen so that the popover is scrollable. Ensure that there is enough space below so that the popover will open on the bottom and not the top
3. Open the popover using the keyboard, and navigate throw the items using the down arrow
4. The popover should not close when you move past the last visible item
Would be good to test to make sure that V3 Picker still scroll into view with this change. You can test with the "long item text" story
=> fix: prevent combobox from closing when navigating through items with keyboard

packages/react-aria-components/src/Virtualizer.tsx
Closes https://github.com/adobe/react-spectrum/issues/8293
In collaboration with @LFDanLu , we tried to write a test that mimicked what Next was doing in our SSR tests, but we couldn't get it to reproduce there. The flow diverges pretty quickly, in the test we immediately have a full collection, but in Next, there's a period of time where it's not been processed yet.
I'm assuming there is something happening with concurrency, but that's just a hunch. Open to suggestions on a test for this.
=> fix: Virtualizer with useIsSSR

packages/@react-aria/selection/src/ListKeyboardDelegate.ts, packages/react-aria-components/example/index.css, packages/react-aria-components/src/Tree.tsx, packages/react-aria-components/stories/Tree.stories.tsx, packages/react-aria-components/test/Tree.test.tsx
Reverting for release since adding support for loading indicator focus for all collection components still has some unresolved issues
RSP
=> chore: Revert "feat: focus loading indicator in rac tree (#8270)"

packages/react-aria-components/src/Checkbox.tsx, packages/react-aria-components/stories/CheckboxGroup.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/7749
Same fix as https://github.com/adobe/react-spectrum/pull/8212
=> fix: clear selection when using form reset in RAC CheckboxGroup

packages/@react-spectrum/s2/src/ActionButton.tsx, packages/@react-spectrum/s2/src/Button.tsx, packages/@react-spectrum/s2/src/TagGroup.tsx
Focus visible styles were being applied on standard focus
RSP
=> fix: Fix S2 button/taggroup coloring so they apply on keyboard focus only

packages/@react-aria/utils/src/useLoadMoreSentinel.ts
Closes #8266 
Workaround for our `Node` colliding with the global one. In this case we don't actually care what kind of collection is passed in since it is only used in a dependency array. Real fix will be in Parcel.
=> fix: TypeScript types colliding with globals

packages/dev/docs/pages/assets/rtl-timefield.svg
For the diagram under the Unicode Bidirectional Algorithm, the correct date should be 8:45, 31.1.2025
=> docs: fix rtl diagram in blog post

packages/@react-aria/interactions/src/usePress.ts, packages/@react-aria/interactions/test/usePress.test.js, packages/@react-spectrum/calendar/test/RangeCalendar.test.js
Fixes #8363
Regression introduced in #8275. Select triggers onSelectionChange during onPressUp rather than onPress. This occurs during the onPointerUp event rather than onClick. When this happens, the popover's `isOpen` state changes to false, which removes the underlay and disables useInteractOutside. Due to the exit animation, the popover is not immediately removed from the DOM, so the onClick event is still fired on the menu item. However since useInteractOutside is already disabled, this results in the parent overlay (which is now the "top-most") closing as well.
We can fix this by delaying onPressUp until onClick as well. When starting from a different origin (e.g. dragging and releasing over an item), we'll still trigger onPressUp during onPointerUp since an onClick will not be …
=> fix: Delay onPressUp to native onClick event

packages/@react-spectrum/s2/chromatic/CardView.stories.tsx, packages/@react-spectrum/s2/src/Image.tsx, packages/@react-spectrum/s2/src/Skeleton.tsx, packages/@react-spectrum/s2/stories/CardView.stories.tsx, packages/react-aria-components/src/Tabs.tsx
- Fixes CardView story formats 
- Fixes `inert` value error (for React 19) in Skeleton and RAC Tabs
- Fixes empty `src` string error in Image
Check S2 CardView and ActionBar stories and verify they render without issues.
=> fix(S2): inert value and img empty src string in React 19

packages/@react-aria/selection/src/ListKeyboardDelegate.ts, packages/react-aria-components/example/index.css, packages/react-aria-components/src/Table.tsx, packages/react-aria-components/src/Tree.tsx, packages/react-aria-components/stories/Tree.stories.tsx, packages/react-aria-components/test/Table.test.js, packages/react-aria-components/test/Tree.test.tsx
=> chore: revert focus loading indicators and table scroll events for patch

packages/@react-spectrum/dialog/src/AlertDialog.tsx, packages/@react-spectrum/dialog/stories/AlertDialog.stories.tsx, packages/@react-spectrum/dialog/test/AlertDialog.test.js, packages/@react-types/dialog/src/index.d.ts
Closes https://github.com/adobe/react-spectrum/issues/8369
Check storybook entry
=> feat: allow dom props on alert dialog. add test ids to alert dialog buttons

packages/@react-stately/form/src/useFormValidationState.ts, packages/@react-stately/layout/src/ListLayout.ts, packages/@react-stately/table/src/TableUtils.ts, packages/@react-stately/toast/src/useToastState.ts, packages/@react-stately/tree/stories/useTreeState.stories.tsx, packages/@spectrum-icons/color/stories/IconsColor.stories.tsx, packages/@spectrum-icons/express/chromatic/IconsExpress.chromatic.tsx, packages/@spectrum-icons/express/stories/IconsExpress.stories.tsx, packages/@spectrum-icons/workflow/chromatic/Workflow.chromatic.tsx, packages/@spectrum-icons/workflow/stories/IconsWorkflow.stories.tsx
Closes 
Same test instructions as https://github.com/adobe/react-spectrum/pull/8375
=> chore: TS explicit modules stately and icons

package.json, packages/@react-spectrum/color/test/ColorPicker.test.js, packages/@react-spectrum/picker/test/TempUtilTest.test.js, packages/@react-spectrum/table/test/TestTableUtils.test.tsx, packages/@react-stately/virtualizer/src/Rect.ts, packages/dev/docs/pages/react-spectrum/testing.mdx
Discovered when writing tests in Quarry
RSP
=> fix: Fix Rect intersection check so that users dont need to provide Virtualizer mocks for tests

packages/@react-spectrum/s2/package.json, packages/dev/parcel-transformer-s2-icon/package.json, yarn.lock
Closes 
Ran chromatic https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=971
=> chore: update spectrum tokens

packages/@react-spectrum/s2/package.json
Closes [Missing page.css.map in @react-spectrum/s2 Package](https://github.com/adobe/react-spectrum/issues/8355#top)
=> fix: missing page.css.map

packages/@react-spectrum/s2/src/ColorField.tsx, packages/@react-spectrum/s2/src/NumberField.tsx, packages/@react-spectrum/s2/src/TextField.tsx, packages/react-aria-components/src/ColorField.tsx, packages/react-aria-components/src/TextField.tsx
Closes #7451
We set `GroupContext` in all of our other field components (e.g. NumberField, SearchField, etc.). For convenience of styling, set it in TextField and ColorField too. These have `role="presentation"` but the data attributes for disabled / invalid can still be useful. We had a todo in S2 for this as well.
=> feat: Provide GroupContext in TextField

packages/@react-stately/layout/src/ListLayout.ts, packages/react-aria-components/stories/Tree.stories.tsx
Fixes drop indicators for "after" an expanded item to be after the last child (was rendering before the first child).
Previously, you would get behavior like this:
https://github.com/user-attachments/assets/fe47b4ed-0547-4485-9bcb-e66982a7d583
Test new story: https://reactspectrum.blob.core.windows.net/reactspectrum/952182bc2a0e9c8a1373918d32c48bb803c7dc8f/storybook/index.html?path=/story/react-aria-components--tree-with-drag-and-drop-virtualized&providerSwitcher-express=false
=> fix: Virtualized Tree DnD drop indicator

packages/@react-aria/select/src/HiddenSelect.tsx, packages/@react-spectrum/picker/test/Picker.test.js, packages/react-aria-components/stories/Select.stories.tsx, packages/react-aria-components/test/Select.test.js
Closes #8032
https://github.com/adobe/react-spectrum/blob/9786f69a1cb6b9a9158fcef4dbb9881faefac016/packages/@react-aria/form/src/useFormValidation.ts#L74-L76
runs before
https://github.com/adobe/react-spectrum/blob/9786f69a1cb6b9a9158fcef4dbb9881faefac016/packages/@react-aria/select/src/HiddenSelect.tsx#L103
, which leads to the autofill failing.
See [here](https://stackblitz.com/edit/vitejs-vite-h4svmjzl) for more information
=> fix: Allow `selectedKey=null` to clear value in HiddenSelect

packages/@react-aria/tag/src/useTagGroup.ts, packages/dev/docs/pages/react-aria/home/ExampleApp.tsx
Closes 
Found in testing, go to RAC landing page and try to use the filters in the plant table with only the keyboard. Previously Esc would clear the tags AND close the filter popover. Now it should keep the selection so that the filters still apply after closing the popover.
=> feat: add escape key behavior to tags

packages/@react-spectrum/textfield/intl/en-US.json, packages/@react-spectrum/textfield/package.json, packages/@react-spectrum/textfield/src/TextFieldBase.tsx, packages/@react-spectrum/textfield/stories/Textfield.stories.tsx, packages/@react-spectrum/textfield/test/TextField.test.js, yarn.lock
1. Run `yarn start` and view TextField "with valid state" stories
2. Inspect validation icon - should have `aria-label="Valid"`
3. Inspect input - should have `aria-describedby` pointing to validation icon
4. Test with screen reader - should announce validation status
5. Run `yarn test` - all tests pass
Personal contribution to improve React Spectrum accessibility
---
**Description**: Adds ARIA labeling to TextField validation icons for improved screen reader accessibility.
**Changes**: 
- Added `aria-label="Valid"` to checkmark icon
- Added `aria-describedby` reference when in valid state
- Updated tests and added Storybook stories
=> feat(textfield): Add proper ARIA labeling to validation icon

packages/@react-spectrum/combobox/intl/en-US.json, packages/@react-spectrum/combobox/src/MobileComboBox.tsx, packages/@react-spectrum/textfield/src/TextFieldBase.tsx
From testing
Test Combobox on mobile and make sure it is announced as "valid" when focused and `validationState="valid"`. Also test that TextField still announces "valid" when focused and is in the valid state
RSP
=> fix: preventing Talkback erroneously focusing valid icon and adding similar support for MobileCombobox 

packages/@react-aria/utils/src/platform.ts
Closes https://github.com/adobe/react-spectrum/issues/8457
Check that platforms are still correct: https://reactspectrum.blob.core.windows.net/reactspectrum/6093f6b85878c9cc3e04eb17d59ac98f5b8ef509/storybook/index.html?path=/story/platform--default&providerSwitcher-express=false
Not sure I have access to any of the browsers that can reproduce the original issue, but if someone does, feel free to verify the fix.
=> fix: user agent brands check

packages/react-aria-components/src/ColorWheel.tsx
Minor documentation fix - corrects duplicate "color" word in ColorWheelRenderProps interface comment
No testing required: this PR only fixes a typo in a code comment
=> fix: remove duplicate "color" in ColorWheelRenderProps comment

packages/@react-aria/interactions/src/useHover.ts
No issue link.
`useEffect(setupGlobalTouchEvents, [])` keeps adding the `handleGlobalPointerEvent` listener to document every time it runs. Although adding the same function means the event handler will only execute once, this unnecessary addition could still be avoided.
Local tests passed.
Private.
=> perf(useHover): minimize unnecessary global events

packages/@react-aria/menu/src/useMenuTrigger.ts, packages/@react-aria/selection/src/useTypeSelect.ts, packages/react-aria-components/stories/Select.stories.tsx, packages/react-aria-components/test/Select.test.js
Closes https://github.com/adobe/react-spectrum/issues/5968
=> fix: Select typeahead spaces

packages/@react-aria/textfield/src/useTextField.ts
Closes https://github.com/adobe/react-spectrum/issues/8506
RSP
=> feat: Prevent onChange from firing in TextFields while user is typing via IME

packages/@react-stately/layout/src/ListLayout.ts, packages/react-aria-components/src/DragAndDrop.tsx
Fixes:
- Before-first-item drop indicator had -1px top positioning, making it hidden. Now we clamp to 0.
- Incorrect 'before' nextKey was being persisted for dnd. We now persist the 'before' the next key that isn't inside the target item. 
In [Tree with drag and drop (virtualized)](https://reactspectrum.blob.core.windows.net/reactspectrum/77d10acd3a3260b8d90e08cad399fcbed849639f/storybook/index.html?path=/story/react-aria-components-tree--tree-with-drag-and-drop-virtualized&providerSwitcher-express=false) story, scroll the tree all the way down, then back up. Tab to the first item's drag button and press 'Enter'. The correct drop target should be visible and scrolled to. Previously the collection itself would be showed as focused, and the drop target wouldn't show until manually scrolled …
=> fix: Virtualized Tree DnD fixes

packages/@react-spectrum/s2/src/TreeView.tsx, packages/@react-spectrum/s2/src/index.ts, packages/@react-spectrum/s2/stories/TreeView.stories.tsx, packages/react-aria-components/src/Tree.tsx
=> feat: Support async loading in S2 TreeView

packages/@react-spectrum/image/src/Image.tsx, packages/@react-spectrum/image/test/Image.test.js, packages/@react-types/image/src/index.d.ts
- Allow setting the crossOrigin prop on the Image component
- Added unit tests
- Updated doc strings for the prop (matching the s2 Image component)
- Fixes #8531
- Check the Image component in Storybook, ensure it's still loading
- Ensure the unit tests pass
Deephaven
=> feat(image): Pass crossOrigin prop in to Image

.circleci/config.yml, starters/tailwind/package.json
=> chore: pin rollup version and use bigger resource class

packages/@react-stately/datepicker/src/useDateFieldState.ts, packages/react-aria-components/test/DateField.test.js
From testing
Go to any datefield stories and fill in the first segment, then delete what you typed in. The empty placeholder should remain instead of autofilling to the current date. Using http://localhost:9003/?path=/story/date-and-time-usedatepicker--programmatic-set-value-example&providerSwitcher-express=false&strict=true should still work though
RSP
=> fix: Ensure that clearing a partially entered date doesn't autofill DateField with the current date

packages/@react-aria/dnd/src/DragManager.ts
When we updated to use inert in ariaHideOutside, I forgot to update other places in the DragManager code that were looking specifically for aria-hidden.
In the Virtualized Tree with dnd story, keyboard navigate to Reports, focus the drag button, and press enter. The drop indicator at the end of the list should scroll into view. This was previously broken in Safari.
=> fix: Update dnd to handle inert

packages/@react-spectrum/s2/src/DateRangePicker.tsx
noticed during testing, fixed to match design
go to DateRangePicker, select the Zoned story, and open the Popover. make sure that the spacing is correct between the calendar and timefields
=> fix(s2): add space between timefield and calendar in DateRangePicker

packages/react-aria-components/src/TreeDropTargetDelegate.ts
Closes https://github.com/adobe/react-spectrum/issues/8561
We normalize to the 'after' drop target, but previously this could have been one of the dragged items (not a valid drop target). Now, we make sure the normalized target is a valid drop target before using it.
Try steps from  https://github.com/adobe/react-spectrum/issues/8561
=> fix(TreeDropTargetDelegate): only normalize to 'after' target if valid

packages/@react-aria/overlays/src/ariaHideOutside.ts, packages/@react-aria/overlays/test/ariaHideOutside.test.js
=> fix: remove stale inert after performing keyboard drag and drop in virtualized tree 

packages/@react-spectrum/s2/stories/TableView.stories.tsx, packages/@react-spectrum/table/stories/Table.stories.tsx, packages/@react-stately/data/src/useAsyncList.ts, packages/@react-stately/data/test/useAsyncList.test.js
Closes 
- in the S2 storybook, load the TableView > Test story
- note when switching between the `All` and `A New Hope` film filters, there's only one load call (logged in console as well)
- also note that when switching from `All` -> `A New Hope`, there's only 1 load called initially, and the second page call isnt made until scrolling down more (previous to this fix, the call would be made immediately)
=> fix: do not dispatch loadMore if hook is still in loading state

packages/@react-spectrum/s2/src/Card.tsx, packages/@react-spectrum/s2/src/Checkbox.tsx, packages/@react-spectrum/s2/src/ComboBox.tsx, packages/@react-spectrum/s2/src/Menu.tsx, packages/@react-spectrum/s2/src/Picker.tsx, packages/@react-spectrum/s2/src/Radio.tsx, packages/@react-spectrum/s2/src/Tabs.tsx, packages/@react-spectrum/s2/src/TagGroup.tsx, packages/@react-spectrum/s2/src/TreeView.tsx, packages/@react-spectrum/tree/src/TreeView.tsx, packages/@react-types/checkbox/src/index.d.ts, packages/@react-types/radio/src/index.d.ts
=> chore: get rid of onClick on S2 and RSP components

packages/@react-aria/overlays/src/ariaHideOutside.ts, packages/@react-aria/overlays/test/ariaHideOutside.test.js
the root cause is because in a virtualizer node reuse/reorder case triggered by the mutation observer, we were removing the node from the hidden nodes list prematurely even though it was going to be readded immediately after, causing the ref count to erroneously increment by 1 again via acceptNode's check
from testing
Go to virtualized tree DnD/tableview dnd/ any virtualized DnD experience and test keyboard drag and drop. In particular, try starting a keyboard drag session, holding ArrowDown to cycle through the list multiple times, then canceling your drop. You should still be able to navigate to each row after that 
RSP
=> fix: remove inert if user cycles through whole list/dnd multiple times via keyboard dnd

packages/@react-spectrum/s2/chromatic/CardView.stories.tsx, packages/@react-spectrum/s2/src/CardView.tsx, packages/@react-spectrum/s2/stories/CardView.stories.tsx, packages/@react-stately/layout/src/GridLayout.ts, packages/@react-stately/layout/src/WaterfallLayout.ts
Closes 
Test the base S2 CardView story and make sure `loadingState: 'loading'` and `loadingState: 'loadingState'` render skeleton cards for both grid and waterfall layout. Also make sure renderEmpty story render the skeletons when `loadingState: 'loading'` 
RSP
=> fix: CardView skeleton loading should appear even if renderEmptyState is provided

packages/@react-spectrum/s2/src/Calendar.tsx
=> fix: make sure tap highlight doesn't appear in S2 Calendar on iOS

packages/@react-spectrum/s2/src/CardView.tsx, packages/@react-stately/layout/src/GridLayout.ts
Test instructions:
1. Check that the skeleton appears in the loading and loadingMore states. Especially when the last row of real cards fills the whole row. There should be an extra row of skeletons at the bottom.
2. Check that the empty state example still displays when the loading state is set.
=> fix: CardView skeleton loaders

packages/dev/docs/pages/react-aria/routing.mdx, packages/dev/docs/pages/react-spectrum/routing.mdx
Since we pass through DOM events now, it's possible to use TanStack Router's `createLink` function directly instead of using RouterProvider. This has the benefit that it automatically supports the TypeScript features of TanStack, and also works with their pre-fetching. Updating the docs accordingly. Also sent a PR to update the docs on the TanStack site: https://github.com/TanStack/router/pull/4757
=> docs: Update TanStack Router guide

packages/@react-stately/datepicker/src/utils.ts
Closes https://github.com/adobe/react-spectrum/issues/7457
=> fix: fallback to en-US when locale resolution fails

packages/@react-aria/virtualizer/src/ScrollView.tsx
This PR improves scroll end detection in supported browsers with fallback to our previous way of detecting via timeout.
We also expose the `isScrolling` state for consumption, which will come in handy for carousel infinite loop 👍
=> Feat: Add `onscrollend` event listener to ScrollView

packages/@react-spectrum/tabs/src/Tabs.tsx
Closes  https://github.com/adobe/react-spectrum/issues/8650
=> fix: react types backwards compat for Tabs

packages/@react-aria/menu/src/useSubmenuTrigger.ts, packages/react-aria-components/src/Menu.tsx, packages/react-aria-components/src/Popover.tsx, packages/react-aria-components/test/AriaMenu.test-util.tsx
Closes https://github.com/orgs/adobe/projects/19/views/4?pane=issue&itemId=121862878
RSP
=> fix: Make submenu hover focus remain on the trigger and collapse submenus when hovering root menu 

packages/@react-stately/layout/src/GridLayout.ts, packages/react-aria-components/stories/GridList.stories.tsx
Closes #8655 
- I didn't find existing test for this file
- from what I can see, running docs locally automatically updated them, so I guess nothing more is necessary?
- not applicable here?
Run the storybook (locally)
Under "React Aria Components > GridList > Virtualized Grid List Grid"
| before (without `maxSpace`) | after (with `maxSpace: 5`) |
|-|-|
| <img width="419" height="422" alt="image" src="https://github.com/user-attachments/assets/37c55aa5-2445-4003-9b3a-b31439d6a3c7" /> | <img width="421" height="423" alt="image" src="https://github.com/user-attachments/assets/f4cc969f-70d5-4479-9a73-42331eab49d7" /> |
you can also test for more complex combination by modifying the `layoutOptions`.
For example with `layoutOptions`:
```js
{
minItemSize: new Size(40, 40),
maxItemSize: new …
```
=> feat: add maxSpace option to @react-stately/layout GridLayout

packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx, packages/@react-spectrum/color/src/ColorField.tsx, packages/@react-spectrum/combobox/src/ComboBox.tsx, packages/@react-spectrum/searchfield/src/SearchField.tsx, packages/@react-spectrum/textfield/src/TextArea.tsx, packages/@react-spectrum/textfield/src/TextField.tsx
Closes https://github.com/adobe/react-spectrum/issues/3250
Not a huge deal, just cleaning up some old issues. We can close if we think this isn't worth including since we now only show in production.
=> chore: avoid showing placeholder warning every render

packages/@react-aria/utils/src/isElementVisible.ts, packages/react-aria-components/stories/Toolbar.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/8636
Can't test in jsdom because it behaved correctly both ways, it seems to be wrong about element visibility compared to browsers.
Test in the story.
=> fix: check for element visibility should take react aria attribute into consideration

packages/@react-aria/overlays/src/calculatePosition.ts, packages/@react-aria/overlays/src/useOverlayPosition.ts, packages/@react-aria/overlays/src/usePopover.ts, packages/@react-aria/overlays/test/calculatePosition.test.ts, packages/react-aria-components/docs/Popover.mdx, packages/react-aria-components/docs/Tooltip.mdx, packages/react-aria-components/src/Popover.tsx, packages/react-aria-components/src/Tooltip.tsx, packages/react-aria-components/stories/Popover.stories.tsx, packages/react-aria-components/stories/Tooltip.stories.tsx, packages/react-aria-components/stories/styles.css
Fixes #8291, closes #8119, closes #6825
As discussed in https://github.com/adobe/react-spectrum/pull/8163#issuecomment-2864201480, this adds a `--trigger-origin` CSS variable to popovers and tooltips that has the position of the trigger relative to the overlay. This variable can be used with `transform-origin` to make origin-aware animations (e.g. scale).
If the overlay has an arrow, the arrow position is used as the origin so that it does not appear to move during an animation. Otherwise, the corner of the trigger is used.
Also fixes scale animations from affecting positioning by skipping re-positioning while positioning is occurring.
Open the RAC Popover and Tooltip stories and test the enter/exit animations with various placements in the controls.
=> feat: Add support for origin-aware overlay animations

packages/@react-aria/utils/src/isVirtualEvent.ts
Closes 
Test that virtual clicks are still properly detected for JAWS/NVDA, sanity check other screenreader/browser combinations.
To test, can try the drag and drop stories and attempt keyboard drag and drop 
A sample flow can be found via https://github.com/adobe/react-spectrum/pull/3221, copied below. Some of the drag messages may not be exactly as below but the overall flow should be the same
1. Using Windows with either JAWS or NVDA screen reader, open https://reactspectrum.blob.core.windows.net/reactspectrum/1331d8e41e11a79c5d05e9086e4c5f8781d566b4/storybook/index.html?path=/story/drag-and-drop--default&id=drag-and-drop--default&providerSwitcher-toastPosition=bottom&viewMode=story
2. In browse mode/virtual cursor mode, navigate to the button labelled "Drag me."
3. The …
=> chore: Replace deprecated mozInputSource check for virtual click detection

packages/@react-aria/utils/src/index.ts
Closes https://github.com/adobe/react-spectrum/issues/8635
RSP
=> fix: re-export UNSTABLE_useLoadMoreSentinel so it isn't a breaking change

.storybook-s2/docs/Illustrations.jsx
Copy an import and check the content: https://reactspectrum.blob.core.windows.net/reactspectrum/727c206ab4134607fb781bac2e0b7842e6d831be/storybook-s2/index.html?path=/docs/illustrations--docs
=> docs: fix import copied from illustrations

packages/@react-aria/tag/src/useTagGroup.ts, packages/react-aria-components/stories/TagGroup.stories.tsx, packages/react-aria-components/test/TagGroup.test.js
Closes https://github.com/adobe/react-spectrum/issues/8354
Tested it with VO before and after this change and it didn't really make a difference in terms of announcement. It always seemed to announce it as a group so I feel like this change is fine and now won't violate accessibility.
=> fix: add role to react aria taggroup when empty

packages/@react-aria/menu/src/useMenuItem.ts, packages/@react-spectrum/menu/test/Menu.test.js
Fixes #8697
We used to trigger `onClose` during `onKeyDown`, but the browser `onClick` event to trigger links didn't fire until after the menu already closed. If there was no exit animation on the popover, the link would not open. Our tests didn't catch this because they rendered a menu outside a MenuTrigger.
This refactors our event handling logic to centralize everything in `onClick`. We track which interaction occurred prior to `onClick` being called, and use that to determine whether the menu should close.
Open the RAC Menu story, and trigger the link with various methods (click, drag and release, Enter key, Space key)
=> fix: Pressing Enter key to trigger Menu item links

packages/@react-spectrum/s2/stories/ComboBox.stories.tsx, packages/@react-spectrum/s2/stories/Picker.stories.tsx, packages/@react-stately/list/src/ListCollection.ts
From testing
Try filtering a S2 combobox that has sections and ensure that the empty state will appear properly. 
RSP
=> fix: properly render empty state when filtering S2 ComboBox with sections

packages/@react-spectrum/s2/src/SelectBoxGroup.tsx, packages/@react-spectrum/s2/stories/SelectBoxGroup.stories.tsx, packages/@react-spectrum/s2/test/SelectBoxGroup.test.tsx
Closes 
things to look out for that we discussed when we tested selectbox:
1. selectbox should have cursor: 'default'. right now it has a pointer cursor
2. the focus ring should be a halo since it conflicts with the selection state. i think all you need to do is remove the outlineOffset
3. we're just going to omit the showCheckbox and have checkboxes always rendered. we can change this later
4. when the user presses down on a select box, the select box should scale down (which is what we call press scaling). search pressScale and example of how to use it in S2 should come up. we want it to look similar to how CardView does when you press down on a Card
5. clean up the stories a little bit since some of the various states can be achieved by using the controls (like the Disabled one for …
=> fix: S2 Selectbox Updates

packages/@react-aria/button/src/useButton.ts, packages/@react-aria/button/test/useButton.test.js, packages/@react-types/button/src/index.d.ts, packages/react-aria-components/test/Button.test.js
Closes https://github.com/adobe/react-spectrum/issues/8687
=> feat: allow DOM pass-through of aria-disabled on Button

packages/@react-spectrum/s2/src/Tabs.tsx, packages/@react-spectrum/s2/stories/Tabs.stories.tsx
When S2 Tabs have only a single word in each tab they would never collapse due to the `min-width: min-content`. Setting this to zero fixes the issue. Updated one of the stories to test.
=> fix: S2 Tabs collapsing with a single word

packages/@react-spectrum/s2/chromatic/SelectBoxGroup.stories.tsx, packages/@react-spectrum/s2/src/SelectBoxGroup.tsx, packages/@react-spectrum/s2/stories/SelectBoxGroup.stories.tsx, packages/@react-spectrum/s2/test/SelectBoxGroup.test.tsx
A few minor API updates and small fixes.
* Changed `value` to `id` to match other collection components
* Added `textValue` and `aria-label` as a prop
* Fixed disabled color
* Removed colored illustrations from example for now (need to discuss with design)
* Made the grid fixed width and centered the items in the available space so the gaps don't differ between the horizontal and vertical directions
=> chore: SelectBox audit

packages/react-aria-components/docs/GridList.mdx, packages/react-aria-components/docs/ListBox.mdx, packages/react-aria-components/docs/Table.mdx
Skipped Tree for now since it's a little more complicated due to the `useTreeData` wrapper objects.
=> docs: Update dnd docs for new getItems API

Makefile, packages/@react-spectrum/s2/src/TableView.tsx, packages/dev/s2-docs/pages/react-aria/Table.mdx, packages/dev/s2-docs/pages/s2/TableView.mdx, packages/dev/s2-docs/src/CodeBlock.tsx, packages/dev/s2-docs/src/CodePlatter.tsx
=> docs: Adding S2 TableView docs to new docs site

packages/dev/s2-docs/pages/s2/Tabs.mdx
=> docs: S2 tab docs

packages/react-aria-components/docs/ComboBox.mdx, packages/react-aria-components/docs/Popover.mdx, packages/react-aria-components/docs/Select.mdx
The scale transition looks weird when the width of the popover is supposed to match the trigger.
=> docs: Disable scale transition on Select and ComboBox popovers

packages/react-aria-components/docs/DropZone.mdx, packages/react-aria-components/src/index.ts, packages/react-aria-components/stories/Dropzone.stories.tsx
This reverts commit 8c5b7a011b0d2dda3efb7182b810383c92170639.
Closes
=> chore: Revert add dnd hooks to rac (#8743)

packages/react-aria-components/src/Tree.tsx, packages/react-aria-components/stories/Tree.stories.tsx
Closes https://github.com/adobe/react-spectrum/issues/8725
Note, this does not address initial load/render of Tree, this is just for expanded keys
`visitNode` in Tree for the expand all action takes
Before: ~20772ms
After: ~190ms
=> fix: Speed up tree collection builder flattening when expanding keys

packages/@react-aria/dnd/test/useDroppableCollection.test.js, packages/@react-aria/selection/src/DOMLayoutDelegate.ts, packages/react-aria-components/test/Table.test.js
A [Scrollport](https://developer.mozilla.org/en-US/docs/Glossary/Scroll_container#scrollport) coincides with the padding box, which should not include border offset. We were calculating on `offsetWidth` & bounding boxes instead of `clientWidth` and for some reason shifted the item rect by scroll offset??
With this change, the DOM layout is now consistent with our virtualized ones 👍
=> Fix: DOMLayoutDelegate miscalculates item & visible rects

packages/@react-spectrum/s2/chromatic/InlineAlert.stories.tsx, packages/@react-spectrum/s2/src/InlineAlert.tsx, packages/@react-spectrum/s2/stories/InlineAlert.stories.tsx
Closes https://github.com/orgs/adobe/projects/19/views/32?pane=issue&itemId=127661299
Test the new "No heading" S2 Inline alert story and make sure the text wraps around the icon if no heading is applied and a icon variant is selected. 
RSP
=> feat: Support heading-less inline alerts

packages/@internationalized/date/src/queries.ts, packages/@internationalized/date/tests/queries.test.js, packages/react-aria-components/stories/Calendar.stories.tsx
Found in testing
Opted not to implement the entirety of https://unicode.org/reports/tr35/#unicode-locale-identifier
This particular change for the first day of the week fallback is only needed for FF and node right now.
unit test should cover it, but there is a story in RAC Calendar which sets a numbering system beyond the first day of the week via controls
=> fix: first day of week bcp 47 parsing in middle of other extensions

packages/@react-aria/disclosure/src/useDisclosure.ts, packages/@react-aria/disclosure/test/useDisclosure.test.ts, packages/@react-spectrum/s2/src/Disclosure.tsx, packages/react-aria-components/docs/Disclosure.mdx, packages/react-aria-components/docs/DisclosureGroup.mdx, starters/docs/src/Disclosure.css, starters/tailwind/src/Disclosure.tsx
Closes #7528
Adds `--disclosure-panel-width` and `--disclosure-panel-height` CSS variables, which are set to the `scrollWidth` and `scrollHeight` of the panel when expanding and collapsing. If any animations are triggered, then we wait to set the `hidden` attribute until they complete.
In the future this may be possible in native CSS with the `interpolate-size: allow-keywords` property (currently only in Chrome) along with `transition-behavior: allow-discrete`, which allows using `height: auto` and `display: none` directly. In the meantime, this is a pretty simple polyfill that must be done within the hooks to ensure correct timing.
=> feat: Add support for disclosure animation

packages/@react-aria/collections/src/Document.ts
Fixes #8885, fixes #8865
With suspense, React can create elements without setting their props, leading to elements that don't have collection nodes yet. These were tracked in `dirtyNodes`, which was cleared at the end of each collection update. However, since these elements don't have nodes, they actually should still be dirty because we haven't added them to the collection yet. This way, on the next render they will be updated.
=> fix: Fix collection dirty node tracking with suspense

packages/@adobe/spectrum-css-temp/components/tray/index.css, packages/@adobe/spectrum-css-temp/components/underlay/index.css, packages/@react-aria/dialog/docs/useDialog.mdx, packages/@react-aria/dialog/src/useDialog.ts, packages/@react-aria/overlays/docs/useModalOverlay.mdx, packages/@react-aria/overlays/src/usePreventScroll.ts, packages/@react-aria/utils/src/index.ts, packages/@react-aria/utils/src/keyboard.tsx, packages/@react-aria/utils/src/useViewportSize.ts, packages/@react-spectrum/overlays/src/Tray.tsx, packages/@react-spectrum/overlays/src/Underlay.tsx, packages/@react-spectrum/s2/src/Dialog.tsx, packages/@react-spectrum/s2/src/FullscreenDialog.tsx, packages/@react-spectrum/s2/src/Modal.tsx, packages/dev/docs/pages/react-aria/home/ExampleApp.tsx, packages/dev/s2-docs/src/Layout.tsx, packages/react-aria-components/docs/Modal.mdx, packages/react-aria-components/docs/examples/command-palette.mdx, packages/react-aria-components/docs/examples/destructive-dialog.mdx, packages/react-aria-components/src/Modal.tsx, starters/docs/src/Modal.css, starters/docs/src/Sheet.css, starters/tailwind/src/Modal.tsx
Fixes #7902, fixes #7972, fixes #5926
iOS Safari 26 significantly changes how the visual viewport works due to the controls that now overlay on top of the page. `position: fixed` elements are clipped to the viewport below the status bar and above the address bar, but other content continues to scroll behind them. This means that the modal backdrop will not fill the entire visible viewport, which looks strange.
To fix this, we can use `position: absolute` for the backdrop instead of `fixed`, and make it cover the entire page instead of just the visual viewport. The actual modal is still sized within the visual viewport. For trays, we add additional padding that extends behind the address bar so it looks seamless.
I also made `useViewportSize` update during the `blur` event instead of …
=> fix: Improve behavior of modals on iOS 26

packages/@react-aria/disclosure/src/useDisclosure.ts, packages/react-aria-components/test/Disclosure.test.js
Found via chromatic 
Check the RSP Accordion "with disabled disclosure" story, the disabled disclosure shouldn't display its contents. The tests and chromatic should cover the other cases
RSP
=> fix: Dont display disclosure panel content if isDisabled and isExpanded=false

packages/@react-aria/autocomplete/src/useAutocomplete.ts, packages/@react-aria/focus/src/FocusScope.tsx, packages/@react-aria/interactions/src/focusSafely.ts, packages/@react-spectrum/combobox/test/ComboBox.test.js, packages/@react-spectrum/s2/stories/Dialog.stories.tsx
Reverts adobe/react-spectrum#8498
Reopens https://github.com/adobe/react-spectrum/issues/5953
Found a new difference, autoFocus is now selecting and that isn't how native works. We'll need to apply this more in a more targeted way.
=> chore: Revert "fix: Focus behaviour on inputs inside a FocusScope"

packages/@react-aria/combobox/src/useComboBox.ts, packages/@react-spectrum/s2/src/ComboBox.tsx, packages/@react-spectrum/s2/stories/ComboBox.stories.tsx, packages/dev/s2-docs/pages/react-aria/ComboBox.mdx, packages/dev/s2-docs/pages/s2/ComboBox.mdx, packages/react-aria-components/stories/ComboBox.stories.tsx, packages/react-aria-components/test/ComboBox.test.js
Closes #8884, closes #8831
The `onAction` prop is accepted by `ListBoxItem` / `ComboBoxItem` in S2 but doesn't actually work with the keyboard. This PR fixes that so it works like links, where actionable items are not selectable.
Also adds docs for both RAC and S2 for the commonly requested use case of adding a "Create" action to a ComboBox.
=> fix: Fix onAction with keyboard in ComboBox and add docs

packages/@adobe/spectrum-css-temp/components/tray/index.css, packages/@react-spectrum/overlays/src/Underlay.tsx, packages/@react-spectrum/s2/src/SegmentedControl.tsx, packages/dev/docs/pages/react-aria/home/ExampleApp.tsx, packages/react-aria-components/docs/Disclosure.mdx, packages/react-aria-components/src/Modal.tsx
* Backdrop height changes while dialog closes (DG)
* on the react aria homepage, clicking on the modal example, the lines grouping the form components changes based on my scroll position. see screenshot row 10 (YL)
* Tray animates too fast now. Probably due to the extra padding (DG)
* background shifts while opening due to scrollbar appearing in Firefox (YL)
* Alignment of interactive elements (button next to disclosure) doesn't have a gap anymore. See screenshot 11 (DR)
* The selection indicator is 1px too high in Safari (DG)
=> fix: Bugs from testing

packages/@react-aria/overlays/src/usePreventScroll.ts, packages/@react-aria/utils/src/useViewportSize.ts
Fixes #1898, fixes #8324
This fixes two issues with `usePreventScroll` on iOS
* Pinch zooming was prevented by the `preventDefault` in `touchmove`, which was only intended to prevent scrolling.
* It was impossible to modify a text selection by dragging the little handles for the same reason.
We now skip the `preventDefault` when using two fingers to allow zooming. Once zoomed, you are allowed to pan around within the zoomed region using two fingers as well. In addition `useViewportSize` now no longer updates when the page is zoomed (similar to what we do for overlay positioning), so that the dialog doesn't resize unexpectedly.
We now also detect whether the target element contains text selection, and allow touchmove events to go through. This means it is also possible to scroll the page …
=> fix: Allow pinch zooming and text selection in modals on iOS

packages/@react-spectrum/menu/src/MenuItem.tsx, packages/@react-spectrum/menu/stories/MenuTrigger.stories.tsx, packages/@react-spectrum/menu/test/MenuTrigger.test.js
Closes https://github.com/adobe/react-spectrum/issues/8871
Test new story: https://reactspectrum.blob.core.windows.net/reactspectrum/a205e07eb8f1f9b0b1d77d98fe70c2da574b41d3/storybook/index.html?path=/story/menutrigger--menu-item-unavailable-with-selection&providerSwitcher-express=false
=> fix(Menu): show checkboxes for selected items with ContextualHelpTrigger isUnavailable={false}

packages/@react-spectrum/s2/src/Disclosure.tsx, packages/dev/s2-docs/pages/react-aria/SegmentedControl.css, packages/react-aria-components/docs/Disclosure.mdx, packages/react-aria-components/docs/Tabs.mdx, packages/react-aria-components/docs/ToggleButtonGroup.mdx, starters/docs/src/Disclosure.css, starters/docs/src/Tabs.css, starters/tailwind/src/Disclosure.tsx, starters/tailwind/src/Tabs.tsx
Ensures our examples for Disclosure, Tabs, and ToggleButtonGroup respect the prefers-reduced-motion setting.
=> fix: Respect prefers-reduced-motion setting in examples

examples/rsp-next-ts/styles/globals.css, packages/@adobe/spectrum-css-temp/components/tray/index.css
This prevents the content box of the Tray from being reduced to 0 due to the extra 100vh padding we apply for iOS 26
Will need to merge in order to test the NextJS test app, but locally you can try applying a global `box-sizing: border-box` in the V3 storybook and make sure it doesn't cause the ComboBox/Menu/etc tray to hide its contents
RSP
=> fix: Ensure Tray always uses `box-sizing: content-box` so it isn't affected by global css resets

packages/@react-spectrum/s2/src/Picker.tsx, packages/@react-spectrum/s2/stories/Picker.stories.tsx
Closes 
Found while working on another branch after merging in main
First comment should show the broken behaviour when you select an item in the S2 Picker Avatar story
Second comment should show it fixed
=> fix: Picker default text display

packages/@react-spectrum/s2/src/TableView.tsx
`pointerEvents: 'none'` was applied to the button.
=> fix: Clicking on TableView column header menu does not work

packages/@react-spectrum/s2/src/Modal.tsx, packages/dev/s2-docs/src/Layout.tsx, packages/dev/s2-docs/src/MobileHeader.tsx
- Fixes issue where when you initially scrolled the page down, then opened the mobile search menu, it wasn't visible.
- Only render a table of contents in mobile header if there are subsections on a page.
=> docs: fix S2 docs mobile search bugs

packages/dev/s2-docs/src/ComponentCardView.tsx
Makes all the image heights match in the component cards. Needed a few overrides for certain SVGs which have hard coded dimensions for the old site. Eventually we'll replace all these images with new ones anyway, but this is better for now.
=> docs: Make component card heights match

packages/@react-aria/utils/src/scrollIntoView.ts
Closes #8977
For people on the team trying to test this, you can use the "Table with React Transition" RAC story, just make sure to shrink your window in such a way that the body is now scrollable. See https://reactspectrum.blob.core.windows.net/reactspectrum/9bf119be79af2a2d2b2605c23f67e0e10628fa76/storybook/index.html?path=/story/react-aria-components-table--table-with-react-transition&providerSwitcher-express=false on main for an example of the broken case
=> fix(scrollIntoViewport): add root to scrollParents
